### ISSUE TITLE
slightly better install.bat file

### ISSUE THREAD

**Issue by fastnicky** [SpotX-Official/SpotX#101]
### Description of the new feature / enhancement

The thing I'm suggesting will only help a small number of people but for me, the install bat file gives me "'powershell' is not recognized as an internal or external command, operable program or batch file." and this is because I use a custom cmd path to make another program I use easier (youtube dlp). So instead in the batch file, I made it where it goes to where PowerShell is located rather than just it running as a command.
```
@echo off

%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Command "& {[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12}"; "& {(Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content | Invoke-Expression}"

pause
exit /b
```

**Comment by amd64fox** [comment]
Is this way working for you?

<kbd>Win</kbd> + <kbd>R</kbd> => powershell => <kbd>Enter</kbd>

right-click paste the following line:

```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content | iex
```

**Comment by fastnicky** [comment]
yes, that works for me, but I was suggesting this change to that bat file so it's more automated for people with different cmd paths since it's easier and faster just to double click something rather than do multiple steps.

**Comment by amd64fox** [comment]
fixed
Thanks
