### ISSUE TITLE
[Request] Linux script too

### ISSUE THREAD

**Issue by linuxmobile** [SpotX-Official/SpotX#102]
### Description of the new feature / enhancement

Hi there. I love your work and I wanna know if you can do this for linux too. I can test if you need.

**Comment by amd64fox** [comment]
Hi, unfortunately I don't use Linux or Mac, so I can't create a script for those systems, but there is a much more powerful alternative to [spicetify](https://github.com/spicetify/spicetify-cli), it support for these OC

**Comment by amd64fox** [comment]
https://github.com/SpotX-CLI/SpotX-Win/discussions/188
