### ISSUE TITLE
Usage with spicetify disable devtools

### ISSUE THREAD

**Issue by SupLiCatinG** [SpotX-Official/SpotX#104]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/blob/main/.github/Doc/FAQ.md#i-have-an-error--bug--strange-client-behavior-what-can-i-do-">described in the FAQ</a>

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.1.91.824
- Windows: Windows 10 Home Single Language 19044.1865
- PowerShell: 5.1.19041.1682
```

### 📝 Description

Enabling SpotX while spicetify installed disables devtools. As expected re-enabling devtools needs to command and it causes to SpotX not working properly. I'm stuck at endless loop.

**Comment by amd64fox** [comment]
Does your problem happen if you install SpotX first and then Spicetify ?

**Comment by SupLiCatinG** [comment]
Nope, first installing spicetify with enable-devtools command afterwards proceeding with spotx.

**Comment by amd64fox** [comment]
try the other way around

remove spotify and spicetify

then install first spotx and second spicetify

**Comment by amd64fox** [comment]
Spicetify also has a problem with enabling devtools for some accounts, for example, sometimes the `spicetify enable-devtools` command without SpotX also does not work for me.
In this case, just use this devtools enable [tool](https://github.com/amd64fox/Enable-devtools-Spotify), works for all accounts, but it's only for Windows.
