### ISSUE TITLE
Canvas on Desktop?

### ISSUE THREAD

**Issue by AKASGaming** [SpotX-Official/SpotX#105]
### Description of the new feature / enhancement

Is it possible to get Canvas on desktop somehow? I know there's a [Spicetify theme](https://github.com/itsmeow/Spicetify-Canvas) that supports it and there's the [online API version](https://canvastify.delitefully.com). Might work well with fullscreen mode or with lyrics

**Comment by amd64fox** [comment]
If there is a ready-made solution for Spicetify, then why don't you want to install it? SpotX works great together with Spicetify

**Comment by AKASGaming** [comment]
The last time I used Spicetify it messed with my username and messed it up a lot (I had to contact support to get it fixed), but maybe that's not an issue anymore. The other thing was the process of installing that theme specifically

**Comment by amd64fox** [comment]
At the moment, the only way is to install this Spicetify theme, I agree that the installation process is not easy there, but there is a detailed description.
If you do not want to risk your account, then create a test one for testing.

And this site [canvastify.delitefully.com](https://canvastify.delitefully.com/) provides api, but you can't use it, you need to create your own server, it's just shown for informational purposes, well, the restrictions are only for premium users.
