### ISSUE TITLE
"Get Spotify Premium" Softlock Until Logout

### ISSUE THREAD

**Issue by glennlp** [SpotX-Official/SpotX#107]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/blob/main/.github/Doc/FAQ.md#i-have-an-error--bug--strange-client-behavior-what-can-i-do-">described in the FAQ</a>

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.91.824.g07f1e963
- Windows: Windows 10 21H2
- PowerShell: 5.1.19041.1682
```

### 📝 Description

1. Opened Spotify and got the message "Get Spotify Premium," softlocking my client until I logout. Clean install and all methods tried.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/61350902/183610505-587ec03e-1419-41d4-9832-95e2b1fbcd63.png)

**Comment by amd64fox** [comment]
which patch installer did you use ?

**Comment by glennlp** [comment]
Tried 'usual installation' and 'automatic full'

**Comment by amd64fox** [comment]
Is this account new? Or maybe you recently ran out of premium

**Comment by glennlp** [comment]
Its an account that had premium but lost it. But, it was still working before that for a few weeks and suddenly giving me this issue

**Comment by amd64fox** [comment]
Okay, and now this dialog appears every time after starting the client and you can't close this one, right?

**Comment by glennlp** [comment]
Correct just suddenly even with a fresh install

**Comment by amd64fox** [comment]
Need to test
You can download this [xpui.zip](https://github.com/amd64fox/SpotX/files/9289683/xpui.zip), rename it to `xpui.spa` and replace your `xpui.spa` with it, located here `%appdata%\Spotify\Apps`

**Comment by glennlp** [comment]
That seems to work for now, thank you

Edit: only bypasses the initial screen but can't play music

**Comment by amd64fox** [comment]
Screenshot or video ?

**Comment by glennlp** [comment]
Found the issue:

Logging in with my USA account **works** but with South Korea, it doesn't work because there is no free tier. Will be an issue for those countries that don't have free tiers.

**Comment by amd64fox** [comment]
Do you know what other countries also do not have a free plan?

**Comment by amd64fox** [comment]
It looks like this is only possible in South Korea.

**Comment by amd64fox** [comment]
[xpui.zip](https://github.com/amd64fox/SpotX/files/9291364/xpui.zip)
Found another way, you can try to replace `xpui.spa` again and check on your South Korean account
If that doesn't help, then I probably don't have any more ideas.

**Comment by glennlp** [comment]
Yep no luck, thank you for trying though

**Comment by amd64fox** [comment]
ok anyway it's not a problem with the mod as there is simply no free usage in this region.

I will add this information a little later to the FAQ
Thanks
