### ISSUE TITLE
Create desktop shortcut (Optional)

### ISSUE THREAD

**Issue by KAGEYAM4** [SpotX-Official/SpotX#108]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/blob/main/.github/Doc/FAQ.md#i-have-an-error--bug--strange-client-behavior-what-can-i-do-">described in the FAQ</a>

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify:1.1.91.824.g07f1e963
- Windows: 21H2 22000.856
- PowerShell: 5.1.22000.832

```

### 📝 Description

1. launch SpotX.bat
2. Shortcut of spotify appears on desktop
...

Solution -- 
1. Option to disable this
2. Create shortcut in %appdata%\Microsoft\Windows\Start Menu\Programs

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/75798544/183904736-7f9d92a1-ff72-4753-b173-a2a3be791475.png)

this is my config of the bat
```
@echo off

powershell -Command "&{[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12}; """"& { $((Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content)} -confirm_uninstall_ms_spoti -confirm_spoti_recomended_over -podcasts_off -cache_on -block_update_off -start_spoti """" | Invoke-Expression"

pause
exit /b
```

**Comment by amd64fox** [comment]
What makes you think that creating a program shortcut on the desktop after installation is a bug? Most applications do this.
Also, after installing SpotX, you should have a Spotify shortcut in `\Start Menu\Programs`

**Comment by KAGEYAM4** [comment]
> What makes you think that creating a program shortcut on the desktop after installation is a bug? 

sorry my bad .. i used to use blockthespot.bat before and it did not used to do that so i was considering it a bug.

>Also, after installing SpotX, you should have a Spotify shortcut in \Start Menu\Programs

yes the shortcut gets created there too . now i end up with two shorcuts. So when i use PowerToys Run - it displays two spotify launch.

**Comment by amd64fox** [comment]
> yes the shortcut gets created there too . now i end up with two shorcuts. So when i use PowerToys Run - it displays two spotify launch.

Can you show how it happens?

**Comment by KAGEYAM4** [comment]
> > yes the shortcut gets created there too . now i end up with two shorcuts. So when i use PowerToys Run - it displays two spotify launch.
> 
> Can you show how it happens?

in my case , no spotify launch shortcut is being created in `C:\Users\Phoenix\AppData\Roaming\Microsoft\Windows\Start Menu\Programs`
i was having this impression because when i migrated from win10 to win11 , i backed up this \program to copy the shortcuts as i use alot of portable apps. 

After using SpotX.bat the only shortcut is being created on desktop.

**Comment by amd64fox** [comment]
SpotX checks the shortcut on the desktop during installation, if it does not exist, it creates a new one, and in cases of installing `clear the cache` a custom shortcut is created on the desktop that replaces the original one.

As for the `Start Menu\Programs`, SpotX does not affect this shortcut, it is created by Spotfy itself.

Understand your PowerToys settings, this is most likely the problem.

**Comment by KAGEYAM4** [comment]
> SpotX checks the shortcut on the desktop during installation, if it does not exist, it creates a new one, and in cases of installing `clear the cache` a custom shortcut is created on the desktop that replaces the original one.

Can we get this as a optional feature, i don't want it to create a shortcut of spotify on desktop.

**Comment by amd64fox** [comment]
can add a new input parameter that will not create a shortcut on the desktop, but then clearing the cache will not work, since it is launched through this shortcut, if you only replace the original shortcut located here `Start Menu\Programs`

**Comment by KAGEYAM4** [comment]
what about adding another code of line where after everything is done . the desktop shortcut will then be deleted permanently (optionally passed as an argument) . this way clear cache will work too.

**Comment by amd64fox** [comment]
I don't quite understand your logic
a shortcut for clearing the cache is created in a single instance on the desktop, and you are going to delete it, so clearing will not work.
Try to create a PR, I will consider.

**Comment by KAGEYAM4** [comment]
> I don't quite understand your logic a shortcut for clearing the cache is created in a single instance on the desktop, and you are going to delete it, so clearing will not work. Try to create a PR, I will consider.

Actually i don't know powershell and i have just started learning c++.  
is there no way to get clearCache still work even when shortcut is removed. As you know more than me , please implemet this as you think would be best.

**Comment by amd64fox** [comment]
Ok, I'll think about what can be done to solve

**Comment by amd64fox** [comment]
added
use new input parameter `-no_shortcut`

Also, if you install along with clearing the cache, then clearing will only work if you run the shortcut from here `AppData\Roaming\Microsoft\Windows\Start Menu\Programs`
