### ISSUE TITLE
Some experimental features bugged, namely new lyrics.

### ISSUE THREAD

**Issue by Caketaco** [SpotX-Official/SpotX#109]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/blob/main/.github/Doc/FAQ.md#i-have-an-error--bug--strange-client-behavior-what-can-i-do-">described in the FAQ</a>

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.1.91.824.g07f1e963
- Windows: Windows 10 19031.450
- PowerShell: 5.1.19041.1
```

### 📝 Description

1. Install Spotify (1.1.91.824.g07f1e963)
2. Install SpotX (Install answers: Y, Y, Y, 10)
3. Install Spicetify (optional, the result for me is the same regardless.)
4. Boot Spotify and log in.
5. Play any song and check the lyrics screen to find no visual difference.
6. Visit any public playlist to find no Enhance button.
*For some reason, my "Liked Songs" playlist has the enhance button, but no public playlists have it visible.*

### 📸 Screenshots

![](https://i.imgur.com/5hDzwGQ.gif)
*Liked Songs enhancing works,*
![image](https://user-images.githubusercontent.com/39420594/184012722-46903476-cd56-40e0-ba09-3511953aafb9.png)
*but Public Playlist enhancing is missing.*
![image](https://user-images.githubusercontent.com/39420594/184012768-78f3ad96-20ea-410f-af7d-990ed6c775ef.png)
*Exclude from Recommendations works,*
![image](https://user-images.githubusercontent.com/39420594/184012864-a44f73e0-24fd-404a-a8a1-6fe55e2521ee.png)
*but any signs of the new lyrics screen is nowhere to be seen.*

**Comment by amd64fox** [comment]
Enhancing for a public playlist and shouldn't work, it only works for your playlists, just open your own playlist and there you will see this button

As for the lyrics, can you click on the lyrics to change your position in the track ?

**Comment by Caketaco** [comment]
> Enhancing for a public playlist and shouldn't work, it only works for your playlists, just open your own playlist and there you will see this button

Ah, I see now, gotcha.

> As for the lyrics, can you click on the lyrics to change your position in the track ?

Yes, I can. However, I cannot get them to look like this, with no sidebar on the left:
![](https://github.com/amd64fox/SpotX/raw/main/.github/Pic/Excremental-fun/New-lyrics.gif)

**Comment by Caketaco** [comment]
Nevermind, I just realized that that gif recording is just a cropped recording of the spotify client. Whoops.
Everything is/was working as intended, sorry for any confusion, thank you.

**Comment by amd64fox** [comment]
Yep, I understand that you're confused about the title of the lyrics `fullscreen`. These are the developers of Spotify for some reason called them that, I will correct the description.
Yes, the gif is just cropped, I'll fix it too, thanks for the feedback
