### ISSUE TITLE
Error downloading SpotifySetup.exe

### ISSUE THREAD

**Issue by AshwinKO** [SpotX-Official/SpotX#114]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/discussions/111#discussion-4304353">described in the FAQ</a>

### Сountry of your account

USA

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: not installed
- Windows: 10 20h2
- PowerShell: Version 5.1.19041.610

```

### 📝 Description

1.cant install spot x when running the powershell command it does this
```txt
Downloading and installing Spotify 1.1.92.647
Please wait...


Error downloading SpotifySetup.exe
ScriptHalted

Will re-request in 5 seconds...

Error again
ScriptHalted

Check your network settings and run the installation again

Script is stopped
Press Enter to continue...:
```

also tried running install.bat when opened says access denied press any key to continue
2.
3.
...

**Comment by amd64fox** [comment]
maybe a problem with your `hosts` file, located here `\Windows\System32\drivers\etc`, you can drop it here for check

Also, you didn't enter your version of PowerShell:
In the Windows PowerShell console, type the following command `Get-Host | Select-Object Version`
and update your post above.

Please don't ignore the requirements when creating an issue

**Comment by AshwinKO** [comment]
> maybe a problem with your `hosts` file, located here `\Windows\System32\drivers\etc`, you can drop it here for check
> 
> Also, you didn't enter your version of PowerShell: In the Windows PowerShell console, type the following command `Get-Host | Select-Object Version` and update your post above.
> 
> Please don't ignore the requirements when creating an issue

**Comment by AshwinKO** [comment]
updated the post with powershell version info

**Comment by AshwinKO** [comment]
my host file

```txt
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
```

**Comment by amd64fox** [comment]
Problem solved?

**Comment by amd64fox** [comment]
there was a similar issue [here](https://github.com/mrpond/BlockTheSpot/issues/406), but there the person did not get in touch.

you can try to download Spotify directly from this link
https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.92.647.ga4397eb7-7.exe
Is it loading for you?

**Comment by dustindog101** [comment]
do you have a direct link for netflix? somehow i broke my microsoft store and i cant install anything through it.

**Comment by amd64fox** [comment]
where did you see the netflix discussions here?

**Comment by AshwinKO** [comment]
> there was a similar issue [here](https://github.com/mrpond/BlockTheSpot/issues/406), but there the person did not get in touch.
> 
> you can try to download Spotify directly from this link https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.92.647.ga4397eb7-7.exe Is it loading for you?

yeah mate this seems to work what i did is downloaded spotify from the link you posted and installed it after installing i ran the full installation powershell command and it worked now it shows installation completed in green everything is working fine

i dont understand why i was facing that issue before

**Comment by amd64fox** [comment]
This is all good, but this is a rare problem that has not been resolved, for some reason the client does not download through the script, you can help catch the error

- create a folder on your desktop and name it "test"

- open a PowerShell terminal and run the following command

```ps1
curl.exe https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.92.647.ga4397eb7-7.exe -o $env:USERPROFILE\desktop\test\SpotifySetup.exe --progress-bar --retry 3 --ssl-no-revoke --show-error
```
- take a screenshot of the terminal and add it here

**Comment by AshwinKO** [comment]
> This is all good, but this is a rare problem that has not been resolved, for some reason the client does not download through the script, you can help catch the error
> 
> * create a folder on your desktop and name it "test"
> * open a PowerShell terminal and run the following command
> 
> ```powershell
> curl.exe https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.92.647.ga4397eb7-7.exe -o $env:USERPROFILE\desktop\test\SpotifySetup.exe --progress-bar --retry 3 --ssl-no-revoke --show-error
> ```
> 
> * take a screenshot of the terminal and add it here

this what i got when i ranned  the above script

PS C:\Users\Ashwin K\Desktop\test> curl.exe https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.92.647.ga4397eb7-7.exe -o $env:USERPROFILE\desktop\test\SpotifySetup.exe --progress-bar --retry 3 --ssl-no-revoke --show-error
######################################################################## 100.0%
PS C:\Users\Ashwin K\Desktop\test>

a spotify setup was downloaded on the test folder created on desktop after the script completion

**Comment by amd64fox** [comment]
run the following command

```powershell
curl.exe -I -s https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.92.647.ga4397eb7-7.exe
```

**Comment by AshwinKO** [comment]
> run the following command
> 
> ```powershell
> curl.exe -I -s https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.92.647.ga4397eb7-7.exe
> ```

when i ran the above command nothing happened it showed like this

PS C:\Users\Ashwin K\Desktop\test> curl.exe -I -s https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.92.647.ga4397eb7-7.exe
PS C:\Users\Ashwin K\Desktop\test>

**Comment by amd64fox** [comment]
Ok, this seems to be the problem.
please run this command now to learn more about your curl
```powershell
curl.exe -V
```
Also I tried to fix this error

You can uninstall Spotify and run the SpotX installation again by downloading and running [install.bat](https://raw.githack.com/amd64fox/SpotX/main/Install.bat) as administrator
or
**Run The following command in PowerShell:**
```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content | iex
```

**Comment by AshwinKO** [comment]
> Ok, this seems to be the problem. please run this command now to learn more about your curl
> 
> ```powershell
> curl.exe -V
> ```
> 
> Also I tried to fix this error
> 
> You can uninstall Spotify and run the SpotX installation again by downloading and running [install.bat](https://raw.githack.com/amd64fox/SpotX/main/Install.bat) as administrator or **Run The following command in PowerShell:**
> 
> ```powershell
> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content | iex
> ```

by running the first command "curl.exe -V" i got this

PS C:\Users\Ashwin K\Desktop\test> curl.exe -V
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: 2017-11-14, security patched: 2019-11-05
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL
PS C:\Users\Ashwin K\Desktop\test>


i tried running install.bat file from the link you had posted but it still shows 

Access is denied.
Press any key to continue . . .

i tried running the above powershell command"[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content | iex"    

i got this ***********************
Patch author: @Amd64fox
***********************

Downloading and installing Spotify 1.1.92.647
Please wait...

######################################################################## 100.0%

Do you want to disable podcasts from the main page? [Y/N]: N

Want to block Spotify updates? [Y/N]: N

Want to set up automatic cache cleanup? [Y/N]: Y

Cache older: XX days to be cleared
Enter the number of days from 1 to 100: 30

Patching Spotify...

installation completed


spotify got successfully installed with the above powershell command but still their is some issue with install.bat file

**Comment by amd64fox** [comment]
Since the underlying issue has been resolved, the issue is now closed.

Thank you for your assistance.

**Comment by amd64fox** [comment]
> i tried running install.bat file from the link you had posted but it still shows Access is denied.

Make sure you are using the admin account.

I also recommend updating your Windows 10.

**Comment by AshwinKO** [comment]
> > i tried running install.bat file from the link you had posted but it still shows Access is denied.
> 
> Make sure you are using the admin account.
> 
> I also recommend updating your Windows 10.

iam using it as an admin but still my widows 10 version is old maybe that can be the issue

**Comment by amd64fox** [comment]
@AshwinKO 
if you haven't updated your windows yet then try to run this command in powershell terminal:
```ps1
curl.exe -I https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.92.647.ga4397eb7-7.exe
```
does it show something or is it empty again?

**Comment by AshwinKO** [comment]
> @AshwinKO if you haven't updated your windows yet then try to run this command in powershell terminal:
> 
> ```powershell
> curl.exe -I https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.92.647.ga4397eb7-7.exe
> ```
> 
> does it show something or is it empty again?

when running the above command it shows like this

PS C:\Users\Ashwin K\Desktop\test> curl.exe -I https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.92.647.ga4397eb7-7.exe
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
PS C:\Users\Ashwin K\Desktop\test>

**Comment by amd64fox** [comment]
if this
```powershell
curl.exe -I https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.92.647.ga4397eb7-7.exe --ssl-no-revoke
 ```

**Comment by AshwinKO** [comment]
> if this
> 
> ```powershell
> curl.exe -I https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.92.647.ga4397eb7-7.exe --ssl-no-revoke
> ```

when running the above command it shows this

PS C:\Users\Ashwin K\Desktop\test> curl.exe -I https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.92.647.ga4397eb7-7.exe --ssl-no-revoke
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 78418944
Last-Modified: Tue, 16 Aug 2022 05:00:51 GMT
ETag: "e1e9e0f85afe8837d356da36f823aaf1-15"
Content-Type: application/octet-stream
Surrogate-Key: 7AEA48589588BA34D9E1DB3244A137BDE62C6234E394631BAFE307BBB3D05CA9
Accept-Ranges: bytes
Date: Thu, 25 Aug 2022 14:55:20 GMT
Age: 812650
X-Served-By: cache-dub4350-DUB, cache-bom4737-BOM
X-Cache: HIT, HIT
X-Cache-Hits: 1, 588
Access-Control-Allow-Origin: *
Cache-Control: max-age=315360000, no-transform

PS C:\Users\Ashwin K\Desktop\test>

**Comment by amd64fox** [comment]
Now it's clear that the problem was with the wrong certificate, thanks a lot for the help
