### ISSUE TITLE
The equalizer. It's not coming up.

### ISSUE THREAD

**Issue by Goosemanfuni** [SpotX-Official/SpotX#117]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/discussions/111#discussion-4304353">described in the FAQ</a>

### Сountry of your account

Australia.

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Latest?
- Windows: 10 home
- PowerShell: no idea.
```

### 📝 Description

1. Basically, the equalizer is not coming up as an option in my spotify settings and I do not know how to get the little switch to pop up.
2. Honestly, there is not much else to it.

...

### 📸 Screenshots

<img width="1128" alt="2022-08-19" src="https://user-images.githubusercontent.com/111545638/185518146-42afdd4d-aec8-4dc3-bd15-17641b6db0cf.png">

**Comment by amd64fox** [comment]
In order for the equalizer to appear, you need to use the `usual installation` or `automatic full installation`
