### ISSUE TITLE
How to enable new home structure and navigation (_disabled by default_)

### ISSUE THREAD

**Issue by kunal-jangid** [SpotX-Official/SpotX#120]
How do we enable the new home structure and navigation? If it is disabled by default, there must be some toggle option or code snippet to turn it on, right?

_Posted by @amd64fox in https://github.com/amd64fox/SpotX/discussions/50#discussioncomment-3202577_

**Comment by amd64fox** [comment]
You need to add the incoming parameter `-enablenavalt` to your installer
Learn more about [incoming parameters](https://github.com/amd64fox/SpotX/discussions/60)
