### ISSUE TITLE
 Hindi Translation

### ISSUE THREAD

**Issue by tdivyajyotis** [SpotX-Official/SpotX#124]
### What language do you want to translate into?

Hindi

### Enter language name in PowerShell

hi

### 📝 Translation strings

```txt
Author          = "पैच लेखक:"
Author2         = "@Amd64fox"
TranslationBy   = "अनुवाद लेखक:"
TranslationBy2  = "@tdivyajyotis"
Incorrect       = "ओह,  एक गलत मान,"
Incorrect2      = "के माध्यम से फिर से दर्ज करें "
Download        = "डाउनलोड करने में गड़बड़ी"
Download2       = "5 सेकंड में फिर से अनुरोध करेंगे..."
Download3       = "फिर से गड़बड़ी"
Download4       = "अपनी नेटवर्क सेटिंग्स की जाँच करें और फिर से इंस्टॉलेशन चलाएँ"
Download5       = "स्पॉटिफाई डाउनलोड हो रहा है"
Download6       = "कर्ल एरर"
StopScrpit      = "स्क्रिप्ट बंद हो गई है("
MsSpoti         = "स्पॉटिफाई के माइक्रोसॉफ्ट स्टोर संस्करण का पता चला है जो समर्थित नहीं है"
MsSpoti2        = "स्पॉटिफाई विंडोज स्टोर संस्करण को अनइंस्टॉल करें [Y/N]"
MsSpoti3        = "स्पॉटिफाई एमएस को अपने आप अनइंस्टॉल कर रहा है..."
MsSpoti4        = "स्पॉटिफाई एमएस को अनइंस्टॉल किया जा रहा है..."
Prem            = "प्रीमियम आकाउंट में बदलाव.."
OldV            = "स्पॉटिफाई का पुराना संस्करण मिला"
OldV2           = "आपका स्पॉटिफाई {0} संस्करण पुराना है, इसे {1} में अपग्रेड करने की अनुशंसा की जाती है"
OldV3           = "अपडेट करना चाहते हैं? [Y/N]"
AutoUpd         = "अनुशंसित संस्करण में स्वचालित अपडेट"
DelOrOver       = "क्या आप {0} के वर्तमान संस्करण की स्थापना रद्द करना चाहते हैं या उस पर स्थापित करना चाहते हैं? Y [अनइंस्टॉल करें] / N [इंस्टॉल ओवर करें]("
DelOld          = "पुराने स्पॉटिफाई को अनइंस्टॉल किया जा रहा है..."
NewV            = "स्पॉटिफाई का असमर्थित संस्करण मिला"
NewV2           = "आपके स्पॉटिफाई {0} संस्करण का अभी तक परीक्षण नहीं हुआ है, वर्तमान में यह एक स्थिर {1} संस्करण है"
NewV3           = "क्या आप {0} संस्करण (त्रुटियां संभव) के साथ जारी रखना चाहते हैं? [Y/N]"
Recom           = "क्या आप अनुशंसित {0} संस्करण स्थापित करना चाहते हैं? [Y/N]"
DelNew          = "परीक्षण न किए गए स्पॉटिफाई को अनइंस्टॉल किया जा रहा है..."
DownSpoti       = "स्पॉटिफाई को डाउनलोड और इंस्टॉल किया जा रहा है"
DownSpoti2      = "कृपया प्रतीक्षा करें..."
PodcatsOff      = "पॉडकास्ट बंद "
PodcastsOn      = "पॉडकास्ट चालू"
PodcatsSelect   = "क्या आप मुख्य पृष्ठ से पॉडकास्ट अक्षम करना चाहते हैं? [Y/N]"
DowngradeNote   = "इसे अवरुद्ध करने की अनुशंसा की जाती है क्योंकि स्पॉटिफाई का डाउनग्रेड था"
UpdBlock        = "स्पॉटिफाई अपडेट ब्लॉक किए गए"
UpdUnblock      = "स्पॉटिफाई अपडेट ब्लॉक नहीं हैं"
UpdSelect       = "स्पॉटिफाई अपडेट को ब्लॉक करना चाहते हैं? [Y/N]"
CacheOn         = "कैशे साफ़ करें सक्षम किया गया ({0})"
CacheOff        = "कैशे साफ़ करना सक्षम नहीं है"
CacheSelect     = "स्वचालित कैश सफाई सेट करना चाहते हैं? [Y/N]"
CacheDays       = "कैश पुराना: XX दिन साफ़ किया जाना है"
CacheDays2      = "1 से 100 तक दिनों की संख्या दर्ज करें"
NoVariable      = "वरिअब्ले नहीं मिला"
NoVariable2     = "xpui.js में"
NoVariable3     = "licenses.html में"
NoVariable4     = "html में"
ModSpoti        = "स्पॉटिफाई पैचिंग..."
Error           = "गडबड"
FileLocBroken   = "स्पॉटिफाई  फ़ाइलों का स्थान टूटा हुआ है, क्लाइंट की स्थापना रद्द करें और स्क्रिप्ट को फिर से चलाएँ"
Spicetify       = "स्पाइसीफाई का पता चला"
NoRestore       = "स्पॉटएक्स पहले ही स्थापित किया जा चुका है, लेकिन xpui.js.bak और xpui.css.bak को पुनर्प्राप्त करने के लिए फ़ाइलें नहीं मिलीं। कृपया स्पॉटिफाई क्लाइंट को अनइंस्टॉल करें और Install.bat को फिर से चलाएं"
ExpSpotify      = "स्पॉटिफाई द्वारा संचालित प्रायोगिक सुविधाएं"
ExpStandart     = "स्पॉटएक्स की प्रायोगिक विशेषताएं शामिल नहीं हैं"
NoRestore2      = "स्पॉटएक्स पहले ही स्थापित किया जा चुका है, xpui.bak नहीं मिला। कृपया स्पॉटिफाई क्लाइंट को अनइंस्टॉल करें और Install.bat को फिर से चलाएं"
UpdateBlocked   = "स्पॉटिफाई अपडेट पहले से ही ब्लॉक हैं"
UpdateError     = "अपडेट ब्लॉक करने में विफल"
NoSpotifyExe    = "Spotify.exe नहीं मिल सका"
InstallComplete = "इंस्टालेशन पूर्ण"
HostInfo        = "hosts फ़ाइल में अवांछित URL मिले"
HostBak         = "hosts.bak का बैकअप ले जा रहा है..."
HostDel         = "मूल होस्ट फ़ाइल से अवांछित URL निकालने का प्रयास किया जा रहा है..."
HostError       = "होस्ट फ़ाइल को संपादित करते समय कुछ गलत हो गया, इसे मैन्युअल रूप से संपादित करें या स्क्रिप्ट को व्यवस्थापक के रूप में चलाएं"
```

**Comment by amd64fox** [comment]
In this form, you have to translate the strings from English into your language yourself, are you ready to do this?

**Comment by tdivyajyotis** [comment]
> In this form, you have to translate the strings from English into your language yourself, are you ready to do this?

yeah done man

updated the comment

**Comment by tdivyajyotis** [comment]
@amd64fox add these to the main script
marking as closed

**Comment by amd64fox** [comment]
Thanks

Line break character <kbd>`n</kbd> was removed from the <kbd>NoRestore</kbd> and <kbd>NoRestore2</kbd> lines, could you please put it back in place.

Also, please run the following code in the PowerShell terminal, this is necessary to check if the font is displayed correctly:

```ps1
$langStringsHI = @{
  TranslationBy   = "अनुवाद लेखक:"
}
$langStringsHI
```

If the Hindi language is set by default on your Windows system, then the font should be displayed correctly

**Comment by tdivyajyotis** [comment]
📝 Translation strings
```txt
Author          = "पैच लेखक:"
Author2         = "@Amd64fox"
TranslationBy   = "अनुवाद लेखक:"
TranslationBy2  = "@tdivyajyotis"
Incorrect       = "ओह,  एक गलत मान,"
Incorrect2      = "के माध्यम से फिर से दर्ज करें "
Download        = "डाउनलोड करने में गड़बड़ी"
Download2       = "5 सेकंड में फिर से अनुरोध करेंगे..."
Download3       = "फिर से गड़बड़ी"
Download4       = "अपनी नेटवर्क सेटिंग्स की जाँच करें और फिर से इंस्टॉलेशन चलाएँ"
Download5       = "स्पॉटिफाई डाउनलोड हो रहा है"
Download6       = "कर्ल एरर"
StopScrpit      = "स्क्रिप्ट बंद हो गई है("
MsSpoti         = "स्पॉटिफाई के माइक्रोसॉफ्ट स्टोर संस्करण का पता चला है जो समर्थित नहीं है"
MsSpoti2        = "स्पॉटिफाई विंडोज स्टोर संस्करण को अनइंस्टॉल करें [Y/N]"
MsSpoti3        = "स्पॉटिफाई एमएस को अपने आप अनइंस्टॉल कर रहा है..."
MsSpoti4        = "स्पॉटिफाई एमएस को अनइंस्टॉल किया जा रहा है..."
Prem            = "प्रीमियम आकाउंट में बदलाव.."
OldV            = "स्पॉटिफाई का पुराना संस्करण मिला"
OldV2           = "आपका स्पॉटिफाई {0} संस्करण पुराना है, इसे {1} में अपग्रेड करने की अनुशंसा की जाती है"
OldV3           = "अपडेट करना चाहते हैं? [Y/N]"
AutoUpd         = "अनुशंसित संस्करण में स्वचालित अपडेट"
DelOrOver       = "क्या आप {0} के वर्तमान संस्करण की स्थापना रद्द करना चाहते हैं या उस पर स्थापित करना चाहते हैं? Y [अनइंस्टॉल करें] / N [इंस्टॉल ओवर करें]("
DelOld          = "पुराने स्पॉटिफाई को अनइंस्टॉल किया जा रहा है..."
NewV            = "स्पॉटिफाई का असमर्थित संस्करण मिला"
NewV2           = "आपके स्पॉटिफाई {0} संस्करण का अभी तक परीक्षण नहीं हुआ है, वर्तमान में यह एक स्थिर {1} संस्करण है"
NewV3           = "क्या आप {0} संस्करण (त्रुटियां संभव) के साथ जारी रखना चाहते हैं? [Y/N]"
Recom           = "क्या आप अनुशंसित {0} संस्करण स्थापित करना चाहते हैं? [Y/N]"
DelNew          = "परीक्षण न किए गए स्पॉटिफाई को अनइंस्टॉल किया जा रहा है..."
DownSpoti       = "स्पॉटिफाई को डाउनलोड और इंस्टॉल किया जा रहा है"
DownSpoti2      = "कृपया प्रतीक्षा करें..."
PodcatsOff      = "पॉडकास्ट बंद "
PodcastsOn      = "पॉडकास्ट चालू"
PodcatsSelect   = "क्या आप मुख्य पृष्ठ से पॉडकास्ट अक्षम करना चाहते हैं? [Y/N]"
DowngradeNote   = "इसे अवरुद्ध करने की अनुशंसा की जाती है क्योंकि स्पॉटिफाई का डाउनग्रेड था"
UpdBlock        = "स्पॉटिफाई अपडेट ब्लॉक किए गए"
UpdUnblock      = "स्पॉटिफाई अपडेट ब्लॉक नहीं हैं"
UpdSelect       = "स्पॉटिफाई अपडेट को ब्लॉक करना चाहते हैं? [Y/N]"
CacheOn         = "कैशे साफ़ करें सक्षम किया गया ({0})"
CacheOff        = "कैशे साफ़ करना सक्षम नहीं है"
CacheSelect     = "स्वचालित कैश सफाई सेट करना चाहते हैं? [Y/N]"
CacheDays       = "कैश पुराना: XX दिन साफ़ किया जाना है"
CacheDays2      = "1 से 100 तक दिनों की संख्या दर्ज करें"
NoVariable      = "वरिअब्ले नहीं मिला"
NoVariable2     = "xpui.js में"
NoVariable3     = "licenses.html में"
NoVariable4     = "html में"
ModSpoti        = "स्पॉटिफाई पैचिंग..."
Error           = "गडबड"
FileLocBroken   = "स्पॉटिफाई  फ़ाइलों का स्थान टूटा हुआ है, क्लाइंट की स्थापना रद्द करें और स्क्रिप्ट को फिर से चलाएँ"
Spicetify       = "स्पाइसीफाई का पता चला"
NoRestore       = "स्पॉटएक्स पहले ही स्थापित किया जा चुका है, लेकिन xpui.js.bak और xpui.css.bak को पुनर्प्राप्त करने के लिए फ़ाइलें नहीं मिलीं। `nकृपया स्पॉटिफाई क्लाइंट को अनइंस्टॉल करें और Install.bat को फिर से चलाएं"
ExpSpotify      = "स्पॉटिफाई द्वारा संचालित प्रायोगिक सुविधाएं"
ExpStandart     = "स्पॉटएक्स की प्रायोगिक विशेषताएं शामिल नहीं हैं"
NoRestore2      = "स्पॉटएक्स पहले ही स्थापित किया जा चुका है, xpui.bak नहीं मिला। `nकृपया स्पॉटिफाई क्लाइंट को अनइंस्टॉल करें और Install.bat को फिर से चलाएं"
UpdateBlocked   = "स्पॉटिफाई अपडेट पहले से ही ब्लॉक हैं"
UpdateError     = "अपडेट ब्लॉक करने में विफल"
NoSpotifyExe    = "Spotify.exe नहीं मिल सका"
InstallComplete = "इंस्टालेशन पूर्ण"
HostInfo        = "hosts फ़ाइल में अवांछित URL मिले"
HostBak         = "hosts.bak का बैकअप ले जा रहा है..."
HostDel         = "मूल होस्ट फ़ाइल से अवांछित URL निकालने का प्रयास किया जा रहा है..."
HostError       = "होस्ट फ़ाइल को संपादित करते समय कुछ गलत हो गया, इसे मैन्युअल रूप से संपादित करें या स्क्रिप्ट को व्यवस्थापक के रूप में चलाएं"
```

**Comment by tdivyajyotis** [comment]
> 📝 Translation strings
> 
> ```
> Author          = "पैच लेखक:"
> Author2         = "@Amd64fox"
> TranslationBy   = "अनुवाद लेखक:"
> TranslationBy2  = "@tdivyajyotis"
> Incorrect       = "ओह,  एक गलत मान,"
> Incorrect2      = "के माध्यम से फिर से दर्ज करें "
> Download        = "डाउनलोड करने में गड़बड़ी"
> Download2       = "5 सेकंड में फिर से अनुरोध करेंगे..."
> Download3       = "फिर से गड़बड़ी"
> Download4       = "अपनी नेटवर्क सेटिंग्स की जाँच करें और फिर से इंस्टॉलेशन चलाएँ"
> Download5       = "स्पॉटिफाई डाउनलोड हो रहा है"
> Download6       = "कर्ल एरर"
> StopScrpit      = "स्क्रिप्ट बंद हो गई है("
> MsSpoti         = "स्पॉटिफाई के माइक्रोसॉफ्ट स्टोर संस्करण का पता चला है जो समर्थित नहीं है"
> MsSpoti2        = "स्पॉटिफाई विंडोज स्टोर संस्करण को अनइंस्टॉल करें [Y/N]"
> MsSpoti3        = "स्पॉटिफाई एमएस को अपने आप अनइंस्टॉल कर रहा है..."
> MsSpoti4        = "स्पॉटिफाई एमएस को अनइंस्टॉल किया जा रहा है..."
> Prem            = "प्रीमियम आकाउंट में बदलाव.."
> OldV            = "स्पॉटिफाई का पुराना संस्करण मिला"
> OldV2           = "आपका स्पॉटिफाई {0} संस्करण पुराना है, इसे {1} में अपग्रेड करने की अनुशंसा की जाती है"
> OldV3           = "अपडेट करना चाहते हैं? [Y/N]"
> AutoUpd         = "अनुशंसित संस्करण में स्वचालित अपडेट"
> DelOrOver       = "क्या आप {0} के वर्तमान संस्करण की स्थापना रद्द करना चाहते हैं या उस पर स्थापित करना चाहते हैं? Y [अनइंस्टॉल करें] / N [इंस्टॉल ओवर करें]("
> DelOld          = "पुराने स्पॉटिफाई को अनइंस्टॉल किया जा रहा है..."
> NewV            = "स्पॉटिफाई का असमर्थित संस्करण मिला"
> NewV2           = "आपके स्पॉटिफाई {0} संस्करण का अभी तक परीक्षण नहीं हुआ है, वर्तमान में यह एक स्थिर {1} संस्करण है"
> NewV3           = "क्या आप {0} संस्करण (त्रुटियां संभव) के साथ जारी रखना चाहते हैं? [Y/N]"
> Recom           = "क्या आप अनुशंसित {0} संस्करण स्थापित करना चाहते हैं? [Y/N]"
> DelNew          = "परीक्षण न किए गए स्पॉटिफाई को अनइंस्टॉल किया जा रहा है..."
> DownSpoti       = "स्पॉटिफाई को डाउनलोड और इंस्टॉल किया जा रहा है"
> DownSpoti2      = "कृपया प्रतीक्षा करें..."
> PodcatsOff      = "पॉडकास्ट बंद "
> PodcastsOn      = "पॉडकास्ट चालू"
> PodcatsSelect   = "क्या आप मुख्य पृष्ठ से पॉडकास्ट अक्षम करना चाहते हैं? [Y/N]"
> DowngradeNote   = "इसे अवरुद्ध करने की अनुशंसा की जाती है क्योंकि स्पॉटिफाई का डाउनग्रेड था"
> UpdBlock        = "स्पॉटिफाई अपडेट ब्लॉक किए गए"
> UpdUnblock      = "स्पॉटिफाई अपडेट ब्लॉक नहीं हैं"
> UpdSelect       = "स्पॉटिफाई अपडेट को ब्लॉक करना चाहते हैं? [Y/N]"
> CacheOn         = "कैशे साफ़ करें सक्षम किया गया ({0})"
> CacheOff        = "कैशे साफ़ करना सक्षम नहीं है"
> CacheSelect     = "स्वचालित कैश सफाई सेट करना चाहते हैं? [Y/N]"
> CacheDays       = "कैश पुराना: XX दिन साफ़ किया जाना है"
> CacheDays2      = "1 से 100 तक दिनों की संख्या दर्ज करें"
> NoVariable      = "वरिअब्ले नहीं मिला"
> NoVariable2     = "xpui.js में"
> NoVariable3     = "licenses.html में"
> NoVariable4     = "html में"
> ModSpoti        = "स्पॉटिफाई पैचिंग..."
> Error           = "गडबड"
> FileLocBroken   = "स्पॉटिफाई  फ़ाइलों का स्थान टूटा हुआ है, क्लाइंट की स्थापना रद्द करें और स्क्रिप्ट को फिर से चलाएँ"
> Spicetify       = "स्पाइसीफाई का पता चला"
> NoRestore       = "स्पॉटएक्स पहले ही स्थापित किया जा चुका है, लेकिन xpui.js.bak और xpui.css.bak को पुनर्प्राप्त करने के लिए फ़ाइलें नहीं मिलीं। `nकृपया स्पॉटिफाई क्लाइंट को अनइंस्टॉल करें और Install.bat को फिर से चलाएं"
> ExpSpotify      = "स्पॉटिफाई द्वारा संचालित प्रायोगिक सुविधाएं"
> ExpStandart     = "स्पॉटएक्स की प्रायोगिक विशेषताएं शामिल नहीं हैं"
> NoRestore2      = "स्पॉटएक्स पहले ही स्थापित किया जा चुका है, xpui.bak नहीं मिला। `nकृपया स्पॉटिफाई क्लाइंट को अनइंस्टॉल करें और Install.bat को फिर से चलाएं"
> UpdateBlocked   = "स्पॉटिफाई अपडेट पहले से ही ब्लॉक हैं"
> UpdateError     = "अपडेट ब्लॉक करने में विफल"
> NoSpotifyExe    = "Spotify.exe नहीं मिल सका"
> InstallComplete = "इंस्टालेशन पूर्ण"
> HostInfo        = "hosts फ़ाइल में अवांछित URL मिले"
> HostBak         = "hosts.bak का बैकअप ले जा रहा है..."
> HostDel         = "मूल होस्ट फ़ाइल से अवांछित URL निकालने का प्रयास किया जा रहा है..."
> HostError       = "होस्ट फ़ाइल को संपादित करते समय कुछ गलत हो गया, इसे मैन्युअल रूप से संपादित करें या स्क्रिप्ट को व्यवस्थापक के रूप में चलाएं"
> ```

added newline characters

I dont use Hindi as my primary language on my PC, I'm trilingual and use English as my default language.
Do we have any other way of testing the powershell characters?

![image](https://user-images.githubusercontent.com/86727214/187066922-7231f5f6-6a80-4ff2-8c49-13403f991f91.png)

**Comment by tdivyajyotis** [comment]
![image](https://user-images.githubusercontent.com/86727214/187067134-24cbe126-840d-45b6-9cc2-baf63568ae58.png)
If this helps, Powershell Interpreter at https://tio.run works fine!
(both in Powershell & Powershell Core interpreters)
PS- [tio.run](https://tio.run/##K8gvTy0qzkjNyfn/XyUnMS89uKQoMy@92MNTwVbBoZpLQSGkKDGvOCexJDM/z6lSQQEorPRgSeuDJSseLG18sGTrgyX7HixZpvBgyaYHS9sfLJn2YMlUKyWuWi5Uw/7/BwA)
PS Core- [tio.run](https://tio.run/##K8gvTy0qzkjNydFNzi9K/f9fJScxLz24pCgzL73Yw1PBVsGhmktBIaQoMa84J7EkMz/PqVJBASis9GBJ64MlKx4sbXywZOuDJfseLFmm8GDJpgdL2x8smfZgyVQrJa5aLlTD/v8HAA)

**Comment by tdivyajyotis** [comment]
changed language to hindi
still doesnt work

I have windows 10 hsl (single language) that may cause this
![image](https://user-images.githubusercontent.com/86727214/187068536-a6ed6a76-5081-4d79-bd54-4fa76d02ca0d.png)
![image](https://user-images.githubusercontent.com/86727214/187068576-685a1d9e-7765-45f6-80d5-6af6f68c039a.png)

**Comment by amd64fox** [comment]
the simplest solution to this problem is to use [terminal windows](https://docs.microsoft.com/en-us/windows/terminal/install)
and also you can read this [post](https://github.com/amd64fox/SpotX/issues/106#issuecomment-1212741854)

Translation will be added after some time. Thank you for your contribution.

**Comment by tdivyajyotis** [comment]
> the simplest solution to this problem is to use [terminal windows](https://docs.microsoft.com/en-us/windows/terminal/install) and also you can read this [post](https://github.com/amd64fox/SpotX/issues/106#issuecomment-1212741854)
> 
> Translation will be added after some time. Thank you for your contribution.

terminal windows is windows 11 only right?

also changing font to simsun-ext8 doesnt work and the force utf8 profile didnt work either

**Comment by amd64fox** [comment]
works at 10 too

**Comment by tdivyajyotis** [comment]
> works at 10 too

oh okay i'll try 

thanks for spotx , works wonderfully and is a lot better than using ublock on firefox for spotify ! 👍
