### ISSUE TITLE
Navigation buttons overlap with the more options toggle in the "unreleased" home structure.

### ISSUE THREAD

**Issue by twistedmacaroni** [SpotX-Official/SpotX#125]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/discussions/111#discussion-4304353">described in the FAQ</a>

### Сountry of your account

USA

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.92.647.ga4397eb7
- Windows: Windows 11 21H2 22000.588
- PowerShell: 5.1.22000.588
```

### 📝 Description

The navigation buttons (back/ forward) overlap with the more options button on the top left.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/93189292/187067460-e3bf8556-75fb-4499-adfc-d0d12415c960.png)

**Comment by amd64fox** [comment]
yes I saw this bug, this Spotify theme is still in development. Maybe this will be fixed in the new version.

**Comment by amd64fox** [comment]
in version 93, the devs didn't fix it again so I temporarily fixed the indentation in the css myself.

**Comment by JourneyOver** [comment]
@amd64fox zooming the client out it still ends up overlapping a bit. Hopefully the spotify devs end up fixing it soon enough.
