### ISSUE TITLE
Kaspersky blocks the install.bat file

### ISSUE THREAD

**Issue by Nicola001** [SpotX-Official/SpotX#126]
### Description of the new feature / enhancement

Event: Malicious object detected
Component: Application Control
Result Description: Detected
Type: Trojan
Name: UDS:Trojan.Win32.Pits
Danger Level: High
Object Path: C:\Users\nicol\Desktop\SpotX-main
Object Name: Install.bat
Reason: Cloud protection
MD5: AC7C923CA3EF2933B47AC086AC7B9269

**Comment by amd64fox** [comment]
Duplicate of https://github.com/amd64fox/SpotX/issues/89

**Comment by amd64fox** [comment]
Please use the [bug report](https://github.com/amd64fox/SpotX/issues/new?assignees=&labels=%E2%9D%8C+bug&template=bug_report.yml) form, this is a form for ideas.

**Comment by n00bje** [comment]
It's probably heuristics because the .bat file downloads a Powershell script from the internet and executes it, which is common malware behavior.
Try downloading install.ps1 yourself and run it. It'll probably won't be blocked.
