### ISSUE TITLE
Sponsored and audio ads come through on the latest version of Spotify (1.1.69.612)

### ISSUE THREAD

**Issue by MathewJake365** [SpotX-Official/SpotX#13]
But I haven't seen pop-ups and video ads. And the ad placeholder and the "UPGRADE" button are gone. 
Which means you're heading the right way.

```
LOG | 01-Oct-2021 20:29:54 - GetModuleInformation OK!
LOG | 01-Oct-2021 20:29:54 - main process - patch failed!
LOG | 01-Oct-2021 20:29:54 - main process 1.1.66.578.gc54d0f69-a - patch failed!
```

**Comment by amd64fox** [comment]
My patch works in conjunction with BTS, so there are problems here too, we are waiting for Bts to be fixed ...

**Comment by amd64fox** [comment]
Bts has been fixed.
