### ISSUE TITLE
Audio Premium Ads still appearing.

### ISSUE THREAD

**Issue by Thechugg7** [SpotX-Official/SpotX#130]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/discussions/111#discussion-4304353">described in the FAQ</a>

### Сountry of your account

France

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.93.896.g3ae3b4f3
- Windows: Windows 10 Pro 21H2 19044.1889
- PowerShell: 5.1.19041.1682
```

### 📝 Description

1. I listen to around 4/5 songs for 20 minutes.
2. Audio ad teling me to swap to premium.

**Comment by amd64fox** [comment]
What installer did you use? 

Were there any errors in the console during installation?

Do you confirm that after receiving the audio ad, you completely uninstalled the client, and did a clean install as described in the FAQ ?

**Comment by Thechugg7** [comment]
After reinstalling from scratch the ads appear to be gone, it seems the install I used didn't disable automatic updates, one of those updates might have reactivated ads.
