### ISSUE TITLE
Create similar playlist option for all playlists

### ISSUE THREAD

**Issue by Ximzend** [SpotX-Official/SpotX#131]
### Description of the new feature / enhancement

Now only your own playlists have the option Create similar playlist.
If you want to create a similar playlist of someone else's playlist, you now have to copy the tracks of the source playlist into your own playlist first.
If SpotX could enable it for all playlists, this process will be as quick as two clicks instead of multiple.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/16002400/188496514-052bb274-0cfe-421e-9863-79f87615948b.png)

**Comment by amd64fox** [comment]
This would most likely require rewriting Spotify's native functions, I'm too bad at JS.

Try to [create a request](https://github.com/spicetify/spicetify-cli/issues/new?assignees=&labels=%E2%9C%A8+feature&template=feature_request.yml) to create a new extension in Spicetify, maybe they will help you there.

**Comment by amd64fox** [comment]
as it turned out it was not so difficult

![Снимок экрана 2022-09-06 050416](https://user-images.githubusercontent.com/62529699/188531567-418175ed-0629-496d-a204-95f70d6cf027.jpg)

added, update spotx
