### ISSUE TITLE
Add SpotX to Chocolatey

### ISSUE THREAD

**Issue by PachiMc** [SpotX-Official/SpotX#135]

**Comment by amd64fox** [comment]
Know how to do it?

**Comment by PachiMc** [comment]
> Know how to do it?

I thinks is
choco new SpotX

https://docs.chocolatey.org/en-us/features/create-packages

**Comment by amd64fox** [comment]
I understand that need to create a new package

i mean, can you do it?

I unfortunately, do not have time to study the documentation now, if someone does this, I will not mind

**Comment by CDzungx** [comment]
Why need to add to Chocolatey? Just a copy-paste command 😂 There are many options user has to choose in SpotX while installing and both SpotX and Chocolatey need to open Powershell. This maybe also violate the Chocolatey rule.
![image](https://user-images.githubusercontent.com/59353870/192081530-22a31f48-2e75-4865-97ff-ed232e06e5c6.png)

**Comment by amd64fox** [comment]
Closed for now, if anyone wants to do it please let me know.
