### ISSUE TITLE
Playlist folders

### ISSUE THREAD

**Issue by GebruikerR** [SpotX-Official/SpotX#136]
### Description of the new feature / enhancement

I don't know if this is possible, but having playlist folders would be a really nice feature.

**Comment by amd64fox** [comment]
![Снимок экрана 2022-09-09 150935](https://user-images.githubusercontent.com/62529699/189346861-38b2ef40-8b47-4784-a1aa-e3eef56cd2d4.jpg)

**Comment by GebruikerR** [comment]
O, didn't know that. Sorry for unnecessary issue.
