### ISSUE TITLE
[BUG] Very High sound quality does not appear when using a premium account

### ISSUE THREAD

**Issue by ghost** [SpotX-Official/SpotX#138]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/discussions/111#discussion-4304353">described in the FAQ</a>

### Сountry of your account

United Kingdom

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.93.896.g3ae3b4f3
- Windows: 10
```

### 📝 Description

The Very High setting is removed even though I should normally have access to it. (Since I use my premium account)

**Comment by amd64fox** [comment]
did you use the installation for premium account ?

**Comment by ghost** [comment]
> did you use the installation for premium account ?

Could you please link me to it?

**Comment by amd64fox** [comment]
Find `Installation for premium` in [installation type](https://github.com/amd64fox/SpotX#choose-installation-type)
