### ISSUE TITLE
Discord bypass Spotify pause

### ISSUE THREAD

**Issue by BUZZARDGTA** [SpotX-Official/SpotX#139]
### Description of the new feature / enhancement

When we listen Spotify music while in a Discord VC, the music pauses.
Would you eventually be able to find a bypass for it not to pause anymore, like it used to be?

**Comment by xBiei** [comment]
this is due to discord sending pause request to spotify api
you can disable it using discord's clients not spotify's since you can't block that specific request afaik.

**Comment by eshaane** [comment]
Use betterdiscord and use the spotify no pause patch

**Comment by xBiei** [comment]
or [replugged](https://github.com/replugged-org/replugged) with [spotify-modal](https://github.com/replugged-org/spotify-modal) plugin

**Comment by BUZZARDGTA** [comment]
Thank you guys!
