### ISSUE TITLE
"Oops, default desktop folder not found, cache clearing installation stopped"

### ISSUE THREAD

**Issue by BUZZARDGTA** [SpotX-Official/SpotX#14]
![cmd_2021-10-08_17-14](https://user-images.githubusercontent.com/62464560/136581633-c70018a9-4f0e-46d0-ae87-6734230a422b.png)

This issue is caused because I've changed the PATH from my desktop to an other drive letter.
You can easily fix this issue using the following RegEdit key: `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders\Desktop` instead of `%USERPROFILE%\Desktop`.
Thanks for your awesome application, in the hope of a bug-fix, I wish you a nice day.

**Comment by amd64fox** [comment]
Thanks for your hint, completely forgot about this problem with the moved desktop folder.

Fixed.

**Comment by BUZZARDGTA** [comment]
Thanks for fixing the issue, it now works perfectly.
btw, it's an amazing project, keep it UP!

**Comment by amd64fox** [comment]
Thank you for the kind words, all the best to you )

**Comment by BUZZARDGTA** [comment]
and you as well
