### ISSUE TITLE
Problem with the SpotX

### ISSUE THREAD

**Issue by VortexV1perZ** [SpotX-Official/SpotX#140]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [ ] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/discussions/111#discussion-4304353">described in the FAQ</a>

### Сountry of your account

Philippines

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows
1.1.93.896.g3ae3b4f3
- Windows: Edition	Windows 11 Pro
Version	21H2
Installed on	‎2/‎25/‎2022
OS build	22000.856
Experience	Windows Feature Experience Pack 1000.22000.856.0

- PowerShell: 5.1.22000.832
```

### 📝 Description

1. After a random song a ad plays and when I do it again it just says Didn't find variable and then installation complete any fix on this bug?
2.
3.
...

### 📸 Screenshots

![Uploading image_2022-09-12_162703380.png…]()

**Comment by amd64fox** [comment]
Before creating a issue, you should read the [FAQ](https://github.com/amd64fox/SpotX/discussions/111) and perform a clean install, and for some reason you do the opposite.
