### ISSUE TITLE
The ability to disable the "New home structure and navigation" feature through spotify settings 

### ISSUE THREAD

**Issue by ghost** [SpotX-Official/SpotX#144]
### Description of the new feature / enhancement

- 1 i would like to tell you that it would be great if u can add a button in the settings menu for turing on or off the "New home structure and navigation"
- 2 it would be very helpfull 
- 3 Thank you

**Comment by amd64fox** [comment]
you need to add the [incoming parameter](https://github.com/amd64fox/SpotX/discussions/60) `-navalt_off` to the installer.

**Comment by ghost** [comment]
thnx but still if u can implement it ,it would be very helpfull still thanks :)
