### ISSUE TITLE
install.bat not working

### ISSUE THREAD

**Issue by yuliy1wnl** [SpotX-Official/SpotX#145]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/discussions/111#discussion-4304353">described in the FAQ</a>

### Сountry of your account

USA

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify:1.1.93.896.g3ae3b4f3
- Windows: Windows 10 20h2 19042.1706
- PowerShell: 5.1.19041.1682
```

### 📝 Description

1.running the install bat file shows error
2.
3.
...

### 📸 Screenshots

![Screenshot (47)](https://user-images.githubusercontent.com/76037332/190676514-eaebabc3-50ba-42cc-b6b7-3d640a6a62d4.png)

**Comment by amd64fox** [comment]
can you open this link in your browser ?
https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1

**Comment by yuliy1wnl** [comment]
not working 
![image](https://user-images.githubusercontent.com/76037332/190678096-23820279-b044-488f-b18f-534a2ea0d02b.png)

**Comment by amd64fox** [comment]
This is problems with your connection, your internet provider is blocking access to GitHub resources, you can either change network or use VPN

**Comment by yuliy1wnl** [comment]
it worked thanks
