### ISSUE TITLE
Spotify wont start

### ISSUE THREAD

**Issue by nanchaara** [SpotX-Official/SpotX#15]
i have tried this, and BlockTheSpot, and its all the same
can you help me to fix it?

**Comment by amd64fox** [comment]
Hi, please describe your problem in more detail, how did you install the patch point by point? What version of Spotify and Windows you have, have you tried uninstalling Spotify (Spicetify) completely and try running Install.bat again? In case of an error, attach a screenshot here.

**Comment by nanchaara** [comment]
hi thanks for responding, 
1. yes, i installed the patch point by point, which download the zip, and run the install.bat
2. Latest version of Spotify  : 1.1.72.439.gc253025e
and 
Latest version of Windows 11 
Edition	Windows 11 Pro
Version	21H2
Installed on	‎21-‎Oct-‎21
OS build	22000.318
Experience	Windows Feature Experience Pack 1000.22000.318.0

3. i tried uninstall the spotify (not the spicetify), but it still doesnt work
the spotify works fine with the spicetify, its broken when i installed the adblocker

**Comment by amd64fox** [comment]
How does your mistake manifest itself? Spotify won't start? or do you mean an error in the console after running Install.bat?

**Comment by nanchaara** [comment]
yes, spotify wont start and after like 20 seconds windows message will pop up says "Spotify not responding"
the install.bat installation was fine, nothing is weird

**Comment by amd64fox** [comment]
Try to uninstall Spotify again:
- Press `Win + R` and enter `appwiz.cpl.`
- Find Spotify in the list and delete it
- Then press again `Win + R` and enter `%APPDATA%`  
- Check if the Spotify folder exists there, if it is, then you need to delete it manually, do the same for `%localappdata%`
- Reboot your PC
- After reboot, download and run the latest [Install.bat](https://cutt.ly/PErptD8)

Note: Do not use `spicetify` during this instruction.

**Comment by nanchaara** [comment]
ok, i'll try it

**Comment by nanchaara** [comment]
its working!
so the problem is on the spicetify?

**Comment by amd64fox** [comment]
Try to install now spicetify

**Comment by nanchaara** [comment]
its working well too, but does your patch block this kind of ad to? or no? 
![image](https://user-images.githubusercontent.com/71387731/141613646-492c7803-82df-4977-800c-c8f4dbb4735a.png)

**Comment by amd64fox** [comment]
My patch is blocking just like Bts and more. 

After installing spicetify, you may need to run Install.bat again

**Comment by nanchaara** [comment]
finally its workinggg
thank you so much
so if in the future i got same error, the step will be :
1. reinstall the spotify
2. install ur adblock
3. install spicetify
4. then install the ur adblock once again

right?

**Comment by amd64fox** [comment]
If a similar error occurs then:
- Start with this [instruction](https://github.com/amd64fox/SpotX/issues/15#issuecomment-967878650)
- Then download and install the latest [official version](https://download.scdn.co/SpotifyFullSetup.exe)
- Install spicetify
- Install my patch or Bts

Important: You may need to run `Install.bat` again after running `spicetify apply` or other commands

**Comment by nanchaara** [comment]
ah i get it now, thank you for your help!
appreciate it a lot!
