### ISSUE TITLE
Spotify shortcut pinned in taskbar shows a different icon and name

### ISSUE THREAD

**Issue by randomcloudswings** [SpotX-Official/SpotX#152]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/discussions/111#discussion-4304353">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.94.870
- Windows: 10
- PowerShell:
```

### 📝 Description

1. Did a clean install of spotify and spotx
2. Pinned spotify to taskbar
3. Icon and name is not same as spotify
...

### 📸 Screenshots

![Screenshot (42)](https://user-images.githubusercontent.com/90744124/190870743-beb6272e-0704-4bd1-8e44-2ea6e3522621.png)

**Comment by amd64fox** [comment]
this is due to the fact that you have set automatic cache cleaning, if you need to have an icon on the bottom panel, then you can simply create a shortcut from the original Spotfiy.exe file or simply do not activate cache cleaning during the installation of spotx
