### ISSUE TITLE
the profile icon is too far to the right that it bumps into the minimize button

### ISSUE THREAD

**Issue by SuperCuek** [SpotX-Official/SpotX#157]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/discussions/111#discussion-4304353">described in the FAQ</a>

### Сountry of your account

Indonesia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.94.872.g7a9200fe
- Windows: Win10 22H2 19045.2006
- PowerShell: 5.1.19041.1682
```

### 📝 Description

bug?

![image](https://user-images.githubusercontent.com/104664907/191878324-0af92e4b-d92c-4c26-b6d8-9321a01d1f73.png)

**Comment by amd64fox** [comment]
did you zoom out in settings?

**Comment by NeuroCPP** [comment]
zooming out too much might do this 
![image](https://user-images.githubusercontent.com/85978957/191923024-fd8430e0-dea7-47d7-ac74-e475f15aa09e.png)

**Comment by amd64fox** [comment]
@NeuroCPP 
the author of the issue has a new theme, and you have an old one

but both the old and the new theme have problems if you use Zoom

**Comment by SuperCuek** [comment]
> did you zoom out in settings?

yes...2x zoom out

**Comment by amd64fox** [comment]
The problem is not SpotX,
You have two options, either don't resize the theme or use the `-navalt_off` [input parameter](https://github.com/amd64fox/SpotX/discussions/60) to set the old theme, but the old theme has problems with that too.
