### ISSUE TITLE
After every spotify update when spotx is installed, spotify reverts to default (songs in playlists are not organized)

### ISSUE THREAD

**Issue by EscobarMoney** [SpotX-Official/SpotX#159]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/discussions/111#discussion-4304353">described in the FAQ</a>

### Сountry of your account

Slovakia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows
1.1.94.872.g7a9200fe
- Windows: Windows 10 Pro 19043.1889
- PowerShell: 5.1.19041.1682
```

### 📝 Description

As I mentioned, when I install new spotify version and after I run SpotXBasic, it looks like it reverts everything to default.
ie: Playlists are not organized by date (which I had before running SpotXBasic)

**Comment by CDzungx** [comment]
Just disable auto update when install spotX and use the SpotX to update Spotify when new ver is available, this isn't a bug you know 😂 Maybe enhancement when Spotify update, SpotX runs with pre-used config.

**Comment by amd64fox** [comment]
fixed
