### ISSUE TITLE
Autoupdate disabler not working

### ISSUE THREAD

**Issue by jimmysofat6864** [SpotX-Official/SpotX#16]
## ℹ Computer information

- Spotify version:c1.1.72.439.gc253025e
- Windows version: 10 Pro 
- PowerShell version: 5.1.19041.1237

## 📝 Describe your problem in detail

Spotify auto update blocker didn't work. And yes, I did use the right button, I opened a post like this a while back.

**Comment by amd64fox** [comment]
Approximately 2 months have passed since your first request, during all this time the update blocking didn't worked for you and only broke down now? Or how did it happen? Tell us from the beginning

**Comment by amd64fox** [comment]
Open this if you have any answers.
