### ISSUE TITLE
Equalizer

### ISSUE THREAD

**Issue by SuperCuek** [SpotX-Official/SpotX#163]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [x] I have checked older issues, open and closed
- [x] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Indonesia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.94.872.g7a9200fe
- Windows: Win10 Pro 22H2 19045.2006
- PowerShell: 5.1.19041.1682
```

### 📝 Description

sometimes the equalizer settings go back to default, even though it's never forced closed and the cache is never cleared via preferences or third party apps (CCleaner/Bleachbit/Wise Cleaner)

**Comment by amd64fox** [comment]
[FAQ](https://telegra.ph/SpotX-FAQ-09-19)
