### ISSUE TITLE
Spotify crashes when you want to enhance a playlist

### ISSUE THREAD

**Issue by 4w3Official** [SpotX-Official/SpotX#166]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Germany

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.95.889.gfc9a996d
- Windows: Windows 11 25206.1000
- PowerShell: 7.2.6
```

### 📝 Description

1. Open Spotify
2. Click on "Liked Songs" in the left menu
3. Click on "Enhance"

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/57543029/192996775-6d73a52d-8fab-45bd-8ece-963ae0319d61.png)

**Comment by amd64fox** [comment]
which spotx installer did you use ?

You may have used a usual install, but since you're on premium, you need a [premium install](https://raw.githack.com/amd64fox/SpotX/main/scripts/Install_Prem.bat).
