### ISSUE TITLE
Can't download tracks in Spotify Premium Account.

### ISSUE THREAD

**Issue by twistedmacaroni** [SpotX-Official/SpotX#167]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Canada

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.95.893.g6cf4d40c
- Windows: Windows 11 22H2 22621.382
- PowerShell: 5.1.22621.169
```

### 📝 Description

Downloading a playlist/album gives the float-out dialog saying "Unlock downloads and other features with Premium" even though I've already got Premium and used the premium command of SpotX.

**Comment by amd64fox** [comment]
Clean install ?
Checking in the original client 1.1.95.893 ?

**Comment by twistedmacaroni** [comment]
> Clean install ? Checking in the original client 1.1.95.893 ?

yes, it seems to be working without the patch...

uninstalling and reinstalling the patch doesn't seem to fix the issue...

**Comment by amd64fox** [comment]
Did you perform a [clean install as described in the FAQ](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation)?

Are you using additional incoming parameters to install spotx ? if so then show your custom installation line, if you are using the standard installation for premium, then show it as well.

At the moment I do not have a premium account, so it is difficult for me to reproduce this error if it is.

**Comment by twistedmacaroni** [comment]
clean install worked for now.. will update this if i get issues further

**Comment by twistedmacaroni** [comment]
the issue wildly appears sometimes but closing and opening the app fixes it for a while. i've uninstalled the script completely and will try it out again in a future update!

**Comment by twistedmacaroni** [comment]
turns out it's a bug for everyone.., and it's not because of this script

**Comment by amd64fox** [comment]
> turns out it's a bug for everyone.., and it's not because of this script

tried the new version 1.1.96?

**Comment by twistedmacaroni** [comment]
> > turns out it's a bug for everyone.., and it's not because of this script
> 
> tried the new version 1.1.96?

yepp, the issue still persists...
