### ISSUE TITLE
Remove Premium tab in the left sidebar

### ISSUE THREAD

**Issue by yodaluca23** [SpotX-Official/SpotX#169]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [x] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States of America

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 

Spotify for Windows 1.1.95.893.g6cf4d40c

- Windows: 

Windows 11 Home 22H2 22621.608
Windows Feature Experience Pack 1000.22634.1000.0

- PowerShell: 

5.1.22621.608
```

### 📝 Description

1. Install the latest SpotX
2. Say no to all optional blocks
3. look in the top left corner
4. Observe ad

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/67206487/193431540-737ce000-fbfa-4457-a260-23e581ee4f41.png)

**Comment by amd64fox** [comment]
[Clean install](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation)

Please, next time, don't just tick off the checkboxes, but do what is written there.

**Comment by yodaluca23** [comment]
> [Clean install](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation)
> 
> 
> 
> Please, next time, don't just tick off the checkboxes, but do what is written there.

I did!! I'll do it again...

**Comment by yodaluca23** [comment]
> > [Clean install](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation)
> > Please, next time, don't just tick off the checkboxes, but do what is written there.
> 
> I did!! I'll do it again...

@amd64fox I used [the script](https://github.com/amd64fox/Uninstall-Spotify) to uninstall Spotify, and then redownloaded it and logged in, then I ran [the main install.bat](https://github.com/amd64fox/SpotX/releases/download/1.5/Install.bat) and I still see the new little Premium thing that I showed in the ScreenShot Above...

**Comment by amd64fox** [comment]
Where do you see in the FAQ that you need to install the client yourself, log into your account and only then install SpotX?

The FAQ lists the following sequence:

- Remove the client with a [patch](https://github.com/amd64fox/Uninstall-Spotify)
- restart PC
- run the SpotX installation
- and only now log into the client

What is difficult to do in the order in which you are asked?

**Comment by yodaluca23** [comment]
> Where do you see in the FAQ that you need to install the client yourself, log into your account and only then install SpotX?
> 
> The FAQ lists the following sequence:
> 
> * Remove the client with a [patch](https://github.com/amd64fox/Uninstall-Spotify)
> * restart PC
> * run the SpotX installation
> * and only now log into the client
> 
> What is difficult to do in the order in which you are asked?

That worked... I'm just confused as to why it matters if you install Spotify from the patch or the official site and why it matters if I sign in first or not...

**Comment by amd64fox** [comment]
sometimes when such errors appear, it is important to follow exactly the sequence that is written in the FAQ
in most cases it doesn't matter
