### ISSUE TITLE
remove Premium tab  in the left sidebar

### ISSUE THREAD

**Issue by amdfox99** [SpotX-Official/SpotX#172]
### Description of the new feature / enhancement

I know this is a very small thing but I was wondering if it was possible to remove what the  sidebar shows up as, currently it shows up as "Premium" I would like to know if removing this tab is possible. Attached screenshots for reference.

### 📸 Screenshots

![github](https://user-images.githubusercontent.com/105096797/193826172-7a2af33f-e48d-4591-805e-a8005ecac709.png)

**Comment by amd64fox** [comment]
duplicate https://github.com/SpotX-CLI/SpotX-Win/issues/169
