### ISSUE TITLE
Problem install (and keep) old Spotify version

### ISSUE THREAD

**Issue by PerNorrman** [SpotX-Official/SpotX#174]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Sweden

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
OS: Windows v10.0.19044
Spotify: v1.1.86.857
Spicetify: < v2.7.3 (2.14.0)
Dribbblish: v4.2.2-8da36b8
```

### 📝 Description

The main purpose for me to use SpotX is to be able to install a previous Spotify version and to prevent Spotify from updating to latest version. but I can't on older versions. After installation of any versions newer than Spotify for Windows
1.1.86.857.g3751ee08 - and the log in- I can see that Spotify has updated to latest version anyway... 
I can run SpotX, but it will only prevent latest version from future updates, and not that version I wanted in first place.
Even if it isn't a real bug, because SpotX will update **"installation of the recommended version of Spotify (if another client has already been found, it will be installed over)"** I can't bypass that with an older version (any working parameters?).

I found a little workaround, however but it only work on old versions until version 1.1.86.857:
1. Install Spotify, **but don't login**  
2. Run SpotX, then 
3. Login to Spotify

It's okay for now, but sooner or later I wan't to do an update - and then I will bee stucked to this version....

**Comment by amd64fox** [comment]
If you only need to block updates, then use this
https://github.com/amd64fox/Rollback-Spotify
