### ISSUE TITLE
new type ad showed up

### ISSUE THREAD

**Issue by nanchaara** [SpotX-Official/SpotX#18]
## ℹ Computer information

- Spotify version: 1.1.73.517.gbef50fdb
- Windows version: Windows 11 Latest 
- PowerShell version: ??

## 📝 Description of the problem
new type of ad showed up on my screen
usually its showing up in the middle of screen (modal pop up)

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/71387731/147315094-53bfa22c-c1c1-4087-94a3-77f4157cf27a.png)

**Comment by amd64fox** [comment]
How long ago did you install my patch?

**Comment by amd64fox** [comment]
Since there is no answer I will close this.

This type of advertisement was fixed in the last update.

To reinstall the patch run `Uninstall.bat`, and then `Install.bat` again
or
uninstall Spotify and run `Install.bat`

**Comment by nanchaara** [comment]
sorry i forgot i open new issues, i  installed your patch nov 13, and this type of ads showed up recently
i'll tried the uninstall.bat, i'll let you know if this ads showing up again
