### ISSUE TITLE
Remove the "Premium" button on the sidebar in Spotify

### ISSUE THREAD

**Issue by Pranav6145** [SpotX-Official/SpotX#180]
### Description of the new feature / enhancement

Please remove the Premium upgrade button below "Your Library" in the sidebar of the new layout of spotify.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/86869338/194726741-0379b1c5-d2b4-4e5d-ae0d-2f88aad055ec.png)

**Comment by amd64fox** [comment]
duplicate https://github.com/SpotX-CLI/SpotX-Win/issues/169
