### ISSUE TITLE
Rich presence not working on Discord anymore

### ISSUE THREAD

**Issue by Watashi199** [SpotX-Official/SpotX#183]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

France

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.94.870.gf994cb0b
- Windows: W11 21H2 22000.1098
- PowerShell: 5.1.22000.832
```

### 📝 Description

1. I've lost Rich Presence on Discord
2. I tried to reinstall SpotX multiple times, on W10 and W11 same result
3. On my screen first it's me and second it's normal rich presence from Spotify

![image](https://user-images.githubusercontent.com/33749671/196030808-27239f1d-a8de-47d5-bc74-4045b1884799.png)
![image](https://user-images.githubusercontent.com/33749671/196030824-65b2bbe6-d518-4798-8a4c-163de952b02e.png)

**Comment by amd64fox** [comment]
install the [latest version](https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit?usp=drivesdk)

**Comment by Tosoju** [comment]
I'm on the latest version and this still does not work

**Comment by vavavr00m** [comment]
Issue is still persistent on the current latest version 1.6 - W10

**Comment by amd64fox** [comment]
@Tosoju @vavavr00m 
Perform a clean install as described in the [FAQ](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation), if that doesn't work then contact [Discord support](https://support.discord.com/hc/en-us)
SpotX has nothing to do with this bug.

**Comment by Watashi199** [comment]
Hello @amd64fox, it perfectly works when SpotX isn't installed, at the moment i install it it won't work, i tried on home pc w11, work pc w10, and snd work pc w10 still not working that's strange, i guess it'll be fine without it

**Comment by Tosoju** [comment]
now for me it works most of the times

yeah, it's probably on discord's end

**Comment by Tosoju** [comment]
I'm back with a really dumb workaround. I'm not sure how well it'll work for others but it worked pretty consistently for me.

So you'll need a phone with spotify and discord on that and your pc. 
Open Spotify on your phone and start playing something. 
Check if discord is showing that you're playing something on discord. 
If it is, go to your pc Spotify and check if Spotify detects that your phone is playing audio. 
If it does detect it, change the device to your pc, which might require you to change it on your phone too. 

After that it'll (probably) work fine.
