### ISSUE TITLE
Any plans for offline downloads?

### ISSUE THREAD

**Issue by AnatuGreen** [SpotX-Official/SpotX#190]
### Description of the new feature / enhancement

- Any plans for offline downloads?
- Nice for experimentation

**Comment by amd64fox** [comment]
Do you mean download tracks? (premium feature)

**Comment by AnatuGreen** [comment]
Yes please. To be able to download music, not only stream, just like
premium.

**Comment by amd64fox** [comment]
Unfortunately this is a server side feature, at the moment I don't know how to get around this.
