### ISSUE TITLE
Custom colors for lyrics

### ISSUE THREAD

**Issue by CanYouJustWorkPlease** [SpotX-Official/SpotX#191]
### Description of the new feature / enhancement

Hi there! Is there a way to accomplish this?
-  Add the possibility for users to customize the lyrics colors, since the current colors are too bright and cause eye strain

If indeed it is possible but it proves it would take too much work, would it be at least possible to set as default the colors of the lyrics following the color scheme from the second picture?

Thank you!

## **How lyrics  currently look like (on Spotify for Windows 1.1.96.785.g464c973a):**
Colors displayed for the lyrics of the song: Godsmack - Bulletproof

![spotify_custom_lyrics_original](https://user-images.githubusercontent.com/73692469/197382814-04b9fc21-0147-4bb1-b853-5eca4006d6d4.png)

---

## <a name="hexColors">How lyrics would look like if the following colors would be applied:</a>

Background: ~~`#000000`~~  `#121212`
Past lyrics: `#E40909B3` <- this hex is expressed as an RGBA value, it has 8 digits (I don't know if Spotify would support that)
Current lyrics: `#C2C2C2`
Next lyrics: `#CA861A`
"Lyrics provided by Musicmatch": `#C2C2C2`
Lyrics hover: `#C2C2C2`

![spotify_custom_lyrics_customized_default](https://user-images.githubusercontent.com/73692469/197383793-cf72092d-5969-446c-857d-80f3c0780195.png)

**Comment by amd64fox** [comment]
Can be implemented as an additional function through incoming parameters

Any ideas with other color options?
I suggest leaving the background everywhere at `#121212`, so as not to spoil the main theme

**Comment by CanYouJustWorkPlease** [comment]
That's really nice! Yeah, no problem, let's keep #121212 for the background color then.

<a name="secondTheme">This could be another color scheme:</a>
https://coolors.co/121212-67697c-c2c2c2-008148


![image](https://user-images.githubusercontent.com/73692469/197410562-427f11b8-3415-4ab0-b8be-01897ae3608b.png)

I don't have any other color schemes for now, as I don't know what you might like.
You can notice in the image that I locked down the background color (#121212) and the current lyrics color (#c2c2c2) while I pressed spacebar to auto generate the other colors. If you want, you can give it a try on that site and pick some colors schemes you'd like.

A, you can also notice that the link to the color scheme has all the hexadecimals colors in the same order they appear on the site: 121212-67697c-c2c2c2-008148

It even has an "Adjust palette" section, where you can tweak the colors some more, like here:
![image](https://user-images.githubusercontent.com/73692469/197410880-f30e02c8-3ff5-4eb6-91be-2b94137223fc.png)

I tried to check the contrast of the colors in Firefox for Spotify web player with my first color scheme, but unfortunately it doesn't work. I did to see if the different colored text on that black background passed the checks. You can see down below that white 4 on that black orange didn't pass the check, getting a 2.45 rating.
For some reason Firefox can't analyze the colors, like it does in this example with Wikipedia:

![image](https://user-images.githubusercontent.com/73692469/197411875-0efb5f10-7dce-495e-b3fb-05d8db1db4bc.png)
---
![image](https://user-images.githubusercontent.com/73692469/197414201-885b24dd-b7d9-4540-83d4-1cd69ed12e44.png)
---
![image](https://user-images.githubusercontent.com/73692469/197411906-2b95b759-d784-4223-9a70-5f3deb58f726.png)


Chrome had something similar in the past, but they removed it in the latest versions, it was called CSS Overview. I'll see tomorrow if I can get my hands on an older version of Chrome and test it out. I just want to do this mostly out of curiosity.

What do you think, should we check the color contrast or should we just wing it? From the looks of it, Spotify didn't bother with it, since I've seen a couple of lyrics that were kind of hard to read.

P.S:
~~Could you tell me how you inserted that circle to match the color of the hex?~~
![image](https://user-images.githubusercontent.com/73692469/197414541-bd6f1651-3aeb-421c-ae29-6b055d1a622a.png)

I have figured it out. I had to hit enter once, and then add \`#121212\`
It doesn't work though with hex coming from RGBA values.

**Comment by CanYouJustWorkPlease** [comment]
I was wrong about CSS Overview, it's still in Chrome, it seems I read an older article. Here's the result for the first color scheme:

![image](https://user-images.githubusercontent.com/73692469/197479792-63b95eac-a262-4e3d-b9e5-a974ca921ef7.png)

This issue is related to the past lyrics color being `#e40909b3` (dark red), but even with this issue it seems fine to me.

There was one more issue, where "Lyrics provided by Musicmatch" color was white, but now I switched it to `#C2C2C2` and it seems fine, as it passed the CSS Overview test, as seen in the top picture.

Here's how it looks now:
![image](https://user-images.githubusercontent.com/73692469/197480877-96cc7ffe-cfdd-4ffe-bf1b-dd9b8cd4b022.png)

I also switched the lyrics hover color to `#C2C2C2`.

You can see the changes I've made over [here](#hexColors), in the first post.


---
Here's the results for the [second theme](#secondTheme):
![image](https://user-images.githubusercontent.com/73692469/197486240-e8d296c0-fb90-48ff-af7b-b9cd3d31004a.png)

It has issues with the past lyrics `#67697C` and next lyrics `#008148` on `#121212` background. 
Also, past lyrics color `#67697C` seems too close to current lyrics color `#C2C2C2`. So, I think we should ditch this theme, unless we would adjust the two colors.

**Comment by amd64fox** [comment]
Added a couple of 4 color options,
1 - black and white
2 - dark yellow
3 - pink
4 - theme by @CanYouJustWorkPlease

to set the desired theme, use the incoming parameter `lyrics_stat`
For example I want to install theme 4: `-lyrics_stat 4`

**Comment by amd64fox** [comment]
If you have any ideas to add new theme, then throw it here, for example:

past lyrics - `#ffffff4a` 
current lyrics - `#ffffffc7`
next lyrics - `#ffffff4a` 
hover - `#0FD40F`
background of lyrics - `#121212`
maxmatch- `#C2C2C2`

**Comment by CanYouJustWorkPlease** [comment]
That's really nice! Thank you! :^D
Sure, if I'll get other themes, I'll post them here.

Just one question, what color will have the hover over the lyrics, as I'm seeing it missing from the colors attributes, will it inherit the color from current lyrics?

**Comment by amd64fox** [comment]
> will it inherit the color from current lyrics?

right

**Comment by amd64fox** [comment]
> > will it inherit the color from current lyrics?
> 
> right

I was wrong, he did not inherit the color
added a new parameter `lyrics on hover` in the [post above](https://github.com/SpotX-CLI/SpotX-Win/issues/191#issuecomment-1289085228), in themes that have already been added inherited the color from `current lyrics`.


There are also lyrics without synchronization, now they inherit the color from the `current lyrics`

**Comment by CanYouJustWorkPlease** [comment]
I see. If it's not too much too ask, would it be possible to make them independent of each other, meaning `current lyrics` and `lyrics on hover` get to keep their own colors? 

For example:
`current lyrics`: green
`lyrics on hover`:  orange

It would be nice if I could choose another color for lyrics on hover.

**Comment by amd64fox** [comment]
> I see. If it's not too much too ask, would it be possible to make them independent of each other, meaning `current lyrics` and `lyrics on hover` get to keep their own colors?

they are independent
but in your theme you specified the same color for current and hover (#C2C2C2)

you can suggest a new profile for your theme, i will update.

**Comment by CanYouJustWorkPlease** [comment]
That's really nice. :^D

I picked `lyrics on hover` to be `#0FD40F`

The whole theme over here:

past lyrics - `#E40909B3` 
current lyrics - `#C2C2C2`
next lyrics - `#CA861A`
lyrics on hover - `#0FD40F`
background of lyrics - `#121212`
txt by Musicmatch - `#C2C2C2`

Thank you! You are awesome! :^D

**Comment by amd64fox** [comment]
updated

**Comment by CanYouJustWorkPlease** [comment]
Hmm, it seems `past lyrics` is getting applied a filter which makes the color darker, tested with Spotify for desktop with the themes implemented by you. 'past lyrics` is the only one that gets applied a filter, out of the 6 attributes. ~~I've seen the same behavior for Spotify web player.~~

As an example, I used the same colors for  `past lyrics` and `next lyrics`, respectively `#895502`, but in turn, `past lyrics` received `#654006`, while `next lyrics` received `#895502`, as seen below, tested on Spotify Desktop:
![image](https://user-images.githubusercontent.com/73692469/197981980-e309aefa-2065-4672-8b8e-54015cb90f63.png)

I used [Just Color Picker ](https://annystudio.com/software/colorpicker/)to get the colors:
- for `past lyrics`:
![image](https://user-images.githubusercontent.com/73692469/197985305-1ac458a1-9f9c-4984-a6b2-fceec42b8eea.png)

- for `next lyrics`:
![image](https://user-images.githubusercontent.com/73692469/197984676-c0eed7c4-4850-48fb-a3de-281a5bf22b58.png)

If you're using a blue filter app, please disable it, otherwise it's possible that Just Color Picker won't pick the real color. It happened in my case with CareUEyes.

Could you make it possible for `past lyrics` to keep its real color, meaning to receive `#895502`, instead of receiving `#654006`, in this case?

**Comment by CanYouJustWorkPlease** [comment]
A, it seems on Spotify web player `past lyrics` has been applied an opacity of 0.7
![image](https://user-images.githubusercontent.com/73692469/197994339-b873a2a7-6ab2-4ff8-b22a-eacb4552efca.png)

, so I guess it's the same for Spotify Desktop.

**Comment by CanYouJustWorkPlease** [comment]
Hmm, I've done some more tests, and it seems the 0.7 opacity for Spotify web player actually makes the color brighter, not darker. So, I'm not sure what's different for Spotify Desktop.

Example using `#895502` for both `past lyrics` and `next lyrics`, tested on Spotify web player:
![image](https://user-images.githubusercontent.com/73692469/197999268-209971fd-81f6-4346-8000-12ae49de6fb8.png)

In this case `past lyrics` turns brighter, respectively `#8E6A30`, instead of turning darker, as for the case of Spotify Desktop. As with Spotify Desktop, only `past lyrics` gets affected on Spotify web player.

**Comment by amd64fox** [comment]
fixed attribute for past lyrics

**Comment by CanYouJustWorkPlease** [comment]
That's really nice! I just tested it out! 
Thank you! You're the best! :^D

P.S:
After seeing how my theme looks like, I'd like to create a pull request to your patches.json, as I'm not happy with it. But I'll have to readjust it first.

**Comment by GREEKY69** [comment]
> That's really nice. :^D
> 
> I picked `lyrics on hover` to be `#0FD40F`
> 
> The whole theme over here:
> 
> past lyrics - `#E40909B3` current lyrics - `#C2C2C2` next lyrics - `#CA861A` lyrics on hover - `#0FD40F` background of lyrics - `#121212` txt by Musicmatch - `#C2C2C2`
> 
> Thank you! You are awesome! :^D

how to apply this theme

**Comment by amd64fox** [comment]
@GREEKY69 
`-lyrics_stat relish`

**Comment by amagiriyuuka** [comment]
What about when playing on fullscreen? Since there's a feature that can either show the album art or the lyrics of the song. The theme works great but the fullscreen version still has colors based  on the album art (I assume).

Lyrics with theme (royal):
![image](https://user-images.githubusercontent.com/82317262/227760656-2d22dae8-a2b6-4e39-988f-77136f648e1f.png)

Lyrics on fullscreen mode (still with the theme applied):
![image](https://user-images.githubusercontent.com/82317262/227760719-143ab3fa-2215-40bc-af3f-b7d9b3e6a0b8.png)

**Comment by PetelAnavim** [comment]
Hello, I also wanted to add a theme if that's possible. it's basically a combination of a few of the existing themes. It would be great if you could add it.

Name: `lavender`

past lyrics - `#B8A2EA`
current lyrics - `#8462DD`
next lyrics - `#575757`
hover - `#F2F2F2`
background of lyrics - `#121212`
maxmatch - `#C2C2C2`

By the way, sorry if I'm reviving an old thread. I'm very new to GitHub and I couldn't find a way to create a new thread.

**Comment by amd64fox** [comment]
> sorry if I'm reviving an old thread.

it's okay, this topic was created just for this

at first glance your theme looks like "royal" or am I mistaken?

**Comment by amagiriyuuka** [comment]
That's cool. Yes my theme used was indeed "royal

**Comment by PetelAnavim** [comment]
> at first glance your theme looks like "royal" or am I mistaken?

No, you're right. It's basically the `royal theme` with a darker background and mixed a little with the `purple theme` as well.

**Comment by amagiriyuuka** [comment]
@amd64fox i'm wondering if you'll be adding themes for spotX, that would be a great addition! If ever that's the case, I would suggest either integrating it into the app or (which i think would be what you'd do) is add it as options for the powershell command just like the lyric themes

**Comment by PetelAnavim** [comment]
> > at first glance your theme looks like "royal" or am I mistaken?
> 
> No, you're right. It's basically the `royal theme` with a darker background and mixed a little with the `purple theme` as well.

Is it possible adding it? Thanks in advance

**Comment by amd64fox** [comment]
@PetelAnavim added

@amagiriyuuka 
to change client themes use Spicetify, I don't have time to implement and support this in spotx.

**Comment by PetelAnavim** [comment]
> @PetelAnavim added

Thanks very much

**Comment by vhc-vir** [comment]
Hi, I want to add a theme if that's possible. It's basically like a spotify theme with some tweaks (I tried to match the background to the color of the lyrics bar (?) on the side panel)

![20240408_192747~2](https://github.com/SpotX-Official/SpotX/assets/160111811/843506c7-f008-47d8-bd2e-feeae6486bff)

![Screenshot 2024-04-08 191547](https://github.com/SpotX-Official/SpotX/assets/160111811/b84f8614-8a18-47a9-a449-5bd3b8ef2f8a)

Name : `alter`  (I don't have any idea for the name lol)

past lyrics - `#9b9b9b`
current lyrics - `#1ed760`
next lyrics - `#666666`
hover - `#f2f2f2`
background of lyrics - `#242424`
maxmatch- `#C2C2C2`

**Comment by vhc-vir** [comment]
@amd64fox 
Hi, I want to add a theme. It's basically like a spotify theme with some tweaks (I tried to match the background to the color of the lyrics bar (?) on the side panel)

![20240408_192747~2](https://github.com/SpotX-Official/SpotX/assets/160111811/843506c7-f008-47d8-bd2e-feeae6486bff)

![Screenshot 2024-04-08 191547](https://github.com/SpotX-Official/SpotX/assets/160111811/b84f8614-8a18-47a9-a449-5bd3b8ef2f8a)

Name : `alter`  (I don't have any idea for the name lol)

past lyrics - `#9b9b9b`
current lyrics - `#1ed760`
next lyrics - `#666666`
hover - `#f2f2f2`
background of lyrics - `#242424`
maxmatch- `#C2C2C2`

**Comment by amd64fox** [comment]
added it with the name `spotify#2`

Thanks

**Comment by vhc-vir** [comment]
> added it with the name `spotify#2`

Thank you very much

**Comment by JumboWumbus** [comment]
![Spotify_JMeLyenGyD](https://github.com/user-attachments/assets/157c7d12-61e1-4dd4-93cf-20721f78d976)


Hello! I've been using this app for awhile and just did a clean windows install so ended up on the FAQs of all my fav apps!

I noticed the BG of spotify is close to gruvbox material so here's a lyric theme based on that.

past lyrics - `#32302F`
current lyrics - `#d4be98`
next lyrics - `#7c6f64`
hover - `#e78a4e`
background of lyrics - `#121212`
maxmatch- `#282828`


_**Also >tfw when you're trying to find what classes color the text you want**_

![Spotify_qY30LKxptU](https://github.com/user-attachments/assets/32bc35f3-50e1-41ed-8fce-6d55613be061)


_edit: changed my mind about previous lyric color :p_

**Comment by amd64fox** [comment]
thanks, come up with a one word name for your theme, here is a [list of existing ones](https://github.com/SpotX-Official/SpotX/blob/main/run.ps1#L96)

**Comment by xdr0p** [comment]
> @GREEKY69 `-lyrics_stat relish`

sorry if its a dumb question, but can you tell me where do i need to type that in?

**Comment by amd64fox** [comment]
> sorry if its a dumb question, but can you tell me where do i need to type that in?

```ps1
iex "& { $(iwr -useb 'https://raw.githubusercontent.com/SpotX-Official/spotx-official.github.io/main/run.ps1') } -new_theme -lyrics_stat relish"
```
