### ISSUE TITLE
Possible Android version?

### ISSUE THREAD

**Issue by ghost** [SpotX-Official/SpotX#193]
### Description of the new feature / enhancement

- 1 Could come with all the same features as SpotX (ive seen it done before, i have a pretty buggy version on my phone)
- 2 There arent many (if any) Spotify mods for Android and I love the desktop version of this
- 3 Obviously a skip limit (where spoti limits you to like 4 skips /hour) override plus other things that workaround spotifys other paywalled mobile features like no skip backwards and shuffle lock
all of this is wishful thinking ngl, but im sure many would benefit from an Android version of this app myself included
(also mobile official spotify clients are REALLY heavily locked down wayyy more than desktop)

**Comment by yodaluca23** [comment]
Use [xManager](https://github.com/xManager-v2/xManager-Spotify), [sideload it](https://www.xda-developers.com/how-to-sideload-install-android-app-apk/) and install whatever Spotify version you like. Next time please look through previously closed issues before creating a new one...

**Comment by ghost** [comment]
Holy shit thanks! Sorry for not looking at closed. This xmanager app is absolutely perfect!

**Comment by fmdkcl4e** [comment]
Yea... this doesnt seem to work anymore.

**Comment by yodaluca23** [comment]
> Yea... this doesnt seem to work anymore.

Latest version should, Spotify's been at war with Android mods, though. Also I would recommend Revanced now.

**Comment by fmdkcl4e** [comment]
doing something wrong? when I install spotify-revanced-v9.0.50.416-all.apk  I get same errors: empty playlists, no songs

**Comment by yodaluca23** [comment]
> doing something wrong? when I install spotify-revanced-v9.0.50.416-all.apk  I get same errors: empty playlists, no songs

This really isn't the place to discuss this, join the Revanced Discord server or something. But did you build it yourself? Or did you get it online somewhere?

**Comment by fmdkcl4e** [comment]
So ye, got it from 2nd(1st now) search result, but not rooted, didnt type anything in termux, didnt download the manager and just downloaded the apk from the git repository. But there's no other results so where else am I supposed to get the apk?

**Comment by yodaluca23** [comment]
> So ye, got it from 2nd search result, but not rooted, didnt type anything in termux, didnt download the manager and just downloaded the apk from the git repository. But there's no other results so where else am I supposed to get the apk?

Please do not install random APKs from the internet, several of the Spotify ones have been known to bundle malware. Also, like I said, really not the place to be discussing this, please join the [Revanced Discord server](https://discord.gg/PqBUgfjAPH) for any further questions.

1. Delete any Spotify apps you currently have installed.
2. Download the latest Spotify version from Google Play Store, or however you access the Google Play Store.
3. Download and install https://github.com/AbdurazaaqMohammed/AntiSplit-M
4. Open it and dump the .apk using the in-app options.
5. Download and install https://github.com/revanced/revanced-manager
6. Open it and use the in-app options to patch from file, and patch the Spotify .apk, and let it install.

**Comment by fmdkcl4e** [comment]
No I'm good though, the counterfeit readme just tried to gain root access, but the apk's are updated weekly and weren't apkm's

**Comment by fmdkcl4e** [comment]
Anyways followed these instructions, still no songs, account is fine. Everything works on desktop.

**Comment by diclonimus** [comment]
Followed these instructions, but I get no songs. Everything works on desktop and my account is fine. 

> > So ye, got it from 2nd search result, but not rooted, didnt type anything in termux, didnt download the manager and just downloaded the apk from the git repository. But there's no other results so where else am I supposed to get the apk?
> 
> Please do not install random APKs from the internet, several of the Spotify ones have been known to bundle malware. Also, like I said, really not the place to be discussing this, please join the [Revanced Discord server](https://discord.gg/PqBUgfjAPH) for any further questions.
> 
>     1. Delete any Spotify apps you currently have installed.
> 
>     2. Download the latest Spotify version from Google Play Store, or however you access the Google Play Store.
> 
>     3. Download and install https://github.com/AbdurazaaqMohammed/AntiSplit-M
> 
>     4. Open it and dump the .apk using the in-app options.
> 
>     5. Download and install https://github.com/revanced/revanced-manager
> 
>     6. Open it and use the in-app options to patch from file, and patch the Spotify .apk, and let it install.

![Image](https://github.com/user-attachments/assets/73289606-0e2f-4936-abaf-c8ec302e2083)
