### ISSUE TITLE
Hiding Ad-like sections from the homepage

### ISSUE THREAD

**Issue by Hal47** [SpotX-Official/SpotX#195]
### Description of the new feature / enhancement

Considering how podcasts/audiobooks have similarly dealt with a optional setting during install/with dev tools, would it be possible to likewise hide from the **Homepage** other sections like: 

- Flavor
- Today's Biggest Hits
- Throwback Favorites
- Fresh New Music
- Trending Now
- Mood
- Popular Artists
- Popular Albums

Many of these sections are essentially just **ads** in disguise, so in my opinion it should still fall within the original scope of SpotX. While people might want to have an option for rarely unused sections like _Your top mixes, Recently played , Made for you, Uniquely yours, More like, Your favorite artists, Suggested artists, Recommended for today and More of what you like_ . . . those at least work using your (musical) preferences instead and thus would (in my opinion) fall more into the scope of things like Spicetify.

**Comment by amd64fox** [comment]
all these sections are very hard to track, I managed to hide the section with podcasts only because inside this section there are not songs, but podcasts.
And other sections will be more difficult to hide, since they do not have a single name, their name depends on which language the user account is currently using.

Perhaps there is a way. We need to study this issue a little more when there is time.

**Comment by amd64fox** [comment]
added a new input parameter `-adsections_off` for the test

sections I tried to hide:
- Popular Albums / Artists
- Popular new releases
- Best of Artists / Tracks
- Best of songwriters
- Fresh New Music
- The state of music today
- Mood
- Today's biggest hits
- Throwback
- Trending now 
- Popular radio 
- Try something else
- Featured Charts
- The best of 2022
- The Best Christmas Music
- Happy Holidays

write here suggestions for adding or removing sections

to test blocking these sections just run it in PowerShell:

```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/SpotX-CLI/SpotX-Win/main/Install.ps1').Content) } -adsections_off"
```
works since version **1.1.93+**

**Comment by Bec-de-Xorbin** [comment]
> write here suggestions for adding or removing sections

Popular artists

**Comment by amd64fox** [comment]
> Popular artists

you can send section id, as most likely `Best of Artists` and `Popular Artists` are the same section

in order to get the section id you need to [get DevTools](https://github.com/amd64fox/Enable-devtools-Spotify#launch-type)

<details>
<summary><small>after you got the DevTools do this</small></summary><p>
  
![Анимация](https://user-images.githubusercontent.com/62529699/205912550-e2a730e5-cb93-4283-8a5d-9965e427ca33.gif)

</details>

**Comment by Bec-de-Xorbin** [comment]
> you can send section id, as most likely `Best of Artists` and `Popular Artists` are the same section

/section/0JQ5DAnM3wGh0gz1MXnu3C

**Comment by amd64fox** [comment]
Yes, this is a new section, it was not displayed in my account
thanks, added

**Comment by Bec-de-Xorbin** [comment]
`Best of songwriters`

0JQ5DAnM3wGh0gz1MXnu4w

**Comment by amd64fox** [comment]
> Best of songwriters

added thanks
what is the region of your account?

**Comment by Bec-de-Xorbin** [comment]
> what is the region of your account?

Finland

**Comment by amd64fox** [comment]
found such sections, your thoughts

**Workout**
spotify:section:0JQ5DAnM3wGh0gz1MXnu3x

**Focus**
spotify:section:0JQ5DAob0JCuWaGLU6ntFY

**Sad songs**
spotify:section:0JQ5DAnM3wGh0gz1MXnu3u

**Happy**
spotify:section:0JQ5DAnM3wGh0gz1MXnu3q

**Music to game to**
spotify:section:0JQ5DAob0Jr9ClCbkV4pZD

**Gaming music**
spotify:section:0JQ5DAob0LaV9FOMJ9utY5

**Comment by Hal47** [comment]
Seems to work for me, since my homepage is now only showing: Your top mixes, Made for, Recently Played, Recommended for today, Discover more from, More like, For fans of, Uniquely yours, Your playlists, More of what you like and New releases for you. Ignoring future software changes, the only remaining issues should be updating sections as they appear/Spotify comes up with them+language section differences.

Thanks for your work @amd64fox 👍

**Comment by amd64fox** [comment]
right, spotify adds new id sections from time to time, if you notice that the blocked section has reappeared, just drop its name and id here, here is a [short instruction](https://github.com/SpotX-CLI/SpotX-Win/issues/195#issuecomment-1339230002) on how to get the section id

I also need your opinion on these sections, are there any [lists in this](https://github.com/SpotX-CLI/SpotX-Win/issues/195#issuecomment-1345194096) that you would not like to see on the main page?

**Comment by Hal47** [comment]
Will do, already had DevTools setup to manually mess around with SpotX's experimental features.

If it were up to me, I'd remove everything that doesn't change according to user listening history so seasonal sections (rip Holidays/Christmas music), Best of X year, Featured Charts (which I don't get for some reason) would go. Do Workout, Focus, Happy, Music to game to, Gaming music take it into account listening history? Haven't seen those on my account, just recently came back to Spotify after a long hiatus...

**Comment by amd64fox** [comment]
> If it were up to me

at the moment it depends only on those who participate in this discussion 😉

added sections Featured Charts, The best of 2022, The Best Christmas Music, Happy Holidays
[other sections](https://github.com/SpotX-CLI/SpotX-Win/issues/195#issuecomment-1345194096) under consideration...

**Comment by Bec-de-Xorbin** [comment]
Do you still get suggestions? If so, then:
Popular new releases
0JQ5DAnM3wGh0gz1MXnu3D

**Comment by amd64fox** [comment]
> Do you still get suggestions?

Certainly
added
update spotx

**Comment by Shituation** [comment]
/section/0JQ5DAuChZYPe9iDhh2mJz
/section/0JQ5DAnM3wGh0gz1MXnu4h
~~/section/0JQ5DAob0JCuWaGLU6ntFY~~
0JQ5DAnM3wGh0gz1MXnu3D

**Comment by amd64fox** [comment]
@Shituation 
thanks, the first two sections have already been added, but 3 have not yet been added, could you please clarify how you display the name for this section?

**Comment by Shituation** [comment]
class="MfVrtIzQJ7iZXfRWg6eM" href="/section/**0JQ5DAuChZYPe9iDhh2mJz**">En tendencia</a>

Im still seeing it and its the first in the list.


This is the "last" ~~it seems it changes?:~~

class="MfVrtIzQJ7iZXfRWg6eM" href="/section/**0JQ5DAnM3wGh0gz1MXnu3D**">Popular new releases</a>

**Comment by amd64fox** [comment]
I meant this section 0JQ5DAob0JCuWaGLU6ntFY

**Comment by Shituation** [comment]
> 0JQ5DAob0JCuWaGLU6ntFY

It seems I passed the wrong code for some reason, the last one is:

"/section/0JQ5DAnM3wGh0gz1MXnu3D">Popular new releases</a>

-----------------------------------

0JQ5DAuChZYPe9iDhh2mJz">En tendencia      is still being shown, you say it has already been added, can there be any error?

**Comment by amd64fox** [comment]
> still being shown, you say it has already been added, can there be any error?

in order to block all these sections, you need to add an incoming parameter `-adsections_off`  to the spotx installation line

or use Install_Auto.bat

**Comment by Shituation** [comment]
the "Automatic full installation" wants to overwrite my old spotify installation with a new version. I don't want to do that because [Spotify removed the "block cookies" option.](https://github.com/amd64fox/SpotX/issues/333)

~~Where do I add that? do I have to download "https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1" and modify it? where do I put that line?~~

I've found the [instructions](https://github.com/amd64fox/SpotX/discussions/60) deep in the main page.

**Comment by Hulayki** [comment]
Hi! I've found some ad sections in the region of Hungary.

Happy
0JQ5DAnM3wGh0gz1MXnu3q
Sad songs
0JQ5DAnM3wGh0gz1MXnu3u

**Comment by amd64fox** [comment]
Thanks @Hulayki 

Hmm, strange...
I initially believed that these sections were personalized, as the descriptions of almost every playlist from these sections mentioned that they were created specifically for the user. When comparing the tracklists of these personalized playlists, I expected them to be entirely distinct for different users. However, upon closer inspection, I noticed that the tracks in these playlists only differed by a maximum of 8-10 percent. It appears that the majority of tracks in these playlists are the same for all users. Therefore, it can be concluded that these playlists are not truly personalized.

I added your “Sad songs” section to the consideration [list](https://github.com/SpotX-Official/SpotX/issues/195#issuecomment-1345194096), the “Happy” section was already there, we need to arrange a vote soon

**Comment by Hal47** [comment]
Interesting, I assumed they were personalized (as long as they had enough information for the user). Couldn't we just assume that the 92-90% are generic ads (since they seem to be major/mainstream/popular artists) and with the rest being actually tailored once they gather enough preference data to form personalized ads?

**Comment by amd64fox** [comment]
Yes, in this way the playlist can be called personalized if out of 100 tracks, one track is selected based on your preferences, and the other 99 are advertisements based on global trends, but not for me. Also, you have no idea if this one track is actually selected specifically for you, as my test consisted of simply comparing these personalized playlists among different users. I did not test those tracks based on taste preferences, so I think it's also advertising. If we take simple personalized playlists that we discussed earlier, I can assume that there are no recommendations specifically tailored to you in them at all. There is a large pool of tracks (4-5k), and for each user, 100 tracks are randomly generated from this selection, later as time passes, this pool is updated or refreshed with other tracks, but it's important to note that Spotify does have genuinely personalized playlists that recommend tracks solely for you, without any deception. The most popular examples of these are "Discover Weekly" and "Release Radar".

**Comment by amd64fox** [comment]
added all these [sections](https://github.com/SpotX-Official/SpotX/issues/195#issuecomment-1345194096)
also the section 0JQ5DAnM3wGh0gz1MXnu3n (best of artists/tracks) was unlocked

**Comment by 15seagulls** [comment]
section/0JQ5IMCbQBLicmNERjnGn5

"Most Listened 2023" for Germany

**Comment by amd64fox** [comment]
added, thanks

**Comment by Mysticc28** [comment]
Hello, is it possible for these sections too?
section/0JQ5DAuChZYPe9iDhh2mJz"
section/0JQ5DAnM3wGh0gz1MXnu4h"

**Comment by annrosetic** [comment]
off-topic: Can you please add "running multiple instances" experimental feature? I want to be able to open at least 2 SpotX programs  for creating and moving playlists easier from one account to another (old theme), without the need to use a browser

**Comment by eragonhnn** [comment]
Hello, I have a few questions.

- I'm using the "Usual installation (New theme)" package and during the installation process I only see two options: "Disable Spotify updates and Hiding podcasts/episodes/audiobooks". I've selected Y.E.S. for both.
- I see "experimental features" with the "Hiding Ad-like sections from the homepage" feature.
-> I want to ask if the "Hiding Ad-like sections from the homepage" feature is enabled or disabled in my installation package? I still want to see those ads, it could be a new flavor in my music playlist.

**Comment by amd64fox** [comment]
> "Hiding Ad-like sections from the homepage" feature is enabled or disabled in my installation package?

disabled
