### ISSUE TITLE
1px gap between taskbar and maximized spotify window

### ISSUE THREAD

**Issue by fancybody** [SpotX-Official/SpotX#196]
### Description of the new feature / enhancement

Firstly, many thanks for making such a helpful script.

A transparent 1px line remains between the taskbar and the window even after maximizing Spotify. This problem only seems to occur in Windows 11 (since its release). Official Spotify channels have been [postponing](https://community.spotify.com/t5/Desktop-Windows/Spotify-desktop-app-not-filling-screen-small-gap-on-Windows-11/td-p/5275984) this for over a year.

Is it possible to solve this?

### 📸 Screenshots

![gap](https://user-images.githubusercontent.com/87397831/198567996-b6c9d520-df2d-4a16-a757-c26436cd800c.png)

**Comment by amd64fox** [comment]
This is an old enough CEF build problem, i have no idea how to fix it
