### ISSUE TITLE
After installing SpotX newest version unable to Scrobble via Last.fm scrobbler. Also Discord activity doesnt working

### ISSUE THREAD

**Issue by SupLiCatinG** [SpotX-Official/SpotX#197]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Turkey

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: Spotify für Windows 1.1.94.870.gf994cb0b
- Windows: 22H2 W10 .2193
- PowerShell: Version 5.1.19041.1682
```

### 📝 Description

As described on title.

**Comment by amd64fox** [comment]
you do not have the latest version, uninstall it and run the SpotX installation again

**Comment by SupLiCatinG** [comment]
Yes, but why it doesnt working, do you have any clue ? (It was working until 1-2 day ago) Since they removed Made For You section from experimental features i don't want to use newer versions. 

Btw Spotify für Windows 1.1.97.962 works as intended.

**Comment by amd64fox** [comment]
versions `1.1.94.870` and `1.1.94.864` have Spotify Connect bug, avoid them

full list of versions [here](https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit#gid=0)

**Comment by SupLiCatinG** [comment]
Yes, it seems to be. Thank you, i was searching for this list.
