### ISSUE TITLE
Lyrics Overlay: Feature Request

### ISSUE THREAD

**Issue by BudhirajaMadhav** [SpotX-Official/SpotX#198]
### Description of the new feature / enhancement

- 1 It would be really great if we can have the lyrics available as overlay, which is always on top, doesn't disappear when switched between desktops.
- 2 Sample picture: 
![ ](https://user-images.githubusercontent.com/73742540/198884666-a7993157-5b8e-4754-92f1-b7c84b1f2e71.jpg)

- 3 Example: https://github.com/mantou132/Spotify-Lyrics (this is available for web only, and stays on single desktop only)

**Comment by amd64fox** [comment]
I think you should make this request in [native repository](https://github.com/mantou132/Spotify-Lyrics)
I don't plan on something like this.
