### ISSUE TITLE
Incompatibility with Win10 LTSC Edition OS

### ISSUE THREAD

**Issue by kcayme** [SpotX-Official/SpotX#200]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Philippines

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.96.785.g464c973a
- Windows: Windows 10 LTSC Version 10.0.17763 Build 17763
- PowerShell: 5.1.17763.2931
```

### 📝 Description

1.  Perform Usual installation and run `Install.bat`
2. Wait until cmd finishes downloading and reach 100% progress
3. Installation throws an error message "This application only runs under WinPE or WinRE".

### 📸 Screenshots

![screenshot1](https://user-images.githubusercontent.com/69841722/199465248-d9a8600f-2c0b-4bf6-97d0-dd26365ccd73.jpg)
![screenshot2](https://user-images.githubusercontent.com/69841722/199465290-4416a7a6-9015-4960-8868-ad29f5e07ebc.jpg)

**Comment by amd64fox** [comment]
Try [this guide](https://youtu.be/3yE6qrUshFA) to solve this problem

**Comment by kcayme** [comment]
The guide works. thanks!
