### ISSUE TITLE
Are the audio books supposed to work? And also in the features it says that "Hiding podcasts, episodes and audiobooks from the homepage" is optional so how do I turn this off to get access to the audiobooks?

### ISSUE THREAD

**Issue by dt604121** [SpotX-Official/SpotX#207]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

united states

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.1.90.859.gf1bb1e36 (couldn't find)
- Windows: Windows 11 21H2 22000.527 (don't have pause/break button - couldn't find)
- PowerShell: 5.1.22000.832 (did get this one though :)
```

### 📝 Description

1. click on the search bar (worked fine - what I expected)
2. click on audiobooks (worked fine - what I expected)
3. choose an audiobook and click on it (doesn't work - not what I expected)
4. it loads and then says "couldn't find that page" 
...

### 📸 Screenshots

![findpage](https://user-images.githubusercontent.com/97199531/201213449-98a9a66a-892b-4090-8a26-909cb68e775c.png)

**Comment by amd64fox** [comment]
Fixed
update SpotX

> **Note**
If you are using Spotfiy version `1.1.92` and below, then in order for audiobooks to work correctly, you should not turn off podcasts on the main page when installing the patch
