### ISSUE TITLE
Ads Returned

### ISSUE THREAD

**Issue by alielmorsy** [SpotX-Official/SpotX#208]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Egypt

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.98.691.gf759311c
- Windows: 10
- PowerShell: 2.0
```

![Screenshot (106)](https://user-images.githubusercontent.com/40503003/201461717-5f8cd2bb-0eb0-4bb0-ba4c-b1c6d897a06a.png)

### 📝 Description

After a while of using that tool ads returned

**Comment by amd64fox** [comment]
Perform a clean install as described in the [FAQ](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation)

If the problem remains then refine your full version of Spotify, no need to specify `latest`

Also describe or take a screenshot to see exactly how your ad looks like.

**Comment by alielmorsy** [comment]
> Perform a clean install as described in the [FAQ](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation)
> 
> If the problem remains then refine your full version of Spotify, no need to specify `latest`
> 
> Also describe or take a screenshot to see exactly how your ad looks like.

I have updated the issue

**Comment by amd64fox** [comment]
you have not installed SpotX
Read the [FAQ](https://telegra.ph/SpotX-FAQ-09-19)
