### ISSUE TITLE
How to return the old left sidebar

### ISSUE THREAD

**Issue by Mojas84** [SpotX-Official/SpotX#213]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Czech

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.1.98.691
- Windows: Windows 11 21H2 22621.819
- PowerShell: PowerShell 7.3.0 x64
```

### 📝 Description

1.
2.
3.
...
Hi im spitecify installed and in new version spotify see only albums on the left panel. NOT marketplace or home.......????

### 📸 Screenshots

![bandicam 2022-11-12 09-27-29-031](https://user-images.githubusercontent.com/108186899/201465625-7155302d-161f-4f41-b5df-ad52e1c3f687.jpg)

**Comment by amd64fox** [comment]
use the input parameter `-left_sidebar_old` to return the old left sidebar

**Comment by lmfaodeep** [comment]
where do i input the parameter to?

**Comment by amd64fox** [comment]
to your install string, read [here](https://github.com/SpotX-CLI/SpotX-Win/discussions/60) if you want details

Example string for PowerShell
```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/SpotX-CLI/SpotX-Win/main/Install.ps1').Content) } -left_sidebar_old"
```

or create a new `*.bat` file with the input parameters you need

**Comment by Mojas84** [comment]
> use the input parameter `-left_sidebar_old` to return the old left sidebar

Very much thanks for this..... Worked!!!

**Comment by amd64fox** [comment]
I brought back the old sidebar because a bug was found in the new one
just update spotx
