### ISSUE TITLE
bug in new left sidebar

### ISSUE THREAD

**Issue by NightofNecromancy** [SpotX-Official/SpotX#215]
### Description of the new feature / enhancement

Give the user the option to change how playlists are shown. I myself really don't like how playlists are viewed as images and not as text. I doubt I am the only one who has this view. Ideally this could be put in the "Display" category or just in the Y/N section of instillation. The removal of showing the cover art for the song is also annoying as it is useful if you close the playlist by accident and can't remember which playlist it was in.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/118074252/201489265-ae368cfe-41bb-4f83-ae11-eff2861ee05b.png)

![image](https://user-images.githubusercontent.com/118074252/201489591-d8ef2847-a40e-4588-8d05-326a973babab.png)

**Comment by amd64fox** [comment]
duplicate https://github.com/SpotX-CLI/SpotX-Win/issues/213
It's just that not long ago a vote was held in the [telegram group](https://t.me/SpotxCommunity/328?topic=315) where users chose a new panel.

**Comment by NightofNecromancy** [comment]
> duplicate #213 It's just that not long ago a vote was held in the [telegram group](https://t.me/SpotxCommunity/328?topic=315) where users chose a new panel.

I imagine this was also something they voted on?:

![image](https://user-images.githubusercontent.com/118074252/201522054-3efa9b14-0fa5-43db-93bf-bb60e8f76875.png)

**Comment by amd64fox** [comment]
ooh damn
didn't see this bug
I will return the old sidebar
