### ISSUE TITLE
Linux support when?

### ISSUE THREAD

**Issue by ghost** [SpotX-Official/SpotX#218]
### Description of the new feature / enhancement

- Linux support for SpotX, like there is for MacOS.
- I know there are Snaps and Flatpaks on Linux, but you can just use the flatpak version to mod it or maybe just the elf binary from the .deb package
- Users may be prompted to insert the spotify binary path at the install stage

**Comment by amd64fox** [comment]
https://github.com/SpotX-CLI/SpotX-Linux
