### ISSUE TITLE
Auto Install on Spotify Update

### ISSUE THREAD

**Issue by yodaluca23** [SpotX-Official/SpotX#22]
## 📝 Description of the idea

1. Have an option in the installation menu to automatically re-install when it detects that Spotify has updated. 

2. Or if that's not possible then at least have an option to have it notify you.

**Comment by amd64fox** [comment]
Hello.
You want to remove the Spotify update confirmation from the script and immediately start installing the update, do I understand you correctly?

**Comment by yodaluca23** [comment]
> Hello.
> 
> You want to remove the Spotify update confirmation from the script and immediately start installing the update, do I understand you correctly?

Yes, and then reinstall SpotX

**Comment by amd64fox** [comment]
Your logic is clear, but what if my patch is temporarily not adapted for the new version? In such cases, even if you manually install an older version of Spotify, the script will automatically update it, although you do not need it.

I suggest leaving the choice to the user.

In any case, I recommend a clean install of my patch when there is no Spotify client on the PC, then the latest version of Spotify at the moment for your region will be installed automatically, often helps to solve possible errors.

**Comment by yodaluca23** [comment]
> Your logic is clear, but what if my patch is temporarily not adapted for the new version? In such cases, even if you manually install an older version of Spotify, the script will automatically update it, although you do not need it.
> 
> 
> 
> I suggest leaving the choice to the user.
> 
> 
> 
> In any case, I recommend a clean install of my patch when there is no Spotify client on the PC, then the latest version of Spotify at the moment for your region will be installed automatically, often helps to solve possible errors.
> 
> 
> 
> 

But you see the problem is that I want to be able to install it once and then forget about it and automatically update Spotify to the latest compatible version and install its self again.

**Comment by amd64fox** [comment]
I don't quite understand you now,
All this can be done now.

Or are you talking about blocking Spotify updates ?

I apologize in advance, I do not always understand English well.

**Comment by amd64fox** [comment]
In general, if you meant to remove this confirmation, which I highlighted in the screenshot, then while I leave it, I explained the reason a little higher.

<details>
<summary><small>Screenshot</small></summary><p>

![Снимок экрана 2022-02-04 225456](https://user-images.githubusercontent.com/62529699/152594885-43f9a64c-230e-44c8-ac09-ed1ad56a253b.jpg)


</small></summary><p>

</details>

If you meant something else, then try again to explain in more detail, and also attach a screenshot.
