### ISSUE TITLE
Installer doesn't work if you havent ran Internet Explorer at least once before running it

### ISSUE THREAD

**Issue by puddenn** [SpotX-Official/SpotX#222]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Sweden

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows
1.1.98.691.gf759311c
- Windows: 7 x64 SP1
- PowerShell: v3.0
```

### 📝 Description

This is not a "bug" but I think that it's important to share, maybe you can put it on the main page as a note. If you have a clean Windows 7 installation and install powershell 3 without ever having ran Internet Explorer the installer doesn't seem to work

I tried running it a million times and eventually got this error; 
![spotxinstaller0](https://user-images.githubusercontent.com/75831581/202903011-6ed224a7-fa87-402d-8a93-5e2a5e5df037.jpg)

So I tried running both 32 and 64 bit Internet Explorer once and that seems to have fixed the issue, the installer then worked flawlessly

**Comment by amd64fox** [comment]
reproduce this error now

**Comment by Kobi-Blade** [comment]
Are you guys even supporting Windows 7 however? Is a dead operating system that not even Spotify is supporting, so yes, not  a bug.

Your time is better wasted on supported software.

**Comment by amd64fox** [comment]
they still support windows vista lul

I support windows 7 partially, most users are win 10

if users have updated their Windows 7, then spotx works with it without problems, but there are always small exceptions

**Comment by Kobi-Blade** [comment]
> they still support windows vista lul
> 
> I support windows 7 partially, most users are win 10
> 
> if users have updated their Windows 7, then spotx works with it without problems, but there are always small exceptions

No.. they don't..

You may be able to install Spotify on Windows Vista, but is not supported by Spotify, you free to check their website.

![image](https://user-images.githubusercontent.com/15495525/204373080-c8158328-45df-4f1a-a00e-0d98eb6bc7dd.png)

**Comment by amd64fox** [comment]
The website contains general information.
here is the manifest of the latest installer for windows:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <assemblyIdentity
    version="1.0.0.0"
    processorArchitecture="*"
    name="SpotifyInstaller"
    type="win32"
  />
  <description>Spotify Installer</description>

  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <!-- Windows 10 -->
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
      <!-- Windows 8.1 -->
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
      <!-- Windows Vista -->
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
      <!-- Windows 8 -->
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
      <!-- Windows 7 -->
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
    </application>
  </compatibility>

  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"></requestedExecutionLevel>
      </requestedPrivileges>
    </security>
  </trustInfo>

  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">system</dpiAwareness>
    </windowsSettings>
  </application>

  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"></assemblyIdentity>
    </dependentAssembly>
  </dependency>
</assembly>
```
