### ISSUE TITLE
Input parameter to hide the 'Now-playing panel'

### ISSUE THREAD

**Issue by Fuerget** [SpotX-Official/SpotX#226]
### Description of the new feature / enhancement

The right-sided 'Now-playing panel' keeps popping up when manually switching to songs of different records/playlists.

Haven't found a fitting parameter for it in the list

https://github.com/SpotX-CLI/SpotX-Win/discussions/60

Spotify für Windows
1.1.99.878.g1e4ccc6e
SpotX 1.6

### 📸 Screenshots

![Capture](https://user-images.githubusercontent.com/99146712/203729321-54a25aab-2dd8-4947-bec7-15e950499301.PNG)

**Comment by amd64fox** [comment]
turn it off in settings
![Снимок экрана 2022-11-24 122646](https://user-images.githubusercontent.com/62529699/203746862-04664755-1bee-4a24-892f-330abd97d786.jpg)
