### ISSUE TITLE
<h2>New left sidebar (disabled by default) not showing</h2>

### ISSUE THREAD

**Issue by StaticGamerYT-India** [SpotX-Official/SpotX#228]
<h2>New left sidebar (disabled by default)</h2>

**Feature from:** Spotify

**Description:** it doesnt show in Spotify for Windows
1.1.99.878.g1e4ccc6e

![vor9bubsryx91](https://user-images.githubusercontent.com/62529699/200853207-4761810f-1ed2-4342-8c98-37233f687fde.jpg)

_Originally posted by @amd64fox in https://github.com/SpotX-CLI/SpotX-Win/discussions/50#discussioncomment-3741709_

**Comment by StaticGamerYT-India** [comment]
![image](https://user-images.githubusercontent.com/77852984/204075942-d5cecc0c-2de2-4781-8741-1ff3afb9c1af.png)

**Comment by amd64fox** [comment]
it also says that `disabled by default`
To enable use the input parameter `-left_sidebar_on`
read more about incoming parameters [here](https://github.com/SpotX-CLI/SpotX-Win/discussions/60)

**Comment by StaticGamerYT-India** [comment]
thank you so much
but i dont know how do i use these parameters
do i have to install spotify again with using new parameters ?

**Comment by StaticGamerYT-India** [comment]
hey well i figured it out thank you so much :)
