### ISSUE TITLE
Off "Album Release Anniversaries"

### ISSUE THREAD

**Issue by IIIu6ko** [SpotX-Official/SpotX#229]
### Description of the new feature / enhancement

I didn't find an option to disable "[Album Release Anniversaries](https://github.com/SpotX-CLI/SpotX-Win/discussions/50#discussioncomment-3215923)" [here](https://github.com/SpotX-CLI/SpotX-Win/discussions/60). Is it possible to add such functionality?

***
If you like the idea, add a 👍 reaction to this post.

**Comment by amd64fox** [comment]
use this [instruction](https://github.com/SpotX-CLI/SpotX-Win/discussions/47) to disable this feature
