### ISSUE TITLE
сбивается громкость звука после перезагрузки

### ISSUE THREAD

**Issue by cherrypashka47** [SpotX-Official/SpotX#23]
привет. проблема, конечно, не критичная, но всё-таки не приятная. по рефлексу включаю музыку после включения пк, а тут включается на всю громкость, минус уши получаются. это возможно как-то исправить чтобы каждый раз не менять громкость?

**Comment by amd64fox** [comment]
Привет
Проверил, подобного бага воспроизвести не удалось.
Какая версия Windows и Spotify ?
Пробовали переустановить начисто клиент ?

**Comment by yodaluca23** [comment]
Ok, that makes more sense, thank you

**Comment by cherrypashka47** [comment]
у меня windows 10 21h2, spotify 1.1.79.763
такое получается (у меня по крайней мере), если я устанавливаю начисто spotify с помощью spotx.
сейчас установил клиент с офф. сайта, и поверх него установил мод - звук больше не сбивается.
так что проблема решена, спасибо)
