### ISSUE TITLE
The remote name could not be resolved

### ISSUE THREAD

**Issue by Hassan20212** [SpotX-Official/SpotX#233]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [x] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Egypt

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.99.878.g1e4ccc6e
- Windows: Windows 11 21H2 22000.1219
- PowerShell: 5.1.22000.832
```

### 📝 Description

Invoke-WebRequest : The remote name could not be resolved: 'raw.githubusercontent.com'
At line:1 char:90
+ ... Tls12}; & {(Invoke-WebRequest -UseBasicParsing 'https://raw.githubuse ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by amd64fox** [comment]
change DNS from ISP default or use VPN

**Comment by amd64fox** [comment]
TESTING:
Only for those who get similar errors when running the SpotX installation 

error screenshots


<details>
<summary><small>error screenshots</small></summary><p>

![8e308754b7eb9754356f6](https://user-images.githubusercontent.com/62529699/220090611-5aa040ed-17b1-4c06-bf99-943c722f95a9.png)
![206230636-25c8e688-9576-47cf-a5eb-78cf623c3a20](https://user-images.githubusercontent.com/62529699/220090618-cb73203a-c960-41d2-ab2c-5f3b3b0735b8.png)
![211215035-bbe9452f-26b7-4385-96f6-b0ca79ddc007](https://user-images.githubusercontent.com/62529699/220090621-c916d730-a36a-4def-80fb-618881001211.png)


</details>


Try to use these bat files:

[Install_New_theme.bat](https://raw.githack.com/amd64fox/SpotX/statically/Install_New_theme.bat)
[Install_Old_theme.bat](https://raw.githack.com/amd64fox/SpotX/statically/Install_Old_theme.bat)

also do not forget to report the result, whether it helped you or not, answer with the mention of this message.

Thanks.

**Comment by prashantk100** [comment]
I have used ultrasurf or snap VPN in google chrome browser and also changed DNS to 8.8.8.8 in tcp/ip 4 properties for the ethernet adapter to make it work. I request developer to use locally https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1 to pack as local install.ps1 script download in local machine and modify  install script use to local install.ps1 script from local drive instead  from internet to resolve the problem for all users OR host the install.ps1 in new web location which is not banned by ISP internet providers.

**Comment by amd64fox** [comment]
You need to use a global VPN for the entire Windows OS, not just for Google Chrome, or you can try our [ready builds](https://t.me/SpotxCommunity/1049).
