### ISSUE TITLE
Chinese Traditional Translation

### ISSUE THREAD

**Issue by asd9176506911298** [SpotX-Official/SpotX#237]
### What language do you want to translate into?

Chinese Traditional

### Enter language name in PowerShell

zh

### 📝 Translation strings

```txt
Author          = "補丁作者:"
Author2         = "@Amd64fox"
TranslationBy   = "翻譯作者:"
TranslationBy2  = "@asd9176506911298"
Incorrect       = "糟糕, 不正確的參數,"
Incorrect2      = "請重新輸入 "
Download        = "下載錯誤"
Download2       = "將在五秒後重試"
Download3       = "再次出錯"
Download4       = "檢查您的網路設定後再次嘗試安裝"
Download5       = "下載 Spotify"
Download6       = "Curl 錯誤"
StopScrpit      = "腳本已停止"
MsSpoti         = "偵測到不支援的 Spotify 微軟商店版本"
MsSpoti2        = "解除安裝微軟商店的 Spotify [Y/N]"
MsSpoti3        = "自動解除安裝 Spotify 的微軟商店版本..."
MsSpoti4        = "正在解除安裝 Spotify 的微軟商店版本..."
Prem            = "針對 Premium 帳號的修改..."
OldV            = "發現過時的 Spotify 版本"
OldV2           = "您的Spotify {0} 版本已過時, 建議更新到 {1}"
OldV3           = "需要更新嗎? [Y/N]"
AutoUpd         = "自動更新到推薦版本"
DelOrOver       = "是否要解除安裝當前版本 {0} 或者覆蓋安裝? Y [解除安裝] / N [覆蓋安裝]"
DelOld          = "解除安裝舊的 Spotify..."
NewV            = "偵測到不支援的 Spotify 版本"
NewV2           = "您的 Spotify {0} 版本還沒有經過測試, 目前穩定的版本是 {1} "
NewV3           = "您想要繼續使用 {0} 版本嗎 (可能會出現錯誤) ? [Y/N]"
Recom           = "您想安裝推薦的 {0} 版本嗎 ? [Y/N]"
DelNew          = "解除安裝未經測試的 Spotify 版本..."
DownSpoti       = "下載並安裝 Spotify"
DownSpoti2      = "請稍等..."
PodcatsOff      = "關閉Podcasts"
PodcastsOn      = "開啟Podcasts"
PodcatsSelect   = "您想要關閉主頁上的Podcasts, 劇集和有聲書嗎? [Y/N]"
DowngradeNote   = "推薦阻止 Spotify 降級"
UpdBlock        = "阻止 Spotify 更新"
UpdUnblock      = "不阻止 Spotify 更新"
UpdSelect       = "您想要阻止 Spotify 更新嗎? [Y/N]"
CacheOn         = "清除快取已開啟 ({0})"
CacheOff        = "未開啟清除快取"
CacheSelect     = "您想要設定自動清除快取嗎? [Y/N]"
CacheDays       = "超過 XX 天的快取將被清除 "
CacheDays2      = "輸入從 1 到 100 之內的天數"
ModSpoti        = "修補 Spotify..."
Error           = "錯誤"
FileLocBroken   = "Spotify 檔案已損壞, 請解除安裝客戶端並重新運行腳本"
Spicetify       = "偵測到 Spicetify"
NoRestore       = "SpotX 已經安裝, 但找不到檔案 xpui.js.bak 和 xpui.css.bak not `n請重新安裝 Spotify 客戶端後再運行 Install.bat"
ExpSpotify      = "啟用 Spotify 的實驗性功能Experimental features operated by Spotify"
ExpStandart     = "SpotX的實驗性功能沒有啟用"
NoRestore2      = "SpotX 已經安裝, 但是找不到xpui.bak `n請重新安裝 Spotify 客戶端後再運行 Install.bat"
UpdateBlocked   = "Spotify 更新已經被阻止"
UpdateError     = "阻止更新失敗"
NoSpotifyExe    = "找不到 Spotify.exe"
InstallComplete = "安裝完成"
HostInfo        = "在 hosts 檔案中發現不需要的 URL"
HostBak         = "備份原始 hosts 檔案為 hosts.bak..."
HostDel         = "嘗試從原始 hosts 檔案中刪除不需要的 URL ..."
HostError       = "在編輯 hosts 檔案時發生了錯誤, 請手動編輯或以系統管理員身分運行腳本"
```
![language_name](https://user-images.githubusercontent.com/35301327/205502526-b2acffbb-c0c5-4ea2-847e-963b75f3e954.png)

**Comment by lumineyuri** [comment]
我在尝试翻译到繁体时发现简体和繁体终端输出都是"zh" 属实是奇怪
When I tried to translate to traditional Chinese, I found that both simplified and traditional Chinese terminals output "zh", which is weird.

**Comment by amd64fox** [comment]
need to redo the function for choosing languages, since I did not expect that there would be so many of them

@lumineyuri 
what does the terminal show if you enter the `$PSUICulture` command


[this list](https://learn.microsoft.com/en-us/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a) is as follows:

Chinese-Taiwan: zh-TW

and how is simplified Chinese indicated there?

**Comment by lumineyuri** [comment]
> need to redo the function for choosing languages, since I did not expect that there would be so many of them
> 
> @lumineyuri what does the terminal show if you enter the `$PSUICulture` command
> 
> [this list](https://learn.microsoft.com/en-us/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a) is as follows:
> 
> Chinese-Taiwan: zh-TW
> 
> and how is simplified Chinese indicated there?

When you enter `$PSUICulture`, you get `zh_CN`.
When inputting `$PSUICulture.Remove(2)`, the result is `zh`.

**Comment by amd64fox** [comment]
added

[this language](https://github.com/SpotX-CLI/SpotX-Win/blob/main/scripts/installer-lang/zh.ps1) will be the main language for all varieties of Chinese, to manually start it, just add the input parameter `-l zh` 
or `-l zh-cn`

but if the default [zh-TW](https://github.com/SpotX-CLI/SpotX-Win/blob/main/scripts/installer-lang/zh-TW.ps1) is found in the console, then it will be launched, or to run it manually, you need to enter its full name, for example: `-l zh-tw`

if I didn't correctly choose `zh-CN` as the main language, then point it out here, I'm not familiar with the varieties of Chinese.
