### ISSUE TITLE
SpotX APK

### ISSUE THREAD

**Issue by yodaluca23** [SpotX-Official/SpotX#24]
## 📝 Description of the idea
Make an APK version of this for mobile, because their are several out their but I don't know if I can trust them...

**Comment by amd64fox** [comment]
Use [xManager](https://github.com/xManager-v2/xManager-Spotify), it's safe

**Comment by yodaluca23** [comment]
> Use [xManager](https://github.com/xManager-v2/xManager-Spotify), it's safe

@amd64fox 

It doesn't look like it blocks ads and allows infinite skips... does it?

Is this perhaps safe?

https://github.com/avatar282/Spotify-APKV7.3.2

But even if it is I doubt that it is any as good as SpotX because SpotX also does not allow the logs to be sent to Spotify therefore keeping my account from being banned...

**Comment by amd64fox** [comment]
> It doesn't look like it blocks ads and allows infinite skips... does it?

Read more about [xManager here](https://telegra.ph/Spotify-Mod-FAQ-07-19)


> Is this perhaps safe?
> 
> https://github.com/avatar282/Spotify-APKV7.3.2

This is the first time I see this repo, it hasn't been updated since 2016, also it doesn't have a compiled apk which you can check somehow.

**Comment by yodaluca23** [comment]
Ok, that makes more sense, thank you

**Comment by yodaluca23** [comment]
@amd64fox Do you have a recommended IPA for iPhone?

**Comment by amd64fox** [comment]
> iOS: Spotilife mod or Plugin. Needs jailbreaked iPhone or access to install unsigned apps. You will know where to find it, if you know how to jailbreak/has access to install unsigned apps.

more information can be found on the discord...

**Comment by yodaluca23** [comment]
> > iOS: Spotilife mod or Plugin. Needs jailbreaked iPhone or access to install unsigned apps. You will know where to find it, if you know how to jailbreak/has access to install unsigned apps.
> 
> 
> 
> more information can be found on the discord...

Can you link their Github and/or Discord?

**Comment by amd64fox** [comment]
I meant SpotX [Discord](https://discord.gg/p43cusgUPm)
