### ISSUE TITLE
Now Playing Panel Not There After Update

### ISSUE THREAD

**Issue by LimitedEdiition** [SpotX-Official/SpotX#241]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

US

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows 1.2.0.1165.gabf054ab
- Windows: 11 2H22 Build 22621
- PowerShell: 5.1.22621.608
```

### 📝 Description

After updating to the latest version of SpotX through command prompt, the Now Playing Panel is now gone from the client. It was working prior to the latest update.

**Comment by amd64fox** [comment]
to enable use the [input parameter](https://github.com/SpotX-CLI/SpotX-Win/discussions/60) `-right_sidebar_on`
