### ISSUE TITLE
SPOT INTALLATION ERROR

### ISSUE THREAD

**Issue by GREEKY69** [SpotX-Official/SpotX#245]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [x] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.99.878.g1e4ccc6e

-Window: Windows 11 22H2 22622.450

- PowerShell: 5.1.22621.436
```

### 📝 Description

**1.** I TRIED INSTALLING SEVERAL TIMES BUT IT DIDNT WORK

**2.** I ALSO TRIED DELETING SPOT X N REINSTALLING FROM GITHUB N INSTALL AGAIN THA ALSO DIDNT WORK

**3.** I ALSO TRIED TO DELETE AND REINSTALL SPOTIFY THAT ALSO DIDNT WORK

### 📸 Screenshots

![Screenshot (32)](https://user-images.githubusercontent.com/120035885/206230636-25c8e688-9576-47cf-a5eb-78cf623c3a20.png)

**Comment by ghost** [comment]
@GREEKY69 i am also facing this problem

**Comment by GREEKY69** [comment]
DEV pls give solution asap TT

**Comment by amd64fox** [comment]
Duplicate https://github.com/SpotX-CLI/SpotX-Win/issues/233
