### ISSUE TITLE
SpotX not working

### ISSUE THREAD

**Issue by ghost** [SpotX-Official/SpotX#246]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify:1.2.0.1165.gabf054ab
- Windows:  21H2 19044.2251
- PowerShell: 5.1.19041.1682
```

### 📝 Description

1.
2.
3.
...

### 📸 Screenshots

![Screenshot 2022-12-08 173930](https://user-images.githubusercontent.com/83867504/206443583-c45c40f8-9441-48f4-905d-447a0aaabc4b.jpg)

**Comment by GREEKY69** [comment]
yes we both having same issue TT

**Comment by amd64fox** [comment]
Is your problem solved if you use this

**Comment by ghost** [comment]
> Is your problem solved if you use this

![image](https://user-images.githubusercontent.com/83867504/206458835-f0ab2647-f676-4e7a-8aa6-9bb62f9c6a64.png)


Not working!!!!

**Comment by amd64fox** [comment]
Duplicate https://github.com/SpotX-CLI/SpotX-Win/issues/233
