### ISSUE TITLE
Possible to add a song streamed counter & sort by stream count in the artist album page & Playlist page?

### ISSUE THREAD

**Issue by Droyk** [SpotX-Official/SpotX#249]
### Description of the new feature / enhancement

![image](https://user-images.githubusercontent.com/15848350/206851608-8dc7ef1f-6d40-42ff-9779-17c550fd2143.png)

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
In SpotX environment this will be difficult to implement, try making a request [here](https://github.com/spicetify/spicetify-cli/issues/new?assignees=&labels=%E2%9C%A8+feature&template=feature_request.yml)
