### ISSUE TITLE
implement spicetify program

### ISSUE THREAD

**Issue by Alz97** [SpotX-Official/SpotX#251]
### Description of the new feature / enhancement

Can you implement the spicetify program inside the code? 
I saw there're some problems with it.

### 📸 Screenshots

[Spicetify revealed, SpotX was installed, but xpui.js.bak & xpui.css.back files to retrieve was not finded. Please, unistall spotify and reopen install.bat](https://easyupload.io/9r0lvs)

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
Perform a clean install of Spicetify then install Spotx
