### ISSUE TITLE
Left playlist bar bugs (I figure you could fix it in advance)

### ISSUE THREAD

**Issue by ben401rs** [SpotX-Official/SpotX#255]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Latest
- Windows: 10
- PowerShell: Latest
```

### 📝 Description

Using the install param _-left_sidebar_on_
1. The playlists are not moveable and cannot be rearrange even when i choose custom order
2. Buggy and not working when enabling local files in the settings (cant open the folders and the app freeze)
3. Currently has messy resizeable sidebar (for some reason cannot move it past the playlists names) and aren't sizable enough
...

### 📸 Screenshots

I figure you can test it and fix it in advance, i suppose these are native spotify features not yet to be released yet and it would be great if you somehow figure a way to fix it

Thank you so much for your attention

**Comment by amd64fox** [comment]
This is an experimental feature of Spotify, there is no point in fixing it, it is in development mode.
You can just disable it until it works stably.
