### ISSUE TITLE
After first song plays, no more songs play until you start another queue

### ISSUE THREAD

**Issue by rlygudprayer** [SpotX-Official/SpotX#258]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Indonesia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.0.1165.gabf054ab
- Windows: Windows 10 Pro 21H2 19044.2364
- PowerShell: 5.1.19041.2364
```

### 📝 Description

1. After the first song is finished, it stops until you skip the current track
2.
3.
...

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/101914197/207860757-fce95230-2c93-4a82-94d1-726a7a6acfd2.png)

**Comment by amd64fox** [comment]
more information from the [1st question of the FAQ](https://telegra.ph/SpotX-FAQ-09-19#I-have-a-bug-/-strange-client-behavior,-what-can-I-do-?)

**Comment by um488** [comment]
I have the same issue. Clean re-installation did nothing.

**Comment by amd64fox** [comment]
Does this bug appear if you are using the original Spotify client?

Perhaps this bug is related to [this](https://community.spotify.com/t5/Ongoing-Issues/Song-Podcast-skipping-when-clicking-sliding-the-progress-bar-in/idi-p/5461014), then try these steps:

1. Go to Settings > Audio quality and set the Streaming quality to High.

2. Scroll all the way down to Compatibility and disable hardware acceleration.

**Comment by um488** [comment]
Don't know about original client but it is not present on web version(Firefox).
These steps didn't help. 

I only started seeing bug last week, this behavior is not consistent though. I can only reproduce this bug like 80% of the times I restart spotify.

**Comment by amd64fox** [comment]
well, check it out in the original desktop version

**Comment by um488** [comment]
I'll check in a few hours.

But apparently this bug only appears when I start a playlist and restart the app. This doesn't happen if I play single song from search or home and then restart.

**Comment by um488** [comment]
So original desktop version(1.2.0.1165.gabf054ab) also has the same bug. 

While reinstalling Spotx noticed that it was also installing the same version instead of the recommended version(1.1.97.962.g24733a46).

Manually installed 1.1.97.962 and now everything works fine.

**Comment by amd64fox** [comment]
So this is not a spotx problem.
Recommended version for spotx is **1.2.0.1165**
