### ISSUE TITLE
Could Not Install SpotX

### ISSUE THREAD

**Issue by StaticGamerYT-India** [SpotX-Official/SpotX#259]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: deleted
- Windows: Windows 11 22H2
- PowerShell: dont know
```

### 📝 Description

1. Installed Spot X by using the bat file but didnt work 
it showed this

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/77852984/207999633-c8fa8427-451f-4546-8c7e-48e8275a40fc.png)

**Comment by amd64fox** [comment]
Duplicate https://github.com/SpotX-CLI/SpotX-Win/issues/233
