### ISSUE TITLE
Patching errors on latest version

### ISSUE THREAD

**Issue by JasonShearer** [SpotX-Official/SpotX#26]
## ℹ Computer information

- Spotify version: 1.80.699.gc3dac750
- Windows version: 21H1 19043.1566
- PowerShell version: 5.1.19041.1320 and 7.2.1

## 📝 Description of the problem

Getting the following errors when patching a clean install of the latest version:

_Didn't find variable $full_screen_1[0] in xpui.js_
_Didn't find variable $full_screen_2[0] in xpui.js_

Everything still seems to be working fine, however the "Upgrade" button isn't being removed.

**Comment by amd64fox** [comment]
At the moment I have no way to fix it, no PC at hand, I will be at home within a week.

In the meantime, you can install the previous version from here https://cutt.ly/8EH6NuH

and choose to block updates when reinstalling the patch
