### ISSUE TITLE
Discord Listen Along Doesnt Work

### ISSUE THREAD

**Issue by draconixx** [SpotX-Official/SpotX#262]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Canada

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows
1.2.1.968.g21027577 
- Windows: Windows 10 Home 22h2 19045.2364
- PowerShell: 5.1.19041.2364
```

### 📝 Description

Listenin along on discord doesn't work for other party.
1. ivite to listen along on spotify
2. friend clicks, but hears no sound and it doesnt work

**Comment by amd64fox** [comment]
![Снимок экрана 2022-12-23 030959](https://user-images.githubusercontent.com/62529699/209245929-e0714fa7-fb4b-4b5f-8f21-788e208e8063.jpg)

or use [plugins](https://youtu.be/iTN50HCZtak) for modified discord client
