### ISSUE TITLE
Full uninstall does not work

### ISSUE THREAD

**Issue by cyberboh** [SpotX-Official/SpotX#263]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Indonesia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.01165
- Windows: Windows 10 21H2
Device name	XXXXXXXXXXXXXX
Processor	Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz   1.99 GHz
Installed RAM	4.00 GB (3.89 GB usable)
Device ID	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Product ID	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

- PowerShell: 5.1.19041.2364
```

### 📝 Description

Full Uninstall does not work
https://github.com/amd64fox/Uninstall-Spotify

PC Username theres space

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/99109969/209262672-f7de9314-542c-42ac-bcba-4e85e33b4107.png)

**Comment by amd64fox** [comment]
thanks for the feedback, fixed
