### ISSUE TITLE
It's showing server not connected every time

### ISSUE THREAD

**Issue by Mohameddhaanish** [SpotX-Official/SpotX#266]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify:  1.2.0.1165
- Windows: 10
- PowerShell: 5.1.19041.2364
```

### 📝 Description

1.unable to connect to remote server.

### 📸 Screenshots

![Screenshot (30)](https://user-images.githubusercontent.com/52352219/210129732-92d01b44-d334-423b-94f6-28c1d9006a69.png)

**Comment by amd64fox** [comment]
Duplicate https://github.com/SpotX-CLI/SpotX-Win/issues/233

**Comment by Mohameddhaanish** [comment]
How to unauthorised it?
