### ISSUE TITLE
Implement a working Xbox Game Bar

### ISSUE THREAD

**Issue by adben27** [SpotX-Official/SpotX#267]
### Working Xbox Game Bar widget

Hello, 
First, thanks for this nice project.

However, it would be good to implement a Spotify Game Bar widget for SpotX. Indeed, the official one just reinstalls stock Spotify.
It would be really nice to make the widget work with SpotX. 

Thanks !

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
Hi
there are no plans to create a new widget
