### ISSUE TITLE
Ability to mark and copy song/album/artist name

### ISSUE THREAD

**Issue by todesschnitzel** [SpotX-Official/SpotX#269]
### Description of the new feature / enhancement

Hey,
Spotify decided, its won't add this feature, so maybe SpotX-Win can add this?

Just some ideas, how this could maybe work:
- through a rightclick menu (Copy Title, Album, Artist)
- else on the Credits page on each song, which also has some of the informations
- you can select the text while holding a key
- through the "share" feature

I would love to see this feature!
Thanks!

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
use the `copy to clipboard` extension in [spicetify](https://github.com/spicetify/spicetify-cli)
