### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by pranavagrawal321** [SpotX-Official/SpotX#271]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [x] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.1165.gabf054ab
- Windows: Windows 11 22H2 22623.1037
- PowerShell: 7.3.1
```

### 📝 Description

Powershell installation shows 

Invoke-WebRequest: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/60977233/211215035-bbe9452f-26b7-4385-96f6-b0ca79ddc007.png)

**Comment by amd64fox** [comment]
Duplicate https://github.com/SpotX-CLI/SpotX-Win/issues/233
