### ISSUE TITLE
How to start music at a certain moment?

### ISSUE THREAD

**Issue by rodukov** [SpotX-Official/SpotX#274]
### Description of the new feature / enhancement

I would like to propose the idea of starting music at a certain moment. This can be useful, for example, to use the Discord function to listen at the same time with your friend.

_❤️Thanks for this project, I wanted to make it better._

### 📸 Screenshots

![example](https://user-images.githubusercontent.com/101352977/212410139-67fd8618-6b68-478c-b4e0-ae66151a7c50.png)

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
thanks for the idea, but I have no idea how to implement it using SpotX
