### ISSUE TITLE
Marketplace option couldn't be seen in latest version 1.2.3.1111.gce8e6576

### ISSUE THREAD

**Issue by sfksuperman** [SpotX-Official/SpotX#277]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.3.1111.gce8e6576
- Windows: Windows 11, 22H2 (22621.1105)
- PowerShell: 7.2.8
```

### 📝 Description

After installing Spicetify to apply new themes, the "Marketplace" option couldn't be seen anywhere in the Spotify app.
In older version of Spotify 1.1.98.691.gf759311c, it worked well.

I clean installed twice but Spicetify keeps saying _**marketplace was already found! Updating...**_

Could you please check how can I get marketplace and more theme options?

**Comment by amd64fox** [comment]
Did you use install new theme in Spotx ? 

if so then Spicetify most likely doesn't support the latest changes in the new theme, use the Spotx installer for the old theme

**Comment by sfksuperman** [comment]
Yeah now it worked and the marketplace is seen with the old theme. Thanks,
bro.
