### ISSUE TITLE
Left sidebar and right sidebar options no longer working

### ISSUE THREAD

**Issue by LimitedEdiition** [SpotX-Official/SpotX#278]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

USA

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 11 2H22
- PowerShell: 5.1.22621.963
```

### 📝 Description

Using the parameters: [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/SpotX-CLI/SpotX-Win/main/Install.ps1').Content) } -confirm_uninstall_ms_spoti -confirm_spoti_recomended_over -podcasts_on -cache_off -block_update_off -left_sidebar_on -right_sidebar_on -hide_col_icon_off -start_spoti"

Windows Powershell gives error claiming "A parameter cannot be found that matches parameter name 'left_sidebar_on'" which was working the last time I ran the same command. Same error for the right sidebar. I have used this script for the past few months and no issues up until recently.

**Comment by amd64fox** [comment]
the incoming parameters for the right and left sidebars have been removed, use the `-new_theme` parameter
