### ISSUE TITLE
Hide Spotify free when alt tab or in uncombined taskbar.

### ISSUE THREAD

**Issue by d6dash37** [SpotX-Official/SpotX#282]
### 📸 Screenshots

![image](https://user-images.githubusercontent.com/114002290/213884136-ee2cce4d-e46f-47f7-adb2-1dbc60d02980.png)

![image](https://user-images.githubusercontent.com/114002290/213884188-d757946c-8f99-405b-a91e-0263febd3595.png)

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
Duplicate of https://github.com/amd64fox/SpotX/issues/95
