### ISSUE TITLE
Variable Error

### ISSUE THREAD

**Issue by vorzdesigns** [SpotX-Official/SpotX#283]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Germany

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: ? (Cant give the version because the Spotify Client is stuck at a Blank Screen)
- Windows: Windows 11 22H2 22621.1105
- PowerShell: 5.1.22621.963
```

### 📝 Description

Probably new Spotify Update causing these problems (change of variables?)

### 📸 Screenshots

https://i.imgur.com/9La1lym.png

**Comment by amd64fox** [comment]
read the [FAQ](https://telegra.ph/SpotX-FAQ-09-19#I-have-a-bug-/-strange-client-behavior,-what-can-I-do-?)
