### ISSUE TITLE
Top bar for song names, albums and duration is bugged when searching

### ISSUE THREAD

**Issue by ben401rs** [SpotX-Official/SpotX#284]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: whatever latest spotify version spotx uses
- Windows: 10
```

### 📝 Description

There's a minor bug with the top bar when searching songs, the bar for album, names and duration at the top where its supposed to be are way below its intended place, as you can see it looks a bit odd. Also please bring back the -left sidebar and right side bar params, i prefer customizing my spotify to my liking.

### 📸 Screenshots

![screens](https://user-images.githubusercontent.com/99275631/213902125-947e8b12-2056-4777-b929-7280e3f2198d.jpg)

**Comment by ben401rs** [comment]
i forgot one more thing, i prefer the right sidebar option behaviour when clicking artists name to be the old option where it goes straight into artists info instead of taking it into the artists page like in the new theme

**Comment by amd64fox** [comment]
It seems that this bug only occurs in the new theme, in any case it is not critical, we will wait a couple of versions maybe they will fix it themselves, there have been similar bugs before.

**Comment by amd64fox** [comment]
fixed
