### ISSUE TITLE
gap between lyrics popup and control bar

### ISSUE THREAD

**Issue by ghoomfrog** [SpotX-Official/SpotX#286]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Morocco

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.3.1115.gd61a8f5c
- Windows: Windows 10 Pro 22H2 19045.2486
- PowerShell: 7.2.8
```

### 📝 Description

I open lyrics in popup mode, and I notice a gap between the popup and the bottom control bar.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/35694451/213924435-772b31c1-3ef5-4928-bdcb-120b1f4e210c.png)

**Comment by mtbrc** [comment]
Same thing but it overlaps the control bar instead

**Comment by amd64fox** [comment]
fixed

**Comment by amd64fox** [comment]
lied
not fixed yet

**PS**
there are a lot of bugs related to full-screen lyrics, I fixed the gap, but it may appear under other conditions, maybe they will fix it in the next versions

**Comment by ben401rs** [comment]
forgive me for posting in the closed issue, i notice it just close the gap by extending it to below the player buttons XD
well i guess its better than nothing
