### ISSUE TITLE
"Error loading en language"

### ISSUE THREAD

**Issue by BrowserApi** [SpotX-Official/SpotX#287]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.3.1115.gb61a8f5c

- Windows: 11

- PowerShell: 
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22621  963
```

### 📝 Description

1. Showing a error saying "Error loading en language"

I checked the language files, and theyre still there and have 4kb 'en' file in it 

### 📸 Screenshots

![error](https://user-images.githubusercontent.com/107455731/213928322-b8691e59-31ce-45bd-b57a-dd77cb16c738.jpg)

**Comment by amd64fox** [comment]
change DNS from ISP default or use VPN

**Comment by BrowserApi** [comment]
Thankyou, its **SOLVED**.. <3
