### ISSUE TITLE
Lyrics absent in the Premium Install

### ISSUE THREAD

**Issue by agopalareddy** [SpotX-Official/SpotX#289]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.3.1115.gd61a8f5c
- Windows: Windows 11 22H2 22621.1192
- PowerShell: 7.2.8
```

### 📝 Description

1. Just open Spotify, search for a song with lyrics (example: Flowers by Miley Cyrus)
2. Neither lyrics nor the button show up. Lyrics song indication is also absent below song name in album/playlist.
...

### 📸 Screenshots

1. Just open Spotify, search for a song with lyrics (example: Flowers by Miley Cyrus)
2. Neither lyrics nor the button shows up. Lyrics song indication is also absent below song name in album/playlist.
...
![image](https://user-images.githubusercontent.com/43609320/213940753-829bc462-467b-4dc2-a0d1-d47c857ad74e.png)

**Comment by amd64fox** [comment]
lyrics moved to right sidebar in new theme
also lyrics are now available in full screen mode
![Снимок экрана 2023-01-23 003222](https://user-images.githubusercontent.com/62529699/213941461-9ca450d0-229a-4d2e-88a1-f68aa96f883d.jpg)
