### ISSUE TITLE
Difference in the patched app and the web versions (web version looks similar to the unpatched app)..

### ISSUE THREAD

**Issue by twistedmacaroni** [SpotX-Official/SpotX#29]
## ℹ Computer information

- Spotify version: 1.1.81.604.gccacfc8c
- Windows version: Version 21H2 (Build 22000.588) [Windows 11 Beta]
- PowerShell version: 5.1.22000.588

## 📝 Description of the problem

1. the toggle buttons for playlist folders appear to be "open" even when they're not. the web player and the unpatched app show the correct form of it.
2. the now playing icon is white (or grey) in the patched app whereas it is green in the web app.
3. (i suggest that remove the icon redesigning altogether because spotify implemented that for everyone in the newest update)

## 📷 Screenshots

<details>
<summary><small>Screenshots</small></summary><p>

The Web App:
![image](https://user-images.githubusercontent.com/93189292/159117651-7f560275-1802-4bf5-a937-bc99b8283735.png)
![image](https://user-images.githubusercontent.com/93189292/159117713-721cab94-3ffa-48c1-adb2-e3607a2c5ce6.png)

The Patched App:
![image](https://user-images.githubusercontent.com/93189292/159117658-4d7e3d98-dbf5-42c3-a4b2-d2d956696ab1.png)
![image](https://user-images.githubusercontent.com/93189292/159117706-88254a7b-0551-494e-859b-9c1a8ce6c7f8.png)

</small></summary><p>

</details>

**Comment by amd64fox** [comment]
Thanks for the feedback.

1. Fixed a bug with folder switches.

2. As for the green speaker icon, this is a feature of the web version of the client, in the desktop version it is white.

3. What makes you think that the icon redesign was activated for all regions?

**Comment by twistedmacaroni** [comment]
> Thanks for the feedback.
> 
> 1. Fixed a bug with folder switches.
> 2. As for the green speaker icon, this is a feature of the web version of the client, in the desktop version it is white.
> 3. What makes you think that the icon redesign was activated for all regions?

1. thanks!
2. oh okay i didnt know that 
3. because india is the country where the features are available at the end and it has got the new icons so...

**Comment by amd64fox** [comment]
I will take note of the information.

**Comment by amd64fox** [comment]
Your information about new icons has been confirmed in the new version `1.1.82.758.g8b7b66c7`
Now starting with this version, new icons are enabled by default for all regions.

Also, the Spotify developers in this version themselves fixed the speaker icon to green.
