### ISSUE TITLE
Missing translation for Hindi

### ISSUE THREAD

**Issue by tdivyajyotis** [SpotX-Official/SpotX#290]
### ❌ Actual phrase(s)

**at line 35 of scripts/installer-lang/hi.ps1**
PodcatsSelect   = "Do you want to disable podcasts, episodes and audiobooks from the main page? [Y/N]" #

### ✔️ Expected phrase(s)

PodcatsSelect   = "क्या आप मुख्य पृष्ठ से पॉडकास्ट, एपिसोड और ऑडियोबुक को निष्क्रिय करना चाहते हैं? [Y/N]"

### ℹ Why is the current translation wrong

The translation was missing, I think the translation framework was updated and thus this field was not added back.

**Comment by amd64fox** [comment]
Thanks
