### ISSUE TITLE
Using Enhanced Disables Playback

### ISSUE THREAD

**Issue by CHjMP** [SpotX-Official/SpotX#291]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Canada

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.3.1115.gd61a8f5c
- Windows: Windows 10 22H2 19045.2486
- PowerShell: 5.1.19041.2364
```

### 📝 Description

1. Go in to playlist of choice
2. Enable Enhanced
3. Spotify disables playback of that playlist until Enhanced is disabled
...

### 📸 Screenshots

![Spotify_Xe2miSNqVJ](https://user-images.githubusercontent.com/31327707/214488067-0ccbb0b0-a487-4919-8ec2-6c0d25c2bcb0.gif)

**Comment by amd64fox** [comment]
The old problem with improving your own playlists and favorite songs mostly works fine for most users, but sometimes there are crashes. It was not possible to find out why. You can try [logging out of all devices](https://www.youtube.com/watch?v=KuyClCzgW34) and performing a [clean installation](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation) as described in the FAQ. I had the same problem for about a month and it went away on its own. I did nothing. Maybe these are temporary problems on the server.
