### ISSUE TITLE
spotify isn't being installed.

### ISSUE THREAD

**Issue by Xisoun** [SpotX-Official/SpotX#292]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: isn't being installed.
- Windows: 11 Pro.
- PowerShell: 5.1.22621.963
```

### 📝 Description

1. I tried using normal setup, doesn't work.
2. I tired using spot-x auto.bat and powershell too doesn't work.
3. I tried installing using normal spotify installer, and that doesn't install either.

> attached screenshot of the issue.

### 📸 Screenshots

![Screenshot (3)](https://user-images.githubusercontent.com/87743318/214836832-886ac6b4-0b4b-44b8-b213-b2967a9d753f.png)

**Comment by Bastigonzales** [comment]
Try running this [tool](https://github.com/amd64fox/Uninstall-Spotify) even if you don't have an existing spotify installed, then run Spot X again.

**Comment by Xisoun** [comment]
> Try running this [tool](https://github.com/amd64fox/Uninstall-Spotify) even if you don't have an existing spotify installed, then run Spot X again.

same error bruv.

**Comment by amd64fox** [comment]
maybe there are characters in your username that the script could not process, try changing your username or just manually download the spotify client and run the spotx installation again

Also possible that your AV is interfering with the installation process, try turning it off while installing SpotX
