### ISSUE TITLE
Authentication token expired 

### ISSUE THREAD

**Issue by VanshMotiramani** [SpotX-Official/SpotX#293]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: latest 
- Windows: 11 pro
- PowerShell: installation didn't have problem
```

### 📝 Description

1. The installation was smooth and fine but on login it is coming Spotify api token is expired 
2.
3.
...

### 📸 Screenshots

![IMG_20230127_010619](https://user-images.githubusercontent.com/116624213/214933052-71d16b5c-d68b-4899-85f2-e39ce1e090b7.jpg)

**Comment by Enxvinity** [comment]
EDIT: SPOTIFY IS WORKING AGAIN (FOR ME)

I'm having the same issue.

Country: Canada
Plan: Free
Spicetify Installed: No

- Spotify: latest 
- Windows: 11 home
- PowerShell/autoinstall.bat: installation didn't have a problem

Spotify stopped working so I uninstalled and after this issue popped up.

![image](https://user-images.githubusercontent.com/75154608/214934231-0a3ff89f-a48e-4d6b-ac8c-47b462f127d3.png)

**Comment by amd64fox** [comment]
I think it's related to [this ](https://github.com/amd64fox/SpotX/issues/294#issuecomment-1405590635)
