### ISSUE TITLE
Spotify is down

### ISSUE THREAD

**Issue by ejestiva** [SpotX-Official/SpotX#294]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Philippines

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 
- PowerShell:
```

### 📝 Description

1. 
2.
3.
...

### 📸 Screenshots

![Spotify Free 27_01_2023 3_56_14 am](https://user-images.githubusercontent.com/57382512/214937696-022faffe-3a8e-4b3a-b8cf-e3dd8c8982ab.png)

**Comment by Doubtedly** [comment]
that happened to me too

**Comment by OrangeJuicelol** [comment]
Spotify is down right now as of 12:08 PST, 26 January 2023. According to downdetector.com, this is a widespread error that is affecting everyone in the world so I'm pretty sure it's not a SpotX-related issue.

**Comment by amd64fox** [comment]
![Снимок экрана 2023-01-27 004523](https://user-images.githubusercontent.com/62529699/214957273-948a0ef2-e8c5-4190-9cef-f8f2ea279621.jpg)
