### ISSUE TITLE
error while installing spotx

### ISSUE THREAD

**Issue by Porygon-2** [SpotX-Official/SpotX#295]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.3.1115.gd61a8f5c
- Windows: 11
- PowerShell: 5.1.22621.963
```

### 📝 Description

Hi i was using spotx previously and had no issues with it until a few hours ago spotify stopped working so i uninstalled that version of spotify and did a clean installation. I then tried running Install_New_theme.bat and it showed an error. I tried running the other types but they all showed the same error. im attaching the screenshot of the error. please help me resolve this issue

thanks

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/123493117/214965797-79e57bbc-737b-403a-9d91-563f75ae79c2.png)

**Comment by amd64fox** [comment]
Duplicate https://github.com/SpotX-CLI/SpotX-Win/issues/233
