### ISSUE TITLE
Installation won't work

### ISSUE THREAD

**Issue by 5cGOfficial** [SpotX-Official/SpotX#296]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Latest version 
- Windows: 11 Home
- PowerShell: 5.1.22621.963
```

### 📝 Description

Whenever I run the installer, a blank command prompt window opens up. Nothing happens. No installation starts, no text. It's just a blank cmd window. 

### 📸 Screenshots

![Screenshot 2023-01-27 130059](https://user-images.githubusercontent.com/123721925/215032202-fac69896-ac62-49bb-bc84-a802b60e3433.png)

**Comment by 5cGOfficial** [comment]
Alright an update on this.... I realized I have to wait for it to do something. However, whenever I run installation I get an error. 
![HUH](https://user-images.githubusercontent.com/123721925/215034108-55084006-1856-4f41-8ef0-51dd7d477a0b.png)

**Comment by sovietscout** [comment]
Duplicate of #233

**Comment by amd64fox** [comment]
Restart your PC, then install directly via powershell:
