### ISSUE TITLE
Cant install spotx...

### ISSUE THREAD

**Issue by squishy2609** [SpotX-Official/SpotX#299]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows
1.2.3.1115.gd61a8f5c
- Windows: windows 11 22H2 
- PowerShell: 5.1.22616.1
```

### 📝 Description

1. tried installing spotx and running the bat file
2. windows powershell opened up and stayed blank for a few mins
3.then it showed me this error message

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/85492076/215162200-515a9361-1b3d-4bda-91a2-f2f7443a1b0b.png)

**Comment by Shaun0307** [comment]
I am having the same issue how to fix it?

**Comment by gauravsoni02** [comment]
am having the same issue , can u get the solution asap
