### ISSUE TITLE
Errors when I update my spotify (fullscreen button is gone and ads are back)

### ISSUE THREAD

**Issue by arlooonie** [SpotX-Official/SpotX#30]
## ℹ Computer information

- Spotify version: 1.1.81.604
- Windows version: 10.0.19044 Build 19044
- PowerShell version: 5.1.19041.1320

## 📝 Description of the problem

Idk why this happens when I update my spotify, but the fullscreen button is gone and ads reappear again

## 📷 Screenshots

<details>
<summary><small>Screenshot</small></summary><p>

![test_screen]![image](https://user-images.githubusercontent.com/100902107/159283917-32f1c929-4275-4428-a5cb-2567af36adff.png)

</small></summary><p>

</details>

**Comment by amd64fox** [comment]
Completely remove Spotify and re-run install.bat
