### ISSUE TITLE
Spotify crashes

### ISSUE THREAD

**Issue by Musey756** [SpotX-Official/SpotX#300]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows
1.2.3.1115.gd61a8f5c
- Windows: Edition	Windows 11 Pro
Version	22H2
Installed on	‎11/‎29/‎2022
OS build	22621.1105
Experience	Windows Feature Experience Pack 1000.22638.1000.0

- PowerShell: 5.1.22621.963
```

### 📝 Description

1. The spotx version I used keeps crashing after 5 minutes, I need a fix for this. Someone, please let me know how to fix it. 
2.
3.
...

**Comment by amd64fox** [comment]
apparently you have updated the client to `1.2.4`, not so long ago I fixed the errors for this version, try to install spotx again
