### ISSUE TITLE
 fullscreen images to greatly improve your Spotify experience.

### ISSUE THREAD

**Issue by saishankar404** [SpotX-Official/SpotX#303]
### Description of the new feature / enhancement

- 1  image set for a playlist/profile it will be the default same as the cover image.

I would like you to see this https://github.com/harbassan/spicetify-galaxy repo, for implementing this feature! It will look great :)

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/73755149/215711840-fcf47324-1231-48df-ab8f-3fc3bbebc941.png)

![image](https://user-images.githubusercontent.com/73755149/215711874-b6ca49c5-c022-44d6-8648-411dd0ee1d4c.png)

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
Use SpotX with Spicetify

**Comment by whitedevil-glitch** [comment]
> Use SpotX with Spicetify


I guess spicetify will patch some things and reinstall it! and that can break spotX I guess?
