### ISSUE TITLE
Make it so that right sidebar option for artists name takes it straight into artists info

### ISSUE THREAD

**Issue by ben401rs** [SpotX-Official/SpotX#305]
### Description of the new feature / enhancement

Its an old behaviour before the new theme, where if you click the artists name on the right sidebar it just takes you straight to the artists info bar instead of the artists page, handy for some people though i'm not sure to others. I don't know who to suggest to this, probably previous Spotify native features that are replaced but maybe you could make a separate params for it, as in the other old params that got missing in the new theme, i have more to suggest for such params, but that is all i come up currently

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/99275631/216078770-9b8cce85-2761-4a1c-8cac-5644da674be9.png)

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
Your logic is more obvious than that of the Spotify developers, but there are a lot of similar moments in the client, so I see no reason to change it all, I simply don’t have all the time for this.

You can submit your idea on their [forum](https://community.spotify.com/t5/Desktop-Windows/bd-p/desktop_windows).

**Comment by amd64fox** [comment]
partially your request was implemented in 1.2.7 or even earlier, but I just noticed that if you click where it says verified artist, the appropriate window opens

**Comment by ben401rs** [comment]
very nice, yeah this is the feature, much nicer since it takes you straight into artists info where you just want to see how much monthly listeners and other stats or background info for the artists without reclicking the artists page, useful for quick info for random shuffled songs nobody heard about, thanks for letting me know
