### ISSUE TITLE
Enable spotify listen along on discord

### ISSUE THREAD

**Issue by LeoDaGuy** [SpotX-Official/SpotX#306]
### Description of the new feature / enhancement

This is already a plugin in BetterDiscord (https://betterdiscord.app/plugin/SpotifyListenAlong) but it would be cool if it was added to spotx

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
What does this plugin have to do with SpotX, just use it along with **Better Discord**
