### ISSUE TITLE
Lyrics(cinema mode) and control bar have space in between

### ISSUE THREAD

**Issue by Calamivathan** [SpotX-Official/SpotX#307]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

india

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.3.1115.gd61a8f5c
- Windows: Windows 11 Pro 22H2 22623.730
- PowerShell: 5.1.22621.436
```

### 📝 Description

1. Open any playlist or liked song and play one
2. expand the lyrics tab on right
3. click on open in cinema mode ( for Lyrics)
4. After that you will see a space between the control bar (play, pause, skip ,etc.) and the lyrics.
5. You can even click on that space to and it would play that song
( it would be better if was merged Thanks.)

### 📸 Screenshots

![Screenshot_14](https://user-images.githubusercontent.com/97376730/216514176-4a09c7b3-417e-41fb-8539-344db41f677b.png)
![Screenshot_15](https://user-images.githubusercontent.com/97376730/216514179-c103460a-781c-42d7-b82b-4f64566292aa.png)

**Comment by amd64fox** [comment]
https://github.com/amd64fox/SpotX/issues/286

**Comment by Calamivathan** [comment]
Still not fixed🤦‍♂️
