### ISSUE TITLE
Fullscreen Album Cover

### ISSUE THREAD

**Issue by GreenRabbits** [SpotX-Official/SpotX#309]
### Description of the new feature / enhancement

A few years ago, Spotify had a fullscreen mode that looked like this : https://imgur.com/dvreOAX.
Then, they changed it to the current fullscreen mode (as it is featured in SpotX), but some users regretted the old one.

It would be great to add a button on the album cover to make it appear in a fullscreen and minimalist mode or to remap the arrow button on album covers to that, insead of opening the right sidebar.

### 📸 Screenshots

![dvreOAX](https://user-images.githubusercontent.com/63850693/216801106-57f83725-1014-4292-849c-2b0832497dbd.jpeg)

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
Sorry, I'm not engaged in restoring or creating new Spotify features, mostly working with what is available at the moment, if you need the old full screen mode, find a mod on the network with a version lower than 1.1.59 or use Spicetify (legacy Spicetify)
