### ISSUE TITLE
Unable to connect to remote server

### ISSUE THREAD

**Issue by AstroCrashed** [SpotX-Official/SpotX#310]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.97.962.g24733a46
- Windows: Device name	Avinash-HP-Laptop
Processor	Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz   2.40 GHz
Installed RAM	8.00 GB (7.84 GB usable)
Device ID	9D1B9578-8F40-4D3A-A7F2-62C885EAC11B
Product ID	00327-35907-46413-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

- PowerShell: 7.2.9
```

### 📝 Description

1.Run the autoinstall.bat file
error occurred
![2023-02-05_17h40_51](https://user-images.githubusercontent.com/102970299/216817934-3767507d-c468-4a79-8495-8d893cf77183.png)

**Comment by amd64fox** [comment]
https://github.com/amd64fox/SpotX/issues/233
