### ISSUE TITLE
Doesn't work with junction/symbolic link

### ISSUE THREAD

**Issue by Myaukolka** [SpotX-Official/SpotX#312]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

N/A

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: any
- Windows: any
- PowerShell: any
```

### 📝 Description

1. Create a junction point for normal Spotify location in application data and local application data
2. Install Spotify normally - it will follow junction and be installed in junction target directory
3. Trying to apply SpotX script fails with broken location message

**Comment by amd64fox** [comment]
- fill out the form as indicated
- in the description of the error, provide the terminal output log or a screenshot of the terminal
- formulate your text concisely so that other people can understand it
