### ISSUE TITLE
Invoke-WebRequest : 404: Not Found, different from "the remote name could not be resolved"

### ISSUE THREAD

**Issue by infernoblaze2ko1** [SpotX-Official/SpotX#314]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows
1.2.3.1115.gd61a8f5c
- Windows: Windows 10 Home 22H2 19045.2486
- PowerShell: 5.1.19041.2364
```

### 📝 Description

1. When I go to the scripts folder and run Install_Auto.bat it shows Invoke-WebRequest : 404: Not Found.
2. I know a very similar error cannot connect to the server or something similar arises due to network connection but this seems different.
3. I have tried changing networks, changing the DNS to CloudFlare, and have also tried using a VPN.
4. I already have Spotify installed but when my friend was trying to install it he got this error and to proove how it works on my pc I tried running the bat file again but it shows me the same error. 

### 📸 Screenshots

![Screenshot (202)](https://user-images.githubusercontent.com/50017056/218030164-e28a22d5-53a2-4263-86e2-ecd508c81bad.png)

**Comment by amd64fox** [comment]
Open your `Install_Auto.bat`
copy the code that will be inside and send it here

**Comment by infernoblaze2ko1** [comment]
I couldn't quite figure out what was the code so here's all that's on my screen displayed after opening it:

Invoke-WebRequest : 404: Not Found
At line:1 char:93
+ ... 2}; "& { $((Invoke-WebRequest -UseBasicParsing 'https://raw.githubuse ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
    
    after pressing a key it just closes the batch file.

**Comment by amd64fox** [comment]
you don’t understand, need to open the `Install_Auto.bat` file using any text editor and send the code that is inside

**Comment by amd64fox** [comment]
also to solve your problem, download the [bat file](https://raw.githack.com/amd64fox/SpotX/main/scripts/Install_Auto.bat) again, this one is already outdated

**Comment by infernoblaze2ko1** [comment]
Installing through that bat file worked, although if I could get that old version back would it be possible?

I have attached the code here.

@echo off

%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Command "&{[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12}; """"& { $((Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/SpotX-CLI/SpotX-Win/main/Install.ps1').Content)} -confirm_uninstall_ms_spoti -confirm_spoti_recomended_over -podcasts_off -cache_off -block_update_on -start_spoti """" | Invoke-Expression"

pause
exit /b

**Comment by amd64fox** [comment]
They have no version differences
not so long ago this repository changed its address, so your old bat file gave a 404 error.
Always up-to-date [installers](https://github.com/amd64fox/SpotX#choose-installation-type)
