### ISSUE TITLE
Playing albums and songs via albums doesn't work (same songs via playlists are fine)

### ISSUE THREAD

**Issue by Undertow6248** [SpotX-Official/SpotX#316]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United Kingdom

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.5.954.gf42f9f0a
- Windows: Windows 10 Pro (10.0.19045)
- PowerShell: 5.1.19041.2364
```

### 📝 Description

1. Fresh install of Spotify via SpotX
2. Click play on an album or song from an album: nothing happens and no song plays.
3. Click play on a playlist: songs play as usual, including any song on an album that doesn't play when attempted to play via playing the album or song on the album.
...

This has been happening for a while now, across different Spotify versions, and I have been 'getting around it' by just adding the albums I want to listen to at that moment to a playlist and then deleting the playlist afterwards lol. Strange thing is that it's inconsistent. Now and again I open Spotify and albums and songs played via albums work perfectly. I come back later, open up Spotify and it isn't working again.

Very weird!

**Comment by bachig26** [comment]
+1

**Comment by amd64fox** [comment]
I could not reproduce this error, it seems like a temporary problem on the Spotify servers.

@Spottyfriend 
what input parameters do you use to install spotx or did you use a ready installer ?

**Comment by Undertow6248** [comment]
I have experienced this bug using Spotify installed using SpotX with no custom settings, and SpotX with updates turned off. And across a number of months. Though it is inconsistent, it seems to be the case more than it isn't.

**Comment by amd64fox** [comment]
specify which ready installer you used

**Comment by Undertow6248** [comment]
I used to use an old one which didn't include custom settings (can't remember exactly which one it was sorry), but more recently I've been using "Usual installation (New theme)".

**Comment by amd64fox** [comment]
if you ran Usual installation, then you were offered 3 options for parameters, answer them in the same way as you did with that installation:
- "Do you want to disable podcasts, episodes and audiobooks from the main page? [Y/N]"
- "Want to block Spotify updates? [Y/N]"
- "Do you want to install automatic audio cache cleaning for Spotify? [Y/N]"

**Comment by nomis51** [comment]
Happened to me aswell not so long ago, with genuine Spotify and SpotX Spotify, and it looks like it was (or still) an issue with Spotify services, not "SpotX version". Unable to play songs on albums or artists, and even some artists pages had issue loading properly, while playlists were fine, but couple hours later it was fine (did nothing to my spotify installation, just waited).

**Comment by amd64fox** [comment]
@nomis51  hi, thanks for the feedback, what country is your account located in ?

**Comment by nomis51** [comment]
> @nomis51  hi, thanks for the feedback, what country is your account located in ?

Canada

**Comment by amd64fox** [comment]
Hi folks
I still haven't been able to catch this bug

any news about this issue? Maybe the problem has disappeared or vice versa, share fresh info

**Comment by Undertow6248** [comment]
> Happened to me aswell not so long ago, with genuine Spotify and SpotX Spotify, and it looks like it was (or still) an issue with Spotify services, not "SpotX version". Unable to play songs on albums or artists, and even some artists pages had issue loading properly, while playlists were fine, but couple hours later it was fine (did nothing to my spotify installation, just waited).

Doing some Googling this seems to be a recurrent problem for some people's genuine Spotify so I'm satisfied it's not to do with SpotX. Still happening for me irregularly.

**Comment by nomis51** [comment]
Same here, happened on genuine aswell, but since my last comment, no issue at all (genuine and spotx). I believe it was only Spotify services that had (have) issues randomly

**Comment by bachig26** [comment]
@Spottyfriend @nomis51 i don't about that, but for only SpotX patched is having issue.
i've have tried both genuine spotify and spotx everyday and everytime I have a chance since this issue opened, only spotx having issue for me.

I have since found this crack version (v1.1.85.895) on another site: https://crackshash.com/spotify-pc/; it should be in 43rd in the spotx official spotify exe file google forum list. this one works perfect for without any issue all day long.

I planned to installed every version between this one and the lastest version with spotx patch to see which works without any issue, haven't done much but I having same issue with 1.2.5.x's and 1.2.4.x's...will try the remaining within this week, and to see what happens.

I also tried the pre-patched package (Spotify.v1.2.5.1006.x86-SPOTX) from telegram channel, same issue for me in this too.

**Comment by Teraisu** [comment]
it has been happening to me as well. has there been a fix yet ?

**Comment by amd64fox** [comment]
It appears to be related to the native Spotify client as complaints about a similar issue have started coming in on their forums, if you're experiencing something like this post it [here](https://community.spotify.com/t5/Ongoing-Issues/Issues-with-playing-tunes-outside-of-Liked-Songs-or-playlists-on/idc-p/5515408).
