### ISSUE TITLE
New Theme

### ISSUE THREAD

**Issue by MCUxDaredevil** [SpotX-Official/SpotX#317]
### Description of the new feature / enhancement

Basically wanted to add a new theme for the lyrics that is based on a few of the existing themes. It would be great if you could add this theme. 

past lyrics - `#00656aa0`
current lyrics - `#01dfea`
next lyrics - `#575757`
hover - `#a97aff`
background of lyrics - `#121212`
Musixmatch- `#00656a`

<br>
PS: I don't know if this is possible, but is it possible to just have a specific theme file like a json in a particular folder that can modify the theme on the go?

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/59441946/219043122-5a9855d5-c049-4aee-98d3-1c56f4b35fe5.png)

The hovered line will be a shade of purple. I couldn't change it on the site.

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
Hi


> PS: I don't know if this is possible, but is it possible to just have a specific theme file like a json in a particular folder that can modify the theme on the go?


There is currently no option to quickly change the theme


> The hovered line will be a shade of purple. I couldn't change it on the site.

I didn’t look into the themes of the lyrics for a long time, there was an error, I fixed it


Come up with a title for your theme, it should be a single word.

**Comment by MCUxDaredevil** [comment]
`Turquoise` I guess?

**Comment by amd64fox** [comment]
added
