### ISSUE TITLE
Song Title When Hovering Over System Tray Icon

### ISSUE THREAD

**Issue by JCollins2048** [SpotX-Official/SpotX#319]
### Description of the new feature / enhancement

**Suggestion:** Add a mouse-over tooltip to the system tray icon that shows the current song and artist.

**Details**
This might be beyond the scope of the _Spot-X_ enhancement suite, but I'd _love_ to see a hover-tip with song info added to _Spotify_ when it's minimized on the Windows system tray.  Other media players have this functionality, such as _Winamp_ and _XMPlay_, but even the *base* version of _Spotify_ just sits there like a lump when you hover over it with the mouse cursor.  That's bugged me since I started using the desktop version.  It just doesn't make sense, as _Spotify_ has code that updates the taskbar entry to display the song title in the taskbar entry, already.  (Or just "Spotify", when it's idle).  I wouldn't think it would be much of a stretch to use the same or similar coding for the taskbar icon.

I know this seems like something I should suggest to Spotify, LLC rather than you guys, but I don't have any faith that they'd have even a passing interest in something like this.  "There's no money in it".

Thank you for your time.

### 📸 Screenshots

![Spotify_Song Title on Hover](https://user-images.githubusercontent.com/102710555/219855697-d23b645e-fcb0-444b-b918-085e56df831a.png)
_A demonstration of how "now playing" would look when hovering over the icon under Windows 10_

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
it's unlikely, unfortunately I have no idea how to work with the source code of an already compiled CEF client

**Comment by JCollins2048** [comment]
Fair 'nuff.  Thanks for letting me know!
