### ISSUE TITLE
Audio loops for 3-4 times before playing a song

### ISSUE THREAD

**Issue by twistedmacaroni** [SpotX-Official/SpotX#32]
## ℹ Computer information

- Spotify version: 1.1.82.758.g8b7b66c7 (this issue appeared in the previous version, before that everything was fine)
- Windows version: 11 Beta Channel (22000.588)
- PowerShell version: 5.1.22000.588

## 📝 Description of the problem

1. When I play a new song on spotify (patched), it loops around a time frame (usually in the beginning) of the song before playing the rest of the song.
2. This issue appeared in the previous build but it still exists and wasn't patched in the latest build released hours ago.
3. Please refer to the attached recording for further clarification.

## 📷 Screen Recording
https://drive.google.com/file/d/1iTiEOjUDCIq14RQunxO-fpOCtiLntM7o/view?usp=sharing

**Comment by amd64fox** [comment]
The problem exists, but this does not apply to the mod, leave your feedback [here](https://community.spotify.com/t5/Desktop-Windows/Starting-a-song-short-loop-in-the-beginning-windows-desktop/td-p/5356090) so that the Spotify developers can fix it faster.

**Comment by twistedmacaroni** [comment]
oh alright, upvoted the issue.

**Comment by amd64fox** [comment]
This has been fixed in version 1.83.954
[Upgrade.](https://cutt.ly/8EH6NuH)
