### ISSUE TITLE
Spotify own ads are not being blocked.

### ISSUE THREAD

**Issue by douzooo** [SpotX-Official/SpotX#320]
### Description of the new feature / enhancement

- 1 Remove Spotify own ads

### 📸 Screenshots

![grafik](https://user-images.githubusercontent.com/71595093/219869735-5c77e003-719b-4753-8572-dfd6909ec5df.png)

![grafik](https://user-images.githubusercontent.com/71595093/219869756-126f865b-023a-4f5d-8b06-a5a0cb807c55.png)

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
https://github.com/amd64fox/SpotX/issues/new?assignees=&labels=%E2%9D%8C+bug&template=bug_report.yml
