### ISSUE TITLE
Invoke-WebRequest : Unable to connect to the remote server

### ISSUE THREAD

**Issue by gauravsoni02** [SpotX-Official/SpotX#321]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [x] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

india

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: Windows 11 21H2 22621.1265
- PowerShell: 7.3.2
```

### 📝 Description

1.downloaded install_auto.bat
2ran that as administrator
3.
...

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/104710407/219917950-78aea68f-210d-402d-ba8e-04ab64b0ca11.png)

**Comment by amd64fox** [comment]
Follow the steps that you are asked to do during the issue creation phase. If you start reading before clicking on anything, your life will become much easier.
