### ISSUE TITLE
New design change to open LRY more easily

### ISSUE THREAD

**Issue by jantendog** [SpotX-Official/SpotX#323]
### Description of the new feature / enhancement

- 1 Love the new design 
- 2 LRY are to hard to reach in my opinion 
- 3 LRY could be displayed in the rectangle, for sill having control over most things.
- 4 I liked the mic icon for the LRY could be placed in the circle.

### 📸 Screenshots

![concept](https://user-images.githubusercontent.com/75538139/220092316-c7e82495-5771-44d1-b4ff-d77d52e0aafa.png)

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
Hi
You wanted to bring back the old lyrics? solved your question?

**Comment by jantendog** [comment]
I found the correct flag to set in the "Installing with parameters" for me this file does it.

[SpotX.txt](https://github.com/amd64fox/SpotX/files/10784193/SpotX.txt)

**Comment by amd64fox** [comment]
`-old_lyrics` right
