### ISSUE TITLE
SpotX is not working in this Version 1.0.60.492.gbb40dab8

### ISSUE THREAD

**Issue by dumbu3** [SpotX-Official/SpotX#324]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United Kingdom

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.0.60.492.gbb40dab8
- Windows: Windows 10 21H2 19044.2604
- PowerShell: 5.1.19041.2364
```

### 📝 Description

1.Still Have AD
2.Upgrade Button Still There
3.Ad Banner is half bugged

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/103606830/220100766-b28b85e5-fb7f-406b-a24d-64e04e04b106.png)
![image](https://user-images.githubusercontent.com/103606830/220105394-1e48a2b7-d08d-4573-92ec-94a99b392abf.png)

**Comment by amd64fox** [comment]
very old versions are not supported
use above 1.1.60
