### ISSUE TITLE
Unresponsiveness

### ISSUE THREAD

**Issue by ghost** [SpotX-Official/SpotX#325]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [x] I have checked older issues, open and closed
- [x] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 
- PowerShell:
```

### 📝 Description

1. Open SpotX
2. Play music >30 minutes
...

**Comment by amd64fox** [comment]
The form is not filled out, I also suspect that the FAQ was not read, but simply a checkmark was ticked.
You do not look like a person who wants to solve his problem.
