### ISSUE TITLE
Sponsored block is not hidden in newer spotify versions

### ISSUE THREAD

**Issue by milindgoel15** [SpotX-Official/SpotX#326]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
Spotify for Windows
1.2.5.1006.g22820f93
- Windows: Windows 11 22621.1265
- PowerShell: Windows terminal
```

### 📝 Description

The sponsored block on the home page is not totally hidden. the ads are blocked but the whole block is still there.
The issue is present on both the new theme and old theme installation.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/45682747/220842212-71bfb447-e7b2-4018-9cf0-60cbef2d8149.png)

**Comment by amd64fox** [comment]
- specify your version of powershell as described in the template
- take a full screenshot of the spotify client, and that piece is not clear what you have

**Comment by milindgoel15** [comment]
Spotify client full ss:
![image](https://user-images.githubusercontent.com/45682747/220851829-48d3b612-f3f1-41ba-b9dc-050bc3d8d053.png)

Windows terminal: 1.16.10262.0
![image](https://user-images.githubusercontent.com/45682747/220852155-386ef021-1c26-4c37-aaa5-b8d9b20cabab.png)

**Comment by amd64fox** [comment]
Thanks

And inside the banner is always empty?

**Comment by milindgoel15** [comment]
Do you mean the sponsor block area? I can click on that portion as if there's some ad and the whole UI refreshes instead.

**Comment by amd64fox** [comment]
> Do you mean the sponsor block area?

yeah

**Comment by amd64fox** [comment]
just checked in different conditions, this banner is blocked for me, perform a [clean installation](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation) exactly as described in the FAQ.

**Comment by milindgoel15** [comment]
uh, it still appears. I did the same thing (although I login in before applying the patch). Will logging in after/before applying patch change anything?

**Comment by amd64fox** [comment]
just do what it says in the faq, it doesn't say to install the client yourself, but for some reason you do it

**Comment by amd64fox** [comment]
it looks like we found the reason for the appearance of this banner, try updating Spotx now, just do a clean install, as old experimental features may remain in obsolete files in which case the banner may not disappear

**Comment by milindgoel15** [comment]
Did a clean install and it's fine now.
