### ISSUE TITLE
Invoke-WebRequest : Unable to connect to remote server

### ISSUE THREAD

**Issue by r4z0r31** [SpotX-Official/SpotX#327]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.5.1006.g22820f93
- Windows: Windows 10 22H2 19045.2604
- PowerShell: 5.1.19041.2364
```

### 📝 Description

The bat file doesn't work

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/81320185/221345687-fc75fe86-6bc9-45c9-89fc-8b29061efefa.png)

**Comment by amd64fox** [comment]
try [this method](https://github.com/amd64fox/SpotX/issues/233#issuecomment-1436782720) and let me know if it worked for you or not

**Comment by r4z0r31** [comment]
Nope shows the same error
Tried both the bat files

**Comment by amd64fox** [comment]
then use [this](https://github.com/amd64fox/SpotX/issues/233#issuecomment-1332881977)

**Comment by r4z0r31** [comment]
It works now thank you
