### ISSUE TITLE
'Spotify cant play this right now'

### ISSUE THREAD

**Issue by jxcobzz** [SpotX-Official/SpotX#328]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United Kingdom

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify:1.2.6.861.g9440c6cf
- Windows: Windows 10 Pro 21H2
- PowerShell: 5.1.19041.2364
```

### 📝 Description

1. Try to play a song
2. get error message 'Spotify cant play this right now '
3.
...

### 📸 Screenshots

was working fine yesterday, this morning it doesn't work at all

**Comment by amd64fox** [comment]
https://community.spotify.com/t5/FAQs/How-do-I-fix-the-quot-Can-t-play-the-current-track-quot-error/ta-p/1279790/redirect_from_archived_page/true#M86679

next time learn how to use google yourself

**Comment by Volderex** [comment]
> https://community.spotify.com/t5/FAQs/How-do-I-fix-the-quot-Can-t-play-the-current-track-quot-error/ta-p/1279790/redirect_from_archived_page/true#M86679
> 
> next time learn how to use google yourself

how would you get rid of this message if you DO have spicetify installed?

**Comment by ecr13** [comment]
what a useless retard...
