### ISSUE TITLE
Blocking of spotify in the country

### ISSUE THREAD

**Issue by BazZziliuS** [SpotX-Official/SpotX#329]
### Description of the new feature / enhancement

Sorry, but I didn't find the right section

Can your app bypass the country lock and if it can't, will such a feature be added?

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
Unfortunately, at the moment, Spotx is not able to bypass country restrictions. If I find a simple way to bypass it, I will definitely add it. Alternatively, you can use the old method of registering in another country and periodically using a VPN.
