### ISSUE TITLE
Friend Activity not working

### ISSUE THREAD

**Issue by JasonShearer** [SpotX-Official/SpotX#33]
## ℹ Computer information

- Spotify version: 1.1.82.758.g8b7b66c
- Windows version: Windows 10 21H2 19044.1620
- PowerShell version: 5.1.19041.1320

## 📝 Description of the problem

Friend Activity is no longer working despite friends and I sharing our listening activity. Was this feature disabled?

**Comment by JasonShearer** [comment]
Hmm. It started working again for no apparent reason. Perhaps it was something on Spotify's end. 🤷‍♂️

**Comment by amd64fox** [comment]
If it appears again, then try testing this bug on the original Spotify client.
