### ISSUE TITLE
SpotX can't open any playlist

### ISSUE THREAD

**Issue by Kesantielu** [SpotX-Official/SpotX#330]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Kazakhstan

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.6.863.ge7902f05
- Windows: Windows 11 22H2 22623.1325
- PowerShell: 7.3.2 (Core)
```

### 📝 Description

1. Open SpotX client
2. Try open some playlist
3. Fail

### 📸 Screenshots

![snap12874](https://user-images.githubusercontent.com/7416833/221523589-a05392f2-b50b-4dd8-aac3-9492dfcf7543.png)

**Comment by amd64fox** [comment]
SpotX is not a client, it's just a patch for the Spotify desktop client, it doesn't affect the loading of playlists or other pages. 
You should read the FAQ before creating an issue.
