### ISSUE TITLE
Volume level

### ISSUE THREAD

**Issue by Operaattor1** [SpotX-Official/SpotX#331]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Finland

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.6.861.g9440c6cf
- Windows:Windows 10 22H2 19045.2673
- PowerShell: 5.1.19041.2673
```

### 📝 Description

Every time I open Spotify again, the voulme level is set to max instead of the level it was last time. I assume it is some kind of bug that came when I installed the SpotX. Any way to fix this?
...

**Comment by amd64fox** [comment]
What does a clean install without Spicetify do?

**Comment by Operaattor1** [comment]
I uninstalled spotify and ran the installation program again. Now it seems to be working.
