### ISSUE TITLE
"https://xpui.app.spotify.com/index.html" being redirected to this link when clicking any playlist

### ISSUE THREAD

**Issue by Matthewkyos** [SpotX-Official/SpotX#332]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.6.863.ge7902f05
- Windows: Windows 11 Home 22H2 22621.1265
- PowerShell: 5.1.22621.963
```

### 📝 Description

1. Left side bar using the "Install_New_theme" of Spotify causes the issues. but when i use the old theme the issue does not occur. 

3.  what's suppose to happen is the playlist just opens into the playlist screen of the specific one but instead it redirects me to https://xpui.app.spotify.com/index.html

### 📸 Screenshots

![image_2023-02-27_124925756](https://user-images.githubusercontent.com/84089845/221643222-413c9e09-aa2c-4a23-87f5-bd48615dfaa6.png)

**Comment by Matthewkyos** [comment]
issue doesn't occur when Spotify side bar is in expanded view

**Comment by amd64fox** [comment]
yes, the same error, it reproduces if I shrink the left sidebar and want to open a playlist in a folder

**Comment by Matthewkyos** [comment]
Yes it has a very simple work around just by expanding once than closing again but when i reopen Spotify it's in the non expanded view so when i click the playlist it does the bug again until i reclick to expand the view

**Comment by amd64fox** [comment]
it looks like this is a bug only for 1.2.6, I checked 1.2.5 it works fine there, so if this error annoys you, you can rollback

by the way Spicetify doesn't work with the new theme, I don't know why you use them together

**Comment by Matthewkyos** [comment]
It does work with me im running the new theme with spicetify with the node black theme and it works fine

**Comment by BoKKeR** [comment]
This is a problem in the official client also

**Comment by Exhigh** [comment]
` .yOKoknIYYzAE90pe7_SE.Yn2Ei5QZn19gria6LjZj { pointer-events: none; }`
adding the above line to xpui.css should fix the issue.

**Comment by amd64fox** [comment]
@Exhigh 
Thanks It works
there is not always time for native client bugs
