### ISSUE TITLE
[question] Removed the "block cookies" option?

### ISSUE THREAD

**Issue by Shituation** [SpotX-Official/SpotX#333]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

no need

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

no

### ℹ Computer information

```markdown
- Spotify: 1
- Windows: 1
- PowerShell: 1
```

### 📝 Description

Just a question, did you remove the "reject cookies" option, or was it removed by spotify?

### 📸 Screenshots

![1](https://user-images.githubusercontent.com/43975882/222311846-816df7ba-e8cd-4d0a-933b-c62063fe765a.jpg)

**Comment by amd64fox** [comment]
the Spotify developers have removed

it for the future, there is no need to create a issue without filling in a template, such issues will be closed without an answer in the future, if you just have a question, then ask it in the [discussions](https://github.com/amd64fox/SpotX/discussions)

**Comment by Shituation** [comment]
ok thanks i guess i will have to download an older  version since this was clearly a move from them to force the use of the cookies to get "richer" private data to sell.

For others seeing this and [worried](https://www.wired.com/story/spotify-tracking-how-to-stop-it/), older versions are here: https://spotify.en.uptodown.com/windows/versions

Last version that had the toggle cookies option I found (with a valid offline installer): 1.2.5.1006

![1](https://user-images.githubusercontent.com/43975882/222429228-8ea76330-ed99-436b-8f98-f186bb863c82.png)

..until they completely disable older versions.
