### ISSUE TITLE
Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a send. At line:1 char:93

### ISSUE THREAD

**Issue by imlinuxuser** [SpotX-Official/SpotX#334]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

india

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 
- PowerShell:
```

### 📝 Description

1.
2.
3.
...

### 📸 Screenshots

![Screenshot 2023-03-02 171427](https://user-images.githubusercontent.com/100107107/222419680-b18f6876-82ee-44b2-b835-09eb4c921cc1.png)

**Comment by imlinuxuser** [comment]
Extremely sorry but what is the solution for the above displayed issue

**Comment by amd64fox** [comment]
the [answer](https://github.com/amd64fox/SpotX/issues/233#issuecomment-1332881977) you had to find
