### ISSUE TITLE
Spotify blends do not open

### ISSUE THREAD

**Issue by DairyProducts** [SpotX-Official/SpotX#336]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.6.863.ge7902f05
- Windows: Windows 11 22H2 22621.1265
- PowerShell: 5.1.22621.963
```

### 📝 Description

1. Attempt to open an existing Spotify blend playlist created with other users by clicking on it on the sidebar
Result: the playlist attempts to load for a while with the three dot loading animation before it times out with the "Couldn't find that Playlist" error

Right-clicking the playlist in the sidebar does not display the dropdown menu as normal.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/66636627/222658468-3ea41bff-bf36-4ace-b6c0-6b2927379f58.png)

**Comment by amd64fox** [comment]
check further along the steps described in the 1st paragraph of the [FAQ](https://telegra.ph/SpotX-FAQ-09-19#I-have-a-bug-/-strange-client-behavior,-what-can-I-do-?), you do not need to create a issue if you have not done so

**Comment by DairyProducts** [comment]
> check further along the steps described in the 1st paragraph of the [FAQ](https://telegra.ph/SpotX-FAQ-09-19#I-have-a-bug-/-strange-client-behavior,-what-can-I-do-?), you do not need to create a issue if you have not done so

The original client does not have the same problem. The installation I'm using is a fully fresh installation with an unmodified host file. There is no mention in the first part of the FAQ regarding playlist or blend behavior.

**Comment by amd64fox** [comment]
Share a link to a blend playlist you can't get into
