### ISSUE TITLE
Add SpotX to the Windows Package Manager (aka winget)

### ISSUE THREAD

**Issue by uffemcev** [SpotX-Official/SpotX#339]
### Description of the new feature / enhancement

The winget command line tool enables users to discover, install, upgrade, remove and configure applications on Windows 10 and Windows 11 computers. This tool is the client interface to the Windows Package Manager service. Windows Package Manager winget command-line tool is available on Windows 11 and modern versions of Windows 10 as a part of the App Installer.

More about winget:
- https://github.com/microsoft/winget-cli
- https://learn.microsoft.com/en-us/windows/package-manager/winget

Winget advantages:
- Winget is already built into windows 10 and 11
- Downloading and installing applications via winget can be done in silent mode
- Winget can use different repositories (ms store, winget and so on)
- The winget repository already includes several different spotify clients, including the official one
- Winget is managed through the powershell and cmd interfaces with a quite simple set of commands

I request you to add SpotX to the Windows Package Manager so winget users can use it.

Sorry for bad english.

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
If someone wants to implement this, I don't mind, temporarily open ...

**Comment by carlosvsilva** [comment]
Winget updated spotify installed with SpotX and now ads and restrictions are back

**Comment by amd64fox** [comment]
![Снимок экрана 2023-03-29 083223](https://user-images.githubusercontent.com/62529699/228436308-8566afaf-2a34-4368-b90a-90c948eb0406.png)

As far as I understood, they need a compiled installer and do not support scripts.
