### ISSUE TITLE
Random play, "playlist radio" and no songs recommendations after playlist ends

### ISSUE THREAD

**Issue by Autistic-Unicorn** [SpotX-Official/SpotX#342]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Germany

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.6.863.ge7902f05
- Windows: Win 10 pro 22h2
- PowerShell: 5.1.19041.2364
```

### 📝 Description

Random play in liked songs issue
1. Turn on random play on liked songs
2. Play thru around 5-6 songs (sometimes doesn't work at all)
3. It stops the music - it is not possible to fix it by hitting the play button and it looks like no next song got picked

The playlist radio issue
1. Turn on "playlist radio" function on any playlist
2. Play button doesn't work at all. 

No songs recommendations after playlist ends 
1. Go thru whole playlist
2. Music stops playing instead of spotify starting to play songs based on playlist

"playlist extension" seems to be breaking the liked songs playlist too.

Those issues seems to be related to each other that's why im reporting them as one bug report.
I just updated the spotify from old version (older GUI) - did the clean install of the spotify so i think those function should work without the premium account.

Edit: Radio function when turned on from song instead of playlist works - which makes this even more weird.

Have a nice day

**Comment by amd64fox** [comment]
none of your problems can be reproduced for me, try to check the result on the same version but without spotx
or use a version downgrade

**Comment by wefalltomorrow** [comment]
I have the same issue, also occurs when trying to play songs directly from artists' pages.

**Comment by amd64fox** [comment]
I think this problem is related or similar to [this](https://github.com/amd64fox/SpotX/issues/316)
