### ISSUE TITLE
latest spotify version is unsupported when running the bat file

### ISSUE THREAD

**Issue by AnonymouseHucker29** [SpotX-Official/SpotX#343]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Philippines

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.7.1264.ge86bd157
- Windows: 11
- PowerShell: 5.1.22621.963
```

### 📝 Description

1. Install the latest Spotify version in the Google Sheets provided.
2. After installing, run the Install_Auto.bat
3. It will say unsupported Spotify version and it will install the last compatible Spotify version.

**Comment by amd64fox** [comment]
right, 1.2.7 is just out, SpotX will be updated soon

**Comment by redsactive** [comment]
same issue??
![Screenshot 2023-03-12 104101](https://user-images.githubusercontent.com/120154788/224525641-430935b2-1a80-4078-a17f-d966563d0d21.png)

**Comment by amd64fox** [comment]
update SpotX
