### ISSUE TITLE
I don't know what this problem is

### ISSUE THREAD

**Issue by WEEBWHOSELLSWEED** [SpotX-Official/SpotX#344]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows 1.2.7.1264.ge86bd157

- Windows: 
Edition	Windows 10
Version	22H2
OS build 19045.2604

- PowerShell: 5.1
```

### 📝 Description

I downloaded the install file and ran it, and that is it, it produced an error, then I ran it as administrator and still the same, then i copied the command to install and guess what still the same issue.
 

### 📸 Screenshots

![Screenshot (46)](https://user-images.githubusercontent.com/94781729/224510499-05264cd9-a2c7-4ff3-a820-72247187de29.png)

**Comment by amd64fox** [comment]
#233

**Comment by ShivrajAMulik** [comment]
ok but @amd64fox now i have got a real problem this time with 100% surety that its new not duplicate.
i Downloaded spicetify now and it shows theres no marketplace, i think its probably the new update but you have it too right? please tell me if theres any fix
![image](https://user-images.githubusercontent.com/94781729/224512530-791f3705-4fbd-4450-8c12-8ad8f89f3d0e.png)
As you can see theres all that black line messing up the place and the market place is there but hidden
