### ISSUE TITLE
Make Unavailable Songs Available?

### ISSUE THREAD

**Issue by JCollins2048** [SpotX-Official/SpotX#345]
### Description of the new feature / enhancement

- Make **all** songs on _Spotify_ available regardless of the user's region

**More Information**
This is probably beyond the scope of this project (much like my previous idea), but I was wondering… is there some easy way to **enable songs that are unavailable** without adding a bunch of VPN stuff into the code?  I'm just curious because I noticed that there's quite a few songs in my playlists that are greyed-out – likely due to being region-locked (okay, but *why*?) – but I guess they *weren't* when I originally added them.

As always, thank you for your continued work!  You folks are awesome!

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
a long time ago I tried to do this through js, but then it didn’t work out for me, most likely this is due to the server side, maybe someone will find a working way in the near future.

**Comment by JCollins2048** [comment]
Alright.  Thank you for reading.
