### ISSUE TITLE
installation error (cant find sol in faq)

### ISSUE THREAD

**Issue by redsactive** [SpotX-Official/SpotX#346]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

india

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: not installed
- Windows: 10
- PowerShell: idk but i got it on 11 03 2023
```

### 📝 Description

1. it seems that others had have had same issues but the link to the solution gives me a page not found

### 📸 Screenshots

![Screenshot 2023-03-12 104101](https://user-images.githubusercontent.com/120154788/224526625-d6e5f6d2-dcef-41c2-8417-f655f5bacae0.png)

**Comment by WEEBWHOSELLSWEED** [comment]
@redsactive 
use a vpn that solves the issue

**Comment by redsactive** [comment]
i have changed the dns is it not enough.....i dont want to use a vpn @WEEBWHOSELLSWEED
