### ISSUE TITLE
Invoke-WebRequest: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..

### ISSUE THREAD

**Issue by MCUxDaredevil** [SpotX-Official/SpotX#348]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.6.863.ge7902f05
- Windows: Windows 11, version 10.0.22621 Build 22621
- PowerShell: 7.3.3
```

### 📝 Description

I tried to do the Automatic Full Installation and got this error message
```
Invoke-WebRequest: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
```

I used this command to install SpotX
```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -confirm_uninstall_ms_spoti -confirm_spoti_recomended_over -podcasts_off -cache_off -block_update_on -start_spoti -new_theme -adsections_off -lyrics_stat spotify"
```

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/59441946/224549782-e53d2771-b881-4b67-a32f-97911a7f740a.png)

**Comment by amd64fox** [comment]
[#233](https://github.com/amd64fox/SpotX/issues/233#issuecomment-1332881977)

**Comment by MCUxDaredevil** [comment]
I tried using a VPN but still no change

**Comment by MCUxDaredevil** [comment]
Hi, sorry to bug you so much
But I was just curious why is it that I have to use VPN for this now?
It worked fine earlier

**Comment by MCUxDaredevil** [comment]
Also, sorry for going offtopic but is there a way to bring the lyrics interface back in the new theme in the playback bar in bottom right?
![image](https://user-images.githubusercontent.com/59441946/224553600-30e90424-fc36-45aa-9163-5efa36246110.png)

**Comment by amd64fox** [comment]
> Hi, sorry to bug you so much But I was just curious why is it that I have to use VPN for this now? It worked fine earlier

In some countries, such as India, ISPs have started blocking github resources, I don’t know why, you can look into this issue more carefully if you are interested, I’m just stating a fact.



> Also, sorry for going offtopic but is there a way to bring the lyrics interface back in the new theme in the playback bar in bottom right? 

Use the input parameter `-old_lyrics`

**Comment by MCUxDaredevil** [comment]
Ok thanks a lot
