### ISSUE TITLE
Option to have Private Session always active.

### ISSUE THREAD

**Issue by puffious** [SpotX-Official/SpotX#352]
### Description of the new feature / enhancement

Private Session is a feature by Spotify which stops updating the listening activity shown to friends, and doesn't use any listening activity to be used by algorithm to suggest similar songs and add in Wrapped.

By Default, Private session gets disabled after 6 hours of inactivity.

Spicetify already has [extension](https://github.com/api-haus/spicetify-antisocial) "Always Private Session". 
Same could be implemented in SpotX.

### 📸 Screenshots

The Toggle could be in Settings > Social, or Quick Menu.

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
just install this extension
