### ISSUE TITLE
Spotify changes UI

### ISSUE THREAD

**Issue by catb0x** [SpotX-Official/SpotX#356]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [ ] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Austria

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.7.1277.g2b3ce637
- Windows: 11 x64
- PowerShell: 7.3.3
```

### 📝 Description

1. Install Spicetify
2. Install SpotX (new/old theme doesn't matter.)
3. Open Spotify.
Don't really know how this happens.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/77354428/226107176-33128001-0136-4047-9fb3-794d7407950d.png)

**Comment by amd64fox** [comment]
read FAQ
