### ISSUE TITLE
Important information

### ISSUE THREAD

**Issue by amd64fox** [SpotX-Official/SpotX#358]
Dear SpotX users,

We would like to take a moment to express our gratitude for your support and trust in our project. We are excited to announce that SpotX for Windows has received over 6,000 stars on Github, and we are averaging over 10,000 daily installations. Additionally, the Telegram SpotX community has grown to over 1,000 users. Your ongoing support and feedback have been incredibly valuable to us.

We want to remind all of our users to only use official SpotX addresses.

**Github:**
▫️ [SpotX (Windows)](https://github.com/SpotX-Official/SpotX)
▫️ [SpotX-Bash (Linux/macOS)](https://github.com/SpotX-Official/SpotX-Bash)

 **Telegram:**
▫️ [SpotX Channel](https://t.me/spotify_windows_mod)
▫️ [SpotX Community](https://t.me/SpotxCommunity)
**FAQ:**
▫️ [Windows](https://te.legra.ph/SpotX-FAQ-09-19)
▫️ [Mac/Linux](https://github.com/jetfir3/SpotX-Bash/wiki/SpotX%E2%80%90Bash-FAQ)

At the moment we are not in other social networks or sites,
so be careful, download SpotX and only get support from official sources.

Almost forgot, if you're not aware yet, we recently started creating [ready-made installers](https://t.me/SpotxCommunity/1049) for SpotX specifically for people who are afraid of the command line. 

Best regards.

**Comment by spidychoipro** [comment]
If you see this coment then can you modify the FAQ page? because the korea now supports free tier account. So that info is misinfo
