### ISSUE TITLE
Auto delete cookies?

### ISSUE THREAD

**Issue by Shituation** [SpotX-Official/SpotX#359]
### Description of the new feature / enhancement

Since recent versions of spotify removed the option to not store cookies on the pc, I would like to ask if there could be an option to delete those cookies forcefully by using SpotX.

I was thinking something like "automatic clear cache" option but for cookies, so after closing spotify the cookies get deleted, or even better, just block them.

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
It would be great to know where they are stored.

Actually, it is unclear why they removed this switch in the first place. On their official website, it still states that cookies can be disabled in the desktop version of Spotify. 
![Снимок экрана 2023-03-25 041140](https://user-images.githubusercontent.com/62529699/227674870-512e969a-9fc1-4f15-a951-a9f018c50c64.png)


One could ask them a fair question [here](https://community.spotify.com/t5/Desktop-Windows/bd-p/desktop_windows), why is their [official website](https://www.spotify.com/us/legal/cookies-policy/#cookies-on-the-spotify-desktop-application) lying?

**Comment by Shituation** [comment]
I found a cue... don't know if the cookies are these or there is more to be removed, but seems to be here:
`
C:\Users\USERNAME\AppData\Local\Spotify\Browser\Network`

About the lie, its probably that they removed the option and didn't update the official page. Still a bad move from them (not the update, but the removal of the option).

**Comment by amd64fox** [comment]
> I found

Yes, I saw them there and not just there, there are other places. I had something a little different in mind. On their website, they divide cookie files into two main categories:

**1. Strictly Necessary Cookies**
These cookies are set by Spotify or a third party on our behalf, and are essential to enable you to use the basic features of our Services, such as technically delivering content, setting your privacy preferences, logging in, or filling in forms. Without these cookies, services you have asked for e.g. payment, cannot be provided.

**2. Optional Cookies**
Optional cookies may be "first party cookies" or "third party cookies" as explained in the table below. You can find out more about how to control "Always Active" cookies in Options for managing cookies and interest-based ads.

So, we need to find out where the second type of cookie files is located, any ideas on how to determine this?

**Comment by amd64fox** [comment]
So, I see that there are no ideas on how to find advertising cookies, unfortunately, I don't have time to search for them right now. All I can advise at the moment is to go to the settings of your account, then to [Privacy settings](https://www.spotify.com/us/account/privacy/) and turn off these two parameters highlighted in red:

![Снимок экрана 2023-03-29 072857](https://user-images.githubusercontent.com/62529699/228428802-4ba8898e-05ef-476a-8cca-f0a04c61ffad.png)


This will significantly reduce advertising cookies on all your devices.

If anyone else has any ideas on how to find and disable (delete) advertising cookies, please write about it in this issue.
