### ISSUE TITLE
I can't play songs on spotify after the installation process what should I do?

### ISSUE THREAD

**Issue by Adicahyon** [SpotX-Official/SpotX#360]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [X] I have checked older issues, open and closed
- [x] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Indonesia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.7.1277.g2b3ce637
- Windows: Windows 11 2H22 22621.1413
- PowerShell: 5.1.22621.963
```

### 📝 Description

I can't play songs on my Spotify after I did the installation!

### 📸 Screenshots

![Screenshot (27)](https://user-images.githubusercontent.com/128873326/227679697-d9118dfe-cefd-46b7-b305-fb1a3ff1cb13.png)

**Comment by amd64fox** [comment]
You can see that there is something wrong with your sound, so you should first sort out your device or windows.

**Comment by AlexAnimateMp4** [comment]
I have the same problem, but the sound is functional on other applications.

**Comment by Adicahyon** [comment]
I can't find anything wrong with my device, I've tried to install the original version of Spotify from the microsoft store but it still won't play the song!..
