### ISSUE TITLE
Cannot play artist's albums

### ISSUE THREAD

**Issue by 4GAP3** [SpotX-Official/SpotX#362]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.8.907.g36fbeacc
- Windows: Windows 10 IoT Enterprise LTSC
- PowerShell: 5.1.19041.2364
```

### 📝 Description

1. Pick an Artist album to play
2. Play it, doesn't work
3. Just goes blank
...

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/72903176/227737506-17e75733-cfba-43d3-a318-167e3b39a295.png)

**Comment by amd64fox** [comment]
Duplicate #316
