### ISSUE TITLE
Fix themes for Lyrics on fullscreen mode

### ISSUE THREAD

**Issue by amd64fox** [SpotX-Official/SpotX#363]
What about when playing on fullscreen? Since there's a feature that can either show the album art or the lyrics of the song. The theme works great but the fullscreen version still has colors based  on the album art (I assume).

### 📸 Screenshots
Lyrics with theme (royal):
![image](https://user-images.githubusercontent.com/82317262/227760656-2d22dae8-a2b6-4e39-988f-77136f648e1f.png)

Lyrics on fullscreen mode (still with the theme applied):
![image](https://user-images.githubusercontent.com/82317262/227760719-143ab3fa-2215-40bc-af3f-b7d9b3e6a0b8.png)

_Originally posted by @amagiriyuuko in https://github.com/amd64fox/SpotX/issues/191#issuecomment-1484014115_

***
If you like the idea, add a 👍 reaction to this post

**Comment by Havasiz** [comment]
Hey, may I ask how did you get the lyrics option when NOT in fullscreen? I can only access them on fullscreen.

**Comment by amagiriyuuka** [comment]
@Havasiz, I have the **new theme**  installed, and I just click the "show lyrics" under the "Now Playing" view. 
![image](https://user-images.githubusercontent.com/82317262/229881779-da31a7ea-0cc1-4d63-a14d-d19941ccc879.png)

However, I'm not entirely sure whether it's the same for those who use the **old theme.**

**Comment by Havasiz** [comment]
@amagiriyuuko Thank you very much, I didn't see the "show lyrics" option. Have a good day/night oh and sorry for the late reply I wasn't home.

**Comment by Paradox1610** [comment]
![image](https://user-images.githubusercontent.com/84443238/230730192-a119aa3d-d9f6-42e4-986e-55bad7c83152.png)
how can i get the lyrics in that bar like this? in my app im having to open the "now playing view" to get the lyrics page. How can i get it beside the devices, queue icon itself

**Comment by amagiriyuuka** [comment]
@Paradox1610 I'm unsure about how to get the lyrics icon next to the "devices" icon. I've been using SpotX/Spotify PC for quite a while now and ever since then it's always been like that. One way I do is put the song in fullscreen and click the mic icon in the bottom right to show the lyrics.
![image](https://user-images.githubusercontent.com/82317262/230730967-76969bd2-3955-4137-a5d3-2056aff72ca3.png)

**Comment by amd64fox** [comment]
@Paradox1610  to return the old lyrics for the new theme, use the input parameter `-old_lyrics`

**Comment by Paradox1610** [comment]
> @Paradox1610 to return the old lyrics for the new theme, use the input parameter `-old_lyrics`

Can you please guide me on how can I implement the `-old_lyrics` parameter?

**Comment by amd64fox** [comment]
> Can you please guide me on how can I implement the `-old_lyrics` parameter?

https://github.com/amd64fox/SpotX/discussions/60

**Comment by Paradox1610** [comment]
> #60

I did it. Thank You so much!!

**Comment by amd64fox** [comment]
https://github.com/amd64fox/SpotX/assets/62529699/27bc3c20-cc70-4172-a3bd-d691ade8dfc3

**Comment by amagiriyuuka** [comment]
> 2023-08-11.02-07-19-337.mp4

Thank you so much for adding this!
