### ISSUE TITLE
Spotify not running after installing the new theme from command prompt

### ISSUE THREAD

**Issue by pranavtamma** [SpotX-Official/SpotX#364]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [x] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 
- PowerShell:
```

### 📝 Description

1.
2.
3.
...

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/85175172/228421253-d2e087f7-eebe-49f5-877b-d9ff34b1113d.png)

**Comment by amd64fox** [comment]
the issue form is not filled out to the end

I also suspect that a clean install was not performed
