### ISSUE TITLE
Latest Update brokes new theme, SpotX can't update to new theme

### ISSUE THREAD

**Issue by ShaggyLorean** [SpotX-Official/SpotX#365]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Turkey

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.8.923.g4f94bf0d
- Windows: Windows 11 22H2 25324.1011
- PowerShell: 5.1.25324.1000
```

### 📝 Description

after Spotify 1.2.8.923.g4f94bf0d new theme stopped working, still on old Spotify theme with clean install + true patch - i tried both premium/free.

**Comment by amd64fox** [comment]
what exactly is broken in your new interface? (add screenshot)

**Comment by Akayashuu** [comment]
I tried to update my version with the install command and that doesn't work either. As he said, the last update seems to have broken the install also? (new theme)

**Comment by ShaggyLorean** [comment]
> what exactly is broken in your new interface? (add screenshot)

not broken, its not updating to new theme it stays with old theme

**Comment by amd64fox** [comment]
Did you receive any error messages during the installation of SpotX?

Which SpotX installer are you using? If it's a custom installer, please specify all the input parameters used.

It was also mentioned that you're using Spicetify, which currently doesn't fully support the new theme. So, it's better not to combine the new theme and Spicetify until they release an update for the new theme.

**Comment by NouaaTW** [comment]
Impossible de trouver un paramètre correspondant au nom « exp_standart ».
Au caractère Ligne:1539 : 104
+ ... _over -podcasts_on -cache_off -block_update_off -exp_standart -hide_c ...
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument : (:) [], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound

**Comment by ShaggyLorean** [comment]
> Did you receive any error messages during the installation of SpotX?
> 
> Which SpotX installer are you using? If it's a custom installer, please specify all the input parameters used.
> 
> It was also mentioned that you're using Spicetify, which currently doesn't fully support the new theme. So, it's better not to combine the new theme and Spicetify until they release an update for the new theme.

I didn't receive any errors, i use the latest Install_Prem.bat

**Comment by NouaaTW** [comment]
> Impossible de trouver un paramètre correspondant au nom « exp_standart ».
> Au caractère Ligne:1539 : 104
> + ... _over -podcasts_on -cache_off -block_update_off -exp_standart -hide_c ...
>     + CategoryInfo          : InvalidArgument : (:) [], ParameterBindingException
>     + FullyQualifiedErrorId : NamedParameterNotFound

**Comment by NouaaTW** [comment]
is this related? can't update either since this moring

**Comment by amd64fox** [comment]
> is this related? can't update either since this moring

incoming parameter `-exp_standart` no longer exists, update your bat file or command line


> I didn't receive any errors, i use the latest Install_Prem.bat

- perform a [clean install](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation) exactly as described in the FAQ
- install only SpotX (without Spicetify)
- take a screenshot of your Spotify after launching it for the first time

**Comment by 0xAnasEzz** [comment]
> > is this related? can't update either since this moring
> 
> incoming parameter `-exp_standart` no longer exists, update your bat file or command line
> 
> > I didn't receive any errors, i use the latest Install_Prem.bat
> 
>     * perform a [clean install](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation) exactly as described in the FAQ
> 
>     * install only SpotX (without Spicetify)
> 
>     * take a screenshot of your Spotify after launching it for the first time

Hi @amd64fox, thank you for your dedicated work on SpotX!

I just followed your exact steps performing a clean install:
![image](https://user-images.githubusercontent.com/26164108/229001807-25da52c1-13d2-43ff-b2c0-064e9c909f50.png)

The first sceen I got after installation was the normal login screen:
![image](https://user-images.githubusercontent.com/26164108/229001879-ec3302a8-b245-4191-af32-829982662829.png)

But after login the client freezes on a black screen forever:
![image](https://user-images.githubusercontent.com/26164108/229001945-4b09c171-0c35-436c-b932-6a290b83edb3.png)

I used your Automatic full installation PowerShell command:
```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -confirm_uninstall_ms_spoti -confirm_spoti_recomended_over -podcasts_off -cache_off -block_update_on -start_spoti -new_theme -adsections_off -lyrics_stat spotify"
```

System Info:
```
- OS: Windows 10 22H2 Build 19045.2728
- PowerShell: 7.3.2
- Spotify: 1.2.5.1006
- Spotify plan: Free
- Spicetify installed: No
- Account Country: Egypt
```

**Comment by ShaggyLorean** [comment]
> > is this related? can't update either since this moring
> 
> incoming parameter `-exp_standart` no longer exists, update your bat file or command line
> 
> > I didn't receive any errors, i use the latest Install_Prem.bat
> 
> * perform a [clean install](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation) exactly as described in the FAQ
> * install only SpotX (without Spicetify)
> * take a screenshot of your Spotify after launching it for the first time

Still same, old theme.
![image](https://user-images.githubusercontent.com/91439299/229094885-75296530-8891-46bf-b155-95cfb4219cb3.png)

**Comment by amd64fox** [comment]
Have you tried changing the experimental features yourself?

also to investigate your problem you can go open [devtools](https://github.com/amd64fox/Enable-devtools-Spotify), log in and show your remote config, for example:
![Анимация](https://user-images.githubusercontent.com/62529699/229218761-5c6f313f-f5c5-44f4-94ec-148f0e9faf86.gif)

**Comment by Solcosm** [comment]
> > is this related? can't update either since this moring
> 
> incoming parameter `-exp_standart` no longer exists, update your bat file or command line
> 
> > I didn't receive any errors, i use the latest Install_Prem.bat
> 
>     * perform a [clean install](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation) exactly as described in the FAQ
> 
>     * install only SpotX (without Spicetify)
> 
>     * take a screenshot of your Spotify after launching it for the first time

Removing '-exp_standart' helped fix my client while keeping the new theme (for better or worse). Thanks.

![image](https://user-images.githubusercontent.com/25302709/229299541-08f2eeae-6fd5-4c9d-9d69-ae84279473c9.png)
