### ISSUE TITLE
The client freezes on a black screen forever

### ISSUE THREAD

**Issue by amd64fox** [SpotX-Official/SpotX#367]
System Info:
```
- OS: Windows 10 22H2 Build 19045.2728
- PowerShell: 7.3.2
- Spotify: 1.2.5.1006
- Spotify plan: Free
- Spicetify installed: No
- Account Country: Egypt
```

Hi @amd64fox, thank you for your dedicated work on SpotX!

I just followed your exact steps performing a clean install:
![image](https://user-images.githubusercontent.com/26164108/229001807-25da52c1-13d2-43ff-b2c0-064e9c909f50.png)

The first sceen I got after installation was the normal login screen:
![image](https://user-images.githubusercontent.com/26164108/229001879-ec3302a8-b245-4191-af32-829982662829.png)

But after login the client freezes on a black screen forever:
![image](https://user-images.githubusercontent.com/26164108/229001945-4b09c171-0c35-436c-b932-6a290b83edb3.png)

I used your Automatic full installation PowerShell command:
```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -confirm_uninstall_ms_spoti -confirm_spoti_recomended_over -podcasts_off -cache_off -block_update_on -start_spoti -new_theme -adsections_off -lyrics_stat spotify"
```

_Originally posted by @6Anasovich9 in https://github.com/amd64fox/SpotX/issues/365#issuecomment-1491183651_

**Comment by amd64fox** [comment]
Hi @6Anasovich9
It's quite strange that you indicated that you have Windows 10, but SpotX somehow identified your system as Win7-8.1 since the recommended version 1.2.5 was installed for these operating systems.

Are you confirming that you have Windows 10?

also could you please enter this into your PowerShell terminal and provide the output?

```ps1
$os = Get-WmiObject -Class Win32_OperatingSystem
$osCaption = $os.Caption
$pattern = "\bWindows (7|8(\.1)?|10|11|12)\b"
$reg = [regex]::Matches($osCaption, $pattern)
$reg.value
```

**Comment by amd64fox** [comment]
So, I figured out the issue with the incorrect OS detection. An outdated cmdlet was being used, and I replaced it with a newer one.
but it seems that this doesn't solve the main issue with the black screen for now.

**Comment by 0xAnasEzz** [comment]
> So, I figured out the issue with the incorrect OS detection. An outdated cmdlet was being used, and I replaced it with a newer one.

Exactly, just figured out that `Get-WmiObject` is now deprecated in Powershell.
Many thanks for your prompt action! You're doing a really great job on this project. @amd64fox

**Comment by amd64fox** [comment]
Hmmm... it seems like the issue with the black screen is a problem with the native Spotify client. 

I'm having the same problem with it not launching properly, but if I wait for about a minute or so, it eventually starts up. I've checked both the native client and SpotX, and the behavior is the same.

Let me know your current situation

**Comment by amd64fox** [comment]
Additionally, to provide more comprehensive information about the issue, you can access the [developer console](https://github.com/amd64fox/Enable-devtools-Spotify) and take a screenshot when you encounter the black screen, for example:
![Снимок экрана 2023-03-31 072144](https://user-images.githubusercontent.com/62529699/229022326-d596228c-a5ad-4d14-aa6a-f1c28994b40d.png)

This will make the reason for your black screen a little clearer.

**Comment by 0xAnasEzz** [comment]
> Let me know your current situation

Currently Spotify client works perfectly without any black screens after your latest commit 8de62621a62f224d9e5e4853f05253b731e8770d.

Here's also a screenshot of the developer console after Spotify launched correctly, if it could be any help to you (I doubt):
![image](https://user-images.githubusercontent.com/26164108/229026863-20967d26-2b76-4769-9232-acf383ef73a5.png)

**Comment by amd64fox** [comment]
Okay, looks like everything is fine now.

**Comment by carleesfoont** [comment]
Nice threat
