### ISSUE TITLE
Issue in opening spotify after installing spotx

### ISSUE THREAD

**Issue by ayeeaaan** [SpotX-Official/SpotX#368]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.8.923.g4f94bf0d
- Windows: Edition	Windows 10 Pro
Version	21H2
Installed on	‎4/‎5/‎2022
OS build	19044.2728
Experience	Windows Feature Experience Pack 120.2212.4190.0

- PowerShell:
```

### 📝 Description

1.
2.
3.
...

### 📸 Screenshots

Spotify just shows a black screen after launching and then, I have to open and close it multiple times in which it start correctly for 1 time

**Comment by amd64fox** [comment]
to provide more comprehensive information about the issue, you can access the [developer console](https://github.com/amd64fox/Enable-devtools-Spotify) and take a screenshot when you encounter the black screen, for example:
![229022326-d596228c-a5ad-4d14-aa6a-f1c28994b40d 1](https://user-images.githubusercontent.com/62529699/229120291-5981756d-adf7-476c-9606-07bf500c0920.png)

**Comment by ayeeaaan** [comment]
I don't what happened to the install but after installing the dev tools, it is starting just fine every time. If, I'll have issues I'll let you know, don't close this issue yet , wait for 2-3 days.
