### ISSUE TITLE
Volume resets after application restart. Also settings reset after update. 

### ISSUE THREAD

**Issue by chunheit** [SpotX-Official/SpotX#369]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [ ] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Canada

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows
1.2.8.923.g4f94bf0d
- Windows: Edition	Windows 10 IoT Enterprise LTSC
Version	21H2
Installed on	‎12/‎20/‎2022
OS build	19044.2728
Experience	Windows Feature Experience Pack 120.2212.4190.0

- PowerShell: 5.1.19041.2673
```

### 📝 Description

Windows restart resets volume, also putting computer to sleep sometimes clears queue/ stops music

Installing spotx updates resets Spotify settings (multimedia preference, local files, auto startup etc. ) 

These are pretty minor issues but just wanted to bring it up. Thanks for your work guys/guy!

**Comment by amd64fox** [comment]
> Windows restart resets volume, also putting computer to sleep sometimes clears queue/ stops music

[clean install](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation)


> Installing spotx updates resets Spotify settings (multimedia preference, local files, auto startup etc. )

During the SpotX installation, if Spotify is detected, you will be prompted to update if your current version is outdated. The installer will offer to update on top of the existing installation or completely remove the client and install it again. If you want to keep your current settings, local downloads, etc., choose to update on top of the existing installation. Additionally, the automatic installer updates on top of the existing installation without warning.
