### ISSUE TITLE
Spotify Student (paid premium subscription) will still show "Upgrade" button

### ISSUE THREAD

**Issue by elibowlby** [SpotX-Official/SpotX#372]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.8.923.g4f94bf0d
- Windows: Windows 10 Enterprise 21H2 19044.2728
- PowerShell: 5.1.19041.2673
```

### 📝 Description

1. Login with a spotify student account
2. Go to the spotify app homepage
3. Notice the "Upgrade" button still exists

**Comment by amd64fox** [comment]
which Spotx installer did you use?

**Comment by elibowlby** [comment]
> which Spotx installer did you use?

I just used the full install automatic bat file to install Spotx

**Comment by amd64fox** [comment]
didn't read the FAQ
didn't read the readme
but created an issue ...🤦
