### ISSUE TITLE
I cannot use the Instal.bat

### ISSUE THREAD

**Issue by Younses** [SpotX-Official/SpotX#373]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

France

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.8.923.g4f94bf0d
- Windows: Windows 10 Professionnel 22H2 19045.2728
- PowerShell: 5.1.19041.2673
```

### 📝 Description

1. I run the install.bat and it doesn't work
2. I changed DNS
3. I used a VPN 
4. nothing changed

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/128409585/230498638-e556c251-ee73-43c1-a59a-09f82d837e0d.png)

**Comment by amd64fox** [comment]
Duplicate #314
