### ISSUE TITLE
Spotify not compatible

### ISSUE THREAD

**Issue by Cookiesgobrr** [SpotX-Official/SpotX#374]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United Arab Emirates

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.4.912.g949d5fd0
- Windows: Windows 11 21H2 Build 22000.1696
- PowerShell: 5.1.22000.1335
```

### 📝 Description

Got an email from Spotify saying:

We have noticed that you’re using an outdated version of the Spotify desktop app.

Starting from May 12, 2023, this version will no longer be supported, meaning that you won’t be able to login and use Spotify. This will affect the version you are using along with any other version of Spotify for desktop released before April 2021.

To continue listening and enjoy the latest features offered by Spotify, we recommend that you download the latest version of Spotify available at [spotify.com/download](http://www.spotify.com/download). Updating to the latest version also ensures that you have access to bug fixes and security updates, improving the stability and security of the application.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/90541179/231522669-38560f54-f32b-488a-af0f-334def05133d.png)

**Comment by jetfir3** [comment]
We may have to keep an eye on this and see how it plays out. Could be a mistake on Spotify's end. Or they are sending this out to everyone in waves to ensure everyone is running a v1.2.x build. 

This doesn't seem to be related to SpotX. There have been multiple reports from other Spotify users on Windows, macOS and Linux... with some users running the very latest desktop build. 

Example: https://community.spotify.com/t5/Desktop-Linux/quot-Your-Spotify-desktop-app-is-out-of-date-quot-when-I-have-1/m-p/5538183

*Edit/update*
After reading the email in the supplied screenshot better, I see it mentions "before April 2021". This would mean that Spotify 1.1.57.443.ga029a6c4 and higher should continue working after this May 12 2023 change. 
Spotify 1.1.56.595.g2d2da0de and lower would no longer be supported after this May 12 2023 change (if Spotify's email is true and accurate). 

1.1.57.443.ga029a6c4 build date - April 13 2021
1.1.56.595.g2d2da0de build date - March 26 2023

**Comment by amd64fox** [comment]
![Снимок экрана 2023-05-16 183015](https://github.com/amd64fox/SpotX/assets/62529699/aea45699-b618-4cc1-be16-e2b5f06968da)

Today officially disabled all desktop versions starting from 1.1.58.820 and below 🫡
