### ISSUE TITLE
Check version windows error

### ISSUE THREAD

**Issue by eao** [SpotX-Official/SpotX#376]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

USA

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.77.643g3c4c6fc6
- Windows: Windows 10 Pro 22H2 19045.2846
- PowerShell: 5.1.19041.2673
```

### 📝 Description

After the most recent Windows update my Spotify albums stopped working for some reason, which I know is an existing bug.  I tried a bunch of things but the only thing that worked was downgrading to 1.1.77.643 from latest.  But that is not the bug, it is the fact that this message pops up during install:

```
Get-CimInstance : Invalid class
At line:252 char:7
+ $os = Get-CimInstance -ClassName Win32_OperatingSystem
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (root\cimv2:Win32_OperatingSystem:String) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
```

I don't know what this implies, but it mentions "Microsoft.Management.Infrastructure" which seems like it might have to do with the WMI (Windows Management Instrumentation) issues mentioned in the Spotify issue thread for albums not working (https://community.spotify.com/t5/Ongoing-Issues/Issues-with-playing-tunes-outside-of-Liked-Songs-or-playlists-on/idi-p/5462485).

### 📸 Screenshots

![まい写真 - 2023-04-13 11 00 24 - CWINDOWSsystem32cmd exe](https://user-images.githubusercontent.com/34289076/231851606-8927be93-993b-4679-9015-e38bcec7e565.png)

**Comment by eao** [comment]
I have determined that this issue is likely directly related to the inability to play albums in Spotify, and is because of a Windows update breaking WMI, and not an issue with Spotify itself, per se.  Due to the same update, my ClickMonitorDDC hotkeys broke and I became unable to change monitor brightness programmatically.  Trying to work around this with AHK and WMI did not work at all, and there are multiple reports online of Windows update breaking WMI somehow.  No idea what the solution to all of this is.

I won't close this issue myself in case it is relevant for other people, but if you want to close it since it's not a problem with SpotX then go ahead.  Thank you for your time making this excellent program.

**Comment by amd64fox** [comment]
Run this code in powershell terminal and paste the answer here::

```ps1
$os = Get-CimInstance -ClassName "Win32_OperatingSystem"
$osCaption = $os.Caption
$pattern = "\bWindows (7|8(\.1)?|10|11|12)\b"
$reg = [regex]::Matches($osCaption, $pattern)
$reg.value
```

**Comment by eao** [comment]
Error thrown on the first line:
```
Get-CimInstance : Invalid class
At line:1 char:7
+ $os = Get-CimInstance -ClassName "Win32_OperatingSystem"
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (root\cimv2:Win32_OperatingSystem:String) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
```
![image](https://user-images.githubusercontent.com/34289076/232536383-3e57c41d-f916-4b97-a839-04804527fd25.png)

**Comment by amd64fox** [comment]
try this code now

```ps1
try {
    $os = Get-CimInstance -ClassName "Win32_OperatingSystem" -ErrorAction Stop
}
catch {
    $os = Get-WmiObject -Class "Win32_OperatingSystem"
}

$osCaption = $os.Caption
$pattern = "\bWindows (7|8(\.1)?|10|11|12)\b"
$reg = [regex]::Matches($osCaption, $pattern)
$reg.Value
```

**Comment by eao** [comment]
Exception caught:
```
Get-WmiObject : Invalid class "Win32_OperatingSystem"
At line:5 char:11
+     $os = Get-WmiObject -Class "Win32_OperatingSystem"
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand
```

![image](https://user-images.githubusercontent.com/34289076/232556902-2d1364e7-40ff-427c-b143-1b1258b90455.png)

**Comment by amd64fox** [comment]
if try this class
```ps1
Get-CimInstance -ClassName "CIM_OperatingSystem"
```

**Comment by eao** [comment]
Similar error
```
Get-CimInstance : Invalid class
At line:1 char:1
+ Get-CimInstance -ClassName "CIM_OperatingSystem"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (root\cimv2:CIM_OperatingSystem:String) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
```

**Comment by amd64fox** [comment]
Check if the WMI service is running. You can do this by running the following command:

```ps1
Get-Service -Name "Winmgmt"
```

If the service is not running, you can start it by running the following command:
```ps1
Start-Service -Name "Winmgmt"
```
If the service is already running, you can try restarting it by running the following command:

```ps1
Restart-Service -Name "Winmgmt"
```

**Comment by eao** [comment]
WMI is running.  Restarting it fails, even in administrator PowerShell, unless -force flag is used.  Even after restarting, the same sort of errors are thrown.

![image](https://user-images.githubusercontent.com/34289076/232567149-ca51ad93-7173-469d-8143-a110d34a256a.png)

**Comment by amd64fox** [comment]
here is a small code that uses 2 methods for getting wasps, if the first one does not work, then the 2nd one will be used

what gives out?

```ps1
$os = Get-CimInstance -ClassName "Win32_OperatingSystem" -ErrorAction SilentlyContinue
if ($os) {
    $osCaption = $os.Caption
} else {
    $osCaption = (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ProductName).ProductName
}
$pattern = "\bWindows (7|8(\.1)?|10|11|12)\b"
$reg = [regex]::Matches($osCaption, $pattern)
$reg.Value
```

but correctly in your OS there is clearly some kind of error with updates or with system services, I would recommend reinstalling the OS.

**Comment by eao** [comment]
This works, and outputs "Windows 10"

![image](https://user-images.githubusercontent.com/34289076/232583409-d9e0c0ab-ed74-4928-9464-ffab84fc81ad.png)

I think you are right, reinstalling Windows would probably work.

**Comment by amd64fox** [comment]
> This works, and outputs "Windows 10"

Thank you for your assistance, I will add the corrected code to the main script a little later.
