### ISSUE TITLE
Auto Update feature

### ISSUE THREAD

**Issue by vilewired** [SpotX-Official/SpotX#377]
### Description of the new feature / enhancement

Add a script that checks if there are any updates for SpotX. Then maybe apply the new patch automatically or notify the user to update manually.

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by ShounenArgha** [comment]
> ### Description of the new feature / enhancement
> 
> Add a script that checks if there are any updates for SpotX. Then maybe apply the new patch automatically or notify the user to update manually.
> ### 📸 Screenshots
> 
> _No response_
> ### ⠀
> 
> If you like the idea, add a 👍 reaction to this post

you can just do it yourself by making a ps1 script or using tasksch to iterate it every month or something.
pass some arguments too,ig.
But the idea is not bad.
only problem would be how the script would run or how would it handle spicetify cause (the spicetify users) first backup their stuff,then update spotx and then upgrade that

**Comment by vilewired** [comment]
This might sound like a somewhat crazy idea, but you could make an installer / auto-updater in a c-language. My Idea for that looks like this:
You have a file, maybe in your spotify folder, that contains just the current version number.
Then you could make a c-program run on start-up, there it could check the most recent version from the github (just checking a version file with the raw tag in the link like this https://raw.githubusercontent.com/amd64fox/SpotX/main/versionfile.txt) and compare it to the version file in the spotify folder. 
If they match it can just terminate its own process so you don't have it running all the time.
If not it could just spawn a powershell process with your auto-full-installer and overwrite the version in the versionfile with the current version on github since you are updating.

Also, since you had worries about the spicetify users, I think you could just check for a file that only spiectify users have, and if it exists, run the spicetify backup command and if not, then to just ignore that.

As I said, this might be a bit much for just a simple installer / auto-updater, but I also read through some other issues that had been opened here, and I saw a discussion about adding spotX to winget. I personally don't use winget ( I don't even use windows that often ) but by having an executable, you could add it to winget as a package aswell. 

If you think this is a good idea then I can try to make a c++ script to exactly do that (although I don't have that much experience in c++) and if things go well, then you can consider to add it to your repo if you want.

**Comment by amd64fox** [comment]
Hi there,

Can someone explain to me why SpotX needs to be automatically updated? Native Spotify releases useful features quite infrequently, while SpotX primarily focuses on ad blocking, which is why there are even fewer instances of something appearing or changing in it.

**Comment by soredake** [comment]
Cause not all people want to update things manually, even if they need to do once in a several months.

**Comment by amd64fox** [comment]
I'm generally not opposed to it as an optional feature for Spotx.
If someone has ideas on how to implement it in practice, you can fork or create a new repository so that we can discuss something specific.

@soredake 
If it is really important to you, then it's strange that you haven't done something [similar to it](https://github.com/amd64fox/SpotX/issues/377#issuecomment-1508501809) yet.

**Comment by ShounenArgha** [comment]
> I'm generally not opposed to it as an optional feature for Spotx. If someone has ideas on how to implement it in practice, you can fork or create a new repository so that we can discuss something specific.
> 
> @soredake If it is really important to you, then it's strange that you haven't done something [similar to it](https://github.com/amd64fox/SpotX/issues/377#issuecomment-1508501809) yet.

for personal needs,the script task way is good and functional.from my view,it is not needed to make a auto updater or if this auto update is very much needed for the further userbase,the dev can just add a auto task when installing ,easy ig

**Comment by vilewired** [comment]
Yeah, I was just confused when it broke one time all of the sudden, didn't realize there was a new update until I checked manually, that's kinda why I mentioned it. But from now on I have a tasksch running to update it. It was really nice of you guys to come back to all this though.

**Comment by ShounenArgha** [comment]
> Yeah, I was just confused when it broke one time all of the sudden, didn't realize there was a new update until I checked manually, that's kinda why I mentioned it. But from now on I have a tasksch running to update it. It was really nice of you guys to come back to all this though.

You just happened to give this issue and i figured out the tasksch way and doing it conveniently.just shoving it in like a command prompt is just chaotic.
You can use the auto install proccedure with some switch editing to have more power over ur update method

**Comment by ShounenArgha** [comment]
Would you care to close the issue?

**Comment by amd64fox** [comment]
Yeah, I'll close this as unplanned for now, but if there is any news, I'll reopen it.
