### ISSUE TITLE
scoop says "Couldn't find manifest for 'spotx-np'."

### ISSUE THREAD

**Issue by johnlee1st** [SpotX-Official/SpotX#378]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [ ] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

USA

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.9.743.g85d9593d
- Windows: Windows 10 Pro 22H2 19045.2728
- PowerShell: 5.1.19041.2673
```

### 📝 Description

This isn't exactly a bug per se but more like an installation glitch. I've been trying to install SpotX for the first time using _scoop_, which I'd like to keep using to update SpotX all the time if possible.
1. I opened an elevated command prompt window and did the following as instructed in the README.md of SpotX.
2. `scoop bucket add nonportable`
3. `scoop install spotx-np`
4. At this point, scoop spewed out an error message that says: `Couldn't find manifest for 'spotx-np'.`
...
I could of course use other installation options, but I'd like to go with scoop because of obvious reasons people use package managers in the first place.

p.s. Maybe it's just me, but It'd be great if SpotX were available as a Chocolatey package as well.

**Comment by amd64fox** [comment]
Run `scoop update; scoop update spotx-np --force`



> p.s. Maybe it's just me, but It'd be great if SpotX were available as a Chocolatey package as well.

you can create a pr if you have the time and desire.

**Comment by johnlee1st** [comment]
I went ahead and went the "Usual installation (New theme)" route, and then found your reply just now.

> Run `scoop update; scoop update spotx-np --force`

Updated scoop, but `scoop update spotx-np --force` didn't work, since SpotX hasn't been installed using scoop.
Tried `scoop install spotx-np` again, but still no dice. The same complaint about no manifest.

> you can create a pr if you have the time and desire.

Oh, ofc it's extra work for you, too. My bad.
Maybe I should learn to write PowerShell scripts, which I've been postponing like forever. : )

**Comment by amd64fox** [comment]
I have no problems installing SpotX via scoop, most likely the problem is with your particular [scoop-nonportable](https://github.com/ScoopInstaller/Nonportable), check their repo for support.

**Comment by johnlee1st** [comment]
I gave it another try and was finally able to install SpotX using scoop.

```
scoop update
scoop bucket rm nonportable
scoop bucket add nonportable
scoop install spotx-np
```
I think what ultimately did the trick was `scoop update`, which you suggested.

I suppose it's better to add it to the installation steps in the README.md as a fail-safe for scoop noobs like me, as follows:
```
scoop update
scoop bucket add nonportable
scoop install spotx-np
```
or even `scoop bucket rm nonportable`, too.

Thank you!
