### ISSUE TITLE
Option to install to program files for all users

### ISSUE THREAD

**Issue by IRainman** [SpotX-Official/SpotX#381]
### Description of the new feature / enhancement

Currently, the installation can't be performed to the program files folder. This possibility is really needed for security reason and using with multi-user configuration.

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
SpotX uses the official Spotify installer, and it is their choice to install their client in the "\AppData\Roaming\Spotify" path. While this path can be changed using various workarounds, I believe it's not worth the effort as it may cause more confusion than benefit. If you really need to change the installation path, you can request it on [their forum](https://community.spotify.com/t5/Desktop-Windows/bd-p/desktop_windows), or try creating your own isolated environment - some people create portable builds for this purpose (google search).
