### ISSUE TITLE
Ads play

### ISSUE THREAD

**Issue by mdashlw** [SpotX-Official/SpotX#382]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

New Zealand

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.9.743.g85d9593d
- Windows: Windows 11 Pro 22H2 22621.1555
- PowerShell: N/A
```

### 📝 Description

Ads play like they would on the free plan

**Comment by amd64fox** [comment]
what type of ads are you getting?

also need a full screenshot of your client

**Comment by mdashlw** [comment]
15/30-second ads after a few songs/skips. interestingly, it only plays one batch of ads and never again until I restart the client
![image](https://user-images.githubusercontent.com/34678047/232474775-bbd0d163-07a9-44cd-8cbf-f1b3efc856f6.png)

**Comment by amd64fox** [comment]
We recently received a similar message about audio advertising, perhaps Spotify has selectively started testing on some users.
You can help us determine this by doing the following:

- Log in to the remote configuration using these [instruction](https://github.com/amd64fox/SpotX/discussions/47)
- Then select and copy all the text, for example using select all (Ctrl + A) copy (Ctrl + C), and paste (Ctrl + V) it into a new text file, 
- Then send the file here.

if something is not clear, then be sure to ask additional questions

**Comment by mdashlw** [comment]
Like this?
[spotify-stuff.txt](https://github.com/amd64fox/SpotX/files/11249925/spotify-stuff.txt)

**Comment by amd64fox** [comment]
right
wait, I need time to study your remote config

hmm weird your remote config is the same as mine, apparently the problem is something else...

**Comment by amd64fox** [comment]
As soon as we get closer to the core of the problem, we may need your help again, please stay in touch, thank you for your assistance.

**Comment by amd64fox** [comment]
Do the following:
 - Clean install ([perform as described in the FAQ](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation))
 - Run SpotX installation
 - Log in to the client and check that the audio ads still appear
 - Log in to the remote configuration using these [instruction](https://github.com/amd64fox/SpotX/discussions/47)
 - Record a video of your remote configuration while viewing it on your screen and send it here. You can record it as either a GIF or a video; it doesn't matter, example:
 
![229218761-5c6f313f-f5c5-44f4-94ec-148f0e9faf86 1](https://user-images.githubusercontent.com/62529699/232726797-3b9cec98-abfa-43bb-954f-60e5ba1ae361.gif)

**Comment by mdashlw** [comment]
I haven't done anything and can't reproduce it anymore, which is strange because it was 100% consistent yesterday. The version is still 1.2.9.743.g85d9593d and nothing changed in the remote config either. I can reopen the issue if it returns, thanks for your help.
