### ISSUE TITLE
Cannot open album/track in app from webversion

### ISSUE THREAD

**Issue by soredake** [SpotX-Official/SpotX#385]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Ukraine

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.9.743.g85d9593d
- Windows: 11 Pro
- PowerShell: 7.3.2
```

### 📝 Description

1. Go to any track/album.
2. Press "Open in desktop app".
3. You will see an error.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/5204968/233164430-88f7509f-3d38-4eb3-9081-05f0ccb48f6c.png)

**Comment by amd64fox** [comment]
not related to SpotX, most likely the problem is related to a violation of file or link associations in your OS
