### ISSUE TITLE
"CAN'T" play any "album" songs, songs just WON'T start playing

### ISSUE THREAD

**Issue by vacarogit** [SpotX-Official/SpotX#386]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Taiwan , definately a legitimate lecountry

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify:  Windows Spotify
1.2.5.1006.g22820f93
- Windows: 7 64bit
- PowerShell: null
```

### 📝 Description

1.I "CAN'T" play any "album" songs, songs just WON'T start playing I tried use null hosts file still can'tf
2.I CAN play "playlist" songs
3.I CAN play "podcasts" songs
...

**Comment by amd64fox** [comment]
Duplicate #316
