### ISSUE TITLE
Add "Your Nich Mixes" to the Desktop app

### ISSUE THREAD

**Issue by Ximzend** [SpotX-Official/SpotX#388]
### Description of the new feature / enhancement

I would like to have the ability to view my "Nich Mixes" inside the Desktop app.
The URL you can use to get the JSON data of the mobile "Made for You" page is:
https://spclient.wg.spotify.com/made-for-you-hub-view/v1/hub/spotify:page:0JQ5DAt0tbjZptfcdMSKl3
The data for your-niche-mixes is in jsondata["body"][5]
Using postman and an Access Token from the Web app, I could get the data without any problem.

(Actually, the app hub is just the desktop hub, but with your-niche-mixes added, so replacing the original desktop endpoint URL with the mobile one would maybe do the trick.)

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
just search for "music picked just for you"

**Comment by Ximzend** [comment]
I know, but I like the 10 recommended Nich Mixes on mobile, so I don't need to search for them myself.

**Comment by amd64fox** [comment]
if you want to constantly view certain Nich Mixes, then you look for them as indicated above, then add those that you especially like to the folder so that you have them at hand next time

**Comment by amd64fox** [comment]
just noticed today that they added Nich Mixes to the "Mad For You" section

![Снимок экрана 2023-08-02 130818](https://github.com/amd64fox/SpotX/assets/62529699/58465c56-e770-4d03-a7cd-940f7f5af1bf)
