### ISSUE TITLE
SpotX Old theme doesn't work

### ISSUE THREAD

**Issue by SkillzAura** [SpotX-Official/SpotX#389]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Bangladesh

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows 1.2.9.743.g85d9593d
- Windows: 11 22H2
- PowerShell: 5.1.22621.963
```

### 📝 Description

1.  Download and run Install_Old_theme.bat or remove new_theme parameter from installer
2. Spotify still runs on the new theme

The old theme spotx installation still installs the new theme instead of the old theme. Please fix it

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/131694696/234052647-b4df3e10-7906-4b6f-8a68-2a6353f375ac.png)

**Comment by amd64fox** [comment]
perform a [clean install](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation) exactly as described in the FAQ

**Comment by SkillzAura** [comment]
> perform a [clean install](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation) exactly as described in the FAQ

I did but it didn't work

**Comment by amd64fox** [comment]
Yes, indeed, the problem exists. Spotify has started to remotely enable a new theme everywhere. While I am searching for a new way to force the old theme to return, you can use a temporary solution:

- use this [instruction](https://github.com/amd64fox/SpotX/discussions/47) to get into Remote Config
- through the search you find `enableYLXSidebar` and set it to false

**Comment by amd64fox** [comment]
fixed

but obviously with each new update the old theme will be minimized by the Spotfiy developers, in such cases it will be possible to return to the old theme only by rolling back the client
