### ISSUE TITLE
歌词功能是否可以接入musixmatch 

### ISSUE THREAD

**Issue by xiaojinxiaojin111** [SpotX-Official/SpotX#391]
### Description of the new feature / enhancement

- 1
- 2
- 3
这样就不会很多歌曲没有歌词

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
![Снимок экрана 2023-04-26 144102](https://user-images.githubusercontent.com/62529699/234564533-20d99a2a-80ec-4e15-9f08-c5ac17821c8b.png)

**Comment by xiaojinxiaojin111** [comment]
因为我是中文歌曲听得多 所以spotify很多中文歌曲没有歌词  而单独下载musixmathc软件却发现这首中文歌是有歌词的

**Comment by amd64fox** [comment]
you can try Spicetify, they have different extensions related to lyrics

**Comment by xiaojinxiaojin111** [comment]
Spicetify配上spotx太臃肿和卡顿
