### ISSUE TITLE
ScrollBar and Main Title Color

### ISSUE THREAD

**Issue by bathtimethiago** [SpotX-Official/SpotX#393]
### Description of the new feature / enhancement

![Topbar Color](https://user-images.githubusercontent.com/88913489/234943224-bacca826-5ace-4206-b189-e816a1f500d1.png)

.EvIR4O7jOSbNmxtMdIQ0 {
    background-color: var(--background-highlight);

![Fluent Scrollbar](https://user-images.githubusercontent.com/88913489/234940412-a0a39fef-d7bc-49b8-a4f7-59c7d2188d5f.png)

.os-theme-spotify.os-host-transition>.os-scrollbar-vertical>.os-scrollbar-track>.os-scrollbar-handle {
    border-radius: 4px;
    width: 6px;
}
.os-theme-spotify.os-host-transition>.os-scrollbar-vertical>.os-scrollbar-track {
    width: 6px;
}

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
> .EvIR4O7jOSbNmxtMdIQ0 {
> background-color: var(--background-highlight);

This makes the color of the top uniform, right?



> .os-theme-spotify.os-host-transition>.os-scrollbar-vertical>.os-scrollbar-track>.os-scrollbar-handle {
> border-radius: 4px;
> width: 6px;
> }
> .os-theme-spotify.os-host-transition>.os-scrollbar-vertical>.os-scrollbar-track {
> width: 6px;
> }


But what are you doing it with the scrollbar?

**Comment by bathtimethiago** [comment]
Default scrollbar is too big and ugly

**Comment by amd64fox** [comment]
I believe it's subjective for everyone, as there are numerous such moments throughout the client. I highly recommend using [Spicetify](https://github.com/spicetify/spicetify-cli), where you can customize your own theme or choose from a variety of ready-made options

Cheers.
