### ISSUE TITLE
lyrics button

### ISSUE THREAD

**Issue by SombreElvio** [SpotX-Official/SpotX#395]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

french

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify  pour Windows
1.2.10.760.g52970952
- Windows: 22H2
- PowerShell: 5.1.22621.963
```

### 📝 Description

hello , no steps for repoduce the error just install spotX and the lyrics button despawn , i dont know why .

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/126872155/235250225-c20991fd-609c-4744-b9d3-cbcbdd54aae7.png)

**Comment by amd64fox** [comment]
in the new theme, the lyrics have been moved to the right sidebar
![Анимация4](https://user-images.githubusercontent.com/62529699/235261857-d1f9beb5-08d8-4157-b1f3-d439bbb499c8.gif)

can also return the old lyrics icon with the `-old_lyrics` parameter

**Comment by SombreElvio** [comment]
old lyrics where is this ?

**Comment by SombreElvio** [comment]
old lyrics where is this ?

**Comment by amd64fox** [comment]
```ps1
[Net.ServicePointManager]::SecurityProtocol = 3072; iex "& { $(iwr -useb 'https://spotx-official.github.io/run.ps1') } -new_theme -old_lyrics"
```

**Comment by SombreElvio** [comment]
its does not work I enter the command in PowerShell but nothing happens

**Comment by SombreElvio** [comment]
it s good thanks you

**Comment by thaynos** [comment]
![image](https://github.com/amd64fox/SpotX/assets/83282129/bae2ea3b-4d90-41ff-85a8-5c3876214a9b)
yo i tried with the old lyrics flag but ti doesnt show, it dint show in the now playing page either

**Comment by amd64fox** [comment]
@thaynos  Most likely, this song simply doesn't have lyrics.

**Comment by thaynos** [comment]
it would be nice to have a button in place that says lyrics not available
or something, but thx for clarifying!

**Comment by killuzii** [comment]
> ```powershell
> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -new_theme -old_lyrics"
> ```

how do i use this

**Comment by amd64fox** [comment]
paste this line into PowerShell terminal

**Comment by VihaanReddyM** [comment]
yes

**Comment by killuzii** [comment]
> paste this line into PowerShell terminal

what is powershell terminal? is there maybe a youtube tutorial that can help me do this because im not sure if that's an app you can download or what

**Comment by amd64fox** [comment]
- press `Win` + `R` and enter `powershell`
- paste this line:
```ps1
[Net.ServicePointManager]::SecurityProtocol = 3072; iex "& { $(iwr -useb 'https://spotx-official.github.io/run.ps1') } -new_theme -old_lyrics"
```

**Comment by killuzii** [comment]
> * press `Win` + `R` and enter `powershell`
> * paste this line:
> 
> ```powershell
> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -new_theme -old_lyrics"
> ```

i got it, thanks!

**Comment by killuzii** [comment]
This is no longer working do you have a fixed version?

**Comment by amd64fox** [comment]
bro, sometimes it would be useful for you to view resolved problems or read the faq

**Comment by killuzii** [comment]
i read the faq and im trying to use the -old_lyrics parameter during installation but it does not let me it just goes straight to installing it and doesn't let me put anything in

**Comment by amd64fox** [comment]
@killuzii 
the command line has changed a bit since then, try this:
```ps1
[Net.ServicePointManager]::SecurityProtocol = 3072; iex "& { $(iwr -useb 'https://spotx-official.github.io/run.ps1') } -new_theme -old_lyrics"
```

**Comment by killuzii** [comment]
thanks bro it works 👍
