### ISSUE TITLE
Force Spotify to Update Timeline Every second.

### ISSUE THREAD

**Issue by yodaluca23** [SpotX-Official/SpotX#40]
## 📝 Description of the idea

1. When patching Spotify, change the code to update the windows timeline every second to fix bugs like [this](https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/963).
2. This should be an optional feature to be activated similarly for when it asks you if you want to "Disable Podcasts" or "Cache Cleanup"

**Comment by amd64fox** [comment]
Too invidual bug related to a particular application, try to leave a suggestion in [community.spotify.com](community.spotify.com), perhaps they will help you there.
If I find out more about this problem, I'll let you know here.
