### ISSUE TITLE
Ads are Being Played in The Spotx Application 

### ISSUE THREAD

**Issue by Therockstar777** [SpotX-Official/SpotX#401]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [x] I have checked older issues, open and closed
- [x] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows
1.2.10.760.g52970952
- Windows: 11 22H2
- PowerShell: 5.1.22621.963
```

### 📝 Description

1.Ads Are Being played the SpotX application since 4 days on  Windows .
2.Requesting the SpotX Team to resolve the issue as soon possible by releasing a new version of the SpotX Application
 Mine is SpotX New Theme (Edit)

### 📸 Screenshots

![Screenshot_2](https://user-images.githubusercontent.com/127512365/236189221-6f670b9c-56e3-492d-a613-17fb891fe01a.jpg)

**Comment by amd64fox** [comment]
Before making a request of the SpotX "team", it's important to review the materials that were provided in the issue creation template. This can help ensure clear communication and increase the likelihood of a successful outcome.

Cheers.

**Comment by Therockstar777** [comment]
I was not able to select the first three checkboxes and now I have Provided all the materials required.... and I have completely "reviewed " the materials provided... so kindly requesting to provide a new version of SpotX
