### ISSUE TITLE
CC or subtitle for video podcast is missing

### ISSUE THREAD

**Issue by Kecupbasah** [SpotX-Official/SpotX#403]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Indonesia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.10.760.g52970952
- Windows: 10 22H2 19045.2130
- PowerShell: 5.1.19041.1682
```

### 📝 Description

Closed caption or subtitles for podcast with video such as Joe Rogan is missing. The icon is gone too. Sorry for the complain. 

### 📸 Screenshots

![Annotation 2023-05-07 163732](https://user-images.githubusercontent.com/132814651/236669761-dd69d374-8b58-42b4-b15f-9ae9324edaf1.png)

**Comment by amd64fox** [comment]
Does the native client have subtitles?

check if you have subtitles in this [podcast](https://open.spotify.com/episode/7nqAYG35Az9bzEkknwhA6B?si=1772c1ab439344a3)

**Comment by amd64fox** [comment]
A temporary fix for this issue has been implemented. Please perform a clean installation.

Overall, this is a longstanding problem with SpotX and how it handles exp processing. I will address it as soon as I have a bit more free time.
