### ISSUE TITLE
Blank ad box showing up

### ISSUE THREAD

**Issue by oliver194** [SpotX-Official/SpotX#406]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United Kingdom

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows
1.2.11.914.gd3175972
- Windows: Windows 10 22H2 19045.2913
- PowerShell: 5.1.19041.2673
```

### 📝 Description

Install SpotX (with old theme) and go to a playlist, lyrics, queue, search, library

### 📸 Screenshots

![image](https://github.com/amd64fox/SpotX/assets/100048880/d74b00f9-a478-4cff-9981-9b06adcefd5c)

**Comment by amd64fox** [comment]
follow this [instruction](https://github.com/amd64fox/SpotX/issues/382#issuecomment-1511214436)

**Comment by amd64fox** [comment]
also you should have done a clean install exactly as described [in the faq](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation)
in order to exclude the interference of tired files and cache from previous versions of the client

**Comment by oliver194** [comment]
fixed, thanks

**Comment by amd64fox** [comment]
Hello, did you see this banner again over time, or has there been no sign of it anymore?
