### ISSUE TITLE
Interactive Lyrics

### ISSUE THREAD

**Issue by twistedmacaroni** [SpotX-Official/SpotX#41]
## 📝 Description of the idea

Interactive lyrics have been available for some Spotify users currently. It'd be great for you to include that in the patch until Spotify enables it for everyone.

## 📷 Screenshots

A YouTube video uploaded on Reddit showing the said feature - https://www.youtube.com/watch?v=rlGq1FsqP4g

**Comment by amd64fox** [comment]
this has already been done, just update

**Comment by twistedmacaroni** [comment]
doesnt work for me for some reason

**Comment by amd64fox** [comment]
Spotify version?

**Comment by twistedmacaroni** [comment]
Spotify for Windows
1.1.84.716.gc5f8b819

**Comment by amd64fox** [comment]
Try to completely uninstall Spotify and re-run install.bat

**Comment by amd64fox** [comment]
Apparently, Spotify developers are forcibly disabling some additional chips for some users.

**Comment by amd64fox** [comment]
Tried to fix this problem... try uninstalling Spotify completely and reinstalling everything.

**Comment by twistedmacaroni** [comment]
> Tried to fix this problem... try uninstalling Spotify completely and reinstalling everything.

thanks that worked for me!
