### ISSUE TITLE
Update to new theme

### ISSUE THREAD

**Issue by EdwardDK** [SpotX-Official/SpotX#413]
### Description of the new feature / enhancement

Spotify updated to a new theme, so now both themese are old. Can you please update and make a new theme for spotify tht fits what currently is the theme?

### 📸 Screenshots

![image](https://github.com/amd64fox/SpotX/assets/73299061/fa69ca93-b1c7-4abd-8f8c-920dee4535b2)

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
I didn't quite understand from the text which theme is not working for you?

What type of SpotX installation (or additional parameters) did you use? 

Have you tried a clean installation?

**Comment by EdwardDK** [comment]
I used the full instillation for the original theme, and it didn't have the new spotify ui

**Comment by EdwardDK** [comment]
NVM, I just installed the new theme. Thankyou!
