### ISSUE TITLE
error patching spotify version 1.2.12.902.g1924b088-3133

### ISSUE THREAD

**Issue by AnonymouseHucker29** [SpotX-Official/SpotX#416]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Philippines

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.12.902.g1924b088-3133
- Windows: 11 22H2 22621.1702
- PowerShell: 5.1.22621.963
```

### 📝 Description

1. Download and install the latest Spotify version in the excel file (1.2.12.902.g1924b088-3133).
2. Open the **Install_Auto.bat** file.
3. An error will show in the Powershell.

### 📸 Screenshots

<img width="516" alt="image" src="https://github.com/amd64fox/SpotX/assets/92257095/6543ec34-2337-4598-9df9-a385e1b1f082">

**Comment by amd64fox** [comment]
Update the bat file
