### ISSUE TITLE
Shows unable to reach remote server

### ISSUE THREAD

**Issue by HoledkRTF** [SpotX-Official/SpotX#417]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [x] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows
1.2.11.916.geb595a67
- Windows: Version	10.0.19045 Build 19045

- PowerShell: 5.1.19041.2673
```

### 📝 Description

1.Whenever i click the old or new theme option it just shows the following error
...
Invoke-WebRequest : Unable to connect to the remote server
At line:1 char:93
+ ... 2}; "& { $((Invoke-WebRequest -UseBasicParsing 'https://raw.githubuse ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Press any key to continue . . .

**Comment by lollita** [comment]
Also I have this problem today:
Unable to connect to the remote server: 'raw.githubusercontent.com'
Do it is possible to have a standalone script that not need to connect to a remote server?
