### ISSUE TITLE
Sudden color change in right side bar

### ISSUE THREAD

**Issue by Grummiom** [SpotX-Official/SpotX#422]
### Description of the new feature / enhancement

When "-rightsidebarcolor" is enabled, sidebar color changes suddenly which you can see in this picture:

### 📸 Screenshots

![Screenshot 2023-05-26 114354](https://github.com/amd64fox/SpotX/assets/80743529/5103762e-e39d-467a-aaaa-79967c3cd3a2)

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
native client bug 1.2.12

**Comment by amd64fox** [comment]
fixed in 1.2.13
