### ISSUE TITLE
My Windows language is in Filipino, but the installer is in Finnish

### ISSUE THREAD

**Issue by infyProductions** [SpotX-Official/SpotX#423]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Philippines

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.12.902.g1924b088
- Windows: Windows 10 22H2 19045.2846
- PowerShell: 5.1.19041.2673
- PowerShell Core: 7.3.4
```

### 📝 Description

1. Clone the repository
2. Start the installer by typing .\install.ps1
3a. Expectation:
- The installer language should be in Filipino and not in Finnish
3.b. Reality:
- The installer language is in Finnish even though my Host OS language is in Filipino and triple-checked the language by running `$PSUICulture` (output: fil-PH)

Temporary workarounds I tried:
1. Swapping the language installer script file between Finnish (fi.ps1) and Filipino (fil.ps1) in scripts\installer-lang
- Doesn't work (still in Finnish)
2. Modifying the Install.ps1 file: replace FI (Finnish) to FIL (Filipino) [lines 93, 195 and 196]
- It's a bit better (in English but not in Filipino)
3. Modifying the Install.ps1 file: replace the return code from EN (English) to FIL (Filipino) [line 222]
- The language is in the correct language now (Filipino)

Suggestion:
- Try using `Get-Culture` as a fallback (aside from just the country codes) to use LCID (Locale ID). The language code for Filipino is fil-PH (or LCID 1124), English as en-US (or LCID 1033), and Finnish as fi-FI (or LCID 1035). The problem here that it cuts off into three character codes (like fil into fi) which I guess the reason it changed the language to Finnish.

### 📸 Screenshots

Image 1: (From temporary workarounds 1 - Suomi on hyvä [Finnish is good])
![image](https://github.com/amd64fox/SpotX/assets/31158494/7338bc95-3447-4925-8320-f217e4615a88)
Image 2: (From temporary workarounds 2 - English is slightly better)
![image](https://github.com/amd64fox/SpotX/assets/31158494/e74d0b50-76ba-496a-89a7-8fc8daa6ddc8)
Image 3: (From temporary workarounds 3 - Magandang Filipino [Filipino good])
![image](https://github.com/amd64fox/SpotX/assets/31158494/9976a42d-cf86-4c27-820b-230bf2ff6d5d)

**Comment by amd64fox** [comment]
Thank you for noticing that.

Is it working for you now?

**Comment by infyProductions** [comment]
Sorry for the late reply, It's now fixed with the correct language after I cloned this one recently.
![image](https://github.com/amd64fox/SpotX/assets/31158494/d353a625-28f8-42ae-9482-7915d96940d4)
