### ISSUE TITLE
Auto-Update

### ISSUE THREAD

**Issue by phoriah** [SpotX-Official/SpotX#425]
### Description of the new feature / enhancement

- Since Spotify itself has automatic updates, why not add support for Auto-Updates for this patcher too
- That way users will avoid having to manually check the page for updates and will always get the latest & greatest patch when it's out!
- This is a generally a good practice in many apps / programs / patchers (look at [xManager](https://github.com/Team-xManager/xManager), they executed it very well). Note: it doesn't have to be a installer or anything like that. Could be a simple code that checks for updates in background, for example every 24h or every time the Spotify is started.

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
#377
