### ISSUE TITLE
Runing in notepad

### ISSUE THREAD

**Issue by RealPankof** [SpotX-Official/SpotX#426]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Florida

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows
1.2.10.760.g52970952
- Windows: windows 10 home 22H2 19045.2965
- PowerShell: 5.1.19041.2673
```

### 📝 Description

1.just launches notepad with code in it
2.
3.
...

### 📸 Screenshots

![image](https://github.com/amd64fox/SpotX/assets/135173850/1449a1fc-a97f-4afa-b894-a40aed3dc720)

**Comment by amd64fox** [comment]
just run batch file
