### ISSUE TITLE
install/update sptx not working

### ISSUE THREAD

**Issue by roy9674** [SpotX-Official/SpotX#429]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

israel

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.12.902.g1924b088
- Windows: 11 Pro 22H2 22621.1778
- PowerShell: 5.1.22621.1778
```

### 📝 Description

When I try to update a version from [Install_Old_theme.bat] I get an error message.

### 📸 Screenshots

![Error](https://github.com/amd64fox/SpotX/assets/6981223/482f3acf-cc1c-4e3c-a284-20e869546719)

**Comment by amd64fox** [comment]
There were issues with the recent change, but now it should work
