### ISSUE TITLE
Change search placeholder text if podcasts are removed

### ISSUE THREAD

**Issue by francescoaracu** [SpotX-Official/SpotX#43]
## 📝 Description of the idea

If the user wants to remove podcasts on install, search placeholder text should be changed to "Artist, albums or songs", similar to what [this Spicetify extension](https://github.com/theRealPadster/spicetify-hide-podcasts) does.

## 📷 Screenshots

<details>
<summary><small>Screenshot</small></summary><p>

Default behaviour
![Default behaviour](https://user-images.githubusercontent.com/48188510/168758169-64057ad7-bfba-4c77-8283-d1613e952400.png)

With Spicetify extension
![With Spicetify extension](https://user-images.githubusercontent.com/48188510/168758309-1c554acf-6336-4280-b23e-9e16e560c6dc.png)

</small></summary><p>

</details>

**Comment by amd64fox** [comment]
Hi, I didn't have a task to completely remove the podcasts from the client, I just wanted to hide them from the main page as it really annoyed a lot of people.
If it's really important to you, you can use SpotX along with Spicetify.
