### ISSUE TITLE
Auto Pause Spotify

### ISSUE THREAD

**Issue by ghost** [SpotX-Official/SpotX#432]
### Description of the new feature / enhancement

- 1 It would be cool to have a way to auto pause spotify when some conditions are met

For example, if the mode "Pause on Game", once i start a game, music pause
Or if im watching a Youtube Video with the mode "Pause on Youtube", music pause 

When no conditions are met, then the music play again

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
Most likely, in order to implement this, we would need access to the CEF code because we need to involve additional event handlers in the OS. However, direct access to the CEF code is restricted.
