### ISSUE TITLE
Error installing SpotX

### ISSUE THREAD

**Issue by Halog-n** [SpotX-Official/SpotX#434]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Australia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: N/A
- Windows: Windows 10 Home 22H2
- PowerShell: 5.1.19041.2673
```

### 📝 Description

Attempting to install the automatic full installation with both cmd and powershell consoles results in this same error:
Property 'ErrorMessage' cannot be found for type 'System.Management.Automation.ValidatePatternAttribute'.
At line:4 char:5
+     [ValidatePattern("^\d+\.\d+\.\d+\.\d+\.g[0-9a-f]{8}-\d+$", ErrorM ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFoundForType

### 📸 Screenshots

<img width="602" alt="image" src="https://github.com/amd64fox/SpotX/assets/135714614/020c56f1-2266-46b3-91cb-b34d5e603175">
<img width="592" alt="image" src="https://github.com/amd64fox/SpotX/assets/135714614/8b2b89dc-55b0-4a36-8632-a40f1aa452c4">

**Comment by amd64fox** [comment]
now works ?

**Comment by Halog-n** [comment]
Works now, thank you!
