### ISSUE TITLE
Error when pressing the bell (Notifications)

### ISSUE THREAD

**Issue by nobef** [SpotX-Official/SpotX#438]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Kazakhstan

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.9.743.g85d9593d
- Windows: 10
- PowerShell: 5.1.19041.2673
```

### 📝 Description

1.When you click on notifications (I think these are subscriptions to artists), an error occurs, no information is shown. And this is regardless of the presence of subscriptions.
2.
![Анимация](https://github.com/amd64fox/SpotX/assets/77186394/b8e1615f-f09a-4f60-8dec-1a64ccd97c60)

3.
...

### 📸 Screenshots

![изображение](https://github.com/amd64fox/SpotX/assets/77186394/2e7cc7db-4b78-4cf6-869a-7fe655842b60)

**Comment by amd64fox** [comment]
Update to 1.2.12+
