### ISSUE TITLE
Enable DevTools

### ISSUE THREAD

**Issue by sakgoyal** [SpotX-Official/SpotX#439]
### Description of the new feature / enhancement

Is there any way I can enable the dev tools on the app? I have the `app.enable-developer-mode=true` line added to my prefs file but I cant find a way to see it still. Would it be possible to add a button to enable it?

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
try it 
https://github.com/amd64fox/Enable-devtools-Spotify
