### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by WalterBiely** [SpotX-Official/SpotX#441]
### Description of the new feature / enhancement

I think it would be cool if there was a feature where you can see stats like playtime top songs, artists.

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by Yashirow** [comment]
There's a custom app on Spicetify that do what you want (you can install it on top of SpotX).

**Comment by amd64fox** [comment]
No plans for it, use something on the side
