### ISSUE TITLE
Add opening lyrics back to where it was in the old theme

### ISSUE THREAD

**Issue by WalterBiely** [SpotX-Official/SpotX#445]
### Description of the new feature / enhancement

I personally don't like where the lyrics open in the new theme and I personally think it would be a good idea to put it back as it was in the old theme or at least give that option.

### 📸 Screenshots

![Lyrics-a712d65114f249da8a72c39c6dfcee4b](https://github.com/amd64fox/SpotX/assets/126421855/19ab1e1e-364e-49f3-ad59-58ff0dd5aca8)
here

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
duplicate #395
