### ISSUE TITLE
Allow to copy name of song

### ISSUE THREAD

**Issue by Luffier** [SpotX-Official/SpotX#446]
### Description of the new feature / enhancement

Allow to copy the name of the song (and possibly album and artist) by right clicking on it. Could be added to the "Share" subgroup.

### 📸 Screenshots

Current right-click context menu:

![image](https://github.com/amd64fox/SpotX/assets/7539849/9ada9568-aa5f-4716-8325-98c8d6dc2bdc)

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
use spicetify
