### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Ewufie23** [SpotX-Official/SpotX#448]
### Description of the new feature / enhancement

- 1 Make it work on Debian based linux (Debian, Ubuntu, ZorinOS, PopOS)
- 2 Make it work on Arch based linux (Arch, BlackArch, Manjaro) (optional lmfao)

Eventually ill try in a free time.

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
already 
https://github.com/jetfir3/SpotX-Bash
