### ISSUE TITLE
Doesn't start after shutting down/restarting (windows)

### ISSUE THREAD

**Issue by TotalyEnglizLitrate** [SpotX-Official/SpotX#449]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [ ] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.14.1149.ga3ae4...(spotify doesn't open can't check version from inside used winget to see)
- Windows: Windows 10 22H2 19045.3086
- PowerShell: 7.4.0-preview.3
```

### 📝 Description

1.Install spotx - didn't disable updates, tried both enabling and disabling "podcasts, episodes and audiobooks" either way "Didn't find variable patches.json.others.podcast_ad_block in Spotify.exe" error was raised
2.Works fine
3. shut down/ reboot
4. Spotify does not start
works fine after reinstalling spotx

**Comment by amd64fox** [comment]
read FAQ

**Comment by TotalyEnglizLitrate** [comment]
I can't, the site doesn't load with a Secure Connection Failed error

**Comment by amd64fox** [comment]
use vpn
