### ISSUE TITLE
More button

### ISSUE THREAD

**Issue by SuperCuek** [SpotX-Official/SpotX#45]
## ℹ Computer information

- Spotify version: 1.1.85.895.g2a71e1b8
- Windows version: Win10 21H2 19044.1706
- PowerShell version: 5.1.19041.1682

## 📝 Description of the problem

i think the [more] button is gone in search result

**Comment by JasonShearer** [comment]
I can confirm.

**Comment by amd64fox** [comment]
Are you talking about these buttons? 

<details>
<summary><small>screenshot</small></summary><p>

![Снимок экрана 2022-05-23 073130](https://user-images.githubusercontent.com/62529699/169744318-e5fc3e67-fc83-4dd9-a80b-7f5f432e6d06.jpg)


</summary><p>
</details>

**Comment by SuperCuek** [comment]
> Are you talking about these buttons?
> screenshot
> 
> ![Снимок экрана 2022-05-23 073130](https://user-images.githubusercontent.com/62529699/169744318-e5fc3e67-fc83-4dd9-a80b-7f5f432e6d06.jpg)

absolutely... PS: i have friend activity section

**Comment by amd64fox** [comment]
Maybe it's the features of the new search that I activated?
It seems to me that these category buttons for the new search, which are at the top, according to the idea of the developers, perform the function of the missing `SEE ALL` buttons in the old search.

I checked the work on the original client and these buttons (SEE ALL) are not there either.

**Comment by amd64fox** [comment]
There are 2 options, either everything remains as it is, or I can create a vote for returning to the old search, since I need to understand the number of people who do not like the new search.

[I started voting here](https://github.com/amd64fox/SpotX/discussions/46)

**Comment by amd64fox** [comment]
Now you can specify various parameters for a more flexible installation, more [details here](https://github.com/amd64fox/SpotX/discussions/60)
