### ISSUE TITLE
Script doesn't work if the user has a "curlrc" file defining an output directory

### ISSUE THREAD

**Issue by bzzrak** [SpotX-Official/SpotX#454]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

N/A

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
N/A
```

### 📝 Description

1. make a textfile at `%userprofile%\_curlrc`
2. put the following in it: `output-dir = C:\Users\%USERNAME%\Downloads` (or some other directory). This sets the default directory for downloaded files.
3. run SpotX and have it update your Spotify installation
4. curl will fail to download SpotifySetup.exe with an error: "failure writing output to destination" (see screenshot)

Solution: add the `-q` argument to ignore the curlrc file: https://curl.se/docs/manpage.html#-q
Or add `--output-dir %temp%\SpotX\`: https://curl.se/docs/manpage.html#--output-dir

### 📸 Screenshots
Notice how the directory from the curlrc is added in front of the desired path.
![slika](https://github.com/amd64fox/SpotX/assets/77467869/54cac64a-11d3-4f0a-a29a-c5ea119aec9f)

**Comment by amd64fox** [comment]
thanks for noticing this and sharing the solution
