### ISSUE TITLE
Spotify not supported

### ISSUE THREAD

**Issue by Tb3986** [SpotX-Official/SpotX#457]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

German

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: v1.2.15.828
- Windows: Windows 10
```

### 📝 Description

Hello,
latest spotify is not supported from SpotX:

Regards

### 📸 Screenshots

![Untitled](https://github.com/amd64fox/SpotX/assets/45364981/600510a4-d281-4277-9d43-7e595f938041)

**Comment by amd64fox** [comment]
That's right, I'm on vacation right now, so there's no way to test 1.2.15, but you can test that version by adding the **-v** argument to the command line, it should look something like this:

```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -v 1.2.15.828.g79f41970-1030 -confirm_spoti_recomended_over -block_update_on"
```

if there are serious errors, it is better to return to the recommended version, by the end of this month I will return and update SpotX.

**Comment by Tb3986** [comment]
> That's right, I'm on vacation right now, so there's no way to test 1.2.15, but you can test that version by adding the **-v** argument to the command line, it should look something like this:
> 
> ```powershell
> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -v 1.2.15.828.g79f41970-1030 -confirm_spoti_recomended_over -block_update_on"
> ```
> 
> if there are serious errors, it is better to return to the recommended version, by the end of this month I will return and update SpotX.

With your tutorial, works good. Thanks for your time.
Happy vacation!
