### ISSUE TITLE
shuffle button next to the play button does not work

### ISSUE THREAD

**Issue by deleorium** [SpotX-Official/SpotX#463]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

italy

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows (32 bit)
1.2.16.947.gcfbaa410
- Windows: windows 10
- PowerShell:
```

### 📝 Description

1. the button next to play, the shuffle one, does not work, if i click it the songs don't actually shuffle, and go in the order of the playlist
2. there is only one solution to fix this bug, that is to go to up right to the three dots and activate the shuffle there, it will start working only with that

### 📸 Screenshots

![image](https://github.com/amd64fox/SpotX/assets/117927206/81c503ad-4cd9-4c7e-8ee6-c47508023357)
the shuffle button is green, but songs don't shuffle

**Comment by amd64fox** [comment]
does shuffling work if use this ?

```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -new_theme -smartShuffle_off"
```
delete Spotify as described in paragraph clean installation in FAQ
after that run above command in terminal powershell

**Comment by deleorium** [comment]
now it works thank you very much

**Comment by amd64fox** [comment]
Temporarily disabled smart shuffling until they debug
