### ISSUE TITLE
Fix the title in the FAQ

### ISSUE THREAD

**Issue by tim77** [SpotX-Official/SpotX#464]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Germany

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.16.947.gcfbaa410
- Windows: 11
- PowerShell: 5.1.22621.1778
```

### 📝 Description

[Not a bug, feature request]: Is possible to achieve the same result for Linux version of Spotify? Thanks in advance.

**Comment by amd64fox** [comment]
https://github.com/jetfir3/SpotX-Bash

If you really read the FAQ, you would find it there.

**Comment by tim77** [comment]
I've read all **titles** in FAQ and there is no word about "Linux". The same for README. The same for searching via issues. And it's simply illogical to make separate github project for the **same** project. Thanks!

**Comment by amd64fox** [comment]
it was enough to read the [FAQ](https://telegra.ph/SpotX-FAQ-09-19#Where-can-I-find-SpotX-for-Android/iOS-and-for-other-platforms?) carefully

**Comment by tim77** [comment]
Sure, sorry. Don't get me wrong. But maybe would be better to change title in FAQ from:
> Where can I find SpotX for Android/iOS and for other platforms?

to something like:

> Where can I find SpotX for Android/iOS/Linux/macOS?

Hope this could help other people. I even found now badge with Linux on main page but if trying to do search via browser on this page you still have zero results. Just my user feedback. 😄 Thank you.

**Comment by amd64fox** [comment]
Thank you, we will definitely fix the title in the Faq
