### ISSUE TITLE
Cannot Install The Old Or New Theme On Windows 8.1 

### ISSUE THREAD

**Issue by Soldierocks** [SpotX-Official/SpotX#468]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.5.1006.g22820f93
- Windows: 8.1
- PowerShell: 4.0
```

### 📝 Description

How To Install It?
I Have Installed It Previously And It Had Worked Well

### 📸 Screenshots

![image](https://github.com/amd64fox/SpotX/assets/94946357/b1caade5-2706-4267-9326-16f1f59e850e)

**Comment by amd64fox** [comment]
try [updating](https://telegra.ph/SpotX-FAQ-09-19#It-seems-I-have-an-old-version-of-PowerShell-2.0,-can-I-install-a-patch-with-it?) your powershell to version 5

**Comment by Soldierocks** [comment]
how do u update it?

**Comment by amd64fox** [comment]
link with instruction in my first post

**Comment by Soldierocks** [comment]
I Installed powershell vs 5
but it shows error
Stating"old version of spotify found cannot update because of old os"

**Comment by amd64fox** [comment]
where does this error pop up? show a screenshot

**Comment by Soldierocks** [comment]
![image](https://github.com/amd64fox/SpotX/assets/94946357/e32a97aa-6060-429c-9ed7-c16cbe23ddb3)
![image](https://github.com/amd64fox/SpotX/assets/94946357/c9a28e5c-fc86-42fe-b92b-397d3c0181f0)
![image](https://github.com/amd64fox/SpotX/assets/94946357/2e459a50-65d7-4fed-98dd-c2fc681abfde)
I Downloaded The Spotify 8.1 Version From Here
![image](https://github.com/amd64fox/SpotX/assets/94946357/abe02bd7-e0bf-44e6-aec3-468aff0840bb)
It Works Normally Like With Ads
link https://www.spotify.com/in-en/download/other/

**Comment by amd64fox** [comment]
delete your spotify as described in the [faq](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation)
then use this command line

```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -v 1.2.5.1006.g22820f93-1078 -confirm_spoti_recomended_over -block_update_on"
```

**Comment by Soldierocks** [comment]
Thanks For Your Help But Uhh Where Is The Now playing Button?
![image](https://github.com/amd64fox/SpotX/assets/94946357/8e2910c8-5113-4d4a-a75f-4d49d5cf8835)
It Used To Be There Before

**Comment by amd64fox** [comment]
I'm not sure that this panel was already there, but try it like this
```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -v 1.2.5.1006.g22820f93-1078 -confirm_spoti_recomended_over -block_update_on -new_theme"
```

**Comment by Soldierocks** [comment]
![image](https://github.com/amd64fox/SpotX/assets/94946357/b0048127-d311-4b47-9dcb-0f93f602e970)
While Installing This Thing Goes on For Like 5 mins

**Comment by amd64fox** [comment]
you enter the wrong value
y or n

**Comment by Soldierocks** [comment]
i entered n But it keeps looping

**Comment by amd64fox** [comment]
close and start again

**Comment by Soldierocks** [comment]
btw i used the bat file in the source and it worked well
thanks for your help

**Comment by Soldierocks** [comment]
Am A Discord Bot Dev Myself And I Have Never Met Someone So Concerned With Helping People
Hats Off Bro

**Comment by amd64fox** [comment]
we are not in the discord yet, there are not enough people for someone to take care of the server
