### ISSUE TITLE
Autoplay feature not working

### ISSUE THREAD

**Issue by GauravSamanta** [SpotX-Official/SpotX#473]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows (32 bit) 1.2.18.999.g9b38fc27
- Windows: Windows 11 22H2 22621.2134
- PowerShell: 5.1.22621.1778
```

### 📝 Description

1.
2.
3.
...

**Comment by amd64fox** [comment]
I am unable to reproduce the issue.
Please provide your steps to reproduce the problem.
Does this issue occur in the native client?

**Comment by GauravSamanta** [comment]
If i search a specific song and play it , after the song ends , this
feature is supposed to play similar songs automatically but it just ends
there only.

**Comment by amd64fox** [comment]
Is the autoplay option enabled in the settings? also, I didn't hear a response about checking the issue in the native client.

**Comment by GauravSamanta** [comment]
it is enabled and sorry i am not sure what do you mean by native client.

**Comment by amd64fox** [comment]
The native client is the original Spotify without SpotX. All of these actions are described in the FAQ at the very beginning, so I conclude that you haven't read it, even though you indicated otherwise.

I suggest engaging in careful reading, as it helps to avoid creating unnecessary issues in 99% of cases.
