### ISSUE TITLE
Stuck at installing Spotify

### ISSUE THREAD

**Issue by vanbang9710** [SpotX-Official/SpotX#475]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Vietnam

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Windows: Windows 10 Pro 21H2 19044.3086
- PowerShell: 7.3.6
```

### 📝 Description

1. uninstall Spotify with the [suggested script](https://raw.githubusercontent.com/amd64fox/Uninstall-Spotify/main/Uninstall-Spotify.bat)
2. Run the usual installation with command `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -new_theme"`

- It's stuck at installing Spotify ![image](https://github.com/amd64fox/SpotX/assets/52906188/ee7e821d-fba2-4cf8-af0c-8b3518eb8779)
- If I already installed Spotify, the script works fine

**Comment by amd64fox** [comment]
this happens sometimes with powershell
just run again after reboot

**Comment by vanbang9710** [comment]
Unfortunately It still doesn't work after shutting down my pc.

**Comment by amd64fox** [comment]
> Unfortunately It still doesn't work after shutting down my pc.

same problem or something new?

**Comment by vanbang9710** [comment]
yes, same problem

**Comment by amd64fox** [comment]
It's likely that something is disrupting the installation process of the script. There's a high probability that it's your AV causing this. Simply disable it during the installation process.

**Comment by vanbang9710** [comment]
Wait, so you must manually click the created .exe to install Spotify? ![|50pct](https://i.imgur.com/1CJx1NI.png)
In my opinion, it should be installed automatically like BlockTheSpot

**Comment by amd64fox** [comment]
script automatically installs Spotify

**Comment by vanbang9710** [comment]
This is weird. It's stuck at installing the script as I mentioned. After installing it manually through .exe, the script continues to install the patch
