### ISSUE TITLE
Language loading Error!

### ISSUE THREAD

**Issue by new4one** [SpotX-Official/SpotX#476]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Germany, Austria

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.5.1006.g22820f93-1078 <<<< from your download link.
- Windows 7 Sp1 64-Bit ESU
- PowerShell: 5.1.14409.1029 <<<< from your download link in the FAQ.
```

### 📝 Description

Gernan or Austrian Language is not Loading.

If you can´t fix the error can you send me the lastest pre-activatet version you have made in yout telegram channel for windows 7 Sp1 64-Bit to my e-mail : b639t@gmx.net.

I have not telegram so can you please do it for me, please. Thank you so much.

Friendly Regards. Björn

### 📸 Screenshots

![Error](https://github.com/amd64fox/SpotX/assets/143336834/6c05f62c-cad9-44bb-8ff8-af440451f94b)

**Comment by amd64fox** [comment]
just run again after reboot

**Comment by new4one** [comment]
Do you have fix it?!

**Comment by amd64fox** [comment]
> just run again after reboot

?

**Comment by new4one** [comment]
It just not work for me!

Please send me a pre patched version for windows 7 64.bit thank you so much.

I have tried this here also :

netsh int ip reset

netsh winsock reset

ipconfig /release6

ipconfig /release

ipconfig /flushdns

ipconfig /registerdns

ipconfig /renew6

ipconfig /renew

**Comment by amd64fox** [comment]
There's no need to ask for ready-made builds to be sent to your email. Currently, we only have one source with pre-patched builds, and that's Telegram. If you need it urgently, please register there and download them.

Regarding the patcher, a rollback was performed to raw.githubusercontent.com. Please try running the script again

**Comment by new4one** [comment]
I have fund the error i had.

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]'Tls11,Tls12' <<<< This helps me.

https://www.windowspro.de/tipp/invoke-webrequest-es-konnte-kein-geschuetzter-ssltls-kanal-erstellt-werden

Thank you so much for trying to help me out amd64fox.

**Comment by amd64fox** [comment]
Tls12 is already activated for everyone when you run the script using the command 
```ps1
[Net.ServicePointManager]::SecurityProtocol = 3072
```
The reason for this correction is in the raw GitHub link, but if you find it convenient to think that your TLS command resolved the issue, I'm fine with it.

**Comment by new4one** [comment]
Okey thank you as always.
