### ISSUE TITLE
Lyrics Button disappeared 

### ISSUE THREAD

**Issue by spyisme** [SpotX-Official/SpotX#478]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Egypt

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows (32 bit)
1.2.19.937.gf6e7cff9
- Windows: Windows 10 Pro 22H2 19045.3324
- PowerShell: Version
-------
```

### 📝 Description

1.
2.
3.
...

### 📸 Screenshots

![image](https://github.com/amd64fox/SpotX/assets/81018008/d1a22496-829e-43d6-b9f1-b8b024e17b45)

**Comment by amd64fox** [comment]
you didn't read the faq
