### ISSUE TITLE
Sidebars size doesn't save after restarting PC

### ISSUE THREAD

**Issue by Rasinzz** [SpotX-Official/SpotX#479]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.19.937.gf6e7cff9
- Windows: Windows 10 22H2 19045.3324
- PowerShell: 5.1.19041.3031
```

### 📝 Description

1. Resize the sidebars and restart your PC

You resize the sidebars (playlist/now playing) and it does not save how big/little you resized it too.

If you resize and restart your Spotify, it will save, but when you restart your PC, it does not save the size, and it goes back to the big/default size.

I would expect it to save whatever size I resized it too, and not change unless I changed it myself.

### BEFORE (what I resized it too):

![image](https://github.com/amd64fox/SpotX/assets/88259422/343c32b1-04d1-4a95-ad94-1fb6b24c031d)

## AFTER (I restarted my PC):

![image](https://github.com/amd64fox/SpotX/assets/88259422/935da3f1-75e3-45ae-be89-8ca315fb925a)

**Comment by amd64fox** [comment]
Before creating an issue, you are asked to read the FAQ and also complete the actions outlined in the [first question of the FAQ](https://telegra.ph/SpotX-FAQ-09-19#I-have-a-bug-/-strange-client-behavior,-what-can-I-do-?).

**Comment by Rasinzz** [comment]
Thanks, I've been dealing with this issue for a minute!

**Comment by amd64fox** [comment]
you didn't reply so i closed it, did it resolve after a clean install ?

**Comment by Rasinzz** [comment]
Just tried it and it still does it when I restart my PC.

I did the full uninstall in the FAQ and reinstalled using the **Usual installation (New Theme)**

For the install options I:
- disabled podcasts
- blocked updates
