### ISSUE TITLE
song lyrics option not showing

### ISSUE THREAD

**Issue by brxndonnn** [SpotX-Official/SpotX#480]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

South Africa

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: latest
- Windows: latest
- PowerShell: latest
```

### 📝 Description

1. as said in title
2.
3.
...

**Comment by amd64fox** [comment]
read FAQ
