### ISSUE TITLE
bug crash

### ISSUE THREAD

**Issue by thienphunguyen21** [SpotX-Official/SpotX#481]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

American

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.19.941
- Windows: Windows 10 Pro 20H2 19042.1466
- PowerShell: 5.1.19041.1320
```

### 📝 Description

1.Uninstall my old spotify by using clean uninstall spotify from readme.md
2.Open Install_New_theme.bat and wait until finish install spotify 1.2.19.941
3.Choose N and Y then the patch error like the image
  After the installation is complete, I can't log in to my account. I'm stuck at the login screen via the web even though the web has announced successful login. I tried logging in first and patching it later but it's just stuck. at the black screen

### 📸 Screenshots

![image](https://github.com/amd64fox/SpotX/assets/100543278/fad117b2-0bc5-4d4b-98ac-9abfa1d2ed30)
![image](https://github.com/amd64fox/SpotX/assets/100543278/e7b42bda-8f60-458c-882e-042dcfb12db3)
![image](https://github.com/amd64fox/SpotX/assets/100543278/c66aa23f-5a6f-40f1-9fe4-8f056caa86e1)
![image](https://github.com/amd64fox/SpotX/assets/100543278/0edd9c09-d7e6-4347-9e13-f3252ccde2a0)

**Comment by amd64fox** [comment]
do a [clean install](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation) again as described in the faq

**Comment by thienphunguyen21** [comment]
> do a [clean install](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation) again as described in the faq

yeah already like i said on my Description part

**Comment by amd64fox** [comment]
I meant for you to repeat this

**Comment by thienphunguyen21** [comment]
> I meant for you to repeat this

it's still the same

**Comment by amd64fox** [comment]
show on the screenshot what you have in the folder:
`AppData\Roaming\Spotify\Apps`

**Comment by thienphunguyen21** [comment]
> show on the screenshot what you have in the folder: `AppData\Roaming\Spotify\Apps`

![image](https://github.com/amd64fox/SpotX/assets/100543278/683c0719-832b-48f5-b405-0911c8985164)
this when download official and unpatched

**Comment by amd64fox** [comment]
nah, I wanted to see what's there after you use the patcher

**Comment by thienphunguyen21** [comment]
> nah, I wanted to see what's there after you use the patcher
![image](https://github.com/amd64fox/SpotX/assets/100543278/6ac783cb-725f-4158-a279-33832fea5fb2)
after patch it still same the xpui.spa just smaller

**Comment by amd64fox** [comment]
do you use AV? if so, try disabling it and perform a clean install of the patch again

also change the method of installing the patch instead of running the bat file, copy this line, open the powershell terminal and paste it there:
```ps1
[Net.ServicePointManager]::SecurityProtocol = 3072; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -new_theme"
```

**Comment by thienphunguyen21** [comment]
> do you use AV? if so, try disabling it and perform a clean install of the patch again
> 
> also change the method of installing the patch instead of running the bat file, copy this line, open the powershell terminal and paste it there:
> 
> ```powershell
> [Net.ServicePointManager]::SecurityProtocol = 3072; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -new_theme"
> ```

![image](https://github.com/amd64fox/SpotX/assets/100543278/9f2e01b0-e46f-4458-8263-c808fd55f0d4)
still there although turn off all av and run it with admin

**Comment by amd64fox** [comment]
hmm...
try performing a fresh clean installation with this file: 

- [completely Uninstall Spotify](https://github.com/amd64fox/Uninstall-Spotify) and restart your PC
- download [Install.zip](https://github.com/amd64fox/SpotX/files/12494751/Install.zip) and extract the file Install.ps1
- then right-click on it and choose the "Run with PowerShell" option

**Comment by thienphunguyen21** [comment]
> hmm... try performing a fresh clean installation with this file:
> 
> * [completely Uninstall Spotify](https://github.com/amd64fox/Uninstall-Spotify) and restart your PC
> * download [Install.zip](https://github.com/amd64fox/SpotX/files/12494751/Install.zip) and extract the file Install.ps1
> * then right-click on it and choose the "Run with PowerShell" option

![image](https://github.com/amd64fox/SpotX/assets/100543278/627821d4-251d-421a-877e-5926a239b793)
i dont think so

**Comment by amd64fox** [comment]
Most likely, something is wrong with your environment. There are two possible scenarios:

- You can download and install the pre-patched version from our [Telegram](https://t.me/SpotxCommunity/1049).
- You can update your Powershell to version 7 and try running the patch again.
- There's also a third option, where you can grant me remote access to your environment, but at the moment, I don't have the time to organize it, so it's better to choose one of the first two.
