### ISSUE TITLE
Lyrics button not showing in latest version

### ISSUE THREAD

**Issue by PizzaSpark** [SpotX-Official/SpotX#482]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [x] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Philippines

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.19.941.gbf202593
- Windows: Windows 10 Home Single Language Version	22H2
- PowerShell: 5.1.19041.3031
```

### 📝 Description

1. Open Spotify
2. Have lyrics button (mic logo) on the bottom left

### 📸 Screenshots

![image](https://github.com/amd64fox/SpotX/assets/108224418/eebda5c6-b827-4e63-8e3c-4da9cbdd2705)

What should be shown

![image](https://github.com/amd64fox/SpotX/assets/108224418/2bb1f2c5-d5be-415f-be42-a3861061b78a)

**Comment by amd64fox** [comment]
read FAQ
