### ISSUE TITLE
Installing the premium version of SpotX removes the lyrics button

### ISSUE THREAD

**Issue by kymerea** [SpotX-Official/SpotX#486]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Australia

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows (64 bit) 1.2.19.941.gbf202593
- Windows: Version 22H2 (OS Build 22621.2215)
- PowerShell: 5.1.22621.1778
```

### Steps to reproduce
1. Install the SpotX premium version found [here](https://raw.githack.com/amd64fox/SpotX/main/scripts/Install_Prem.bat)
2. No lyrics button when playing songs that have lyrics.

### How I confirmed this is an issue with SpotX:
1. On open.spotify.com, there is a lyrics button.
2. Completely uninstalling Spotify and SpotX and install the normal SpotX (`Install_New_theme.bat`) the lyrics button appears.

**Comment by kymerea** [comment]
Would also like to say that installing SpotX with the `-old_lyrics` parameter does bring back the button but as the lyric button is just in the normal version (non-SpotX) and normal spotx version, it is still somewhat of a bug.

**Comment by kymerea** [comment]
### Side-by-side comparison of web ver and SpotX install with params
![image](https://github.com/amd64fox/SpotX/assets/62679764/2da08faf-6ec7-4b53-bfd7-c1150b460645)
Even with the params, it's still not the correct lyrics tab.

### Here is Spotify desktop without the param showing the correct lyric tab
![image](https://github.com/amd64fox/SpotX/assets/62679764/8e8e7f5e-a1f0-4fac-988c-6da455d139af)

**Comment by amd64fox** [comment]
The new Spotx theme comes with new lyrics by default. If you need the old ones, as you've already mentioned, you should use `-old_lyrics` The screenshot with the dark background for lyrics is a custom theme, you installed the automatic full installation or used the `-lyrics_stat` parameter. 

Your installation string for Spotx is: 
```ps1
[Net.ServicePointManager]::SecurityProtocol = 3072; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -premium -new_theme -old_lyrics"
```
before installation, do not forget to perform a clean installation as indicated in the FAQ.

**Comment by kymerea** [comment]
As I said in my original comment, if you install SpotX with the premium params, the lyrics button is completely gone. I will see if removing the `-lyrics_stat` and keeping `-old_lyrics` fixes it. 

I still believe using the premium params removes the lyrics button.
