### ISSUE TITLE
unable to see lyrics on spotx spotify client 

### ISSUE THREAD

**Issue by N0tBLUE** [SpotX-Official/SpotX#490]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

india

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.20.1210.g2a8a8a57
- Windows: windows 11 22H2 22621.2215
- PowerShell: 5.1.22621.1778
```

### 📝 Description

1.uninstalled by the bat file provided by amd64fox - [here](https://github.com/amd64fox/Uninstall-Spotify)
2.installed spotx spotify client from this repo [spotx repo](https://github.com/amd64fox/SpotX)
3.launched and logged in spotify 
tried this multiple times with spicefy and all still unable to see lyrics please help me through this asap 
tried old and new releases of spotx as well 

### 📸 Screenshots

![image](https://github.com/amd64fox/SpotX/assets/74755694/d88f1a89-2153-4bc2-891c-7c9932f80c95)

**Comment by amd64fox** [comment]
I have no idea how Spicetify currently works with version 1.2.20, so install SpotX without it after completely uninstalling Spotify using the patch from the FAQ

Also in your screenshot there is no installed SpotX

**Comment by N0tBLUE** [comment]
> I have no idea how Spicetify currently works with version 1.2.20, so install SpotX without it after completely uninstalling Spotify using the patch from the FAQ
> 
> Also in your screenshot there is no installed SpotX

already tried 
still the same issue

**Comment by N0tBLUE** [comment]
> I have no idea how Spicetify currently works with version 1.2.20, so install SpotX without it after completely uninstalling Spotify using the patch from the FAQ
> 
> Also in your screenshot there is no installed SpotX

my bad here is the screenshot of spotx 
![image](https://github.com/amd64fox/SpotX/assets/74755694/ae436a60-fdba-4a7f-b589-83bd95272c5a)

no spicefy 
version 1.2.13.661.ga588f749-4064

**Comment by amd64fox** [comment]
what does your command look like that you use to install SpotX?

**Comment by N0tBLUE** [comment]
> what does your command look like that you use to install SpotX?

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -confirm_uninstall_ms_spoti -version 1.2.13.661.ga588f749-4064 -podcasts_off -block_update_on -start_spoti -old_lyrics -rightsidebar_off -lyrics_stat blueberry"

**Comment by N0tBLUE** [comment]
i wanna mention one more thing that when i play songs from spotify web i facing the same issue as app 
![image](https://github.com/amd64fox/SpotX/assets/74755694/eeb59792-24e2-41b3-ae12-6b723e55c778)

**Comment by amd64fox** [comment]
I couldn't reproduce the error,
looks like a server problem with Spotify, [create a problem here](https://community.spotify.com/t5/Desktop-Windows/bd-p/desktop_windows)
naturally without mentioning SpotX

**Comment by N0tBLUE** [comment]
> I couldn't reproduce the error, looks like a server problem with Spotify, [create a problem here](https://community.spotify.com/t5/Desktop-Windows/bd-p/desktop_windows) naturally without mentioning SpotX

my friend told me that they are testing lyrics only for premium maybe thats the issue ?

[news](https://www.bing.com/news/search?q=Spotify+Testing+Lyrics+For+Premium&qpvt=spotify+testing+lyrics+for+premium&FORM=EWRE)

[spotify community ](https://community.spotify.com/t5/Social-Random/Recent-update-and-premium-restrictions/m-p/5633994)

**Comment by amd64fox** [comment]
yes, they are now testing song lyrics in two regions, these are Italy and India, your account must also be free and be included in the sample of tested accounts

but you don't have obvious signs of restriction, they should look like this:

![Снимок экрана 2023-09-10 123613](https://github.com/amd64fox/SpotX/assets/62529699/653832f9-fc8b-41f1-b2f6-50713afcb056)

most likely just a network bug

**Comment by N0tBLUE** [comment]
> yes, they are now testing song lyrics in two regions, these are Italy and India, your account must also be free and be included in the sample of tested accounts
> 
> but you don't have obvious signs of restriction, they should look like this:
> 
> ![Снимок экрана 2023-09-10 123613](https://user-images.githubusercontent.com/62529699/266827510-653832f9-fc8b-41f1-b2f6-50713afcb056.png)
> 
> most likely just a network bug

actually i am from India so maybe spotx blocking this pop up and i am unable to see the lyrics

**Comment by amd64fox** [comment]
What does SpotX have to do with it if you have the same situation in your web player?

**Comment by N0tBLUE** [comment]
> What does SpotX have to do with it if you have the same situation in your web player?

true 
but maybe host file if spotx uses host file to block ads ??

**Comment by amd64fox** [comment]
nah 
I told you what to do, don’t invent problems out of the blue

**Comment by N0tBLUE** [comment]
> nah I told you what to do, don’t invent problems out of the blue

okay fine but do you know any work around for this issue ?
any help would be appreciated :))

**Comment by amd64fox** [comment]
> but maybe host file if spotx uses host file to block ads ??

if your hosts file was changed by another program or by you personally, then delete it or clear it

or

use [this](https://github.com/amd64fox/SpotX/issues/490#issuecomment-1712763647)

in any case not a problem SpotX, good luck
