### ISSUE TITLE
the images in the home menu don't work

### ISSUE THREAD

**Issue by lechatdeschats** [SpotX-Official/SpotX#491]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

France

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: Spotify pour Windows (32 bits) 1.2.20.1210.g2a8a8a57
- Windows: Windows 11 Professionnel 22H2 22621.2215
- PowerShell: 5.1.22621.1778
```

### 📝 Description

the images in the home menu don't work

### 📸 Screenshots

![image](https://github.com/amd64fox/SpotX/assets/125388873/e8265419-4436-4e60-8a23-40a6a6e44815)

**Comment by amd64fox** [comment]
not related to SpotX, temporary problem on Spotify servers
