### ISSUE TITLE
smart shuffle button appears with spicetify but doesn't work

### ISSUE THREAD

**Issue by AkinaRulez** [SpotX-Official/SpotX#492]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

united states

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.20.1216.ge7a7b92f
- Windows: cant do that on a bootcamp 2015 MacBook would need a different explanation
- PowerShell: 5.1.19041.3031
```

### 📝 Description

1. so at first i downloaded spotx on my macbook and it had the smart shuffle feature. then spotify updated the button was gone and all the songs i had added from smart shuffle where also gone.
2. then i later switched to windows on my macbook downloaded the windows version thinking it would have the smart shuffle feature and it didnt.
3. after that i came to report issue saw the spicetify download, downloaded that enabled smart shuffle button and the button appears but doesent smart shuffle. it just shuffles the songs in my playlist as normal, and yes i skipped a bunch of songs testing it
...

### 📸 Screenshots

![smart shuffle issue](https://github.com/amd64fox/SpotX/assets/145064033/d1b4aea2-608f-429c-8595-b36dce80ea16)

**Comment by amd64fox** [comment]
`enableSmartShuffle` has been disabled for Spotx Windows for quite some time, and it was recently done for Spotx Bash. Currently, this experiment is not running stably. We will enable it as soon as they complete debugging it.

**Comment by AkinaRulez** [comment]
when do you think it will be enabled? like an estimated time

**Comment by amd64fox** [comment]
we are not Spotify developers, as soon as they fix this exp we will immediately enable it

**Comment by AkinaRulez** [comment]
now im having issues with the premium. i've redownloaded and fully deleted it over 12 times and it wont give me prem

**Comment by AkinaRulez** [comment]
thank you
