### ISSUE TITLE
lyrics dont show

### ISSUE THREAD

**Issue by Pluzas** [SpotX-Official/SpotX#496]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

tunisia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.20.1218.g02aff7a4
- Windows: windows 10
- PowerShell: 5.1.19041.3031
```

### 📝 Description

1. bro the lyrics show up on certain songs only and when i uninstall the mod i can see the lyrics on free plan
2.
3.
...

### 📸 Screenshots

![image](https://github.com/amd64fox/SpotX/assets/62484611/b4ae83df-aa0b-4c4a-bc83-c4539b37f87c)

**Comment by amd64fox** [comment]
example of a song in which you see lyrics without spotx?

Also, you show the bottom panel in the screenshot, but in the new theme, the song lyrics have moved to the right side panel. This is mentioned in the FAQ that you indicated as read. So what's the matter?

**Comment by Pluzas** [comment]
> example of a song in which you see lyrics without spotx?
> 
> Also, you show the bottom panel in the screenshot, but in the new theme, the song lyrics have moved to the right side panel. This is mentioned in the FAQ that you indicated as read. So what's the matter?

that's not entirely true, while uninstalling spotX i had the lyrics button right between the now playing and the queue buttons, installing spotX removed it and moved it to the now playing right panel, but that's not the point of my post, example of a song that has lyrics 100% but can't see em on spotX is location by carti, poppin by yeat, and much more.
![image](https://github.com/amd64fox/SpotX/assets/62484611/63f53332-667b-4595-8c93-5cc9e396157c)

![image](https://github.com/amd64fox/SpotX/assets/62484611/cfcd11f1-2577-4ed7-8562-fdbfd47caac8)

**Comment by demirage2** [comment]
Similar issue on old-theme client. May have something to do with Spotify gatekeeping the lyrics to premium?
![image](https://github.com/SpotX-Official/SpotX/assets/101514099/93468bd1-bc7f-4636-8358-66f8f20bdefa)
[Relevant article I found](https://gizmodo.com/spotify-tests-making-lyrics-a-premium-only-feature-1850807657)

**Comment by amd64fox** [comment]
In the songs listed above, there is no lyrical content. It's possible that they were recently removed, and they were there before. This is not related to SpotX. Additionally, some gaps in lyrics may be related to testing limitations on displaying lyrics for free users. If you don't see song lyrics in any of the songs, then you have entered this testing group.

**Comment by MachoMan1988** [comment]
Is it possible to add Lyrics Plus?

**Comment by KaleidoscopicPrism** [comment]
for me lyrics only show up on one album but no other albums that i've played

**Comment by Pluzas** [comment]
i have lyrics rn, im not in no testing group, its just that some hits have no lyrics that previously did, like the songs i gave u, for example the newest mac demarco song has lyrics, location by carti doesn't.

**Comment by PaulGitProject** [comment]
Hey, any update on that issue? I need to open the player in full screen to see the microphone icon

**Comment by PwccaCode** [comment]
This issue is still present is not a problem of the song not having lyrics, since a few versions ago the problem started for me too.

The song has a lyric but the microphone icon is missing and can only be seen after acessing the fullscreen player

I add screenshots to make it more clear.

![missing1](https://github.com/SpotX-Official/SpotX/assets/51799102/284a4837-91ad-405b-a79d-d479dbccbfd0)
![missing2](https://github.com/SpotX-Official/SpotX/assets/51799102/c4af2d6d-b872-4b19-b140-f30788962ed3)
![missing3](https://github.com/SpotX-Official/SpotX/assets/51799102/db52c343-c5b5-4274-a2af-f14684844201)


But after clicking the mic icon in fullscreen the lyrics start working perfectly fine. im pretty sure this started happening after 1.9.x
since i had it working properly back then.

**Comment by Pluzas** [comment]
Only some songs have lyrics for me, and many more that used to do says "Hmm. We don't know the lyrics for this one." now, example : 
![image](https://github.com/SpotX-Official/SpotX/assets/62484611/b873d676-d955-47a1-83ef-1a444fa280f1)

![image](https://github.com/SpotX-Official/SpotX/assets/62484611/770d7ad6-d106-42d5-9f2f-b4f4563d3b01)

im using old theme.

**Comment by vteeha** [comment]
have the same behavior as @PwccaCode. Basically no button to show lyrics in normal mode, and yet have it in full screen

**Comment by amd64fox** [comment]
> Basically no button to show lyrics in normal mode, and yet have it in full screen

maybe you should read the [FAQ](https://telegra.ph/SpotX-FAQ-09-19#Why-can%60t-I-find-lyrics?) first?
