### ISSUE TITLE
Text bugging.

### ISSUE THREAD

**Issue by Spinoscythe** [SpotX-Official/SpotX#498]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United Kingdom

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: the absolute latest
- Windows: 11
- PowerShell: 7.3.6
```

### 📝 Description

1. Use Automatic Full Installation.

### 📸 Screenshots
![image](https://github.com/amd64fox/SpotX/assets/84230130/c825256b-acb4-4029-a624-6703f50aac0b)

_No response_

**Comment by amd64fox** [comment]
Thanks, I didn't notice that, there are issues with the new card style
