### ISSUE TITLE
Not sure

### ISSUE THREAD

**Issue by brxndonnn** [SpotX-Official/SpotX#501]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

South Africa

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: latest
- Windows: 10 Single language
- PowerShell: latest
```

### 📝 Description

1. not sure
2.
3.
...

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/103594572/7cca56c8-06b3-4c8d-8632-950e77f2cca2)

**Comment by jacob-thanh** [comment]
The new commit [Install.ps1 to run.ps1](https://github.com/SpotX-Official/SpotX/commit/16d99113da53077af708d332afad4fb2957d172b) change the Install.ps1 to run.ps1
I think download that run.ps1 directly from this repo you can install it.
