### ISSUE TITLE
Error loading en language

### ISSUE THREAD

**Issue by reddddddzzzzz** [SpotX-Official/SpotX#502]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Canada

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.21.1104.g42cf0a50
- Windows: Edition	Windows 11 Home
Version	22H2
Installed on	‎2023-‎04-‎11
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0

- PowerShell: 5.1.22621.1778
```

### 📝 Description

1. when I open either bat file (install new or old theme) it shows me this error
2.
3.
...

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/113384940/3dcdb249-9513-46c8-9d9f-ba8dfaf044a6)

**Comment by reddddddzzzzz** [comment]
Nevermind how do i close this i fixed it

**Comment by amd64fox** [comment]
Hi, how did you fix this?

**Comment by reddddddzzzzz** [comment]
this was a previous issue remember you fixed it issue 287

**Comment by reddddddzzzzz** [comment]
thats why i closed it but i didn't fix it
