### ISSUE TITLE
Constrained Language Mode

### ISSUE THREAD

**Issue by reddddddzzzzz** [SpotX-Official/SpotX#503]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Canada

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.21.1104.g42cf0a50
- Windows: Edition	Windows 11 Home
Version	22H2
Installed on	‎2023-‎04-‎11
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0

- PowerShell: 5.1.22621.1778
```

### 📝 Description

(I closed my previous issue, thinking that issue #287's response would help me. However, it didn't so that's why I'm putting this issue back up again)

1. I downloaded the latest zip of spot x and extracted it using  7 zip and then if I open either bat file (install_new_theme.bat or install_old_theme.bat) it gives me this error. i did do a clean install of spotify too.
2. i did trying using a VPN because it was a solution for issue 287 but i don't know how to do "change DNS from ISP default"
3. i think mine is slightly different from issue 287 because i have this red text but it doesn't show for them

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/113384940/b7dc6688-a5f5-4f68-90f2-b45ec00b58ca)

**Comment by reddddddzzzzz** [comment]
also yes the vpn didnt help

**Comment by amd64fox** [comment]
- Open the Powershell console and enter the following command:
```ps1
$ExecutionContext.SessionState.LanguageMode
```
- send response

**Comment by reddddddzzzzz** [comment]
ConstrainedLanguage

**Comment by amd64fox** [comment]
enter the commands into the console one by one and show their response:

```ps1
[Net.ServicePointManager]::SecurityProtocol = 3072
```
```ps1
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor [System.Net.SecurityProtocolType]::Tls12
```
```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

```

**Comment by reddddddzzzzz** [comment]
![image](https://github.com/SpotX-Official/SpotX/assets/113384940/9e5b8f33-692f-4635-a141-088d6482e897)

**Comment by amd64fox** [comment]
ok, then try this first
```ps1
Set-ExecutionPolicy RemoteSigned -Force
```

then [this](https://github.com/SpotX-Official/SpotX/issues/503#issuecomment-1743681165) again

**Comment by reddddddzzzzz** [comment]
![image](https://github.com/SpotX-Official/SpotX/assets/113384940/b35f5f89-f59f-4779-9ceb-c2668a48745f)

I did and then still didn't do anything

**Comment by amd64fox** [comment]
try this
```ps1
$ExecutionContext.SessionState.LanguageMode = "FullLanguage"
```
and this

```ps1
[Net.ServicePointManager]::SecurityProtocol = 3072
```

**Comment by reddddddzzzzz** [comment]
Both didn't do anything
![image](https://github.com/SpotX-Official/SpotX/assets/113384940/c6890e5d-81a4-4d54-86fd-c48366476e2b)

**Comment by amd64fox** [comment]
```ps1
(Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment')
```

**Comment by reddddddzzzzz** [comment]
Its ok I have fixed this issue. For anyone in the future wondering how to do this, you search "View advanced system settings" in the search bar. Click environment variables on the bottom right. There should be user variables and system variables. There should be a variable called "__PSLockdownPolicy" under system variables. You should change the value to 8. Dont forget to press ok and then ok again to save changes Doing so will make it so your powershell comes with full language because constrained language brings some errors with SpotX. If you don't see the __PSLockdownPolicy variable, you should make it yourself by clicking New (under system variables of course don't do it under user variables I don't know if it makes a difference. Name it __PSLockdownPolicy and set the value to 8 and click ok and then ok again to save changes. Basically what the error is it can't load the en language because the powershell is set to Constrained Language.  Changing the variable of PSLockdownPolicy will make it so your powershell is full language and it will fix your error. Hope this helps. More information here: https://cyberark.my.site.com/s/article/language-mode-error

**Comment by reddddddzzzzz** [comment]
Thanks for helping me
