### ISSUE TITLE
Script not connecting to the internet

### ISSUE THREAD

**Issue by Doomelf** [SpotX-Official/SpotX#504]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Bulgaria

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.21.1104.g42cf0a50
- Windows: 10 22H2 19045.2965
- PowerShell: 5.1.19041.2673
```

### 📝 Description

Wasn't having any issues before. Decided to make a clean install of windows and suddenly got this screen when I ran the script. Same thing happens, regardless if I use a command or .bat file. The strange part is my internet connection works as expected for everything else.

### 📸 Screenshots

![1](https://github.com/SpotX-Official/SpotX/assets/12450654/9137ebdc-f573-45d6-bd48-2f5db7092335)

**Comment by amd64fox** [comment]
strange, show your output when you run this code in the powershell console:

```ps1
$pingServers = @("www.google.com", "www.microsoft.com", "www.apple.com", "www.ibm.com", "www.baidu.com")
$maxRetryCount = 3

for ($retry = 1; $retry -le $maxRetryCount; $retry++) {
    foreach ($server in $pingServers) {
       Test-Connection -ComputerName $server -Count 1
  
    }
    }
```

**Comment by N0tBLUE** [comment]
me neither it isnt connecting

**Comment by N0tBLUE** [comment]
![image](https://github.com/SpotX-Official/SpotX/assets/74755694/869b2d7f-5e50-491d-84f0-c80c0f60b55f)
not moving ahead

**Comment by Doomelf** [comment]
![2](https://github.com/SpotX-Official/SpotX/assets/12450654/5316de1c-37d3-4589-abdf-1e3ed443383d)

**Comment by amd64fox** [comment]
if this

```ps1
ping www.google.com
```

**Comment by Doomelf** [comment]
![3](https://github.com/SpotX-Official/SpotX/assets/12450654/dfedaa20-c44a-48c0-8742-cbbeb57cf42c)

**Comment by amd64fox** [comment]
try it

```ps1
$pingServers = @("www.google.com", "www.microsoft.com", "www.apple.com", "www.ibm.com", "www.baidu.com", "www.yandex.ru")
$maxRetryCount = 3

for ($retry = 1; $retry -le $maxRetryCount; $retry++) {
    foreach ($server in $pingServers) {
        try {
            Test-Connection -ComputerName $server -Count 1 -ErrorAction Stop
        } catch {
            $errorMessage = $_.Exception.Message
            Write-Host "Error pinging $($server): $($errorMessage)"
        }
    }
}
```

**Comment by Doomelf** [comment]
![1](https://github.com/SpotX-Official/SpotX/assets/12450654/10050866-32c6-4a3b-8473-9e11097a9497)

**Comment by amd64fox** [comment]
check if these sites open in your browser

**Comment by Doomelf** [comment]
Each opened just fine. www.11google.com didn't open first time, but on 2nd try opened http://ww12.11google.com/

**Comment by amd64fox** [comment]
lol, this was corrected a couple of seconds later on www.google.com

**Comment by amd64fox** [comment]
I suspect this is a problem with your firewall or av, you can disable this while running the test code above

**Comment by Doomelf** [comment]
I'm running a clean install version right now. Don't have anything changed in firewall or anywhere else. No windows updates installed or any programs aside from spotify. Doubt it's the cause since was working just fine up until this happened, but could resetting my router settings help? Also, is there a way to disable built in firewall?

**Comment by amd64fox** [comment]
just a reminder, windows has its own av and firewall
 
 also show what the command outputs:
 ```ps1
Get-ExecutionPolicy; $ExecutionContext.SessionState.LanguageMode
 ```

**Comment by Doomelf** [comment]
![1](https://github.com/SpotX-Official/SpotX/assets/12450654/742af238-f78e-4da6-9c3e-9243950bb1b9)

**Comment by Doomelf** [comment]
Disabled the 3 parts of windows firewall and the virus and threat protection settings in windows defender and previous code didn't change results.

**Comment by amd64fox** [comment]
something is blocking icmp requests, it could be anything - software, a router, your internet service provider, or possibly an issue with your environment. If possible, try testing in a different network or on another computer. In any case, at the moment, it's not a problem with SpotX, except for cases of widespread complaints.

**Comment by Doomelf** [comment]
Will reset router settings and see if that helps. If can't fix it am thinking of using the old script and hope it blocks spotify ads. Editing the hosts file wouldn't get me banned, right?
[Host Block.txt](https://github.com/SpotX-Official/SpotX/files/12785937/Host.Block.txt)

**Comment by Doomelf** [comment]
In my router settings had enabled "Ignore Ping Packet From WAN Port" and "Forbid Ping Packet From LAN Port". After clearing the boxes everything was fixed. The script ran as normal and the things you sent me to check above also worked. Was able to run the script previously with those boxes ticked so not sure why suddenly stopped working. Btw, was using the old script:

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1' | Invoke-Expression

**Comment by amd64fox** [comment]
alright, the old script didn't employ internet connectivity checks, whereas the new one does, so, the issue you encountered arose when using the new script. 

perhaps, later on, I'll add an alternative for ICMP requests

thank you for the information.

**Comment by Doomelf** [comment]
Thanks for the help :)
