### ISSUE TITLE
Invoke-WebRequest : 404: Not Found, Spot-x cmd window error

### ISSUE THREAD

**Issue by vkansxl** [SpotX-Official/SpotX#505]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

No

### Computer information

```markdown
- Spotify: 1.2.20.1218.g02aff7a4 
- Windows: Windows 10 version 22H2 19045.3448
- PowerShell: 5.1.19041.3031
```

### 📝 Description

1.  I download the zip file of spotx-main 
2. i extract it there
3. i open "install new theme" and it shows error
image provided
it shows the same error with 
"install new theme"
"install old theme"
"install auto"
i expected it to ask me questions about my preferences as i was listening to music and suddenly my side "now playing view" stops working. i close the app and restart it and it shows spotify is not able to respond.
i uninstall the mod 
then i reinstall it but it doesn't work

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/147214399/47d2380c-45ae-4c79-8fb5-52f5c8518f23)

![image](https://github.com/SpotX-Official/SpotX/assets/147214399/47caceae-2f91-41a6-bb8b-153206e59b6c)

**Comment by amd64fox** [comment]
you should update the bat file

**Comment by vkansxl** [comment]
> you should update the bat file

already tried it

**Comment by vkansxl** [comment]
> you should update the bat file

how?

**Comment by amd64fox** [comment]
https://raw.githack.com/amd64fox/SpotX/main/Install_New_theme.bat

**Comment by vkansxl** [comment]
> https://raw.githack.com/amd64fox/SpotX/main/Install_New_theme.bat

already tried this , same error

**Comment by amd64fox** [comment]
screenshot

**Comment by vkansxl** [comment]
> screenshot

nvm it worked, Microsoft firewall was blocking it

**Comment by melissis** [comment]
I had to use the latest bat from the files, not the latest release. Fixed it.
