### ISSUE TITLE
The underlying connection was closed could not establish trust relationship for the ssl/tls

### ISSUE THREAD

**Issue by Rxlm** [SpotX-Official/SpotX#506]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [ ] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Philippines

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: None (Cant Install)
- Windows: 11 pro 22H2
- PowerShell: 5.1
```

### 📝 Description

1.I have tried all the installation files (Old theme, New theme, Auto) and they all return with the same error.
2. The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
3.Tried this on all 3 of my computers on my network but no luck, I already had this installed on my PC before I upgraded to windows 11.
4. I saw a previously similar problem, but the fix was already deleted (404 not found on github).
...

### 📸 Screenshots

![Screenshot_1](https://github.com/SpotX-Official/SpotX/assets/147603491/7f9ed0a6-f6c2-4a99-9cb3-5bc5b484f946)

**Comment by jblanc88** [comment]
I'm also having this issue.

**Comment by amd64fox** [comment]
If we look at your screenshot, you're likely running the command not from a batch file but from the PowerShell console. 

Please show the complete command you're entering

**Comment by jblanc88** [comment]
I ran mine from the batch file and this is the error I get
![image](https://github.com/SpotX-Official/SpotX/assets/31604547/d2b7621c-2142-4015-8700-a15bfb1a0dc9)

**Comment by amd64fox** [comment]
@jblanc88
a completely different issue is being discussed here, read the FAQ or look at previous resolved issues

**Comment by Rxlm** [comment]
> If we look at your screenshot, you're likely running the command not from a batch file but from the PowerShell console.
> 
> Please show the complete command you're entering

Copied this from the full installation

![image](https://github.com/SpotX-Official/SpotX/assets/147603491/bc4e1707-f2ba-42be-b9ac-5f80b5c1cad1)

**Comment by amd64fox** [comment]
Does one of the following commands work for you?

```ps1
iex "& { $(iwr -useb 'https://spotx-official.github.io/run.ps1') } -new_theme"
 ```
or
```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $(iwr -useb 'https://spotx-official.github.io/run.ps1') } -new_theme"
```

**Comment by Rxlm** [comment]
thanks for the reply.

1st:
![1ST](https://github.com/SpotX-Official/SpotX/assets/147603491/c92d36f7-f7a1-4cb7-8252-797ed105d8bf)



2nd:
![2ND](https://github.com/SpotX-Official/SpotX/assets/147603491/d42ce0a6-1d08-4c6d-b11f-8e7b601897e2)

tried both.

**Comment by amd64fox** [comment]
- `Win + R` => `inetcpl.cpl`
- `Advanced` tab
- send a screenshot

**Comment by Rxlm** [comment]
> * `Win + R` => `inetcpl.cpl`
> 
>     * `Advanced` tab
> 
>     * send a screenshot

Here:

![1](https://github.com/SpotX-Official/SpotX/assets/147603491/9426bf93-9f0a-4cef-b08d-81ef11b4201a)
![2](https://github.com/SpotX-Official/SpotX/assets/147603491/3069b24c-1119-48f4-9ed2-9d9b208bcc46)
![3](https://github.com/SpotX-Official/SpotX/assets/147603491/b7ede897-cd3c-453b-afbf-44caf06d7a56)
![4](https://github.com/SpotX-Official/SpotX/assets/147603491/cb04a30a-b15c-499f-9df6-91decfe38b7f)

**Comment by Rxlm** [comment]
For some reason its now working. I haven't changed anything at all.

**Comment by amd64fox** [comment]
It's obvious that the problem is on your end, either it's a network (provider) issue or an issue with your operating system. 

For now, this will be closed.

**Comment by rubby-c** [comment]
For anyone else experiencing this, it seems to be a DNS issue. After changing my DNS server to 1.1.1.1 (Cloudflare) the problem was gone.
