### ISSUE TITLE
Windows 7 ESU Support for 1.2.22.xxx

### ISSUE THREAD

**Issue by darkalexis1990** [SpotX-Official/SpotX#507]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Greece

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 
- PowerShell:
```

### 📝 Description

1.Can you add support for Windows 7 ESU and 8.1?? Thank you.
2.Spotify versions 1.2.22.xxx

**Comment by amd64fox** [comment]
It’s strange that you are asking this question here, and not to the official client developers

I don't plan to do this.

**Comment by darkalexis1990** [comment]
too pity,bye.
