### ISSUE TITLE
The system cannot execute the specified program

### ISSUE THREAD

**Issue by Manibalan27** [SpotX-Official/SpotX#508]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

india

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows (64 bit)
1.2.22.982.g794acc0a
- Windows:Edition	Windows 10 Pro
Version	22H2
Installed on	‎27-‎09-‎2020
OS build	19045.3448
Experience	Windows Feature Experience Pack 1000.19044.1000.0
 
- PowerShell: 5.1.19041.3031
```

### 📝 Description

1.
2.
3.
...

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/147843128/f63efc2f-b8a6-4bb3-a034-f1e014213b14)

**Comment by amd64fox** [comment]
Your PowerShell environment variable is broken, which is beyond Spotx support. You'll need to resolve this on your own or consult Google for assistance.

Additionally, you can run the script directly from the PowerShell terminal:

- Press Win + R, then type "powershell"
- Execute the following command:
```ps1
[Net.ServicePointManager]::SecurityProtocol = 3072; iex "& { $(iwr -useb 'https://spotx-official.github.io/run.ps1') } -new_theme"
```

**Comment by Manibalan27** [comment]
![Screenshot (304)](https://github.com/SpotX-Official/SpotX/assets/147843128/dd7bb539-6de4-48b9-9813-a639690cc0dd)
