### ISSUE TITLE
Shuffle Turns off After Manually Selecting a Song

### ISSUE THREAD

**Issue by AliGFarhat** [SpotX-Official/SpotX#509]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United Arab Emirates

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows (64 bit) 1.2.22.982.g794acc0a
- Windows: Windows 11 Home (10.0.22000 Build 22000)
- PowerShell: 5.1.22000.2538
```

### 📝 Description

1. Turn Shuffle On
2. Select a song to play manually
3. Then the shuffle turns off and you have to re-enable
...

**Comment by amd64fox** [comment]
I can't reproduce this issue, please record your screen while reproducing this problem.

**Comment by AliGFarhat** [comment]
> I can't reproduce this issue, please record your screen while reproducing this problem.

Found out the problem is only happening in the New theme, not the old one. (v1.8)

**Comment by AliGFarhat** [comment]
> I can't reproduce this issue, please record your screen while reproducing this problem.


https://github.com/SpotX-Official/SpotX/assets/148215223/81ea0916-72cd-4953-84db-7e24fc0743b3

**Comment by AliGFarhat** [comment]
I've gone through the FAQ and I installed while windows defender is disabled and it fixed it

**Comment by amd64fox** [comment]
fixed
