### ISSUE TITLE
Spotify won't install

### ISSUE THREAD

**Issue by Henkkkkkk** [SpotX-Official/SpotX#51]
Whenever I try to install with the command this error shows up:
![image](https://user-images.githubusercontent.com/87282156/171470279-55dfcb4e-f556-489b-bd9b-6bf7ea35a9fa.png)
and then it opens the documents folder.
Do you have any idea on how to solve this?
Thanks

**Comment by amd64fox** [comment]
Thanks for the feedback, I tried to fix this error.
