### ISSUE TITLE
spotify cant play this right now.if you have this file on your computer u can import it

### ISSUE THREAD

**Issue by Manibalan27** [SpotX-Official/SpotX#510]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

india

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: - Spotify: Spotify for Windows (64 bit) 1.2.22.982.g794acc0a
- Windows: Windows 11 Home (10.0.22000 Build 22000)
- PowerShell: 5.1.22000.2538
```

### 📝 Description

1.issue inside the app
2.
3.
...

### 📸 Screenshots

![Screenshot (304)](https://github.com/SpotX-Official/SpotX/assets/147843128/ebe07844-f0cc-493f-9d6e-945692ff4a29)

**Comment by HDTS1** [comment]
I have this bug too, is there a workaround?
