### ISSUE TITLE
Antivirus false positive suggestion

### ISSUE THREAD

**Issue by htrshtsr** [SpotX-Official/SpotX#512]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Germany

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 
- PowerShell:
```

### 📝 Description

Kaspersky and multiple other antivirusses detect SpotX as a virus.

How to fix this:

Instead of using "%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe" in the installation batch file, simply use "powershell". You need to check if the script is being run as admin tho.
Here would be the final script(Install_New_theme.bat):

@echo off
NET SESSION >nul 2>&1
IF %ERRORLEVEL% EQU 0 (
    powershell.exe -Command "&{[Net.ServicePointManager]::SecurityProtocol = 3072}; """"& { $(Invoke-WebRequest -UseBasicParsing 'https://spotx-official.github.io/run.ps1')} -new_theme """" | Invoke-Expression"
) ELSE (
    ECHO RUN AS ADMINISTRATOR!
)
pause
exit /b

**Comment by htrshtsr** [comment]
[Install_New_theme.txt](https://github.com/SpotX-Official/SpotX/files/13062987/Install_New_theme.txt)
Rename this to .bat

**Comment by amd64fox** [comment]
You don't necessarily need to run the SpotX patcher with elevated administrator privileges, and the *.bat file itself doesn't cause any [issues with av](https://www.virustotal.com/gui/file/fa7ff9975dce1fc26987f6457ee9ef5e9a9fbe4d21b68a34941343f5cb00651e). If you're experiencing problems, it's a false positive from your av. Add it to the exclusion list as described in the FAQ, which you ignored
