### ISSUE TITLE
New install removed a feature.

### ISSUE THREAD

**Issue by Aki65RU** [SpotX-Official/SpotX#513]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Ireland

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.13.661.ga588f749
- Windows: Windows 10 22H2 19045.3570
- PowerShell: 5.1.19041.3570
```

### 📝 Description

My lyrics weren't working for a little while so i decided to redownload SpotX (old-theme.bat is the only one i use) But once it reinstalled it got rid of the the cool song info and artist info that was on the right side.
It did fix the lyrics issue but I'm still annoyed it got rid of the side bar.
I had all of those on the old theme now theyre both gone? should have i just stuck without lyrics or is there now a toggleable option to add the right info bar back? 
If so I'd like that alot thanks.

### 📸 Screenshots

screenshot showing the button for the side bar gone. 
![image](https://github.com/SpotX-Official/SpotX/assets/129411243/6af0bf5b-537c-4369-adad-053f006cec31)

**Comment by amd64fox** [comment]
In the old theme, the right sidebar was never enabled by default, but you can activate it yourself using [this instruction](https://github.com/SpotX-Official/SpotX/discussions/47). You need to enable the exp with the name `enableRightSidebar`

**Comment by Aki65RU** [comment]
thx a bunch! i found some other cool options in there i liked aswell.
