### ISSUE TITLE
Shuffle button doesn't work

### ISSUE THREAD

**Issue by Ema420** [SpotX-Official/SpotX#515]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [x] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Italy

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.23.1125.g920a7ada
- Windows: Windows 11 Pro 22H2 22621.1702
- PowerShell: 5.1.22621.963
```

### 📝 Description

1. The Shuffle button doesn't work, both the button in the playback bar and the button in the playlist page
2. when i click it, the button turn in green but doesn't work
3. I tried to install an older version of spotify with the parameter "-version" but it still doesn't work
4. the only solution to fix it, after reading the issue of Deleorium posted on Jul 20 2023 #463, is: go to up right to the three dots and activate the shuffle there and it work. 

### 📸 Screenshots

![Immagine 2023-10-26 020340](https://github.com/SpotX-Official/SpotX/assets/81303769/2671c428-d810-411e-a02d-9d8dfe6c7827)
![1](https://github.com/SpotX-Official/SpotX/assets/81303769/1e8e2f8d-38ee-43c9-bb9e-7e5c11fec1fd)

**Comment by amd64fox** [comment]
not reproducible, try a clean installation from the faq

**Comment by theaniketraj** [comment]
Just install afresh. Should work fine.

**Comment by Ema420** [comment]
i just unistall spotify with the "unistall-spotify.bat" and reinstall it with "install-new-theme.bat" as the faq described but it still doesn't work. 
i will continue to use the keyboard shortcut to activate it. i hope there is another fix besides this one.
thanks by the way

**Comment by amd64fox** [comment]
It is possible that this is a temporary server bug for your account, it is possible that it will resolve itself, you can also contact Spotify's official support.

**Comment by Vantanay** [comment]
My shuffle button is also not working, ive tried uninstalling and reinstalling spotify and it still isnt working

**Comment by Fallenwastaken** [comment]
My shuffle button wouldn't work either, I've also tried a clean install as described in faq. I also tried the fix that was shown in a previous post

**Comment by amd64fox** [comment]
try completely uninstalling Spotify and installing the [latest version](https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.23.1125.g920a7ada-925.exe) without SpotX. 

Will you still experience this issue?

**Comment by Nickolatte** [comment]
Shuffle works but when exit the spotify app, shuffle is disabled

**Comment by alunefrye** [comment]
Shuffle doesnt work at me aswell. Tried clean installation. It was workin before patch but its not workin after patch.

**Comment by rarewaifu** [comment]
hello i just wanted to chime in as well that its not working for me neither despite doing a fresh reinstall, the shuffle option does work if i dont install the SpotX patch, but once i apply it the ads are gone but the shuffle doesnt work

**Comment by Mrbennyboi** [comment]
everything else works for me but the enhanced feature doesn't show up for me anymore when i installed the newest version. i have done a clean install multiple times and it still doesn't show up

**Comment by amd64fox** [comment]
Thank you all for your feedback. To determine if SpotX is the root cause of this error 100%, I need a couple of logs from the client. For those who have encountered this error, please follow the steps below:

1. Perform a [clean installation](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation) ([this version ](https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.23.1125.g920a7ada-925.exe)of the client must be installed) of SpotX as described in the FAQ and restart your computer.

2. Log in to the client and make sure you are still experiencing the shuffle error. If the error is gone, your testing is complete, thanks.
3. Access DevTools using the [following instructions](https://github.com/amd64fox/Enable-devtools-Spotify)

   <details>
   <summary>3.1. Obtain the remoteExp log</summary>
   
      https://github.com/SpotX-Official/SpotX/assets/62529699/3a840cd5-1a07-40ec-83c6-968a4c3d5465

    </details>
    
    
    <details>
    <summary>3.2. Obtain the productState log</summary>
    
      https://github.com/SpotX-Official/SpotX/assets/62529699/34021d05-0a6f-4cfe-bcea-289065e6f3bc

     </details>
 

4. Save these logs as separate text files with their respective names and upload them here.

**Comment by csjey** [comment]
I got that bug too. Here there are the text files: 

1. [productState.txt](https://github.com/SpotX-Official/SpotX/files/13221842/productState.txt)

2. [remoteExp.txt](https://github.com/SpotX-Official/SpotX/files/13221843/remoteExp.txt)

**Comment by amd64fox** [comment]
@jeysoncc 

Thank you, I've checked your logs and didn't notice anything unusual. Could you please record your screen while reproducing the shuffle-related error? 

also, you can try using the `-EnhanceSongs` parameter to install Spotx. This parameter disables smart shuffling and enables playlist and liked songs enhancement in the latest versions.

**Comment by csjey** [comment]
@amd64fox Fixed adding that parameter. Thank you.

**Comment by spotifyshuffle** [comment]
my shuffle, too, does not work. very annoying

**Comment by amd64fox** [comment]
as we have established above, a small percentage of users encounter a problem with shuffling. This happens because spotx, by default, activates smart shuffle.

The temporary solution to this issue is to use the `-EnhanceSongs` parameter, which disables smart shuffle and brings back the old feature for enhancing playlists and liked tracks

**Comment by amd64fox** [comment]
a new build [1.2.24](https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.24.756.g7a7fc7f0-1487.exe) has been released, which may solve the problem with shuffling
or 
just update Spotx to the recommended version

can someone confirm this?

**Comment by spotifyshuffle** [comment]
> a new build [1.2.24](https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.24.756.g7a7fc7f0-1487.exe) has been released, which may solve the problem with shuffling, can someone confirm this?

yes, thank god. i have shuffle finally

**Comment by spotifyshuffle** [comment]
i just got a pop-up ad....

![2023-11-08 06_38_29-Spotify Free](https://github.com/SpotX-Official/SpotX/assets/149895608/e7392a2a-2152-4492-bb2e-dc4a00218c64)

**Comment by amd64fox** [comment]
> i just got a pop-up ad....

you're strange, it's probably worth patching this native build or do you think that I'm posting a pre-patched build on the Spotify servers?

**Comment by pedrojuliogc** [comment]
Good morning, now it works, thanks for the update.

**Comment by spotifyshuffle** [comment]
> > i just got a pop-up ad....
> 
> you're strange, it's probably worth patching this native build or do you think that I'm posting a pre-patched build on the Spotify servers?

im strange? for reporting a pop up? are you alright?

**Comment by dabignerd** [comment]
Just reinstalled with a clean installation. Seems to be working. Thanks for the update.

**Comment by Ema420** [comment]
With the new version of spotify the bug is fixed, thanks everyone
