### ISSUE TITLE
Enhance Liked Songs Patch no longer working

### ISSUE THREAD

**Issue by Panther7170** [SpotX-Official/SpotX#516]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.23.1125.g920a7ada
- Windows: Windows 11 22H2 22621.248
- PowerShell: 5.1.22621.2428
```

### 📝 Description

1. Launch Spotify with new version
2. Open liked song playlists
3. Notice the Enhance playlist button has completely disappeared.
This was working in the previous Spotify version which leads me to believe this is a recent regression.

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/125446389/0cba2bcb-ca96-4f1f-86d2-6e2f6dbca4ac)

**Comment by amd64fox** [comment]
Now, by default, smart shuffle is enabled. If you need to enhance the playlist and liked songs, use the installation parameter `-EnhanceSongs`

but keep in mind that EnhanceSongs may not work correctly in the latest versions.
