### ISSUE TITLE
Lyrics

### ISSUE THREAD

**Issue by Veolinan** [SpotX-Official/SpotX#517]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [x] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Kenya

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 
- PowerShell:
```

### 📝 Description

I could not get lyrics button

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/104050582/f85198c9-8c43-437c-9209-ab65fb3dbe00)

**Comment by amd64fox** [comment]
you decided not to read the faq and ask for the 99th time a question that has already been asked? a wise decision
