### ISSUE TITLE
SPOTIFY CANT PLAY THIS RIGHT NOW.IF YOU HAVE THE FILE ON YOUR COMPUTER YOU CAN IMPORT IT.

### ISSUE THREAD

**Issue by Manibalan27** [SpotX-Official/SpotX#518]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

india

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows (64 bit)
1.2.22.982.g794acc0a
- Windows: Edition	Windows 10 Pro
Version	22H2
Installed on	‎27-‎09-‎2020
OS build	19045.3448
Experience	Windows Feature Experience Pack 1000.19044.1000.0

- PowerShell: 5.1.19041.3031
```

### 📝 Description

SPOTIFY CANT PLAY THIS RIGHT NOW.IF YOU HAVE THE FILE ON YOUR COMPUTER YOU CAN IMPORT IT.

### 📸 Screenshots

![Screenshot (305)](https://github.com/SpotX-Official/SpotX/assets/147843128/00d8f91d-3bd8-4aca-b819-26b949c393dc)

**Comment by Manibalan27** [comment]
PLEASE HELP ME

**Comment by amd64fox** [comment]
you would have helped yourself a long time ago if you just read what they ask you for
