### ISSUE TITLE
"Now Playing" Lyrics doesn't work.

### ISSUE THREAD

**Issue by bearye5** [SpotX-Official/SpotX#519]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Spain

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: Spotify for macOS (Apple Silicon)1.2.23.1125.g920a7ada
- Windows: 
- PowerShell:
```

### 📝 Description

1. The "Now Playing Button" just doesn't appear.
2.
3.
...

### 📸 Screenshots

<img width="612" alt="Screenshot 2023-11-06 at 12 35 15 p m" src="https://github.com/SpotX-Official/SpotX/assets/150023413/6f5889c9-a8f3-4848-aad6-31ce1fabba7d">

**Comment by amd64fox** [comment]
you don't read the FAQ

lyrics should be in the right sidebar

also this is a repo for windows
