### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by revepastrop** [SpotX-Official/SpotX#52]
## ℹ Computer information

- Spotify version: 1.1.86.857 (or rather : none since it can't download it)
- Plan Spotify: free 
- Windows version: 7 SP1
- PowerShell version: 5.1

## 📝 Description of the problem

running the install always returns the same error when trying to download spotify :  "could not resolve host : upgrade.scdn.co"
it just stops there

![Image 001](https://user-images.githubusercontent.com/93463821/171853200-34f915ed-af3c-47c9-b612-eab08b64f4b4.png)

**Comment by amd64fox** [comment]
I'm on vacation, I'll come back in a month and fix it

**Comment by amd64fox** [comment]
Is this error still happening to you?

This error is most likely related to your network connection or its special settings.

**Comment by revepastrop** [comment]
for the record it's stll happening, those upgrade.scn.co just won't resolve, it's not behind any firewall/enterprise stuff, pretty much standard home fiber, no vpn/proxy either... "workaround" was to wait for spotify installer to catch up then, so the script didn't have to dld...
ps : googling tells me this shit happens w/ plenty spotify users for years, sometimes also comes with the desktop player skipping most songs... oh well

**Comment by amd64fox** [comment]
I did a test to disable downloading via curl, can you try to run the following line directly through powershell and report if there is a similar error?

```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/Test/main/test.ps1').Content) } -curl_off"
```

**Comment by amd64fox** [comment]
It seems to be related to the file host, check it
- `Win + R`
- `%WinDir%\System32\Drivers\Etc`
- Run the `hosts` file as administrator and remove all URLs from it

**Comment by revepastrop** [comment]
haha, spot on, totally forgot about those old days of hosts editing, must have put the upgrade adresses there around 2014 ^^
