### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by Lxidel** [SpotX-Official/SpotX#523]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

sweden

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows (32 bit)
1.2.24.756.g7a7fc7f0
- Windows: windows 11 version idk
- PowerShell: 5.1.22621.2428
```

### 📝 Description

when i wanna search for a song it dosent show up anything it says no results found and tells me to add more key words 
sometimes when i lets say i go to home and than i type like s to see if it works it works but only in like that letter catogory but when lets say i remove the s and i type and I its just goes back to no results found and than i end up in and loop of nothing shows up even if i would go back to the letter that did work that would also now not work i have reinstalled spotify and fully removed everything even from my local folder reinstalled the newest spot x everything nothing seems to work and im not sure what causes it so i need help (ps). i just found out that my sptoify instalastion is a 32-bit verison of spotify idk if that has to do about anything but yeah

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/150601868/c3d14cca-1e62-4dea-8d33-6e075fa9b72f)

**Comment by itsmeorestis** [comment]
I'm having this problem as well

**Comment by amd64fox** [comment]
Spotify backend problem

PS
Looks like it's fixed, check it out

**Comment by itsmeorestis** [comment]
> Spotify backend problem
> 
> PS Looks like it's fixed, check it out

all ok now
