### ISSUE TITLE
Can't play Spotify Group Session?

### ISSUE THREAD

**Issue by ErSatrio** [SpotX-Official/SpotX#524]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Indonesia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows (64 bit) 1.2.24.756.g7a7fc7f0
- Windows: Windows 11 22H2 22621.2428
- PowerShell: 5.1.22621.2428
```

### 📝 Description

1. Spotify Group Session is a feature where a user can invite other users to listen together in a group session
2. It should be able to be accessed through the "device" button in the bottom right corner of the spotfiy client. But the SpotiX version doesn't have the optino to "start session"
3.

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/88559953/6cc486e2-cef0-485d-8724-710375139851)
No option to start session 

![image](https://github.com/SpotX-Official/SpotX/assets/88559953/3c705ec9-85fb-4cb5-894c-855368d5d70f)
The example from the web found here said it should be like that.
https://www.businessinsider.com/guides/streaming/spotify-group-session#:~:text=A%20group%20session%20can%20feature,your%20own%20Spotify%20Group%20Session.

**Comment by amd64fox** [comment]
Group sessions are available only for premium users, this is stated in the article you linked to, but it seems you only got to the pictures.

**Comment by ErSatrio** [comment]
I've misunderstood then. I thought SpotX worked like Vanced, where it unlocks premium content. Beg your pardon.
