### ISSUE TITLE
Didn't find variable error

### ISSUE THREAD

**Issue by BGR2** [SpotX-Official/SpotX#526]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Turkey

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.13.661
- Windows: Windows 10 22H2 (19045.3570)
- PowerShell: 5.1.19041.3570
```

### 📝 Description

1. Started Installer (old)
2. Waited 12 or more seconds
3. Errors started to pop up saying "Didnt find variable "
4. Said "setup complete" and pressed the space key.

**Comment by amd64fox** [comment]
yeah, I checked now, there are problems with some patches for old versions

**Comment by amd64fox** [comment]
fixed
