### ISSUE TITLE
Local files not working

### ISSUE THREAD

**Issue by obeys** [SpotX-Official/SpotX#527]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.25.1011
- Windows: Windows 10
- PowerShell: 5.1.19041.3693
```

### 📝 Description

1. After turning on local files in Spotify settings a file called local-files.bnk is generated in spotify's app data folder
2. The file has a bunch of unreadable bullshit in there, not sure if its intended
![image](https://github.com/SpotX-Official/SpotX/assets/131892818/e37806c1-e08f-4194-a02a-23cd72b6729a)
3. Local files are not showing up in spotify as well
...

**Comment by amd64fox** [comment]
If your local files aren't displaying, it's likely the client couldn't find them using standard paths. Add an additional path in the settings.
