### ISSUE TITLE
I'm integrating Spotify SpotX to xbox. It's not a bug. I just need help

### ISSUE THREAD

**Issue by EdwardDK** [SpotX-Official/SpotX#528]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

America

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 
- PowerShell:
```

### 📝 Description

So, here I need help. Basically, I finished everything but to test and download I need a certificate. I would be thankful if someone DMed me their certificate in this format: 
![image](https://github.com/SpotX-Official/SpotX/assets/73299061/6d29f7e4-5a1c-4991-a395-10dc13625255)

On discord: .eddy47

Thankyou,

**Comment by amd64fox** [comment]
You chose a rather strange place to receive certificate.

**Comment by EdwardDK** [comment]
Yeah true, its jsut most .pfx are expensive. I'm just trying to promote spotx to xbox users. @amd64fox

**Comment by EdwardDK** [comment]
I have the file made. To deploy and test further I need the certificate.

**Comment by amd64fox** [comment]
reverse engineering does not require certificates

**Comment by EdwardDK** [comment]
You need a certificate deploy it and run it. I need to sign it in order to run.
