### ISSUE TITLE
Lyrics in now playing don't scroll properly. 

### ISSUE THREAD

**Issue by RorgiCorgi** [SpotX-Official/SpotX#529]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.25.1011.g0348b2ea
- Windows: Windows 11 22H2 22621.2715
- PowerShell: Get-Host | Select-Object Version
```

### 📝 Description

1. Open now playing tab.
2. Open lyrics (lyrics will scroll)
3. Hover over the lyrics  with mouse and move it away. They'll suddenly stop scrolling on their own. The white highlight moves down but it won't scroll down. If you hover again the lyrics will jump to the proper place and scroll again, but if you move your mouse it'll stop auto scrolling. 
4. Close now playing and reopen and it'll work fine (until you hover again)
...

**Comment by amd64fox** [comment]
This is the native behavior of lyrics in the right sidebar, it needs debugging from Spotify developers. 

Also, you can revert to old song lyrics using the parameter `-old_lyrics`
