### ISSUE TITLE
Premium Accounts

### ISSUE THREAD

**Issue by setmetatable** [SpotX-Official/SpotX#53]
I have a Spotify premium account. But I want to use SpotX for some of the QoL features. Can I still use it?
(I see that "Upgrade" shows in the top right when signed in but it allows me to download music. I assume it will work?)

**Comment by amd64fox** [comment]
There are plans to make for premium users

**Comment by setmetatable** [comment]
I actually forgot about this issue, your reply reminded me. I've been using it since I made this issue and I've experienced no big problems with using SpotX, downloads work, I can go offline. It's been pretty good.

One issue is with the `Upgrade` button still being visible, but it's not something that urgently needs fixing.

Updating/installing SpotX will override downloaded songs and it will have to re-download them upon starting Spotify after updating/installing. That would be something nice to have fixed.

I'll leave it up to your discretion for if you want to keep this issue open.

**Comment by amd64fox** [comment]
Now I'm testing the installation for premium accounts, for those who want to participate, delete Spotify if you have it and run the following line in the PowerShell terminal
```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-Expression "& { $(Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/amd64fox/Test/main/test.ps1') } -Premium"
```

**Comment by amd64fox** [comment]
Added support for premium accounts, a bug was also fixed in which downloaded songs were deleted when installing the client over.

**Comment by setmetatable** [comment]
Great news! Thank you for all your work!
