### ISSUE TITLE
Spotify is Broken

### ISSUE THREAD

**Issue by taser-laser** [SpotX-Official/SpotX#531]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Canada

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows (64 bit)
1.2.25.1011.g0348b2ea
- Windows: Windows 11 23H2 Dev build 23590.ni_prerelease.231110-1455
- PowerShell: 5.1.23590.1000
```

### 📝 Description

1. have no spotify
2.get spotx with spotify being auto installed
3. delete spotify 
4. and now spotify is bricked cannot play albums cannot load custom playlist
...

### 📸 Screenshots

![Screenshot 2023-11-30 193718](https://github.com/SpotX-Official/SpotX/assets/152571783/0d787649-a125-4901-8105-5626314cae4f)
![Screenshot 2023-11-30 193821](https://github.com/SpotX-Official/SpotX/assets/152571783/cfaaf178-fe14-400a-a20d-7164ed17c44c)

**Comment by taser-laser** [comment]
spotfiy is completely bricked and broken cannot do anything

**Comment by amd64fox** [comment]
In the first FAQ item, a list of actions is presented that you need to use and provide an answer
