### ISSUE TITLE
Spotify no longer auto updating

### ISSUE THREAD

**Issue by kymerea** [SpotX-Official/SpotX#534]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Australia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Any
- Windows: 23H2 22631.2792
- PowerShell: 5.1.22621.2506
```

### 📝 Description

Whenever I install SpotX, Spotify refuses to show any updates. For example:
1. Install an outdated version of Spotify
2. Install SpotX ensuring you **do not** update Spotify and say 'No' to `Want to block Spotify updates? [Y/N]:`
3. Check Spotify install for any updates- none will appear. 

I have noticed this with several versions of Spotify now, I've ensured that Spotify Updates are enabled, yet they still seem to be blocked.

**Comment by amd64fox** [comment]
Hi, there was indeed a mistake, thank you for your vigilance, everything should be fine now
