### ISSUE TITLE
'Plus' feature broken

### ISSUE THREAD

**Issue by kymerea** [SpotX-Official/SpotX#535]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Australia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.26.1180.g6af55bfb
- Windows: Windows 11 23H2 22631.2792
- PowerShell: 5.1.22621.2506
```

### 📝 Description

I understand that the plus feature is marked as experimental in your docs, but I believe it's been fully implemented into Spotify. Currently using the `-Plus` flag it shows all songs being liked/added in the bottom left corner with none of the songs being liked/added in the playlist view - only the song with the cursor on it shows it as being liked/added.

This all could just be a big misinterpretation of this feature, if so please forgive me.

### 📸 Screenshots

![Screenshot 2023-12-06 002218](https://github.com/SpotX-Official/SpotX/assets/62679764/d6b0652e-bb20-468c-8d80-dfb7596df47f)

https://github.com/SpotX-Official/SpotX/assets/62679764/30a04b98-3b30-4a9c-8c45-37be0204eac8

**Comment by amd64fox** [comment]
Unfortunately, this is the new native logic for displaying likes for the plus feature 😢
