### ISSUE TITLE
Reopening issue about lyrics

### ISSUE THREAD

**Issue by PwccaCode** [SpotX-Official/SpotX#537]
This issue is still present is not a problem of the song not having lyrics, since a few versions ago the problem started for me too.

The song has a lyric but the microphone icon is missing and can only be seen after acessing the fullscreen player

I add screenshots to make it more clear.

![missing1](https://github.com/SpotX-Official/SpotX/assets/51799102/284a4837-91ad-405b-a79d-d479dbccbfd0)
![missing2](https://github.com/SpotX-Official/SpotX/assets/51799102/c4af2d6d-b872-4b19-b140-f30788962ed3)
![missing3](https://github.com/SpotX-Official/SpotX/assets/51799102/db52c343-c5b5-4274-a2af-f14684844201)

But after clicking the mic icon in fullscreen the lyrics start working perfectly fine. im pretty sure this started happening after 1.9.x
since i had it working properly back then.

_Originally posted by @PwccaCode in https://github.com/SpotX-Official/SpotX/issues/496#issuecomment-1852869210_

**Comment by amd64fox** [comment]
didn't read the [FAQ](https://telegra.ph/SpotX-FAQ-09-19#Why-can%60t-I-find-lyrics?)
