### ISSUE TITLE
Invoke-WebRequest : 404: Not Found

### ISSUE THREAD

**Issue by PandxonPC** [SpotX-Official/SpotX#538]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Germany

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows (64 bit)
1.2.26.1187.g36b715a1 
- Windows: Win 10
- PowerShell: 5.1.19041.3693
```

### 📝 Description

1. when i start the install it shows Invoke-WebRequest : 404: Not Found
2.
3.
...

### 📸 Screenshots

![Screenshot 2023-12-14 152019](https://github.com/SpotX-Official/SpotX/assets/153837630/6238544f-6776-4c45-ad57-3af2e30c0107)

**Comment by amd64fox** [comment]
on the main page of the repo there is a description of the current installation
