### ISSUE TITLE
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. At line:1 char:12

### ISSUE THREAD

**Issue by Gamer550** [SpotX-Official/SpotX#539]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Bulgaria

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.26.1187.g36b715a1-269
- Windows: Windows 11 Pro 23H2 22631.2861
- PowerShell: 5.1.22621.2506
```

### 📝 Description

1.I reinstalled clean my windows 11 
2.It was working fine before then
3.
...

### 📸 Screenshots

![SPOTX](https://github.com/SpotX-Official/SpotX/assets/81639870/d07189e2-168c-4def-97d7-40be04319db6)

**Comment by amd64fox** [comment]
- `Win + R` => `inetcpl.cpl`
- `Advanced` tab
- send a screenshot

**Comment by untoor** [comment]
@Gamer550 Today i installed latest version (the one i used was released beginning of this year) using this powershell-method without using admin rights, and it worked.

**Comment by amd64fox** [comment]
probably, this is a specific issue with some modified builds of Windows 11, but since this guy is not responding, I'll close it.
