### ISSUE TITLE
Add SpotX to the Scoop installer

### ISSUE THREAD

**Issue by TechPro424** [SpotX-Official/SpotX#54]
## 📝 Description of the idea

Scoop (https://scoop.sh/) is a command line installer for Windows which does things like:
1. Eliminating permission popup windows
2. Hiding GUI wizard-style installers
3. Finding and installing dependencies automatically 
and a lot more.

I request you to add SpotX to the Scoop installer so Scoop users can use it, and to keep it compatible with the Scoop installation of Spotify.

(spicetify-cli is also on Scoop btw)

**Comment by azumukupoe** [comment]
winget and choco as well?

**Comment by amd64fox** [comment]
I have no experience of adding, I need to study the documentation, there is no time for this yet.

If someone is ready to help with this, then I do not mind.

While temporarily open...

**Comment by NeoFoxxo** [comment]
I will look into adding it to scoop

**Comment by NeoFoxxo** [comment]
So this is the app manifest file I have made for scoop (This explains what the app is and how to install it). Once the user types `scoop install spotx` it will download and run the install.bat file. If the user types  `scoop update` it will also check if there is a new version of SpotX to install.
{
    "version": "1.2",
    "description": "Blocks ads and updates for the desktop version of Spotify and more.",
    "homepage": "https://github.com/amd64fox/SpotX/",
    "license": "MIT License",    
    "url": "https://github.com/amd64fox/SpotX/releases/download/1.2/Install.bat", 
    "post_install": "Start-Process -FilePath $env:USERPROFILE\\scoop\\apps\\spotx\\1.2\\Install.bat",
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/amd64fox/SpotX/releases/download/v$version/Install.bat"    
    }  
} 
Is there anything I should change before I submit it to the public scoop repository?

**Comment by amd64fox** [comment]
> Is there anything I should change before I submit it to the public scoop repository?

Yes, there are questions, but can't you immediately use `Install.ps1` instead of `Install.bat` to start the installation in Scoop?

This file is also used to launch and update SpotX, it is possible to specify its url https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1
both in autoupdate and in normal installation?

and also this .ps1 accepts incoming parameters, can they be specified when installing from Scoop ?

**Comment by NeoFoxxo** [comment]
Ok so I switched to the powershell file and used parameters so the install is now fully automated. But autoupdate would not work since the ps1 file is not in the release. The autoupdate works by checking the github release version number. Yes I could download the source code but that would take longer than just installing the powershell script. 
{
    "version": "1.2",
    "description": "Blocks ads and updates for the desktop version of Spotify and more.",
    "homepage": "https://github.com/amd64fox/SpotX/",
    "license": "MIT",    
    "url": "https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1", 
    "post_install": "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex \"& { $((iwr -useb 'https:\/\/raw.githubusercontent.com\/amd64fox\/SpotX\/main\/Install.ps1').Content) } -confirm_uninstall_ms_spoti -confirm_spoti_recomended_over -podcasts_off -cache_off -block_update_on -start_spoti\"",
    "checkver": "github",
    "autoupdate": {
        "url": "https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1"    
    }  
} 
So could you include the Install.ps1 file in the release?

**Comment by amd64fox** [comment]
Ohh, let's go back to the first option then, it's probably the easiest.
The `Install.bat` installer will run without additional parameters.

```json
{
    "version": "1.2",
    "description": "Blocks ads and updates for the desktop version of Spotify and more.",
    "homepage": "https://github.com/amd64fox/SpotX/",
    "license": "MIT License",
    "url": "https://github.com/amd64fox/SpotX/releases/download/1.2/Install.bat",
    "post_install": "Start-Process -FilePath $env:USERPROFILE\scoop\apps\spotx\1.2\Install.bat",
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/amd64fox/SpotX/releases/download/v$version/Install.bat"
    }
}
```
By the way, maybe it's better to use the latest version in `url` or is it not possible?
https://github.com/amd64fox/SpotX/releases/latest/download/Install.bat

**Comment by NeoFoxxo** [comment]
Alright I think this is good. The release latest will work well and I made it so the bat file is executed inside the powershell window and that it doesn't open up another window.
{
    "version": "1.2",
    "description": "Blocks ads and updates for the desktop version of Spotify and more.",
    "homepage": "https://github.com/amd64fox/SpotX/",
    "license": "MIT",
    "url": "https://github.com/amd64fox/SpotX/releases/latest/download/Install.bat",
    "post_install": "cd $env:USERPROFILE\\scoop\\apps\\spotx\\1.2\\; .\\Install.bat",
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/amd64fox/SpotX/releases/download/v$version/Install.bat"
    }
}

**Comment by amd64fox** [comment]
Okay, then will you send this?

**Comment by NeoFoxxo** [comment]
Yup. I'll send it now

**Comment by amd64fox** [comment]
@NeoFoxxo 
By tested the installation, it works well, thank you very much for doing this.
I noticed by the way a small bug, at the end of the installation, the shortcut is removed from the desktop, then I saw the line in the manifest:
```json
"Remove-Item \"$([Environment]::GetFolderPath('Desktop'))\\Spotify.lnk\""
```
Did it get there by accident?)

**Comment by amd64fox** [comment]
> shortcut is removed from the desktop

Fixed

**Comment by JourneyOver** [comment]
Just a note but since you changed the repository url, you (or well anyone who wants to) should probably think about sending a PR to https://github.com/ScoopInstaller/Nonportable to fix up the spotx-np.json file otherwise it's going to just continue running into issues like:

![10-06-2022_10-33-51](https://user-images.githubusercontent.com/13910285/194356081-3587026b-0cdf-4153-89b0-767b976fd839.png)

**Comment by JourneyOver** [comment]
@amd64fox looks like there is another issue of sorts going on with spotx in scoop, not sure exactly on what broke it this time around though... 
![12-25-2022_17-08-17](https://user-images.githubusercontent.com/13910285/209484145-8d9eaee2-5735-4cb2-bc64-995db849257e.png)

From the looks of things it started about 3 weeks ago (on Dec 5th)

**Comment by amd64fox** [comment]
@JourneyOver 
to be honest, I don't see the point in fixing something there, there have been no commits from real Contributions in this repo for 2 months, try to create a issue there when they get back to work maybe they will solve it.

**Comment by JourneyOver** [comment]
@amd64fox I mean I don't use nonportables buckets anyways I have my own buckets that I use (and have spotx in my bucket as well). 

Was running into the same issue in my bucket that is going on on nonportables buckets so just thought I'd report the issue, but I'm thinking about changing up how the versioning is done in my bucket in the near future anyways for spotx so it doesn't run into anymore issues like this anymore, just need to figure out how exactly I am going to do that xD

**Comment by e-t-l** [comment]
Is SpotX still on Scoop? Searching for it, I only see spotx-np, which it looks like is unmaintained. 

If it's not currently in the main public spotx bucket, it looks like someone else might have created their own bucket for it, which users can add manually to their Scoop installation? see: https://github.com/Ast3risk-ops/spotx-bucket
