### ISSUE TITLE
Windows Anti-virus detecting a trojan virus

### ISSUE THREAD

**Issue by Titi68730** [SpotX-Official/SpotX#543]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [x] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

France

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: /
- Windows: Processor AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx 2.30 GHz
Installed RAM 8.00 GB (5.88 GB usable)
Device ID 18E83E73-54AA-4025-8769-52F443288EF1
Product ID 00325-96597-99570-AAOEM
System type 64-bit operating system, x64 processor
Stylus and touch functionality Touch or stylus input functionality is not available on this screen.

- PowerShell: 5.1.22621.2506
```

### 📝 Description

I'm making this report because there's nothing about the current app detected from the anti-virus you know.
1. Open the app from the taskbar when it's full closed (no spotify task running)
2. Error : C:\Users\titch\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User
Pinned\TaskBar\Spotify.Ink
Unable to complete the operation, because the file contains a virus or software
potentially undesirable.
3. And then when I go to see what type of "virus" it is, it says : Trojan:Win32/Bearfoos.A!ml
Alert level: Serious
Status : Active
Date : 12/23/2023 15:57
Category: Trojan Horse
Details: This program is dangerous and it executes commands
emanating from a malicious person.
(I'm giving you screenshots but they're in french.)

### 📸 Screenshots

![ApplicationFrameHost_NHf73AuGYN](https://github.com/SpotX-Official/SpotX/assets/98215346/9b56c4e0-ee99-496e-9c94-f5632826665c)
![ApplicationFrameHost_o6549x3lrl](https://github.com/SpotX-Official/SpotX/assets/98215346/7d901713-67f7-46bf-b792-a1b0b3891f8f)
![ApplicationFrameHost_OCQin5V1qy](https://github.com/SpotX-Official/SpotX/assets/98215346/81134c07-246d-4950-b8c2-374782a8df6b)
![ApplicationFrameHost_WombGuOWR7](https://github.com/SpotX-Official/SpotX/assets/98215346/63f3b933-fc45-4cb5-a6da-e14b19875b27)

**Comment by amd64fox** [comment]
false positive, read faq
