### ISSUE TITLE
Error occured while installing spotify

### ISSUE THREAD

**Issue by What-Zit-Tooya** [SpotX-Official/SpotX#545]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Singapore

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Not installed
- Windows: Windows 10 21H2 19044.3803
- PowerShell: 5.1.19041.3803
```

### 📝 Description

I get error while installing spotify. See screenshot below

### 📸 Screenshots

![error](https://github.com/SpotX-Official/SpotX/assets/9832875/a2e53d9b-6fdc-44c6-b568-1ed8bb5cff76)

**Comment by amd64fox** [comment]
Most likely, this is related to your username, can you show it?

**Comment by What-Zit-Tooya** [comment]
> Most likely, this is related to your username, can you show it?

I put `WZT ALL` in my computer username.
There is space and all in uppercase letter.
So, the full path is `C:\Users\WZT ALL\`

**Comment by amd64fox** [comment]
Execute these two commands sequentially in the PowerShell terminal and show the result:
- Push-Location -LiteralPath $env:TEMP
- Push-Location -LiteralPath "$env:TEMP"

**Comment by What-Zit-Tooya** [comment]
>     * Push-Location -LiteralPath $env:TEMP
> 

```
PS C:\Windows\system32> Push-Location -LiteralPath $env:TEMP
Push-Location : An object at the specified path C:\Users\WZTALL~1 does not exist.
At line:1 char:1
+ Push-Location -LiteralPath $env:TEMP
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Push-Location], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.PushLocationCommand
```

>     * Push-Location -LiteralPath "$env:TEMP"
>

```
PS C:\Windows\system32> Push-Location -LiteralPath "$env:TEMP"
Push-Location : An object at the specified path C:\Users\WZTALL~1 does not exist.
At line:1 char:1
+ Push-Location -LiteralPath "$env:TEMP"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Push-Location], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.PushLocationCommand
```

Are they used to store temporary files? If so, why not using `%temp%` directory instead?

**Comment by amd64fox** [comment]
no, `%temp%` is used in cmd

try this command
```ps1
Push-Location -LiteralPath ([System.IO.Path]::GetTempPath())
```

**Comment by What-Zit-Tooya** [comment]
> no, `%temp%` is used in cmd
> 
> try this command
> 
> ```powershell
> Push-Location -LiteralPath ([System.IO.Path]::GetTempPath())
> ```

This is the result of that command:
`PS C:\Users\WZT ALL\AppData\Local\Temp>`

**Comment by amd64fox** [comment]
fixed, thanks for the feedback
