### ISSUE TITLE
Smart Shuffle functionality doesn't work

### ISSUE THREAD

**Issue by Panther7170** [SpotX-Official/SpotX#546]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.26.1187.g36b715a1
- Windows: Windows 11 22H2 22621.2861
- PowerShell: 5.1.22621.2506
```

### 📝 Description

1. Launch spotify
2. Go to liked songs playlist
3. Try to enable smart shuffle by clicking shuffle multiple times or long pressing
4. Instead of smart shuffle being presented or enabled, clicking just disables and enables shuffling
...

### 📸 Screenshots

<img width="296" alt="image" src="https://github.com/SpotX-Official/SpotX/assets/125446389/0c2867b6-122d-4661-84ea-d8b72d9e10dc">

**Comment by amd64fox** [comment]
smart shuffle only works in your playlists
