### ISSUE TITLE
Not Unlocked Speaker Device

### ISSUE THREAD

**Issue by kokofixcomputers** [SpotX-Official/SpotX#547]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Canada

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.28.581.gd018a92c
- Windows: 11 23H2
- PowerShell: 5.1.22621.2506
```

### 📝 Description

1. Have a airplay-enabled dumb speaker
2. Try to connect to it within Spotify
3. It says require premium

**Comment by amd64fox** [comment]
![Снимок экрана 2024-01-02 055938](https://github.com/SpotX-Official/SpotX/assets/62529699/af4854b9-9b7e-47bc-8efb-26963760587f)

**Comment by kokofixcomputers** [comment]
> ![Снимок экрана 2024-01-02 055938](https://private-user-images.githubusercontent.com/62529699/293620318-af4854b9-9b7e-47bc-8efb-26963760587f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDQ5NzMsIm5iZiI6MTcwNDQwNDY3MywicGF0aCI6Ii82MjUyOTY5OS8yOTM2MjAzMTgtYWY0ODU0YjktOWI3ZS00N2JjLThlZmItMjY5NjM3NjA1ODdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDIxNDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZTQ0YmI0NjU4NGZmYmU0YWYyNjAwNWVhMjk5YzY1NTgyMGZlZDY3ZmViZDE0MTU1NzhhMGQwZDMzYThmMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D8h01DahxlG9DEU3m34F15CiiUev17LXVf1pwg3GRB0)

But my dumb speaker is still not unlocked, spotify says that it requires spotify premium to listen on only my iphone is unlocked

**Comment by kokofixcomputers** [comment]
> > ![Снимок экрана 2024-01-02 055938](https://private-user-images.githubusercontent.com/62529699/293620318-af4854b9-9b7e-47bc-8efb-26963760587f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDQ5NzMsIm5iZiI6MTcwNDQwNDY3MywicGF0aCI6Ii82MjUyOTY5OS8yOTM2MjAzMTgtYWY0ODU0YjktOWI3ZS00N2JjLThlZmItMjY5NjM3NjA1ODdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDIxNDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZTQ0YmI0NjU4NGZmYmU0YWYyNjAwNWVhMjk5YzY1NTgyMGZlZDY3ZmViZDE0MTU1NzhhMGQwZDMzYThmMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D8h01DahxlG9DEU3m34F15CiiUev17LXVf1pwg3GRB0)
> 
> But my dumb speaker is still not unlocked, spotify says that it requires spotify premium to listen on only my iphone is unlocked

And what does it mean some device cannot be unlocked??? Does it mean the device itself checks for your subscription??? Does a dumb speaker checks too???
