### ISSUE TITLE
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

### ISSUE THREAD

**Issue by Frug222** [SpotX-Official/SpotX#548]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Australia 

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify:1.2.26.1187.g36b715a1
- Windows: 10
- PowerShell: 5.1
```

### 📝 Description

1.Downloaded it and ran it 
2.came up with the error 
3.
...

### 📸 Screenshots

![Capture](https://github.com/SpotX-Official/SpotX/assets/155434976/5c44aad3-e266-4b73-af0a-044980a177ab)

**Comment by amd64fox** [comment]
- `Win + R` => `inetcpl.cpl`
- `Advanced` tab
- send a screenshot of the security section

**Comment by iamrehan1808** [comment]
well, i was facing the same issue. 
![image](https://github.com/SpotX-Official/SpotX/assets/147645204/02606ebe-86f2-4a5a-8e8d-78737d9f7ddd)

![image](https://github.com/SpotX-Official/SpotX/assets/147645204/cb6aa99c-6635-4b11-ae2a-46bbab81d8bb)

**Comment by iamrehan1808** [comment]
> well, i was facing the same issue. ![image](https://private-user-images.githubusercontent.com/147645204/293889097-02606ebe-86f2-4a5a-8e8d-78737d9f7ddd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzgxNzQsIm5iZiI6MTcwNDI3Nzg3NCwicGF0aCI6Ii8xNDc2NDUyMDQvMjkzODg5MDk3LTAyNjA2ZWJlLTg2ZjItNGE1YS04ZThkLTc4NzM3ZDlmN2RkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxMDMxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjFkNjllNGU1NGVhNjRlZGNmNTU0MmE1N2YyOGMyMzc1NTk2ZTZiNjk0MTlkMTNhZTc2ZWE2YTBiZGFhODM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bw2QWqKRlSggRf0v-9GRR3C1WTowtKS1b0KYKJbylDc)
> 
> ![image](https://private-user-images.githubusercontent.com/147645204/293889054-cb6aa99c-6635-4b11-ae2a-46bbab81d8bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzgxNzQsIm5iZiI6MTcwNDI3Nzg3NCwicGF0aCI6Ii8xNDc2NDUyMDQvMjkzODg5MDU0LWNiNmFhOTljLTY2MzUtNGIxMS1hZTJhLTQ2YmJhYjgxZDhiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxMDMxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGNkMmY0ZGE1YjBhZWMwMzZkODhmYzU5NTA0ZWE1ZWZhNmM5NjdiNjI3NDNlODU5ZTE4MjU0YmQ2NWVmMzQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o6qPlQQW71c74j-x3BU7lgudIVeDC8_dC5buyWThRn4)

![image](https://github.com/SpotX-Official/SpotX/assets/147645204/407a4ce8-471f-4c45-a8b1-77a7e9ccbd2e)
this is the error i'm facing

**Comment by amd64fox** [comment]
@dianarehan1808 
your error has nothing to do with the current problem, most likely inaccurate substitution of input parameters

**Comment by Frug222** [comment]
> * `Win + R` => `inetcpl.cpl`
> * `Advanced` tab
> * send a screenshot of the security section

**Comment by Frug222** [comment]
![image](https://github.com/SpotX-Official/SpotX/assets/155434976/82f6f5d0-a680-422e-855b-b22bb2466881)
![image](https://github.com/SpotX-Official/SpotX/assets/155434976/9f593498-0d61-4306-ba2f-79bb2def14e9)

**Comment by amd64fox** [comment]
why closed, resolved? 

if not, try activating it:

- [x]  Use TLS 1.0
- [x]  Use TLS 1.1

Apply and restart your PC

**Comment by alunity** [comment]
Had the same issue. Noticed that I couldn't access the [Github Pages](https://spotx-official.github.io/SpotX/), with Chrome error "This site can’t be reached, The connection was reset". However I can access the [Github Pages](https://spotx-official.github.io/SpotX/) using mobile data on my phone. I ended up USB tethering as a workaround to install SpotX. 

In my case feels like an ISP related issue. They might be deliberately blocking it (unlikely) or haven't updated some certificates/some other issue on their end.

**Comment by Frug222** [comment]
> why closed, resolved?
> 
> if not, try activating it:
> 
> * [x]   Use TLS 1.0
> * [x]   Use TLS 1.1
> 
> Apply and restart your PC

Still didn't work and i closed it by accident sorta new to github.

**Comment by amd64fox** [comment]
@Frug222 @alunity 

open these links one by one in your browser and show the result:
- https://spotx-official.github.io/run.ps1
- https://raw.githubusercontent.com/SpotX-Official/spotx-official.github.io/main/run.ps1

**Comment by alunity** [comment]
![image](https://github.com/SpotX-Official/SpotX/assets/75143943/44ff5ba7-4e48-498f-8682-0b34c64c6164)
![image](https://github.com/SpotX-Official/SpotX/assets/75143943/587eaa85-b684-4e7d-bca7-35bb5caae551)

**Comment by Autperformance** [comment]
Alright so i came here from my own post and i did the use tls 1.0 and 1.1 restarted pc and tried again, same error. What now?

**Comment by amd64fox** [comment]
> What now?

https://github.com/SpotX-Official/SpotX/issues/548#issuecomment-1877098222

**Comment by Frug222** [comment]
> > What now?
> 
> [#548 (comment)](https://github.com/SpotX-Official/SpotX/issues/548#issuecomment-1877098222)

the first one 

> @Frug222 @alunity
> 
> open these links one by one in your browser and show the result:
> 
> * https://spotx-official.github.io/run.ps1
> * https://raw.githubusercontent.com/SpotX-Official/spotx-official.github.io/main/run.ps1

the first one comes up with this 
![image](https://github.com/SpotX-Official/SpotX/assets/155434976/eb18c4e5-388b-4f73-9d64-dc7953f94b15)
And the 2nd one comes up with this
![image](https://github.com/SpotX-Official/SpotX/assets/155434976/216be639-c452-4793-be7f-3fb8a2228887)

When I opened the first one fully it came up with this:
![image](https://github.com/SpotX-Official/SpotX/assets/155434976/8a9bcd58-6037-48f9-8494-6284ad8b32d5)

**Comment by Autperformance** [comment]
> > > What now?
> > 
> > 
> > [#548 (comment)](https://github.com/SpotX-Official/SpotX/issues/548#issuecomment-1877098222)
> 
> the first one

what do you mean "the first one", you quote the wrong text/person?

**Comment by Autperformance** [comment]
> @Frug222 @alunity
> 
> open these links one by one in your browser and show the result:
> 
> * https://spotx-official.github.io/run.ps1
> * https://raw.githubusercontent.com/SpotX-Official/spotx-official.github.io/main/run.ps1

Second Link (https://raw.githubusercontent.com/SpotX-Official/spotx-official.github.io/main/run.ps1): ![e091af69ab58bb423ee7985b8e5131b1](https://github.com/SpotX-Official/SpotX/assets/155200366/17cb8dbd-c440-47b7-9dad-339366a0fbee)
First Link (https://spotx-official.github.io/run.ps1): ![ae8e39d45d7cd4d09e07da37f367e9cf](https://github.com/SpotX-Official/SpotX/assets/155200366/7281fc90-12f5-4dbe-8e14-1c8c9abe15a4)

those are the two links when opened in my browser (google chrome)

**Comment by amd64fox** [comment]
> When I opened the first one fully it came up with this

@Frug222 
so now the first link works for you again, try running the SpotX installation command again:
```ps1
[Net.ServicePointManager]::SecurityProtocol = 3072; iex "& { $(iwr -useb 'https://spotx-official.github.io/run.ps1') } -new_theme"
```

@Autperformance 
please indicate next to your screenshots the links you used

**Comment by Autperformance** [comment]
> > When I opened the first one fully it came up with this
> 
> @Frug222 so now the first link works for you again, try running the SpotX installation command again:
> 
> ```powershell
> [Net.ServicePointManager]::SecurityProtocol = 3072; iex "& { $(iwr -useb 'https://spotx-official.github.io/run.ps1') } -new_theme"
> ```
> 
> @Autperformance please indicate next to your screenshots the links you used

i updated my comment

**Comment by StalwartNightmare** [comment]
Created an account just to say I reformatted Windows today and I guess at the wrong time because a week ago I guess there was a Windows update in which they turned up their virus protection by 500 percent because any .bat files (not just SpotX) is unable to be ran. Privacy.Sexy is having this issue as well with them talking about it on their Github.

**Comment by StalwartNightmare** [comment]
> Created an account just to say I reformatted Windows today and I guess at the wrong time because a week ago I guess there was a Windows update in which they turned up their virus protection by 500 percent because any .bat files (not just SpotX) is unable to be ran. Privacy.Sexy is having this issue as well with them talking about it on their Github.

Okay a very quick update.....I hadn't gone through and set all my settings yet so I just set my network from Public to Private and I said "what the hell" and tried the .bat again and it actually worked. So~ if anyone has an issue with this .bat or any others see if you're on a public network and if so, switch it to private.

**Comment by 0xJsoul** [comment]
Isn't this the same issue? #553

**Comment by Autperformance** [comment]
> > > When I opened the first one fully it came up with this
> > 
> > 
> > @Frug222 so now the first link works for you again, try running the SpotX installation command again:
> > ```powershell
> > [Net.ServicePointManager]::SecurityProtocol = 3072; iex "& { $(iwr -useb 'https://spotx-official.github.io/run.ps1') } -new_theme"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @Autperformance please indicate next to your screenshots the links you used
> 
> i updated my comment

@amd64fox marked my comment with "thumbs up", but is there a solution now that you got the info about the screenshots? or did you just not have the time yet to see what the problem might be?

**Comment by amd64fox** [comment]
> Isn't this the same issue? #553 see how he solved it.

Yes, there is a temporary manual solution already available in the FAQ, and it's not guaranteed to work for everyone. 

However, I want to fix this automatically during the script execution. Currently, I am in the process of resolving the issue. Also, if any of you have ideas on how to solve this problem through PowerShell, please let me know here. 

Thanks.

**Comment by Frug222** [comment]
> > When I opened the first one fully it came up with this
> 
> @Frug222 so now the first link works for you again, try running the SpotX installation command again:
> 
> ```powershell
> [Net.ServicePointManager]::SecurityProtocol = 3072; iex "& { $(iwr -useb 'https://spotx-official.github.io/run.ps1') } -new_theme"
> ```
> 
> @Autperformance please indicate next to your screenshots the links you used

Yo it works thanks so much

**Comment by amd64fox** [comment]
And so we continue testing for those who still encounter connection issues. Please try running the following command in the PowerShell terminal:

```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12; iex "& { $(iwr -useb 'https://spotx-official.github.io/run.ps1') } -new_theme"
```

**Comment by Autperformance** [comment]
> And so we continue testing for those who still encounter connection issues. Please try running the following command in the PowerShell terminal:
> 
> ```powershell
> [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12; iex "& { $(iwr -useb 'https://spotx-official.github.io/run.ps1') } -new_theme"
> ```

just tried this, will attach screenshot.
![dd6981cb876780c2afc6139845ff4e6a](https://github.com/SpotX-Official/SpotX/assets/155200366/90ba0a70-1437-4d81-9b52-a560add72675)

**Comment by amd64fox** [comment]
try running this bat file

[Install.zip](https://github.com/SpotX-Official/SpotX/files/13853498/Install.zip)

**Comment by Autperformance** [comment]
> try running this bat file [Install.zip](https://github.com/SpotX-Official/SpotX/files/13853762/Install.zip)

alright, i just tried it and what happened you can see in the screenshot attached.
![c0b5b485f078cd64984f17b8f8e492bc](https://github.com/SpotX-Official/SpotX/assets/155200366/38f891f3-52f2-4a84-b071-0eebc51d24f4)

**Comment by amd64fox** [comment]
@alunity @Autperformance @Frug222 

added a backup url, testing is required, run the [bat file](https://raw.githack.com/amd64fox/SpotX/main/Install_New_theme.bat) and show the result

**Comment by Autperformance** [comment]
> @alunity @Autperformance @Frug222
> 
> added a backup url, testing is required, run the [bat file](https://raw.githack.com/amd64fox/SpotX/main/Install_New_theme.bat) and show the result

it just went through without an error (first time it worked) - it asked me about my spotify version and podcasts etc. and then it patched it - i think it worked, right?

**Comment by amd64fox** [comment]
> it just went through without an error (first time it worked) - it asked me about my spotify version and podcasts etc. and then it patched it - i think it worked, right?

yeah, this is expected behavior, thanks for your feedback, I'll wait for other people with this problem to check this

**Comment by alunity** [comment]
The new bat file works as intended

**Comment by amd64fox** [comment]
> The new bat file works as intended

thanks for your feedback

closed for now, if you have any problems write to this thread

**Comment by brianne-railway** [comment]
@amd64fox couldn't this be resolved by having all of the spotX data manually installable? Then, instead of needing to call a website and running into security settings bullshit, you could just download the installer with all the data already inside it

I am not a programmer so I don't know how complex this would be. Perhaps .bat files would not take well to having all of those code lines stored inside, and it would get unmanagable? But I can't really see a reason why the current method is the only possible method

Also, BTW, it'd be nice to have the FAQ page also be on the github page, because the link brings up a firefox security message.

**Comment by amd64fox** [comment]
At the moment, offline patching is not provided for, but I may implement it when I have free time.

You can also use the pre-patched builds we've already created in the [telegram group](https://t.me/SpotxCommunity/1049).
