### ISSUE TITLE
Error when trying to run the bat file

### ISSUE THREAD

**Issue by Autperformance** [SpotX-Official/SpotX#549]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [x] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Austria

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.26.1187.g36b715a1
- Windows: couldn't Win+Pause/Break but i think i found the version: Windows 10 22H2 (Build 19045.3803)
- PowerShell: 5.1.19041.3803
```

### 📝 Description

1. Running Install_New_theme.bat
2. Running Install_Auto.bat
3. Copying the link from the github into Powershell
...

So first i downloaded the Install_New_theme.bat, opened it and it gave me this error (i will upload a screenshot but part of it is in my language aka german)
then i tried it with "auto bat" file, same thing. and i tried it with the link instead, same thing.

What do i need to do?

### 📸 Screenshots

![5126adb467b1ca5912628654c909f40f](https://github.com/SpotX-Official/SpotX/assets/155200366/3d89afa3-4156-4eba-825e-cb79acf2fb19)

**Comment by amd64fox** [comment]
I don't understand German, but it looks like this is a duplicate #548

**Comment by Autperformance** [comment]
> I don't understand German, but it looks like this is a duplicate #548

Thanks i will try whatever the suggestions for a solution are in that post and update this post when i have done that. Probably will be in 12h or less.
