### ISSUE TITLE
"Top Artists and Tracks" feature breaking

### ISSUE THREAD

**Issue by Gitsom1337** [SpotX-Official/SpotX#55]
The "Top artists this month" and "Top tracks this month" lists available in the profile page are breaking off. The issue is observed in the latest stable version, that is, 1.1.86.857. Also, it has been observed that this issue only occurs when the podcasts are turned off during the patch. when not turned off, app is still stable without the issue. screenshots for the same have been attached.

Before:
![before](https://user-images.githubusercontent.com/99592651/172621410-85e64993-037f-4d0f-98bc-bb6d2516cc5c.jpg)

After:
![after](https://user-images.githubusercontent.com/99592651/172621416-9c5f5e7f-1e60-4110-a181-fa2cea5f43a8.jpg)

**Comment by twistedmacaroni** [comment]
Having the same issue. have you found a solution yet?

**Comment by vacarogit** [comment]
> Having the same issue. have you found a solution yet?

Jusr reenable the podcast stup

**Comment by twistedmacaroni** [comment]
> > Having the same issue. have you found a solution yet?
> 
> Jusr reenable the podcast stup

yeah well, except that.
