### ISSUE TITLE
Getting error while installing it

### ISSUE THREAD

**Issue by iamrehan1808** [SpotX-Official/SpotX#550]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Not installed
- Windows: Windows 11 Home Single Language 23H2 22631.2861
- PowerShell: 5.1.22621.2506
```

### 📝 Description

1. I get this error while installing it by running command. See screenshot below.
2. I use K7 antivirus which says the .bat file contains suspicious program. I disabled the antivirus and then tried but still i got similar error.

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/147645204/8a29572e-6b77-4848-947b-b59bd63c4cc7)

**Comment by amd64fox** [comment]
as I told you earlier most likely inaccurate substitution of input parameters
download the bat file again or show what is inside the one that gives the error

**Comment by iamrehan1808** [comment]
[Net.ServicePointManager]::SecurityProtocol = 3072; iex "& { $(iwr -useb 'https://spotx-official.github.io/run.ps1') } -new_theme"

i ran the above command that i copied from here
![image](https://github.com/SpotX-Official/SpotX/assets/147645204/85b122cf-c8d5-4aaf-863a-98169686c0b1)

**Comment by amd64fox** [comment]
the command you indicate to run spotx in the screenshot works, your bat file that you did not provide was most likely corrupted, download it or use the command directly for the powershell terminal

**Comment by iamrehan1808** [comment]
in my pc the same command gives that error. look at the screenshot below
![image](https://github.com/SpotX-Official/SpotX/assets/147645204/d26d6e63-7814-49d0-ad5d-5d6253878a11)

**Comment by amd64fox** [comment]
open these links one by one in your browser and show the result:
- https://spotx-official.github.io/run.ps1
- https://raw.githubusercontent.com/SpotX-Official/spotx-official.github.io/main/run.ps1

**Comment by iamrehan1808** [comment]
![image](https://github.com/SpotX-Official/SpotX/assets/147645204/86b5a216-0484-4b4e-bcfc-bcf07e04c189)
upon opening the first link

![image](https://github.com/SpotX-Official/SpotX/assets/147645204/dc288758-a134-4749-b910-68931b4234ab)
upon opening the 2nd link

**Comment by amd64fox** [comment]
your av is blocking the connection, not a problem spotx, completely disable or remove your av

**Comment by iamrehan1808** [comment]
Thanks. I now have this issue
i didn't get funnyprogressBar though i used it in parameter
also, upon adding 'idbox_goofy' or 'urlform_goofy' in parameter it gives error. see the screenshots below
![image](https://github.com/SpotX-Official/SpotX/assets/147645204/3fce28d0-bf4e-4600-bc12-826540cfbc01)
![image](https://github.com/SpotX-Official/SpotX/assets/147645204/4c171196-5e37-4b0a-831b-3db742ec7b0e)

**Comment by amd64fox** [comment]
don't use the 'idbox_goofy' and 'urlform_goofy' parameters if you have no idea what they are for
