### ISSUE TITLE
bat file

### ISSUE THREAD

**Issue by nithinana** [SpotX-Official/SpotX#553]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [ ] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United Kingdom

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 
- PowerShell:
```

### 📝 Description

it says Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:63
+ ... 72}; "& { $(Invoke-WebRequest -UseBasicParsing 'https://spotx-officia ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

when i try insstall any of the bats

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/67801576/544277a2-a097-4c65-9ff2-46d0a9bca836)
![Capture](https://github.com/SpotX-Official/SpotX/assets/67801576/5b2ca59b-1156-46ca-9a54-dfa3000767ee)

**Comment by nithinana** [comment]
For anyone with the same problem, just change the DNS preferablely to Google (8.8.8.8/8.8.4.4) or Cloudflares (1.1.1.1).

It's solved now.

**Comment by Autperformance** [comment]
did you change the DNS and then restarted the PC to try again with the Bat file, or did you just change it and then tried it? because the second thing i already tried, i just didnt restart inbetween.

> For anyone with the same problem, just change the DNS preferablely to Google (8.8.8.8/8.8.4.4) or Cloudflares (1.1.1.1).
> 
> It's solved now.

did you change the DNS and then restarted the PC to try again with the Bat file, or did you just change it and then tried it? because the second thing i already tried, i just didnt restart inbetween.

**Comment by nithinana** [comment]
I didn't have to restart my PC.
heres a quick tutorial through it.
settings>network and internet>wifi>change adapter options> right click ur
wifi> properties>internet protocol version 4 (TCP/IPv4)>properties>use the
following DNS server addresses
[image: image.png] this one is for cloudflares, which is probably the best
one in my opinion
