### ISSUE TITLE
Unable to install SpotX

### ISSUE THREAD

**Issue by Spinoscythe** [SpotX-Official/SpotX#554]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United Kingdom

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.28.581.gd0e8a92c
- Windows: 11
- PowerShell: 7.4.0
```

### 📝 Description

1. Try to run the new theme command
2.
3.
...

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/84230130/e4affe36-79d7-4a16-be03-9375fa21330e)

**Comment by amd64fox** [comment]
It seems to be temporary network issues. Try restarting your pc and executing the same command again. If that doesn't help, please read [this comment](https://github.com/SpotX-Official/SpotX/issues/548#issuecomment-1879997195)

I am currently looking for a new solution to the problem there.
