### ISSUE TITLE
Cinema Mode with art cover in fullscreen?

### ISSUE THREAD

**Issue by wangdog123** [SpotX-Official/SpotX#556]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Taiwan

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.28.581.gd0e8a92c
- Windows: Windows 11 23H2 22631.3007
- PowerShell: 5.1.22621.2506
```

### 📝 Description

When using Fullscreen mode, it will have an art cover in the background, and u can switch between it and only lyrics with colored-background like this.
![image](https://github.com/SpotX-Official/SpotX/assets/111276872/033c7ab0-8c8d-45eb-ae5a-0ab1d969a1b6)
![image](https://github.com/SpotX-Official/SpotX/assets/111276872/d426a1b4-6f15-4124-aebf-0b2c3e721607)

I'm currently using Spicetify now and I saw some themes displayed that you can see the art cover with Cinema mode instead of Fullscreen mode.
![image](https://github.com/SpotX-Official/SpotX/assets/111276872/3f6e054f-20c4-4aff-9d4f-67d67b2f4fee)

But I can only use this button to turn on Cinema mode, and it won't have the art cover like the themes description said.
![image](https://github.com/SpotX-Official/SpotX/assets/111276872/146a2fc7-bbc1-4052-b5f3-d2c0b2caf5e9)
![image](https://github.com/SpotX-Official/SpotX/assets/111276872/7c3cde94-ba3d-469b-a501-6c9f4d419d37)
I really want to have the art cover without using fullscreen, are there any ways to do that?
ps. sorry if I am being silly, I'm new to spotify and I think there should be a Cinema mode button like fullscreen has?
ps2. BTW I just found that 1.28 breaks some themes, and also some features in SpotX like funnyprogressbar. (maybe

**Comment by amd64fox** [comment]
not related to spotx
