### ISSUE TITLE
latest not working, errors, will not install

### ISSUE THREAD

**Issue by MarshMeadow** [SpotX-Official/SpotX#557]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

us

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: latest, it just installed, and this mod will not install..
- Windows: windows 10 (moddel atlas os)
- PowerShell: umm not sure, windows powershell I would think..
```

### 📝 Description

1. error codes
2. wont install
3.
...

**Comment by MarshMeadow** [comment]
ok i looked into the source code, with python, and it looks like the installers can't reach the servers to install, it gets a 404 error, and can't follow through with the request..

**Comment by amd64fox** [comment]
show your error in full

**Comment by MarshMeadow** [comment]
> Show your error in full

![image](https://github.com/SpotX-Official/SpotX/assets/88599122/b0334b66-a3a0-4b3c-9ef1-a454b7ee3507)

This is the release: 1.7 (not the latest), from the releases page.. and that one used to still work, "Install_Auto.bat".

When I looked into it and dug into the files/code, the link went to a 404 page..

**Comment by amd64fox** [comment]
The always up-to-date batch files for installation can be found on the readme page, there's no need to search for them in outdated releases.

**Comment by MarshMeadow** [comment]
> The always up-to-date batch files for installation can be found on the readme page, there's no need to search for them in outdated releases.

ok thanks, wait does that mean 1.8 does not work??
