### ISSUE TITLE
stuck on cmd

### ISSUE THREAD

**Issue by Tomias-Impola** [SpotX-Official/SpotX#558]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

finland

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 11
- PowerShell:
```

### 📝 Description

1. when i download its just goes to the cmd screen and doesnt do anything
2.
3.
...

**Comment by amd64fox** [comment]
> when i download its

download what?  launch what? screenshot ?

**Comment by lazybones678** [comment]
I may have found a fix.
When trying to run the _run_ script using PowerShell, cmd, Ect. It appears for a split second, my fix is the following.

1. Install Visual Studio Coding Software
2. Enter Extensions Marketplace And Install _PowerShell_ From The Search Bar
3. After This Navigate To Your Unzipped _SpotX-main_ Folder Inside You Sould See A _run.ps1_ or it will say _run_. 
![image](https://github.com/SpotX-Official/SpotX/assets/103843308/726e54f7-c506-436e-86c8-0d18cb46c1e1)
5. Right Click On _run.ps1_, navigate to _Open With >_, Then Click Open With Visual Studio.
![image](https://github.com/SpotX-Official/SpotX/assets/103843308/9b62e2a1-5f54-4f3b-b4cc-46ebcfb8f7ca)
6. You Should See The Normal Visual Studio Interface, But On The Left Click The _Run And Debug_ Panel. 
![image](https://github.com/SpotX-Official/SpotX/assets/103843308/e91bd8c9-f06a-4584-9b12-5c4504ce169f)
Click On _Run And Debug_ The Big Blue Box 
![image](https://github.com/SpotX-Official/SpotX/assets/103843308/e9e0bf59-a912-46e5-b94f-4a629c79e775)
7. After This Answer The Prompts In The Terminal With Either _Y_ or _N_ On Your Keyboard.

I Hope This Works For You
