### ISSUE TITLE
installer only works with a vpn

### ISSUE THREAD

**Issue by KurunesisUwU** [SpotX-Official/SpotX#559]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

australia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.29.605.g66a43ceb
- Windows: windows 11 22h2 22621.3007
- PowerShell: 5.1.22621.2506
```

### 📝 Description

1. gives me an error as soon as i run the installer
2. restarting my computer doesn't help
3. i had installed spotx a month before this happened, but the original spotify client recently reinstalled itself
4. i can install spotx when using a vpn, otherwise it gets blocked

### 📸 Screenshots

![Screenshot 2024-01-20 224357](https://github.com/SpotX-Official/SpotX/assets/157214594/f16a0473-6ccd-4a99-98da-dd5e12f56a34)

**Comment by amd64fox** [comment]
update your bat file from [readme](https://github.com/SpotX-Official/SpotX?tab=readme-ov-file#fast-installation--update)
