### ISSUE TITLE
Login error code auth:2

### ISSUE THREAD

**Issue by new4one** [SpotX-Official/SpotX#560]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Germany | Austria

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.5.1006.g22820f93
- Windows: 7 Ultimate 64-Bit, Version 6.1 (Build 7601:Service Pack 1)
- PowerShell: 5.1.14409.2001
```

### 📝 Description

NET Framework 4.8 <<<< First installation step.
WMF 5.1 <<<< Second Istallation step.
Reboot your PC <<<< Third step.
https://raw.githack.com/amd64fox/SpotX/main/Install_Old_theme.bat <<<< Last installations step.

### 📸 Screenshots

![Error](https://github.com/SpotX-Official/SpotX/assets/143336834/9a840a42-0797-4145-99f6-b5ea7fb2ef02)

**Comment by amd64fox** [comment]
Spotx does not affect authorization, make sure you enter your login and password correctly, or [reset your current password](https://www.spotify.com/password-reset)

**Comment by amd64fox** [comment]
P.S.
other users also reported a similar error, but now manual login is working again, maybe it was a temporary glitch on the spotify servers
