### ISSUE TITLE
Spotx users now confirmed being banned from spotify

### ISSUE THREAD

**Issue by SLVPYY** [SpotX-Official/SpotX#561]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Ireland

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: can't be viewed, cant get passed log in screen. 
- Windows: Latest 23H2 package
- PowerShell: V5.1.22621.2506
```

### 📝 Description

Main account on spotify randomly logged out one day, thought it was weird so I went back to the website to check and log back in to no avail, my account is banned. I proceeded to make another account thinking nothing of it, that account subsequently received a ban a day later. After thinking for a while I realized I have spotx installed, so I made another account after uninstalling spotx, the account survived happily for over a week and a half. After getting tired of ads and curiosity getting the better of me I reinstalled spotx and hey, what do you know a day later, I got ban 5 ever. (no variables were changed in the duration of testing this includes  installation of software related to spotify, ad block, vpns, windows updates, game anti cheats, firewalls, anti viruses etc.)

**Comment by amd64fox** [comment]
When your account is banned, you automatically receive an email with the reason for the ban. Please familiarize yourself with this reason.

**Comment by EvaXephon13** [comment]
>email with reason for ban
And that's bullshit because I never received a single email for both of my banned accounts.
