### ISSUE TITLE
CMD just close when I press a key

### ISSUE THREAD

**Issue by Maxx1mus** [SpotX-Official/SpotX#562]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

México

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.29.605
- Windows: 10 22h2 19045.3930
- PowerShell: 7.4.1
```

### 📝 Description

1.  I double-clicked the Uninstall-Spotify.bat
2. It says Spotify is uninstalled and press any key
3. I press any key then the cmd close and nothing happens
...

**Comment by amd64fox** [comment]
Uninstall-Spotify.bat completely removes your current Spotify, installation is [here](https://github.com/SpotX-Official/SpotX?tab=readme-ov-file#choose-installation-type)
