### ISSUE TITLE
Bug in the new queue right panel

### ISSUE THREAD

**Issue by brxndonnn** [SpotX-Official/SpotX#563]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

South Africa

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.30.1135.g02fef27a
- Windows: Version 22H2 (10.0.19045 Build 19045)
- PowerShell: 5.1.19041.3930
```

### 📝 Description

1. The song that's currently playing is displayed 2 times in the queue menu.
2. Top song in Now Playing won't select when clicked on, the menu still pops up though. The second song (same one that's playing as said in no.1) works fine when right clicked on.

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/103594572/724a950d-958a-40d2-8be0-a01a91ef1ba9)
![image](https://github.com/SpotX-Official/SpotX/assets/103594572/b3cfddc1-aa09-4b1c-93ca-2b1f5cbb1e40)

**Comment by amd64fox** [comment]
native client bug 1.2.30, disable the new sidebar called "enableQueueOnRightPanel" in the [debug menu](https://github.com/SpotX-Official/SpotX/discussions/47) or roll back to the previous version until it is fixed in new versions
