### ISSUE TITLE
DJ not working

### ISSUE THREAD

**Issue by brxndonnn** [SpotX-Official/SpotX#564]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

South Africa

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Latest
- Windows: 22H2
- PowerShell: Latest
```

### 📝 Description

1. I enabled the DJ in the debug options but it does not seems to work even though everything is enabled, i know it is in Beta so its not a big problem, just wanna hear if i did everything right?

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/103594572/8b0a6ae3-2cdc-4723-a3f5-8e4f24243db3)

**Comment by amd64fox** [comment]
read FAQ
