### ISSUE TITLE
Unable to Play a Song in the middle of the Queue

### ISSUE THREAD

**Issue by BedBug2479** [SpotX-Official/SpotX#566]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.30.1135.g02fef27a
- Windows: Windows 10 22H2 19045.3930
- PowerShell: 5.1.19041.3930
```

### 📝 Description

When trying to play a song that is present after 2 or more songs is not possible. I am able to press NEXT; But using the cursor to play a random song is not possible.

This is possible in Spotify v1.2.29.605.g66a43ceb

Thanks.

**Comment by amd64fox** [comment]
Temporarily disabled the new queue panel for version 1.2.30+ due to issues introduced in the latest update.

As soon as they fix the issue, I'll restore it.
