### ISSUE TITLE
spotx interfering with spicetify's custom app (lyrics-plus)

### ISSUE THREAD

**Issue by N0tBLUE** [SpotX-Official/SpotX#567]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.30.1135.g02fef27a
- Windows: Windows 11 23H2 22631.3085
- PowerShell: 5.1.22621.2506

Spicetify: v2.31.2
   - Theme:
   - Extensions:
   - Custom apps: lyrics-plus
```

### 📝 Description

1.installed spotify latest version with spicetify (parameters option)
2.installed spicetify 
3.added custom app (lyrics-plus)
4.there should be lyrics-plus config button in under profile picture icon but there is nt after the new update of spicetify

without spotx there is actually lyrics-plus config button 
so its spotx issue which is interfering with lyrics-plus config button to appear there

i contacted spicetify team they said its spotx issue so thought of asking here once

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/74755694/239f80f1-813f-4a4f-a67a-2f4a92a7668f)
----> this is whats there in menu for me with spotx installed 

![image](https://github.com/SpotX-Official/SpotX/assets/74755694/f40ff149-d86e-4d18-b0d0-fc5897cde850)
-----> this is without spotx installed

**Comment by amd64fox** [comment]
not reproducible
