### ISSUE TITLE
Songs that are "enhancing" the liked songs list can't be played

### ISSUE THREAD

**Issue by koneko** [SpotX-Official/SpotX#57]
## ℹ Computer information

- Spotify version: [1.1.86.857](https://cutt.ly/8EH6NuH)
- Plan Spotify: free
- Windows version: Windows 10
- PowerShell version: no idea

## 📝 Description of the problem

Trying to use "Enhance" button on liked songs visually puts the songs there, however I can not play them or do anything with them.
## 📷 Screenshots

<details>
<summary><small>Screenshot</small></summary><p>

![Spotify_YIPu492eAU](https://user-images.githubusercontent.com/67551503/174493248-a9243b33-6070-413f-87cc-8da7b35b37e2.png)

</small></summary><p>

</details>

**Comment by amd64fox** [comment]
This has already been [discussed](https://github.com/amd64fox/SpotX/discussions/49), in the new version 1.1.87-1.1.88.612, as I understand it, the spotify developers have not fixed this, we are waiting ...
