### ISSUE TITLE
Notification Button

### ISSUE THREAD

**Issue by Wikinger8** [SpotX-Official/SpotX#571]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Germany

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.31.1205.g4d59ad7c
- Windows: Windows 10 Pro 22H2 19045.4046
- PowerShell: 5.1.19041.4046
```

### 📝 Description

1. I can see a new "Notifications" button (in almost every window).
2. I want it removed.
3. In normal spotify there was no "Notifications" button.

and yes I tried a clean install with SpotX

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/85295145/e05ea240-28e3-4e9b-a793-dfef5e5cf1e0)
![image](https://github.com/SpotX-Official/SpotX/assets/85295145/79693baa-a0a9-494d-9b72-4ce95a3787f8)
![image](https://github.com/SpotX-Official/SpotX/assets/85295145/950ccad0-2b93-449d-aec8-dfa2c3405640)

**Comment by amd64fox** [comment]
read the [faq](https://telegra.ph/SpotX-FAQ-09-19#Can-I-change-some-of-the-experimental-features?) before creating a useless issue

**Comment by Wikinger8** [comment]
Unfortunately, there is nothing helpful to be found in the FAQ. Even the clean installation did not help. But this post https://github.com/SpotX-Official/SpotX/discussions/47 helped me. This experimental feature was activated by default for me after the installation. But thanks for the unhelpful anwser.

**Comment by amd64fox** [comment]
for the faq to be useful it must be read, you couldn’t do it in 2 attempts

![Снимок экрана 2024-02-21 181245](https://github.com/SpotX-Official/SpotX/assets/62529699/c40789cf-69e0-4ab1-8a48-11b8eb565679)

**Comment by Wikinger8** [comment]
Then it would be helpful to link the FAQ here 
![image](https://github.com/SpotX-Official/SpotX/assets/85295145/38556a29-77dd-4019-8e49-eb78d0a2a376)

Because I was looking for similar problems and then clicked on this link
https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation
![image](https://github.com/SpotX-Official/SpotX/assets/85295145/ba345451-dae3-4d5b-9a7a-b17c7ace034d)

I apologize for my misunderstanding and my answer earlier.

**Comment by amd64fox** [comment]
hyperlink is present when creating a problem, accordingly you need to read the faq before/during the creation of the problem, and not after creating the problem

![Снимок экрана 2024-02-21 182512](https://github.com/SpotX-Official/SpotX/assets/62529699/fe31211e-7f3c-4adf-b22a-daeca398c97f)

**Comment by Wikinger8** [comment]
Sorry for my misunderstanding, but I thought I saw the FAQ when I clicked on it.
![image](https://github.com/SpotX-Official/SpotX/assets/85295145/830f3c6f-5612-4136-8f46-1480c06e67f6)
