### ISSUE TITLE
Downloading spotify is extremely slow and the download fails when using vpn

### ISSUE THREAD

**Issue by Softland99** [SpotX-Official/SpotX#574]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

CN

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: None
- Windows: Windows 11 23H2 22631.3235
- PowerShell: 5.1.22621.2506
```

### 📝 Description

1.Using the default network environment, downloading takes approximately one hour (confirm that the network is fine).
2.Download failed after trying to use VPN to speed up downloads.

### 📸 Screenshots

C:\Windows\System32>"C:\Users\123\Downloads\Install_New_theme.bat"                                                    
╔════════════════════════════════╗
║ 欢迎使用 SpotX 的 Windows 版本 ║
╚════════════════════════════════╝

下载并安装 Spotify 1.2.33.1039
请稍等...

Curl error code: 000

下载错误 SpotifySetup.exe
ScriptHalted

将在五秒后重试

Curl error code: 000
再次出错
ScriptHalted

请检查您的网络设置后再次尝试安装

脚本已停止
按 Enter 键继续...:

**Comment by Softland99** [comment]
The "Screenshots" describes problem 2

**Comment by EdwardDK** [comment]
It worked fine for me using New York connection on SurfShark

**Comment by amd64fox** [comment]
spotx should not greatly affect the download speed, you can independently test the download speed, for example from your browser and compare it with the current download from spotx

also do not forget that you can always download the file from [here](https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit#gid=803394557) and install it manually and then run the spotx installation
