### ISSUE TITLE
song radio not working

### ISSUE THREAD

**Issue by SuperCuek** [SpotX-Official/SpotX#575]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Indonesia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows (32 bit) 1.2.33.1039.g8ddb5918
- Windows: Windows 10 22H2 19045.4123 x64
- PowerShell: 5.1.19041.4123
```

### 📝 Description

"go to song radio" doesn't work. clicked and nothing happened
![image](https://github.com/SpotX-Official/SpotX/assets/104664907/fc3d8cb9-095b-41ee-a593-f8320d5b1b69)

**Comment by amd64fox** [comment]
It seems like a temporary network error or issues with outdated cache. A clean installation from the FAQ and a reboot should help. 

Additionally, you might want to check with another network or device.
