### ISSUE TITLE
ISP blocking of SpotX-official.github.io

### ISSUE THREAD

**Issue by brianne-railway** [SpotX-Official/SpotX#578]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Australia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: [currently uninstalled]
- Windows: Edition Windows 10 Home Version 22H2 19045.4046 Windows Feature Experience Pack 1000.19053.1000.0

- PowerShell: [Not Applicable]
```

### 📝 Description

1. live in a rural backwater in Australia
2. be an unwilling telstra customer
3. attempt to open https://spotx-official.github.io/spotx-docs/guide/advanced-guides/installation-win
4. be confronted with a Firefox security warning (click through it)
5. Be confronted with a impassable Telstra warning

5.1 ALT TEXT: 
(telstra logo and warning symbol) 
THIS WEBSITE HAS BEEN BLOCKED 

We blocked this website because it may contain malicious content and could be harmful to your devices.

You haven't done anything wrong. We automatically block potentially dangerous websites. We recommend you leave this website.

If you believe this website is safe, you can [report this website as **safe](https://www.telstra.com.au/forms/report-misuse-of-service).**
...

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/104614425/7f74cfa3-7aed-41e5-8813-0179aace65f2)

**Comment by amd64fox** [comment]
The [spotx-docs](https://spotx-official.github.io/spotx-docs/) resource is not worth using at the moment, we plan to use it, but it is currently under development.

If you need to read the faq then use this [link](https://telegra.ph/SpotX-FAQ-09-19) or [mirror](https://te.legra.ph/SpotX-FAQ-09-19) or use vpn

**Comment by SamErde** [comment]
You might be able to get past Telestra's blocks if they are [probably] DNS-based. A DNS proxy on your network (eg Pihole with DNSCrypt-Proxy) or even something on your PC that uses either DoH (DNS over HTTPS) or DoT (DNS over TLS) should do the trick.
