### ISSUE TITLE
cannot download song/playlist

### ISSUE THREAD

**Issue by shrigiri81** [SpotX-Official/SpotX#58]
Spotify premium downloaded from SpotX
version - 1.1.86.857

**Comment by Gitsom1337** [comment]
the download feature to keep songs offline isn't a SpotX feature. check the Code tab before adding an issue.

**Comment by amd64fox** [comment]
SpotX does not currently support premium accounts, I plan to do so in the near future, follow this[ thread](https://github.com/amd64fox/SpotX/issues/53).
