### ISSUE TITLE
Can't listen to any podcasts!!!

### ISSUE THREAD

**Issue by iTzMAS** [SpotX-Official/SpotX#580]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [X] I have checked older issues, open and closed
- [x] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Germany

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1235.663.gb699649e
- Windows: 11 Version 2382 (OS Build 22631.3374)
- PowerShell: 5.1.22621.2506
```

### 📝 Description

1. open Spotify
2. try to listen to any podcasts

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/38975749/88a89b92-6f14-4496-8829-44c175e4dbee)

**Comment by amd64fox** [comment]
couldn't reproduce the problem, install the [original Spotify](https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit#gid=0) of the same version and check your error again
