### ISSUE TITLE
Pop-up and Banner ads still appearing after install.

### ISSUE THREAD

**Issue by LabRatMime** [SpotX-Official/SpotX#582]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

USA

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.90.859.gf1bb1e36
- Windows: Windows 10 Home 22H2 19045.4291
- PowerShell: 5.1.19041.4291
```

### 📝 Description

1. Cleanly remove spotify
2. Use powershell to install spotx with the specific version I wanted. ( iex "& { $(iwr -useb 'https://raw.githubusercontent.com/SpotX-Official/spotx-official.github.io/main/run.ps1') } -v 1.1.90.859.gf1bb1e36-11 -confirm_spoti_recomended_over -block_update_on" )
3. Wait a bit while playing music and ads pop-up (no audio ads though, just visual ads.)
...

### 📸 Screenshots

![img-2024-04-18-22-09-43](https://github.com/SpotX-Official/SpotX/assets/86023645/3bf65385-a71d-4e8e-8fb7-24452a7491c5)
![img-2024-04-18-22-09-51](https://github.com/SpotX-Official/SpotX/assets/86023645/7928d8e4-82f0-4bfc-a73b-ae8835089634)

**Comment by amd64fox** [comment]
thanks for the feedback, there was a small fix now, try updating spotx and check again

**Comment by LabRatMime** [comment]
I updated and have been using it for a while now and no ads seem to be appearing! tysm!
