### ISSUE TITLE
The term 'iwr' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by elvisef** [SpotX-Official/SpotX#583]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Poland

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.5.1006.g22820f93
- Windows: Windows 7 Professional
- PowerShell: 2.0 (it is written, that 5.1 is "recommended", so "not needed")

I have never used PowerShell before, so if I need to install something, please let me know. Thanks.
```

### 📝 Description

1. Installed official Spotify version for Win7 (latest one, 1.2.5 ?)
2. Tried to use the BAT file for installing SpotX premium.
3. Error occured in the CMD: "The term 'iwr' is not recognized as the name of a cmdlet ... "
...

### 📸 Screenshots

![cmd_2024-04-21_22-03-32](https://github.com/SpotX-Official/SpotX/assets/25976749/3a9b1e7d-1a7f-4f9b-b462-0f45a9b674ce)

**Comment by amd64fox** [comment]
You are ignoring the points that need to be completed before creating an issue

One of these important points is to read the [faq](https://telegra.ph/SpotX-FAQ-09-19#It-seems-I-have-an-old-version-of-PowerShell-2.0,-can-I-install-a-patch-with-it?)
