### ISSUE TITLE
Use the new spotify like button with the old one

### ISSUE THREAD

**Issue by Spinoscythe** [SpotX-Official/SpotX#585]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United Kingdom

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.36.955.gd8cc9372
- Windows: 11
- PowerShell: 7.4.2
```

### 📸 Screenshots

SpotX currently:
![image](https://github.com/SpotX-Official/SpotX/assets/84230130/8c4c50b7-1d90-4c5b-955a-0f8295c458cd)
SpotX should be:
![image](https://github.com/SpotX-Official/SpotX/assets/84230130/58d342ee-b5d9-4d89-8f4c-1efd517d1188)

**Comment by amd64fox** [comment]
by default spotx uses the old heart type

if you need a new type in the form of a plus, then you can use the `-plus` parameter during spotx installation
