### ISSUE TITLE
lyrics not synced/incomplete.

### ISSUE THREAD

**Issue by papayathebun** [SpotX-Official/SpotX#587]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Peru

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.36.955.gd8cc9372
- Windows: 10
- PowerShell: 5.1.19041.4355
```

### 📝 Description

Installed SpotX following the instructions provided. Thought it to be caused by the lyrics being relocated to the rightside bar, so I added -old_lyrics and removed -lyrics_stat parameters to auto_install.bat.
Uninstalled, purged remaining files with Uninstall-Spotify.bat, reinstalled. Problem persists. Everything works as intended otherwise.

Tried: Install_Auto.bat, Install_New_theme.bat.
### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/168588138/55811cde-43ad-4f19-8ae2-a7239ff95a6b)
![image](https://github.com/SpotX-Official/SpotX/assets/168588138/084c5c0b-f62b-442c-aac1-fb21eb9ec0e7)

**Comment by amd64fox** [comment]
this is normal behavior for a native client, spotx does not affect synced/not synced lyrics

**Comment by EliaCoon** [comment]
> this is normal behavior for a native client, spotx does not affect synced/not synced lyrics

This is NOT normal behavior.
The modified client is showing only a part of the lyrics you would see using any other non-customized client.

**Comment by amd64fox** [comment]
example ?

- lyrics in spotx
- lyrics in the native client

**Comment by amd64fox** [comment]
Spotify has started restrictions song lyrics for free users today.
Currently, SpotX removes this restriction for latest version **1.2.36**, but all song lyrics become not synced/incomplete, for versions lower than **1.2.36** the lyrics do not work. 

Once we have more information about this issue, we will notify...

**Comment by amd64fox** [comment]
The bad news for the lyrics has been confirmed, they limit the lyrics on the server side 👀

Maximum that the server returns is part of the beginning of the lyrics without synced

We are waiting for the new release 1.2.37, but judging by the existing feedback, we should not expect changes to the current logic of this restriction.


For those who want to use lyrics, [lyrics-plus](https://spicetify.app/docs/advanced-usage/custom-apps/#lyrics-plus) in [spicetify](https://spicetify.app/) still works

P.S.

unfortunately, new versions did not give hope for returning the lyrics
