### ISSUE TITLE
Bad connection makes music stop

### ISSUE THREAD

**Issue by 1221363** [SpotX-Official/SpotX#589]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Portugal

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.25.1011.g0348b2ea
- Windows: Windows 11 23H2 223631.3447
- PowerShell: 5.1.22621.2506
```

### 📝 Description

When the wifi goes down, the music instantly stops, and clears my queue. When it goes back up i have to manually play the playlist again. I think the music should simply be paused while the internet is down.

**Comment by amd64fox** [comment]
this behavior is not related to spotx, check the native client of the same version
