### ISSUE TITLE
Spotify unable to play this right now

### ISSUE THREAD

**Issue by shrek1802** [SpotX-Official/SpotX#59]
## ℹ Computer information

- Spotify version: Spotify for Windows 1.1.88.612.gcc529952
- Plan Spotify: free 
- Windows version: 11
- PowerShell version:

## 📝 Description of the problem

When I try and play a song I keeps on saying spotify unable to play this right now

I have uninstalled spotify and reinstalled then run the patch again and its still doing the same thing.

Any help would be great thank you

**Comment by litfin88** [comment]
The song you want to listen to may have been removed from spotify for copyright reasons. 
You can download the song from the 3rd source and listen from the local folder.

**Comment by shrek1802** [comment]
All song are doing it they are playing fine on my mobile phone with Spotify

**Comment by amd64fox** [comment]
Does this happen if you install the [original Spotify](https://cutt.ly/8EH6NuH) client without SpotX?

**Comment by shrek1802** [comment]
So I uninstalled everything the install Spotify only.

When I reboot the computer it plays fine for about 20 seconds them comes up with the same error.

Don't get it was working fine untill today.

**Comment by amd64fox** [comment]
Maybe it's a bug in the new version `1.1.88.612 `

Try to completely uninstall Spotify using [this script](https://github.com/amd64fox/Uninstall-Spotify) and reinstall.

If it's the same again, try downgrading and blocking updates. Also write feedback about the bug in [community.spotify.com](https://community.spotify.com/t5/Desktop-Windows/bd-p/desktop_windows)

**Comment by shrek1802** [comment]
Right I reinstalled everything again and it was bugging me so looked into it more.

Found the problem windows has updated and it changed my audio output because this has nothing on it, it won't let it play any songs.

Thank you for all the response and hope this helps someone eles if them have a problem.
