### ISSUE TITLE
it will close randomly and crash several times when you try to reopen

### ISSUE THREAD

**Issue by malzia** [SpotX-Official/SpotX#590]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.35.663.gb699649
- Windows: 11
- PowerShell: 5.1.22621.2506
```

### 📝 Description

1. crashes randomly
2. crashes multiple times when you try to reopen
3.
...

**Comment by amd64fox** [comment]
have you tried to perform a clean installation or check for a bug in the native client?

these are the default actions that you should follow before creating an issue here
