### ISSUE TITLE
getting error if accidently reapplied patch and also mini player button vanished in latest patch

### ISSUE THREAD

**Issue by J0hnMilt0n** [SpotX-Official/SpotX#591]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.36.959.g04bf500c-845
- Windows: Windows 11 Enterprise Insider Preview 24H2 26200.5001
- PowerShell: 7.4.2
```

### 📝 Description

Didn't find variable patches.json.free.emptyblock in xpui.js
Didn't find variable patches.json.free.playlistsponsor in xpui.js
Didn't find variable patches.json.VariousJs.sentry in xpui.js
Didn't find variable patches.json.VariousJs.disablelog in xpui.js
Didn't find variable patches.json.VariousJs.hidemerchsidebar in xpui.js
Didn't find variable patches.json.VariousJs.filtertags_locale_fix in xpui.js
Didn't find variable patches.json.others.discriptions in xpui-desktop-modals.js
Didn't find variable patches.json.others.disablesentry 1 in vendor~xpui.js
Didn't find variable patches.json.others.htmlmin 0 in licenses.html
Didn't find variable patches.json.others.htmlmin 1 in licenses.html
Didn't find variable patches.json.others.htmlmin 2 in licenses.html
Didn't find variable patches.json.others.htmlmin 3 in licenses.html
Didn't find variable patches.json.others.htmlmin 4 in licenses.html
Didn't find variable patches.json.others.binary.block_slots in Spotify.exe
Didn't find variable patches.json.others.binary.block_gabo in Spotify.exe

### 📸 Screenshots

![Screenshot (167)](https://github.com/SpotX-Official/SpotX/assets/155903304/4f370824-e96c-4486-89ad-28c1c765d51f)
![Screenshot (166)](https://github.com/SpotX-Official/SpotX/assets/155903304/1016f0e1-2494-4237-8084-6cb7a5783142)

**Comment by amd64fox** [comment]
You don’t read the faq before creating a issues in which it is written at the very beginning the first thing that needs to be done is a clean installation and so on point by point.

but you indicated that the faq was read, do not waste your and our time
