### ISSUE TITLE
these lyrics aren't synced to the song yet

### ISSUE THREAD

**Issue by fayezswilam4** [SpotX-Official/SpotX#593]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

egypt

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 
- PowerShell: 
these lyrics aren't synced to the song yet
```

### 📝 Description

1.these lyrics aren't synced to the song yet
2.these lyrics aren't synced to the song yet
3.these lyrics aren't synced to the song yet
...these lyrics aren't synced to the song yet

**Comment by amd64fox** [comment]
last warning, don't spam
