### ISSUE TITLE
Help with installing static themes for lyrics. 

### ISSUE THREAD

**Issue by ash-byee** [SpotX-Official/SpotX#594]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States of America

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.34.783.g923721d9
- Windows: Windows 11 23H2 22631.3527
- PowerShell: 5.1.22621.2506
```

### 📝 Description

I'm not a frequent github user or programmer so I'm not too well versed in how to run the lyrics_stat command. Where do I run it? Does it work on Windows? I already have spotx installed and have been using it for a few months now, is there a spot to input code/command lines or will I need to reinstall spotx through powershell in order to run the lyrics_stat command?

**Comment by amd64fox** [comment]
free users recently lost full lyrics #587

**Comment by cheweny** [comment]
Did you ever find out how to do this? I'm searching now but still lost

**Comment by amd64fox** [comment]
use `-lyrics_stat` [parameter](https://github.com/SpotX-Official/SpotX/discussions/60)

example:

```ps1
iex "& { $(iwr -useb 'https://raw.githubusercontent.com/SpotX-Official/spotx-official.github.io/main/run.ps1') } -new_theme -lyrics_stat spotify"
```
