### ISSUE TITLE
the lyrics doesn't sync with the song nor there was the full song's lyrics, i would appreciate if you can fix that, and thanks for your amazing work 

### ISSUE THREAD

**Issue by shehatesu** [SpotX-Official/SpotX#595]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Algeria

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.36.959
- Windows: 10
- PowerShell: idk
```

### 📝 Description

1.
2.
3.
...

**Comment by amd64fox** [comment]
duplicate #593
