### ISSUE TITLE
Why aren't the song lyrics synced/working?

### ISSUE THREAD

**Issue by amd64fox** [SpotX-Official/SpotX#596]
On May 1, 2024, song lyrics were restricted for all free users. Now, to access song lyrics as before, you'll need to purchase premium, or use [lyrics-plus](https://spicetify.app/docs/advanced-usage/custom-apps/#lyrics-plus) in [Spicetify](https://spicetify.app/).

> [!IMPORTANT] 
SpotX currently does not unlock song lyrics, they will be incomplete and unsynchronized. Use the parameters `-old_lyrics` or `-lyrics_stat` only if you have a premium account.

> [!NOTE] 
For those who don't need native lyrics or don't want to use the limited version, I added the `-lyrics_block` parameter to completely disable native lyrics

**Comment by amd64fox** [comment]
On July 30, the lyrics were returned to some users. At the moment, there have been no official statements from Spotify, so we can only assume that they may have added a more expanded limit or simply decided to return them under public pressure.

**Comment by PeraDev7** [comment]
Any news?
https://www.msn.com/en-us/news/technology/spotify-lyrics-returning-to-ad-supported-free-tier/ar-BB1qYVib

**Comment by amd64fox** [comment]
Latest news regarding the lyrics:

- as our [voting](https://t.me/SpotxCommunity/315/14954) showed, about half of our free users have already had the lyrics restored. It has also become clear that Spotify is artificially blocking lyrics for old clients, regardless of whether you have a real premium account or not. As of today, the whitelist of versions looks like this: **1.2.36 - 1.2.43**

- there has been no official statement from Spotify, and there may not be one, as they are not very keen on restoring the lyrics, therefore, there is no information on when they will return the lyrics to other users or if they will return them at all

- I just released a patch for spotx windows that allows old clients (1.2.35 and below) to access the lyrics, provided they are available to you on the server side
