### ISSUE TITLE
Instead of canvases, an empty space is displayed

### ISSUE THREAD

**Issue by BOR-LAND** [SpotX-Official/SpotX#598]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Великобритания

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.37.701.ge66eb7bc
- Windows: LTSC 1809 17763.5696
- PowerShell: 5.1.17763.5696
```

### 📝 Description

На некоторых композициях проявляется такой визуальный дефект:
![1](https://github.com/SpotX-Official/SpotX/assets/93826441/84200d28-43e7-44e2-bff0-8465c250e021)

Оригинальный **xpui.spa**:
![0](https://github.com/SpotX-Official/SpotX/assets/93826441/f8dddcd8-ce8a-472d-a7c9-adbcbb8d497a)

[https://open.spotify.com/track/14s1kaqq2iS4CkxjySKzHk?si=0196c68623c74e62](https://open.spotify.com/track/14s1kaqq2iS4CkxjySKzHk?si=0196c68623c74e62)

[https://open.spotify.com/track/6A3LllKRvquXxypzjVWLPc?si=b62be5940c0340ce](https://open.spotify.com/track/6A3LllKRvquXxypzjVWLPc?si=b62be5940c0340ce)

**Comment by amd64fox** [comment]
канвасы у некоторых пользователей могут не прогружаться по разным причинам, их можно отключить в настройках или пкм по канвасу

**Comment by amd64fox** [comment]
хотя попробуй ради теста переключить клиент на английский язык и перезагрузиться, канвасы работают в этом случаи ?

**Comment by BOR-LAND** [comment]
> канвасы у некоторых пользователей могут не прогружаться по разным причинам, их можно отключить в настройках или пкм по канвасу

Рука лицо.
Дело было в ключе запуска **--disable-component-update**. Как-то я не досмотрел. Зато теперь знаю, что есть какие-то канвасы.
Извиняюсь и Большое Спасибо!

**Comment by amd64fox** [comment]
не совсем понял, этот параметр cef был включен в ручном порядке или он был включен автоматически после установки клиента ?

**Comment by BOR-LAND** [comment]
> не совсем понял, этот параметр cef был включен в ручном порядке или он был включен автоматически после установки клиента ?

В ручном порядке по пути **C:\Users\\%UserName%\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar** к ярлыку Spotify, когда-то давно.
После переустановки Spotify ярлык оставался с ключами запуска, которые я сам когда-то указал.
