### ISSUE TITLE
how to prevent Spotify from updating in Winget?

### ISSUE THREAD

**Issue by fenglengshun** [SpotX-Official/SpotX#600]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Indonesia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.39.578.g0ea3f38b
- Windows: 
  - Edition		Windows 10 Pro
  - Version		22H2
  - Installed on	‎8/‎20/‎2022
  - OS build		19045.4412
  - Experience		Windows Feature Experience Pack 1000.19056.1000.0
- PowerShell: 5.1.19041.4412
```

### 📝 Description

1. Install SpotX via main script
2. Put `y` for `Want to block Spotify updates? [Y/N]:`
3. Do `winget upgrade`
4. Spotify is listed in `winget upgrade` and would be automatically upgrade by `winget upgrade --all`

It would be great if SpotX could somehow not register its installed Spotify into winget's detection. It's kinda annoying since winget can only either upgrades all or one package per `winget upgrade` command.

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/26621899/8fdec34c-34d4-45b1-8371-0f8ef4840a3c)

![image](https://github.com/SpotX-Official/SpotX/assets/26621899/0574acd8-d783-4fb5-b4ba-41510c3aa979)

**Comment by amd64fox** [comment]
winget has a native option not to update the packages you specify

- run terminal as administrator
- add Spotify package
```ps1
winget pin add --id Spotify.Spotify
```
- check that the package was added successfully
```ps1
winget pin list
```
- update all packages except Spotify
```ps1
winget upgrade --all
```
