### ISSUE TITLE
Your Country does not match 

### ISSUE THREAD

**Issue by DerFuchs1997** [SpotX-Official/SpotX#601]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Germany 

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 
- PowerShell:
```

### 📝 Description

everything is fine now sorry 

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/94188650/8e6e011c-41e5-442e-80ac-cc8427169da1)
![Spox](https://github.com/SpotX-Official/SpotX/assets/94188650/e8ebb9d4-3ed3-4908-9dc2-9bacd5becd31)

**Comment by amd64fox** [comment]
this problem is not related to Spotx, you need to log into your account with the ip of the country that is listed in your spotify profile
