### ISSUE TITLE
The system cannot execute the specified program.

### ISSUE THREAD

**Issue by shiftlessturtle** [SpotX-Official/SpotX#602]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

USA

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.40.592.gb83da72d
- Windows: Device name    DESKTOP-81PH59I
Processor    Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz   2.90 GHz
Installed RAM    16.0 GB
Device ID    9883184A-3AE8-4188-8F84-E9F2DFC2D57C
Product ID    00326-10000-00000-AA640
System type    64-bit operating system, x64-based processor
Pen and touch    No pen or touch input is available for this display
- PowerShell: 5.1.19041.4522
```

### 📝 Description

1. opened the .bat file
2.
3.
...

### 📸 Screenshots

![image](https://github.com/SpotX-Official/SpotX/assets/87055245/9be25e70-047d-41d3-992e-f200b7775631)

**Comment by amd64fox** [comment]
show what is inside the bat file you run

does running the bat file as administrator help? If not, then try to follow these steps so that you can understand this case in more detail:

- press Win + R, then type "cmd"
- run these commands one by one

**1.**
```cmd
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe
```

**2.**
```cmd
%SYSTEMROOT%\SysWOW64\WindowsPowerShell\v1.0\powershell.exe
```

**3.**
```cmd
powershell.exe
```

- show the result here
