### ISSUE TITLE
Issue Booting SpotX On Fresh Install

### ISSUE THREAD

**Issue by Tj-Ace** [SpotX-Official/SpotX#604]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [x] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

USA

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.13.661
- Windows: Windows-10
- PowerShell: 5.1.19041.4522

- Processor: Core i5-12600K
- Motherboard: MSI-B760 Pro DDR4
- Graphics: RTX-4070
```

### 📝 Description

When Doing A Fresh Install Of Spot X It Brings Me To The Standard Login Screen, But After Just Brings me To A Black Screen.
Same Issue As (https://github.com/SpotX-Official/SpotX/issues/367) But I Couldent Get It To Work At All
I Tried Running The Powershell Cmd And .Bat File For Old Theme But Both Have This Issue
Stock Spotify Boots Fine After Login Its Just With SpotX Applied. Sorry To Be A Bother, Thanks For Any Help <3

### 📸 Screenshots

![Screenshot_3](https://github.com/SpotX-Official/SpotX/assets/174831315/f0bb9842-66f8-4ed9-9881-aaae976055df)

**Comment by amd64fox** [comment]
Thanks for reporting this, it looks like there are some problems with the latest patcher update

**Comment by Tj-Ace** [comment]
Hey Thanks For The Quick Reply :D 
Sorry If me Asking This Is Annoying But If The Issue Is With A Recent Update Are There Legacy Patches That Could Be Used Temporarally?

**Comment by amd64fox** [comment]
try again

**Comment by Tj-Ace** [comment]
Oml That Fixed It :D 
Thanks So Much Love Your Work <3
