### ISSUE TITLE
ads come back when playing from device, alexa speakers

### ISSUE THREAD

**Issue by jaghachi** [SpotX-Official/SpotX#605]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.42.290.g242057a2
- Windows: 11
- PowerShell: 5.1.22621.3930
```

### 📝 Description

1. connect to device
2. choose alexa group speakers

My guess is that once you do, the songs are playing from alexa now and not the computer. Although you can still control it from the desktop app. If this is verified to be the case, then we can just close this "bug".

**Comment by amd64fox** [comment]
you didn't read [faq](https://telegra.ph/SpotX-FAQ-09-19#I-get-ads-when-I-use-Spotify-Connect,-Airplay-etc.-Why?)

**Comment by jaghachi** [comment]
yup my bad, it's explained right there! just wanted to state i can just double click a new song on desktop and it goes away! thank you, you're the best!
