### ISSUE TITLE
cant like songs 

### ISSUE THREAD

**Issue by agreetosee** [SpotX-Official/SpotX#606]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

usa

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: . 1.2.42.290.gf42057a2
- Windows: 10
- PowerShell:   5.1.19041.4648
```

### 📝 Description

cant like songs just ,add button appears to work but it doesn't add m to liked songs, i can still add stuff to playlist

**Comment by amd64fox** [comment]
have you tried a clean install from FAQ?

I couldn't reproduce your problem

Show what command line/file you are using to install SpotX

We also strongly recommend that you check your problem without Spicetify to exclude the influence of third-party software
