### ISSUE TITLE
customize shortcuts

### ISSUE THREAD

**Issue by sakgoyal** [SpotX-Official/SpotX#607]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Do you have Spicetify installed?

No

### 📝 Description

I want to be able to customize shortcuts in the app
examples:
Ctrl + S -> search (currently Ctrl + L)
Ctrl + L -> liked songs
Ctrl + N -> unbind (currently creates a new playlist, which I do not want)

is there any way to do this without having to install spicetify or something like that?

**Comment by amd64fox** [comment]
this is not planned at the moment.
