### ISSUE TITLE
Random Shuffle button non-functional, in own playlist

### ISSUE THREAD

**Issue by null15** [SpotX-Official/SpotX#608]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Sweden

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows (64 bit) 1.2.42.290.g242057a2
- Windows:
Edition	Windows 11 Pro
Version	23H2
Installed on	‎2023-‎03-‎01
OS build	22631.3880
Experience	Windows Feature Experience Pack 1000.22700.1020.0
Device name	DESKTOP-SGUSQHC
Processor	AMD Ryzen 5 3600X 6-Core Processor                3.80 GHz
Installed RAM	32,0 GB
Device ID	7BC7BEB2-D923-407E-A8C9-2AF9F5DF7D35
Product ID	00330-80000-00000-AA184
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
- PowerShell: Version 5.1.22621.3880
```

### 📝 Description

I'm in my playlist, does not work. Clicking button makes the clicked button animation, but nothing happens. Talking about Shuffle.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/d81a52c0-17b6-496d-9ba5-24b38107bbb9)

**Comment by amd64fox** [comment]
Try to perform a clean installation of the latest version [1.2.43](https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit?gid=803394557#gid=803394557)

and then check if this bug reappears without SpotX.
