### ISSUE TITLE
How to disable Made For You icon

### ISSUE THREAD

**Issue by neptunevinus** [SpotX-Official/SpotX#61]
I use old version and Made For You not fit the theme How to hide or disable it?

**Comment by amd64fox** [comment]
are you using an old version of SpotX or an old version of Spotify ?

Now during the installation it is possible to add [incoming parameters](https://github.com/amd64fox/SpotX/discussions/60).
For example, here is your key `-made_for_you_off` which removes this button, 
It just needs to be added to the installation line and run directly from PowerShell:
```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -made_for_you_off"
```


Or you can remove this button manually with [this instruction](https://github.com/amd64fox/SpotX/discussions/47), use this text `Show "Made For You" entry point in the left sidebar` to search in the `xpui.js` file
