### ISSUE TITLE
Volume is too low

### ISSUE THREAD

**Issue by schwifty07** [SpotX-Official/SpotX#610]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Philippines

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.43.420
- Windows: Windows 11 23H2 22631.3958
- PowerShell: 5.1.22621.3958
```

### 📝 Description

1. Volume is too low when i use the spotx patch
2.  Already tried turning the volume level to loud on settings
3.  The original version's volume is normal, it just happens on the spotx patch
4. Reinstall doesn't seem to work unlike the closed issue
...

**Comment by amd64fox** [comment]
SpotX doesn't affect the client's volume, it wouldn't hurt you to figure out the native settings of Spotify

**Comment by schwifty07** [comment]
> SpotX doesn't affect the client's volume, it wouldn't hurt you to figure out the native settings of Spotify

Like i said, the volume seems to be working fine on microsoft or original version of spotify (without spotx patch) and also, I've been using the same account and the same settings on my spotify. How else would my volume be too low on a spotx patch while on the original app it sounds perfectly fine?

**Comment by amd64fox** [comment]
So, you're the only person out of millions for whom SpotX causes this problem.

Now, seriously, if you had read the FAQ and done a clean installation, the problem would have been solved by 99% without creating unnecessary issues that SpotX theoretically can't even cause.

Also, the FAQ clearly states at the very beginning that if the same error reappears after a clean installation of the original client, you should file a bug report on the [Spotify support forum](https://community.spotify.com/t5/Desktop-Windows/bd-p/desktop_windows).

Why is it that when I check their forum, I immediately find your issue reported by other users?

[One post](https://community.spotify.com/t5/Desktop-Windows/Volume-wont-adjust-on-desktop/td-p/6226670)
[Another post](https://community.spotify.com/t5/Desktop-Windows/Spotify-lowers-the-volume-through-windows-volume-mixer/td-p/6230948)

This all goes to show that you expect something from the developers, yet you can’t even make the slightest effort yourself.

**Comment by schwifty07** [comment]
> So, you're the only person out of millions for whom SpotX causes this problem.
> 
> Now, seriously, if you had read the FAQ and done a clean installation, the problem would have been solved by 99% without creating unnecessary issues that SpotX theoretically can't even cause.
> 
> Also, the FAQ clearly states at the very beginning that if the same error reappears after a clean installation of the original client, you should file a bug report on the [Spotify support forum](https://community.spotify.com/t5/Desktop-Windows/bd-p/desktop_windows).
> 
> Why is it that when I check their forum, I immediately find your issue reported by other users?
> 
> [One post](https://community.spotify.com/t5/Desktop-Windows/Volume-wont-adjust-on-desktop/td-p/6226670) [Another post](https://community.spotify.com/t5/Desktop-Windows/Spotify-lowers-the-volume-through-windows-volume-mixer/td-p/6230948)
> 
> This all goes to show that you expect something from the developers, yet you can’t even make the slightest effort yourself.

I guess I am the only person? I've already done a clean installation and it still didn't work, so I'll just use spotify without the spotx patch. And no, I am not expecting for the devs to fix this bug of mine, I'm just looking for answers that could probably fix this, you didn't exactly give me a clear answer, you just called me dumb without calling me dumb by saying that i didn't even make the "slightest effort" myself. I sincerely apologize if I somehow offended you to make you say things like that, I'm just new to asking help since I can't really figure out how to fix this. Still, thank you for helping me to try and fix it.

**Comment by amd64fox** [comment]
> so I'll just use spotify without the spotx patch

In the case when can't read, this is the only correct solution
