### ISSUE TITLE
Smart shuffle not working 

### ISSUE THREAD

**Issue by Darkrues** [SpotX-Official/SpotX#611]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

US

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows (64 bit)
1.2.43.420.gc7b23f70
- Windows: 10
- PowerShell: 5.1.19041.4717
```

### 📝 Description

1. I put smart shuffle 
2. The reccomended songs appear for a bit and then dissapear
3.
...

**Comment by amd64fox** [comment]
this is normal behavior for smart shuffle, recommended songs only appear in the queue tab
