### ISSUE TITLE
Powershell, and Batch installer return an error on opening. 

### ISSUE THREAD

**Issue by ashwin-2007-git** [SpotX-Official/SpotX#612]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United Arab Emirates

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 11 Home 23H2 22631.3880
- PowerShell: 5.1.22631.3880
```

### 📝 Description

1.
2.
3.
...

### 📸 Screenshots

![Screenshot 2024-08-03 105238](https://github.com/user-attachments/assets/0d386c8e-4b98-4aff-b4e5-cb54d3493b12)

**Comment by ashwin-2007-git** [comment]
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by amd64fox** [comment]
in the readme for each installation command a mirror is indicated:

```ps1
iex "& { $(iwr -useb 'https://spotx-official.github.io/run.ps1') } -m -new_theme"
```

**Comment by ashwin-2007-git** [comment]
I've tried both and the same error appears. I'd been using SpotX on multiple devices, but I download 'Pluckeye' recently. I'm guessing that's why.
