### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by ItsFoxCrafter** [SpotX-Official/SpotX#613]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Egypt

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Windows 7 version
- Windows: Windows 7 Professional
- PowerShell: version 2.0

I checked older issues and closed ones, but couldn't find a solution
```

### 📝 Description

 I got an error message when I open install-auto.bat and pasting the command in the PowerShell

error message : 

The term 'iwr' is not recognized as the name of a cmdlet, function, script file
, or operable program. Check the spelling of the name, or if a path was include
d, verify that the path is correct and try again.
At line:1 char:131
+ try { iwr -useb 'https://raw.githubusercontent.com/SpotX-Official/spotx-offic
ial.github.io/main/run.ps1' } catch { $p+= ' -m'; iwr <<<<  -useb 'https://spot
x-official.github.io/run.ps1' }
    + CategoryInfo          : ObjectNotFound: (iwr:String) [], CommandNotFound
   Exception
    + FullyQualifiedErrorId : CommandNotFoundException

Press any key to continue . . .

**Comment by amd64fox** [comment]
you didn't read the [faq](https://telegra.ph/SpotX-FAQ-09-19#It-seems-I-have-an-old-version-of-PowerShell-2.0,-can-I-install-a-patch-with-it?)
