### ISSUE TITLE
Is there no spotify widget working with SpotX?

### ISSUE THREAD

**Issue by anirudhburman** [SpotX-Official/SpotX#619]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.44.405.g81fd6352
- Windows: Windows 10 Pro 22H2 19045.4780 Windows Feature Experience Pack 1000.19060.1000.0
- PowerShell: 5.1.19041.4780
```

### 📝 Description

1. In the original spotify app which I downloaded from the Microsoft store, there is possibility that we can have a desktop widget for the app.
2. Download Microsoft store spotify, play a song, press Win+G, it should be there.
3. It's a small window to control the music player and its very convinient.
4. The installer I downloaded from the Excel Sheet does not show up in the GameBar.

Is there any possibility that we can get this feature? Is there a different workaround for this?

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/b3351ee5-a9ad-43fa-a1e9-aebc1b8bf7ae)

**Comment by amd64fox** [comment]
this widget is only available for the version from the Microsoft store, there are no plans to port it
