### ISSUE TITLE
Patch removes lyrics button (spotify re-added it couple days ago)

### ISSUE THREAD

**Issue by Dight67** [SpotX-Official/SpotX#620]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Poland

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.44.405.g81fd6352
- Windows: 11 23H2 22631.4037
- PowerShell: 5.1.22621.3958
```

### 📝 Description

1. Install SpotX
2. Open Spotify
3. Check in right bottom button area

Lyrics button re-appears when i uninstall SpotX

**Comment by amd64fox** [comment]
you don't read the FAQ and solved issues
