### ISSUE TITLE
some spotx patches not working properly in 1.2.45

### ISSUE THREAD

**Issue by amd64fox** [SpotX-Official/SpotX#621]
**The following patches require updates:**

- [x] fix lyrics_stat
- [ ] fix hidemerchsidebar (not relevant)
- [x] fix goofyhistory

**Comment by Va1er0n82** [comment]
I have minimum 2 issues for now. I can't log in when I'm using the Freedom VPN and the same I can't play any music while I'm using the Freedom VPN, once I logged on without VPN. Any suggestion?

**Comment by darshitlimbad** [comment]
after patching spotify using this spotx the **lyrics but at play bar is gone** ( well if i listen song in full screen the lyrics button shows up and it is working fine also) and i can't use **download features** anymore.

**Comment by MHitMaN** [comment]
After patching with the latest version, Canvas worked once but did not function again when I reopened Spotify after the first use.

**Comment by Chaython** [comment]
I don't seem to have lyrics for any songs with spotx patched...
I've tried playing around with 
-lyrics_block - disable native lyrics
-old_lyrics - return old lyrics for new them
Old lyrics returned the button but it's grayed out.
