### ISSUE TITLE
Malwarebytes detected SpotX as a Trojan

### ISSUE THREAD

**Issue by KASUTANEDA** [SpotX-Official/SpotX#623]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [x] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Mexico

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.45.451.gac8a666f
- Windows: Windows 11 IoT Enterprise LTSC 26100.1457
- PowerShell: 5.1.26100.1301
```

### 📝 Description

Out of nothing malwarebytes detected the .zip as a Trojan, it's probably normal according to the FAQ, but I placed it in here, just in case

### 📸 Screenshots

![Screenshot_1](https://github.com/user-attachments/assets/cea81cf8-b8eb-4b46-8f8f-613aee423ff9)

**Comment by amd64fox** [comment]
If you read the FAQ, it states that you need to identify what you think is a suspicious place in the code 

all these meaningless reports from your AVs don't say anything
