### ISSUE TITLE
Laggy client while in the home menu

### ISSUE THREAD

**Issue by KristijanM1** [SpotX-Official/SpotX#624]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Croatia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.45.454.gc16ec9f6
- Windows: Windows 10 22H2 19045.4780
- PowerShell: 5.1.19041.4780
```

### 📝 Description

Every time im on the Home menu, the whole client becomes laggy. Both the main screen and submenus (Now playing view, Queue) lag while scrolling.
The client performs normally while in a playlist and i do not experience any lag.
This issue is happening both on my PC and laptop since spotify updated and i installed SpotX again.

**Comment by amd64fox** [comment]
does a clean installation of the same version of the client without spotx change anything?

**Comment by A2R14N** [comment]
> does a clean installation of the same version of the client without spotx change anything?

yes, after a clean install everything is back to normal, the interface works smoothly, I have this problem too

**Comment by amd64fox** [comment]
show your command line for installing spotx

also can someone demonstrate this bug on video?


> yes, after a clean install everything is back to normal, the interface works smoothly, I have this problem too

do you mean that the problem was solved after a clean installation of the native client or after a clean installation of spotx?

**Comment by amd64fox** [comment]
nvm, I think I figured out what was causing the problem, it's their new exp enableHomeCarousels which I recently turned on, temporarily disabled it, update spotx

Thanks all for the feedback

**Comment by KristijanM1** [comment]
After updating spotx, everything works fine again. Thanks for fixing the issue.

**Comment by notNSANE** [comment]
yeah, I had the same issue and had to disable that experimental carousel.

Thanks for the change since Spotify was 100% unusable.
