### ISSUE TITLE
Can't view canvas video loop?

### ISSUE THREAD

**Issue by Naammz** [SpotX-Official/SpotX#626]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Indonesia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 
- PowerShell:
```

### 📝 Description

1.
2.
3.
...

### 📸 Screenshots

![2024-09-11 19_02_28-New Issue · SpotX-Official_SpotX](https://github.com/user-attachments/assets/dd11ab88-b81e-4534-ab39-5268759db874)
![2024-09-11 19_02_42-New Issue · SpotX-Official_SpotX](https://github.com/user-attachments/assets/7f54fb9e-d230-4a39-a979-1251f50b3eeb)

**Comment by amd64fox** [comment]
Canvases on the desktop are still in experimental mode, and some users may experience display issues. They can optionally be disabled by right-clicking on the canvas or in the settings

**Comment by Naammz** [comment]
how to turn on the video canvas?

Pada Rab, 11 Sep 2024, 19.31, amd64fox ***@***.***> menulis:

**Comment by Naammz** [comment]
> optionally can be disabled by right-clicking on the canvas or in the settings

okay, now the looping video canvas can be seen
![Uploading 2024-09-12 17_15_17-.png…]()

**Comment by Naammz** [comment]
> optionally can be disabled by right-clicking on the canvas or in the settings

okay, now the looping video canvas can be seen
![2024-09-12 17_15_17-](https://github.com/user-attachments/assets/c978f9b4-cef9-4461-ae64-cbefcb40d999)

**Comment by 0xJsoul** [comment]
how can I enable this canvas video loop in now playing

**Comment by justreportingissues** [comment]
> > optionally can be disabled by right-clicking on the canvas or in the settings
> 
> okay, now the looping video canvas can be seen ![2024-09-12 17_15_17-](https://github.com/user-attachments/assets/c978f9b4-cef9-4461-ae64-cbefcb40d999)

So.. how did you fix this and make the Canvas reappear?
