### ISSUE TITLE
Shuffle/Smart Shuffle not working

### ISSUE THREAD

**Issue by ayayrom** [SpotX-Official/SpotX#627]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

US

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows (32 bit)
1.2.46.462.gf57913e0
- Windows: Version	10.0.19045 Build 19045
- PowerShell: 5.1.19041.4780
```

### 📝 Description

1. install full installation
2. login
3. go to a playlist that you have made and is owner to, with it being a collaborative playlist
4. click shuffle
it is supposed to stay on and shuffle the queue

### 📸 Screenshots

![Untitled (1)](https://github.com/user-attachments/assets/19b107d5-79f6-4314-ab92-8a0be4840098)

**Comment by amd64fox** [comment]
this is broken in native version 1.2.46

roll back to previous version

```ps1
iex "& { $(iwr -useb 'https://raw.githubusercontent.com/SpotX-Official/spotx-official.github.io/main/run.ps1') } -v 1.2.45.454.gc16ec9f6-118 -confirm_spoti_recomended_over -block_update_on -new_theme"
```
