### ISSUE TITLE
Shuffle bug.

### ISSUE THREAD

**Issue by S0ULZXHeRo** [SpotX-Official/SpotX#628]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Pakistan

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.46.462.gf57913e0
- Windows: Windows 11 Pro 23H2 22631.4169
- PowerShell: 5.1.22621.4111
```

### 📝 Description

1. Open Spotify after applying patch.
2. Log in to your acccount.
3. Open any one of your playlists.
4.  Click on Play button.
5.  Click on Shuffle button.
... After clicking on shuffle button, We expect the playlist to be shuffled when playing. i.e the tracks won't play in the order they're added in the playlist but rather randomly. However, this doesn't happen. It still plays sequence wise. Even if you check the queue or enable/disable shuffle mode. The shuffle option also gets disabled on it's own after a while.

### 📸 Screenshots

 I have enabled shuffle. ![image](https://github.com/user-attachments/assets/fcc2a618-3708-48c9-bad7-7bb5c1b9d92b)
The tracks are still in the sequence, not shuffled. ![image](https://github.com/user-attachments/assets/247e34e7-9e55-4e74-8ff5-98a4a1e1f926)
The shuffle mode gets disabled automatically. 
![image](https://github.com/user-attachments/assets/310b1d24-6d1e-4ae1-8efa-15e3e0212059)

**Comment by amd64fox** [comment]
duplicate #627
