### ISSUE TITLE
Installation fail with "Curl error code: 000"

### ISSUE THREAD

**Issue by Psycho-A** [SpotX-Official/SpotX#629]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Russia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: Windows 7 Pro 64-bit
- PowerShell: 5.1.14409.1005
```

### 📝 Description

Trying to do clean install of SpotX on Windows 7 with "Install_Auto" script, but always getting error on the screenshot. It's okay with all my network. Running as admin or disableing any tunnelling software don't help.

### 📸 Screenshots

![Screenshot_2024-09-15_124832](https://github.com/user-attachments/assets/02e0da09-69fd-42d8-b0da-2e87ab98ce4e)

**Comment by amd64fox** [comment]
покажи ответы от 

```ps1
curl.exe -Is -w "%{http_code} \n" -o /dev/null https://download.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.5.1006.g22820f93-1078.exe --retry 2 --ssl-no-revoke
```
и

```ps1
curl.exe -Is -w "%{http_code}" -o /dev/null https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.5.1006.g22820f93-1078.exe --retry 2 --ssl-no-revoke
```
и

```ps1
curl.exe -v -Is https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.5.1006.g22820f93-1078.exe
```



так же не помешало проверить работоспособность этих ссылок напрямую из браузера:

https://download.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.5.1006.g22820f93-1078.exe

https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.5.1006.g22820f93-1078.exe

**Comment by Psycho-A** [comment]
Ссылки в браузере работают. А curl я так понимаю должен быть установлен в системе, или скрипт его скачивает во время установки? У меня есть системный. Первые 2 строки выводят "000", третья не выводит ничего.

Есть одно но. Браузер использует pac-файл прокси, а вот curl этот проки использовать не может. Возможно, проблема в этом. Но тогда бы я был с этой проблемой не один здесь.

**Comment by Psycho-A** [comment]
UPD: Если добавить в строку curl ключ "-k" (разрешить небезопасное соединение), то скачивание работает. Я так понимаю, проблема в сертификатах - или сайтовых, или виндовых. Поэтому лучше бы добавить ключ в скрипт по дефолту - хуже не будет, а юзерам меньше проблем. Плюс до кучи ключ -L (переходить по редиректам), ибо вдруг архив с версиями перейдёт на новое место, а скрипт опять сломается.

**Comment by amd64fox** [comment]
> А curl я так понимаю должен быть установлен в системе, или скрипт его скачивает во время установки?

скрипт чекает curl в системе, если он есть, то использует его в первую очередь, если его нет то использует модуль **BitsTransfer** либо класс **System.Net.WebClient**


> третья не выводит ничего.

вообще странно, флаг -v должен выводить хоть что-то


> Если добавить в строку curl ключ "-k" (разрешить небезопасное соединение), то скачивание работает.

Ага, если с этим ключом работает, то это самая распространенная проблема с устаревшеми ос, сертификаты закончились, раньше думал добавить этот флаг, но как-то руки и не дошли из-за того, что никто не сообщал о похожих проблемах так как большенству видимо было достаточно команды перед выполнением основного скрипта :
```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12;
```

> Плюс до кучи ключ -L (переходить по редиректам), ибо вдруг архив с версиями перейдёт на новое место, а скрипт опять сломается.

это мало вероятно, они настолько долго используют  своё хранилище, наверное столько сколько сами существуют, плюс чтобы сработал редирект они должны указать ответные заголовки в своём сервере куда производить редирект, что-то вроде Location или Patch, если его нет то это все не работает.

**Comment by amd64fox** [comment]
обновил скрипт, спасибо за обратную связь

**Comment by amd64fox** [comment]
> большенству видимо было достаточно команды перед выполнением основного скрипта :
> 
> ```powershell
> [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]
> ```

хотя что я несу 🤦‍♂️, это же относится только к среде ps
