### ISSUE TITLE
Old client versions login fail

### ISSUE THREAD

**Issue by Psycho-A** [SpotX-Official/SpotX#630]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Russia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.5.1006
- Windows: Windows 7
```

### 📝 Description

Зная, что разработчик мой земляк, не придётся тужиться с английским :)
Уверен, что скорее всего это уже обсуждалось, но в этом контексте нет. С новых версий Spotify закрыли внутреннюю авторизацию в приложении, заменив её на браузерную. Это само по-себе идиотизм, но проблема ещё в том, что на Windows 7 и 8.1 последняя версия это 1.2.5.1006, где такую авторизацию ещё не завезли. 

Есть крайне костыльный способ с новой версией клиента и подменой файла prefs.js - но по понятным причинам он на этих ОС не работает (и хорошо, ибо тоже идиотизм). Некоторые юзеры докладывают, что достаточно открыть веб-версию сайта и авторизоваться там - но ведь форма логина в приложении сломана, и это сработает только если УЖЕ был ранее авторизован.

Короче говоря, может быть есть способ с помощью мода, портировать новый вариант логина в старые клиенты? Уверен, он как и прочий интерфейсный хлам, зашит в JS, а не захардкоден. В противном случае, все описанные проблемы делают чистую установку мода на Win 7/8 полностью невозможной. Да и на 10 не добавляет радости с учётом костылей выше.

**Comment by amd64fox** [comment]
попробуй потестить методом подмены от более новой версии:
- скачать [login.zip](https://github.com/user-attachments/files/17022333/login.zip)
- переименовать в `login.spa`
- заменить `Spotify\Apps\login.spa` на скаченный
- запустить клиент (должна подгрузится страница как на новых клиентах )
если будет работать то могу добавить логику в скрипт что бы подтягивался этот архив для старых версий

----------------------------------------------------------------------------------------------------------------------------
можно так же протестировать 2-ой более простой метод авторизации:
- войти через браузер здесь [https://accounts.spotify.com/ru/login](https://accounts.spotify.com/ru/login)
- после успешной авторизации не закрывая бразуер открыть клиент и нажать авторизацию через google, apple или facebook (не важно что), по идеи должно подтянуться уже авторизированная учетка из браузера  

но все равно нужно понимать, что старые версии уже не долго протянут, как не старайся им продлевать жизнь, они просто дернут рубильник и привет 

я уже вижу новый список жертв  `1.1.59-1.2.5`

**Comment by Psycho-A** [comment]
> попробуй потестить методом подмены от более новой версии:

Спасибо, обязательно попробую. Только сейчас на провайдере проблемы с випиэн, так что тут уже как получится. Просьба пока не закрывать репорт.. Может, другие за это время проверят.

> после успешной авторизации не закрывая бразуер открыть клиент и нажать авторизацию через google, apple или facebook (не важно что), по идеи должно подтянуться уже авторизированная учетка из браузера

А как клиент прочитает данные из браузера - разве браузер может их сообщать сторонней программе? Особенно если браузер, скажем, портативный или какой-то нестандартный.

> но все равно нужно понимать, что старые версии уже не долго протянут, как не старайся им продлевать жизнь, они просто дернут рубильник и привет

Вот это больше всего и огорчает. Вместо расширения функционала в новых версиях с сохранением совместимости, они тупо банят старые, которые всё ещё могли бы использовать базовый функционал без этих новшеств. Уверен, что это делается намеренно, а не по острой нужде. Тот же процесс доставки аудио не менялся у них лет 5 - это можно подтвердить по рабочим андроид-клиентам 2019 года, если они с того момента настроены и не разлогинивались.

> я уже вижу новый список жертв 1.1.59-1.2.5

1.1.59 самая лучшая версия была, по факту. Лёгкая, с лаконичным дизайном, без мусора. Что ещё надо от десктопного клиента для музыки? Хз, что им надо. Видимо зарплаты вовремя получать.

**Comment by Psycho-A** [comment]
UPD: Подмена архива с логином работает! Кнопка входа открывает браузер, в нём успешно залогинился с включённым впн-расширением. Правда, при "переходе обратно" в приложение, оно ругнулось, что мол, я не в той стране - т.к. глобальный впн не работал в винде (жаль конечно - думал, логина в браузере теперь достаточно чтоб сидеть с родными айпишниками). Но думаю, это уже не связано с багом из топика, и при впн всё будет работать.

**Comment by amd64fox** [comment]
> А как клиент прочитает данные из браузера - разве браузер может их сообщать сторонней программе? Особенно если браузер, скажем, портативный или какой-то нестандартный.

ну у них же есть механ (OAuth) в старых клиентах для авторизации через google, apple или facebook, по сути это тоже самое. 

сам механ достаточно простой, браузер  перенаправляет на локальный URL (например, localhost:port/callback), где у десктопного клиента должен быть запущен легкий локальный сервер, который сможет принять этот запрос

на деле сработает или нет, сложно сказать, я просто предположил что такая вероятность есть, если происходит чек  уже созданной авторизации перед тем как перенаправлять на oauth для google, apple, facebook то должно завестись

как поведут портативные - без понятие, мы рассматриваем естественно полноценно установленные браузеры, желательно хром.

> 1.1.59 самая лучшая версия была

ты наверное имел ввиду ниже 1.1.59, так как сама 1.1.59 еще работает на сколько я знаю



> Подмена архива с логином работает!

хорошо, один рабочий вариант уже есть, как протестируешь второй способ дай знать

**Comment by Psycho-A** [comment]
> сам механ достаточно простой, браузер перенаправляет на локальный URL (например, localhost:port/callback), где у десктопного клиента должен быть запущен легкий локальный сервер, который сможет принять этот запрос

Понято, принято.

> как поведут портативные - без понятие, мы рассматриваем естественно полноценно установленные браузеры, желательно хром.

Видимо, нормально, т.к. портативный фаерфокс отправил запрос, раз Спотифай увидел мой аккаунт и что он "в другой стране". Вопрос теперь ещё, как поведёт себя сам Спотифай, если его портативно установить в кастомную папку, а не в AppData (ненавижу захламлять системные папки). Полагаю всё-таки, что сопряжение не через пути идёт, а через запущенные процессы.

> ты наверное имел ввиду ниже 1.1.59, так как сама 1.1.59 еще работает на сколько я знаю

Да, я всё-таки ошибся, имея ввиду версию 1.1.58, на которой ещё был лайт-мод (её сломали в прошлом году). Просто их уже столько было...

> хорошо, один рабочий вариант уже есть, как протестируешь второй способ дай знать

Это про авторизацию через Гугл/Фейсбуч*? Мне кажется, если после подмены работает основной вариант, то во втором нет нужды. Типичный юзер увидит в клиенте поле с логином/паролем, начнёт их вводить, обломится, и на этом всё. А на кнопочку Гугла нажмут те, у кого именно так был зареган акаунт. Мало, кому придёт в голову входить через такой обходной путь именно в нативный акк - когда как суть ровно та же самая как с подменой (тот же браузер, та же отправка запроса). Плюс эти формы с соцсетями есть на самой странице авторизации в сайте, и результат, думаю, будет тем же.

**Comment by amd64fox** [comment]
добавил подгрузку архива, парк версий пока такой, от 1.1.87.612 до 1.2.5.1006, нужно еще выборочно пройтись, возможно в какой-то версии могут возникнут проблемы, но ниже 1.1.87.612 точно нет, там крашится уже
