### ISSUE TITLE
Top search bar is activated even without present in the script

### ISSUE THREAD

**Issue by BedBug2479** [SpotX-Official/SpotX#631]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

India

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.46.462.gf57913e0
- Windows: Win 11 22H2 22631
- PowerShell: 7.4.5
```

### 📝 Description

Even without **-topsearchbar** in install script it is present in the spotify. I have even did a fresh install but still it is present

![image](https://github.com/user-attachments/assets/69ce0759-22a0-43d7-9bc7-a26097171f01)

![image](https://github.com/user-attachments/assets/e47cb3dc-d4aa-4a63-b597-888f9ee80245)

**Comment by amd64fox** [comment]
the new search bar is now impossible to disable starting with version 1.2.46, the `-topsearchbar` parameter will not work accordingly, you can downgrade your spotify version to 1.2.45 and below

```ps1
iex "& { $(iwr -useb 'https://raw.githubusercontent.com/SpotX-Official/spotx-official.github.io/main/run.ps1') } -v 1.2.45.454.gc16ec9f6-118 -confirm_spoti_recomended_over -block_update_on -new_theme"
```
