### ISSUE TITLE
disable the autostart on Windows startup

### ISSUE THREAD

**Issue by Moffinguer** [SpotX-Official/SpotX#632]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Spain

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.46.462.gf57913e0
- Windows: Windows 11 Home 23H2 22631.4169
- PowerShell: 5.1.22621.4111
```

### 📝 Description

1. Clean install with custom parameters
2. No "Disable to launch on start up of the computer" option or similar
3. SpotX gets installed but I have to disable manually or else it will launch everytime my computer switchs on

**Comment by amd64fox** [comment]
From your text, it is not entirely clear what exactly starts up after the PC is rebooted.

If you mean the Spotify client itself, that is normal; in the client settings, auto-start on Windows startup is enabled by default, and this can be disabled in the settings.

if you mean launching an automatic Spotify update, then this is disabled by blocking updates during the installation of spotx

If you mean that the SpotX patcher automatically starts from the command line, that is impossible; it has always been launched manually with the user's participation.

**Comment by Moffinguer** [comment]
Pardon me for not being completly clear.
I meant the first of the three options you have listed. I know it is enabled by default the auto-start. My question is, would it be possible to add a new parameter to allow the users to disable the auto-start on Windows startup.

Sorry for any inconveniences

**Comment by amd64fox** [comment]
> My question is, would it be possible to add a new parameter to allow the users to disable the auto-start on Windows startup.

yes, it can be done

**Comment by amd64fox** [comment]
added parameter `-DisableStartup`, which now disables Spotify autostart when windows boots
