### ISSUE TITLE
Could not play any song in the spotx

### ISSUE THREAD

**Issue by Afiqwan75** [SpotX-Official/SpotX#635]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Malaysia

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- 1.2.47.364.gf06e5cee
- Spotify for Windows (32 bit)
- PowerShell:
```

### 📝 Description

1. i could play any of the song
2. after login, i noticed my profile is logged in, but the name of my profile is like anonymous/random generated username e.g. ( u0kze1f8vt4vba5i6emrhifgf )
3. i can search song but i could play it
4.  i could not open any of my playlist and it keep prompt ( could not find any playlist )
5. is this related with windows version or what? Spotify for Windows (32 bit) since i am using windows 11 23h2?
...

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/b4bd300d-1291-4d01-9c56-c93fe2bfa298)
![image](https://github.com/user-attachments/assets/e878ad44-03a8-40b3-a769-7fd1c7f96d00)

**Comment by just5ky** [comment]
i ended up installing old theme, then playing one song then again installing new theme.
This somehow fixed it.

**Comment by amd64fox** [comment]
I think these are just temporary problems on the server side that resolve themselves after some time
