### ISSUE TITLE
New home structure and navigation not applied when run installation command in powershell

### ISSUE THREAD

**Issue by sentestlk** [SpotX-Official/SpotX#636]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Sri Lanka

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.47.364.gf06e5cee
- Windows: Windows 11 23H2 22631.4169
- PowerShell: 5.1.22621.4111
```

### 📝 Description

 I just downloaded Spotify from their website and after login I applied SpotX installation PowerShell command ([ -new_theme](iex "& { $(iwr -useb 'https://raw.githubusercontent.com/SpotX-Official/spotx-official.github.io/main/run.ps1') } -new_theme"))  and the new home structure not applied. ( no change when run the command ) 

### 📸 Screenshots

My Spotify after run the command ( no change in home structure just like ORIGINAL Spotify format )
![image](https://github.com/user-attachments/assets/d4dd5198-deeb-4eb5-8caf-e115868191f4)

SpotX New theme
![image](https://github.com/user-attachments/assets/e9d3b2f4-eb5e-44db-af83-967e6ee438b7)

**Comment by amd64fox** [comment]
they have already forced ew home structure and navigation for all users on the latest versions

**Comment by sentestlk** [comment]
> they have already forced ew home structure and navigation for all users on the latest versions

That means we can't go to the old SpotX interface, right?

**Comment by amd64fox** [comment]
you can downgrade manually, here is the [list of official versions ](https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit#gid=0)
