### ISSUE TITLE
Can't play certain albums/songs

### ISSUE THREAD

**Issue by TheStreetKingRyan** [SpotX-Official/SpotX#637]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Bosnia and Herzegovina

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.47.364.gf06e5cee
- Windows: Windows 10 22H2 19045.4894
- PowerShell: 5.1.19041.4894
```

### 📝 Description

1. Find a certain album/playlist (for example, JoJo's Bizarre Adventure: Golden Wind OST)
2. All of the songs are greyed out
3. None of them can be played, the error that shows up is "This content is not available."
...

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/20a489eb-5347-4251-bcb8-8a98e86f3abc)

**Comment by amd64fox** [comment]
it's not a problem with spotx, you don't read the faq
