### ISSUE TITLE
Empty window area

### ISSUE THREAD

**Issue by Selkus** [SpotX-Official/SpotX#638]
### 🧐 Have you read the FAQ and viewed similar issues?

- [x] I have read the FAQ
- [X] I have checked older issues, open and closed
- [x] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Nederland

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.47.366.g0d3bd570
- Windows: Windows 11 Pro 22H2 22621.2428
- PowerShell: 5.1.22621.2428
```

### 📝 Description

1. Включаю музыку
2. Появляется Пустая область окна где обычно бывает реклама
3. Съедает полезное пространство
...
Хотелось бы его убрать, это возможно?

### 📸 Screenshots

![pr](https://github.com/user-attachments/assets/ed4fb837-a3fd-4bda-8da5-91216632e791)

**Comment by amd64fox** [comment]
99% что обновления не были заблокированы и твой клиент обновился, тем самым перезаписав spotx

**Comment by Selkus** [comment]
> 99% что обновления не были заблокированы и ваш клиент обновился, тем самым перезаписав Spotx

как их заблокировать? только через переустановку?
могу ли поверх того что есть установить или не поможет?

**Comment by amd64fox** [comment]
можно поверх, во время установки просто подтверди блокировку обновлений
