### ISSUE TITLE
Old install script detects my OS as Windows 7/8.x instead of Windows 10

### ISSUE THREAD

**Issue by defautluser0** [SpotX-Official/SpotX#639]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Spain

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.5.1006.g22820f93
- Windows: Windows 10 21H2 19044.4894 (LTSC IoT 2021)
- PowerShell: 5.1.19041.4894
```

### 📝 Description

1. Install [this transformation pack](https://www.deviantart.com/imswordqueeen/art/Windows-10-21H2-22H2-to-7-Transformation-Pack-1081353677).
2. Run install script.
3. Get warning [1st screenshot] saying that my windows version is 7/8.x instead of 10.

### 📸 Screenshots

Warning![image](https://github.com/user-attachments/assets/29e6dd81-49f0-4d0b-abe4-16bda0da6c37)

Winver(as you can probably tell, 21H2 is not a valid Windows 7 version. Its a valid 10/11 version(10 in this case) tho.
![image](https://github.com/user-attachments/assets/2340f471-caac-4abb-8192-c344143b4ad5)

**Comment by amd64fox** [comment]
Why did you open this here lol

try to run this code in a powershell terminal and show the response

```ps1
$registryVersion = (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").ProductName

$environmentVersion = [System.Environment]::OSVersion.VersionString

$cimInstanceVersion = (Get-CimInstance Win32_OperatingSystem).Caption

Write-Host "(Regedit): $registryVersion"
Write-Host "(System.Environment): $environmentVersion"
Write-Host "(Get-CimInstance): $cimInstanceVersion"
```

**Comment by defautluser0** [comment]
> Why did you open this here lol

???


Anyways, heres the output
```
(Regedit): Windows 10 IoT Enterprise LTSC 2021
(System.Environment): Microsoft Windows NT 10.0.19044 Service Pack 1
(Get-CimInstance): Microsoft Windows 7 Ultimate
```

**Comment by amd64fox** [comment]
I'm saying that the patch you installed changes the system specifications of Windows, but you are asking for help not where the source of the problem is, but on the side, which is quite strange.

All I can do is try to use a more universal way to check the OS

for example, you can try to show your response from this code:

```ps1
switch ([System.Environment]::OSVersion.Version) {
    { $_.Major -eq 10 -and $_.Build -ge 22000 } { 
        "Windows 11"
        break
    }
    { $_.Major -eq 10 } { 
        "Windows 10"
        break
    }
    { $_.Major -eq 6 -and $_.Minor -eq 0 } { 
        "Windows Vista"
        break
    }
    { $_.Major -eq 6 -and $_.Minor -eq 1 } { 
        "Windows 7"
        break
    }
    { $_.Major -eq 6 -and $_.Minor -eq 2 } { 
        "Windows 8"
        break
    }
    { $_.Major -eq 6 -and $_.Minor -eq 3 } { 
        "Windows 8.1"
        break
    }
    default { 
        "Unknown Windows Version"
    }
}
```

**Comment by defautluser0** [comment]
i installed arch linux before running this, i forgot

**Comment by amd64fox** [comment]
what does arch linux have to do with it

I will add the construction with System.Environment later, for now this is closed

**Comment by defautluser0** [comment]
> what does arch linux have to do with it

nothing, js wanted to add that i forgot

**Comment by defautluser0** [comment]
> for example, you can try to show your response from this code:

ive reinstalled windows and ran this with the pack, it prints "Windows 10"
ik this issue is closed but js wanted to respond to that
