### ISSUE TITLE
Is there any way to display song/track info page, just like on spotify web? (open.spotify.com)

### ISSUE THREAD

**Issue by onmyouji** [SpotX-Official/SpotX#640]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Indonesia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows (32 bit) 1.2.48.405.gf2c48e6f
- Windows: Windows 10 Home 22H2 19045.4894
- PowerShell: 5.1.19041.4894
```

### 📝 Description

On spotify web (https://open.spotify.com), the song/track name is clickable (if you hover your mouse on the song name, it will show underline link).

![Copy of 2024-10-09_184122](https://github.com/user-attachments/assets/eabbe2ae-74e9-43c1-a66d-2259f4bf2d06)

If you click it, it will display a page with song info:

![2024-10-09_184322](https://github.com/user-attachments/assets/60a0a453-ea4c-4660-8c00-e379833583ce)

But on SpotX desktop client, you can't do this. The song/track name can't be clicked.

Is there any way to show similar thing, just like on open.spotify.com ?

Thanks

**Comment by amd64fox** [comment]
In the old versions of the desktop client, they had already added this functionality, but then they removed it. At the moment, I haven't noticed anything similar in the experiments, but if they have started using it in the web version, it is highly likely that it will soon make its way to the desktop version. 

As soon as this exp becomes available, I will enable it.
