### ISSUE TITLE
after patching getting CANT PLAY THIS error

### ISSUE THREAD

**Issue by deFrogdev** [SpotX-Official/SpotX#641]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

germeny

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.45.405
- Windows: 11
- PowerShell: 5.1.22621.4111
```

### 📝 Description

1.installing latest spotify (and songs getting played fine)
2.patching with Install_New_theme.bat 
3.no longer musics can be played 
...

### 📸 Screenshots

![{10DD7995-DA39-40B7-878E-7F499C68EE62}](https://github.com/user-attachments/assets/1b05ac6b-eea2-42c4-a340-d2fefa602a70)

**Comment by amd64fox** [comment]
this is not a spotx problem, read faq
