### ISSUE TITLE
add a parameter for 'now playing' canvas video loop

### ISSUE THREAD

**Issue by 0xJsoul** [SpotX-Official/SpotX#642]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Philippines

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.48.405.gf2c48e6f
- Windows: 10
- PowerShell:
```

### 📝 Description

dsadsad

**Comment by amd64fox** [comment]
duplicate #626

**Comment by 0xJsoul** [comment]
what version should I use to enable experimental features?

**Comment by amd64fox** [comment]
1.1.79 and above

**Comment by 0xJsoul** [comment]
I'm using the latest (1.2.48.405.gf2c48e6f) but can't seem to enable it
adding -exp_spotify to the parameter does nothing.
am I doing it wrong?

**Comment by amd64fox** [comment]
exp_spotify parameter returns almost all exp to the position that the native spotify client uses, how can this help you?

- canvases don't work in all songs
- at the moment canvases are an experimental feature and spotx only enables it, 

if it doesn't work for you then in your particular case you're unlucky
