### ISSUE TITLE
Occasional Spotify Premium overlays pop up

### ISSUE THREAD

**Issue by ghost** [SpotX-Official/SpotX#645]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [ ] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

USA

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.48.405.gf2c48e6f
- Windows: 10
- PowerShell: Default
```

### 📝 Description

1. Use Spotify for a bit
2. The overlay will show

*(I expected the overlays to disappear as well)*

### 📸 Screenshots

![2024-10-25 16_43_43-Occasional Spotify Premium overlays pop up · Issue #645 · SpotX-Official_SpotX -](https://github.com/user-attachments/assets/066b63dd-0a3a-4887-8057-0767902fa3a3)

**Comment by amd64fox** [comment]
Actually, this pop-up banner was blocked from the moment SpotX was created

Open`About Spotify`
![Снимок экрана 2024-10-25 120038](https://github.com/user-attachments/assets/d2806d4e-1315-478f-a33c-b68cab33ccf8)

Show a screenshot

**Comment by ghost** [comment]
Alright
![2024-10-25 16_45_21-Spotify](https://github.com/user-attachments/assets/d10cccb1-7772-49bf-a602-6b3b58e2714a)

**Comment by amd64fox** [comment]
I meant the whole About Spotify window

**Comment by ghost** [comment]
Oh
![2024-10-25 17_52_24-Spotify](https://github.com/user-attachments/assets/63ff2d39-7d87-45a4-813c-1d1b4964526f)

**Comment by amd64fox** [comment]
Yes, now I see that spotx is installed, but you installed it together with spicetify, which is not recommended, to ensure that this is a spotx issue, you need to install spotx without spicetify, using a [clean installation](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation) that you should have done before creating this problem. 

After that, you should check the problem again.

Also, if you notice any errors in the console during the installation of SpotX, please let me know.

**Comment by ghost** [comment]
That seems to have fixed the issue (for the time being). Thanks for the help. I'll let you know if I get the ad later.
