### ISSUE TITLE
Infinite "downloading spotify" screen

### ISSUE THREAD

**Issue by arnepardon** [SpotX-Official/SpotX#646]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Netherlands

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.59.710.g134abcca-4032
- Windows: 7 10 11
- PowerShell: windows 11 uses newest i think
```

### 📝 Description

spotx installer says downloading > connecting infinitely long. It also opens  the C:\Users\user\Documents folder. This is my bat file, anyone can help me?

@echo off

:: Line for changing spotx parameters, each parameter should be separated by a space
set param=-version 1.1.59.710.g134abcca-4032 -DisableStartup -block_update_on -podcasts_off -homesub_off -plus -adsections_off -rightsidebar_off -exp_spotify -premium -lyrics_stat spotify

set url='https://raw.githubusercontent.com/SpotX-Official/spotx-official.github.io/main/run.ps1'
set url2='https://spotx-official.github.io/run.ps1'
set tls=[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12;

%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe ^
-Command %tls% $p='%param%'; """ & { $(try { iwr -useb %url% } catch { $p+= ' -m'; iwr -useb %url2% })} $p """" | iex

pause
exit /b

**Comment by amd64fox** [comment]
closed because already answered in telegram
