### ISSUE TITLE
When I try to log in is gives me an error 

### ISSUE THREAD

**Issue by Biggestweeninthewest** [SpotX-Official/SpotX#648]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United States 

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 
- PowerShell:
```

### 📝 Description

1.Hit log in
2. It sends you to Google 
3. It sends you back 
4. Error code:auth:1

### 📸 Screenshots

![IMG_20241110_084610](https://github.com/user-attachments/assets/1fc54d66-710f-4ccc-8d75-2a67cb107d7f)

**Comment by amd64fox** [comment]
not related to Spotx, change your network or use vpn
