### ISSUE TITLE
Anti-Virus Deleting SpotX

### ISSUE THREAD

**Issue by SirGryphin** [SpotX-Official/SpotX#651]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United Kingdom

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.50.335.g5e2860a8
- Windows: Windows 10 Pro Version 22H2 19045.5131
- PowerShell: 5.1.19041.5129
```

### 📝 Description

1. Run Install.bat
2. Kaspersky Deletes

Event: Malicious object detected
User type: Initiator
Application name: explorer.exe
Application path: C:\Windows
Component: File Anti-Virus
Result description: Detected
Name: UDS:DangerousObject.Multi.Generic
Precision: Exactly
Threat level: High
Object type: File
Object name: Spotify.exe
Object path: C:\Users\User\AppData\Roaming\Spotify
MD5 of an object: FDDF3EB71398C21CB63427ADE127FEFF
Reason: Cloud Protection

---

Event: Object deleted
Application: Spotify
User type: Initiator
Component: System Watcher
Result description: Deleted
Type: Trojan
Name: PDM:Trojan.Win32.Bazon.a
Threat level: High
Object type: Process
Object path: C:\Users\User\AppData\Roaming\Spotify
Object name: Spotify.exe
MD5: FDDF3EB71398C21CB63427ADE127FEFF

**Comment by amd64fox** [comment]
you don't read the faq
