### ISSUE TITLE
Song canvas doesn't show

### ISSUE THREAD

**Issue by jbodee1** [SpotX-Official/SpotX#652]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [ ] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

USA

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 
- PowerShell:
```

### 📝 Description

 whenever i play a song the canvas doesn't show

### 📸 Screenshots

![Screenshot 2024-11-20 224246](https://github.com/user-attachments/assets/44acae4f-cebf-4489-b175-d5a06d228de7)

**Comment by amd64fox** [comment]
duplicate #626
