### ISSUE TITLE
Spotify UI Problem

### ISSUE THREAD

**Issue by SkillzAura** [SpotX-Official/SpotX#654]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Bangladesh

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.51.345.gcc39d911
- Windows: Windows 11 24H2 
- PowerShell: 5.1.26100.2161
```

### 📝 Description

1. Download Spotify with or without SpotX
2. Check the Close button in the top right corner

You will see that the Close button (X) in the top right corner is not aligned properly, its a bit below where it's supposed to be. there is a gap on top which makes the position of the close, minimize and maximize buttons to not be in the right spot like other programs. 

![gap](https://github.com/user-attachments/assets/82012363-742a-4de4-bfc2-9753c0f390d9)

This happens without SpotX installed aswell on Native Spotify. Is it possible so that when we install SpotX this problem will be fixed?

**Comment by amd64fox** [comment]
after the release of their new top bar, they centered all the elements on it, including the control elements, this is not a bug
