### ISSUE TITLE
Next song bug

### ISSUE THREAD

**Issue by Noblefrix** [SpotX-Official/SpotX#655]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Philippines

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.51.345.gcc39d911
- Windows: Windows 10 Pro Version 22H2 19045.5131
- PowerShell: 5.1.19041.5129
```

### 📝 Description

1. Play any song, best noticable at playlist
2. Wait for the song to end or manually skip the song
3. notice how the song is not in the playlist and the song the song playing is comepletely different
4. Switch to older version
5. It works
...

### 📸 Screenshots

N/A, Function bug, not visual

**Comment by amd64fox** [comment]
It’s possible that Smart Shuffle is enabled, which adds new tracks to your queue.

**Comment by Noblefrix** [comment]
> It’s possible that Smart Shuffle is enabled, which adds new tracks to your queue.

Both shuffle and smart shuffle was off

**Comment by amd64fox** [comment]
the problem does not reproduce for me

additionally, I haven't heard from you about performing these steps (which need to be done before reporting the issue) and providing the results after completing them:

- a [clean installation](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation) of SpotX exactly as described in the FAQ
- a [clean installation](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation) of the [native Spotify client](https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit?gid=803394557#gid=803394557) of the same version and architecture
- checking the originality of your hosts file
