### ISSUE TITLE
Lyrics don't show up when listening along with someone

### ISSUE THREAD

**Issue by M2Dawn** [SpotX-Official/SpotX#656]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

USA

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.52.442.g01893f92
- Windows: 10 22H2 1904X.5131
- PowerShell: 5.1.19041.5129
```

### 📝 Description

1.  lyrics doesn't show up when listening along on discord however it works fine in old theme 

hope it get fixed any next updates cause i like new theme

### 📸 Screenshots
![image](https://github.com/user-attachments/assets/c8307f49-d1fa-4926-8045-bf890e94f338)
 here while listening with someone  
(can't press on  now playing view)
 
 
![image](https://github.com/user-attachments/assets/64fe6bdd-1a7d-4292-bcf8-02050449bb57)
here if i listen to song by myself i can click on it

**Comment by amd64fox** [comment]
I'm sure this problem is not related to spotx

check the problem in the native client

**Comment by M2Dawn** [comment]
i tried to add -old_lyrics parameter and it works fine with new theme 

that fixed the issue
