### ISSUE TITLE
sending data to google form

### ISSUE THREAD

**Issue by sadkingo** [SpotX-Official/SpotX#657]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Algeria

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
You should not send information of version without telling users
https://docs.google.com/forms/d/e/1FAIpQLSegGsAgilgQ8Y36uw-N7zFF6Lh40cXNfyl1ecHPpZcpD8kdHg/formResponse
```

### 📝 Description

1.
2.
3.
...

**Comment by amd64fox** [comment]
Wow, you really uncovered a devious scheme for leaking information about Spotx users!

P.S. do something useful with your boring life
