### ISSUE TITLE
All Playlist Blank,Can't Play any song

### ISSUE THREAD

**Issue by nayumiDEV** [SpotX-Official/SpotX#66]
## ℹ Computer information

- Spotify version: lastest recomment version
- Plan Spotify: free
- Windows version: Windows 10 Enterprise 21H2 v19044.1766 Feature Experience Pack 120.2212.4180.0
- PowerShell version: 5.1.19041.1682 BuildVersion 10.0.19041.1682

## 📝 Description of the problem

1. Playlist Can't Load
2. No song can play

## 📷 Screenshots

<details>
<summary><small>Screenshot</small></summary><p>

![image](https://user-images.githubusercontent.com/59746573/177525023-2e98fa5f-cfc2-4359-96c2-f0a8e2c45588.png)

![image](https://user-images.githubusercontent.com/59746573/177525099-fcd2ad86-a242-4d8b-865d-bf4ee00914d1.png)

</small></summary><p>

</details>

**Comment by amd64fox** [comment]
check your host file and remove from it all the ip addresses that you previously added

- Win + R 
- `%WinDir%\System32\Drivers\Etc\hosts`

**Comment by nayumiDEV** [comment]
> check your host file and remove from it all the ip addresses that you previously added
> 
> * Win + R
> * `%WinDir%\System32\Drivers\Etc\hosts`

I never edited it, it's still in default state

**Comment by amd64fox** [comment]
> I never edited it, it's still in default state

host file can be automatically edited without your knowledge by other ad blockers

You can install the [latest version of the original client](https://cutt.ly/8EH6NuH), does your problem reoccur there?

**Comment by nayumiDEV** [comment]
> > I never edited it, it's still in default state
> 
> host file can be automatically edited without your knowledge by other ad blockers
> 
> You can install the [latest version of the original client](https://cutt.ly/8EH6NuH), does your problem reoccur there?

Yes, but it's not edited. Also Spotify in the browser works normally

Edit: maybe this bug is my fault. Original client can load playlist but still can't play anything

**Comment by amd64fox** [comment]
> Also Spotify in the browser works normally

Spotify from the browser is not that, You need to uninstall my mod and install the original Spotify from the link above and check your issue there.

**Comment by nayumiDEV** [comment]
The error occurred because I updated SpotX (previously installed with spicetify). Fixed it by uninstalling spicetify and spotX then restarting the computer and installing original Spotify and SpotX again.
