### ISSUE TITLE
Install_New_theme.bat Fails

### ISSUE THREAD

**Issue by B-Rett89** [SpotX-Official/SpotX#660]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

United states

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: fresh / not yet installed
- Windows: 10 (up to date)
- PowerShell: 7 (newest version)

Using the full installer (Install_Auto.bat) works though. Figured yall could use a heads up that the Install_New_theme.bat is not working. Says something about not being able to make an SSL connection, tried twice same problem.
```

### 📝 Description

1. go to website
2. choose the Install_New_theme.bat 
3. attempt to launch/install

**Comment by amd64fox** [comment]
Technically, the files Install_Auto.bat and Install_New_theme.bat are not different, it is possible that you are using an old version of the bat file. To exclude this case, open your Install_New_theme.bat file through a text editor and send the entire code here.

You should also take a screenshot of the console at the moment the SSL error occurs.

**Comment by cisko99za** [comment]
sorry for my intrusion, but I too have problems with the script... why don't you share a 7z archive with the desktop app version already patched with your script?
usually i use a SpotX repack version from a russian dev, but this one is not updating, so i ended up here on github. so technically you can to do this, and share 7z file only

and while i'm here i haven't been able to create a new discussion (how do you do that? is it closed?) so i had to join this already open issue

**Comment by amd64fox** [comment]
> sorry for my intrusion, but I too have problems with the script... why don't you share a 7z archive with the desktop app version already patched with your script?
> usually i use a SpotX repack version from a russian dev, but this one is not updating, so i ended up here on github. so technically you can to do this, and share 7z file only

from your text, I didn't notice any problems with the script. This repo is only related to the patcher, everything else is off-topic, so contact your Russian "dev" or use the patcher yourself

> and while i'm here i haven't been able to create a new discussion (how do you do that? is it closed?) so i had to join this already open issue

anyone with a GitHub account can create a new issue or discussion
or is this some new github rules

**Comment by cisko99za** [comment]
my question isn't about my spotify app make from russian dev (old app but work great) but why can't share already patched app and not script only...

about second question (open new discussion) yes, i have account from github (in fact i'm posting here my comment) but from discussion page i can't open new thread (look my shot above). why?
![shot_01](https://github.com/user-attachments/assets/58c3e840-7b1f-46f0-83d1-66fd618625dc)

**Comment by amd64fox** [comment]
There was an item in org settings that affects all the org repos, now the creation of a new discussion should work.

**Comment by cisko99za** [comment]
> There was an item in org settings that affects all the org repos, now the creation of a new discussion should work.

yes now work. thanks
