### ISSUE TITLE
"Enhanced" songs dont play

### ISSUE THREAD

**Issue by KieranDevvs** [SpotX-Official/SpotX#72]
## ℹ Computer information

- Spotify version: 1.1.89.862.g94554d24
- Plan Spotify: Free
- Windows version: 10
- PowerShell version: 7
- Spicetify installed: No

## 📝 Description of the problem

1) Enable "Enhanced" playlist
2) Play an "Enhanced" song
3) Nothing plays.

Note: Regular songs play as normal.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/21192520/178600727-a2a2f0f1-0371-4e2e-87e5-e78630830af1.png)

**Comment by amd64fox** [comment]
Perform a clean install as described [here](https://github.com/amd64fox/SpotX/blob/main/.github/Doc/FAQ.md#i-have-an-error--bug--strange-client-behavior-what-can-i-do-)

**Comment by KieranDevvs** [comment]
> Perform a clean install as described [here](https://github.com/amd64fox/SpotX/blob/main/.github/Doc/FAQ.md#i-have-an-error--bug--strange-client-behavior-what-can-i-do-)

A fresh install appears to have fixed the issue, which indicates its a client sided issue. Thanks.
