### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by Yoon0117** [SpotX-Official/SpotX#74]
Can you please add a new release with the newest code? Cause the latest release Is from a year ago. I know i can manually download newest version but it would be much simpler to just download from release

Thank you :)

**Comment by Yoon0117** [comment]
(also I love this script so much!)

**Comment by amd64fox** [comment]
Updated just for you 🙏

**Comment by Yoon0117** [comment]
Thank you  you are the kindest:D
