### ISSUE TITLE
"Something went wrong, try reloading the page" after installing.

### ISSUE THREAD

**Issue by IroConOx** [SpotX-Official/SpotX#77]
## ℹ Computer information

- Spotify version: 1.1.89.862
- Plan Spotify: free
- Windows version: Windows 10 Home 21H1
- PowerShell version: 5.1.19041.1682
- Spicetify installed: no

## 📝 Description of the problem

1. Ran uninstall spotify first before install.bat, didn't fix the issue
2. After sign-in, spotify shows this (see screenshot attached)
3. Button does nothing.

## 📷 Screenshots

<details>
<summary><small>Screenshot</small></summary><p>

![image_2022-07-14_032309094](https://user-images.githubusercontent.com/54962938/178884329-031af7f7-7f08-44e3-b68b-3830084198c9.png)

</details>

**Comment by amd64fox** [comment]
Hi
Follow the recommendations in the first paragraph of [possible problems](https://github.com/amd64fox/SpotX#possible-problems)

**Comment by IroConOx** [comment]
I did do this. Like I said I ran uninstall-spotify.bat first before running install.bat, clarified now. 
I checked the hosts file but there was no issue there that would result in any issue
I already used the original official client before and this issue was not there.

**Comment by amd64fox** [comment]
> I already used the original official client before and this issue was not there.

Can you install this [original client of the latest version](https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.89.862.g94554d24-13.exe) right now and check it out ? To be 100% sure

**Comment by IroConOx** [comment]
issue has fixed itself, maybe a restart of my computer was what was required, I don't know. 
Sorry to bother
