### ISSUE TITLE
Variable not Found in Licenses.html

### ISSUE THREAD

**Issue by GhostTwohand** [SpotX-Official/SpotX#84]
## ℹ Computer information

- Spotify version: 1.1.90.855
- Plan Spotify: Free
- Windows version: Windows 11
- PowerShell version: 7.2.5
- Spicetify installed: No
## 📝 Description of the problem

1. Error

Was using the Automatic Full Installation (Code in Powershell)

## 📷 Screenshots

<details>
<summary><small>Screenshot</small></summary><p>

![spotify](https://user-images.githubusercontent.com/26114684/179765771-d84bee28-e946-4c61-90e1-0e2b86aacd74.png)

</small></summary><p>

</details>

**Comment by amd64fox** [comment]
Can't reproduce this error.

You are installing over another version, perhaps this is the problem.

Does this error happen again with a clean install?

**Comment by GhostTwohand** [comment]
After a Full Clean Install there is no more Error now, maybe it was the Install Over the Old Spotify Version

But it seems the Error with the Licenses didn't effect the Patch itself

Still Thanks didn't test it with Complete Clean Installation from the beginning

**Comment by n00bje** [comment]
- Spotify version: 1.1.91.824.g07f1e963
- Plan Spotify: Free
- Windows version: 10.0.19044
- PowerShell version: 7.2.5
- Spicetify installed: No

I get "Didn't find variable $contents.HtmlLicMin2 in licenses.html" on a clean install.
When I check AppData\Roaming\Spotify\Apps\ I only have 2 files: Login.spa and xpui.spa. No licenses.html.

The (patched) Spotify seems to work fine though.

**Comment by amd64fox** [comment]
@GhostTwohand @koen-debacker 
Managed to reproduce a bug that prevented the licenses.html file from being truncated.
fixed
