### ISSUE TITLE
Media Buttons not are shown

### ISSUE THREAD

**Issue by mirronake** [SpotX-Official/SpotX#85]
## ℹ Computer information

- Spotify version: 1.1.90.855.ga73cc2ce
- Plan Spotify: free 
- Windows version: 22000.778
- PowerShell version: 5.1.22000.653
- Spicetify installed: no

## 📝 Description of the problem

1. Media buttons are not shown

## 📷 Screenshots

<details>
<summary><small>Screenshot</small></summary><p>

![image](https://user-images.githubusercontent.com/96698262/179846645-8fd0c543-b806-47bf-9104-762a9809394f.png)

**What should it be?**
![image](https://user-images.githubusercontent.com/96698262/179847133-d80f7bfd-90b6-48f5-86cb-20842506763a.png)

</small></summary><p>

</details>

**Comment by amd64fox** [comment]
Follow all the steps of the first paragraph from [possible problems](https://github.com/amd64fox/SpotX#possible-problems)
