### ISSUE TITLE
Spotify not opening at all.

### ISSUE THREAD

**Issue by ToastyNani** [SpotX-Official/SpotX#89]
## ℹ Computer information

- Spotify version: 1.1.90.859
- Plan Spotify: free
- Windows version: 10.0.19044 build 19044          or windows 10
- PowerShell version: 10.0.19041.546
- Spicetify installed: no

## 📝 Description of the problem

1. spotify stopped opening after i installed the patch even after uninstalling. even without the patch.
2. and avast keeps putting the chrome_elf.dll in quarantine even tho i had an exeption on the temp file.
3. i kept adding it to exeption yet it still does that.

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/99569117/180632913-19d353b1-2354-49f8-8761-a909df96dfe3.png)

<details>
<summary><small>Screenshot</small></summary><p>

![test_screen](https://user-images.githubusercontent.com/62529699/149568115-36120440-1799-4b1b-80d5-06df10da5ec4.png)

</small></summary><p>

</details>

**Comment by Daddy-Shade** [comment]
I had this exact problem, I solved it by right-clicking avast premium in my taskbar and setting avast shields to be disabled for 10 minutes to allow it to install—it worked like a charm.

**Comment by amd64fox** [comment]
You need to find the right way to add files to exclusions for your antivirus.

Also disable your antivirus completely during the installation of the patch. Perhaps the advice above will help you.

If you do not want to do all this, then simply remove it and use the standard Microsoft defender (by the way, it is not almost worse, and in some places even better)
