### ISSUE TITLE
Equaliser not working

### ISSUE THREAD

**Issue by henrynaja** [SpotX-Official/SpotX#90]
## ℹ Computer information

- Spotify version:
- Plan Spotify: free
- Windows version: 10, 21H2
- PowerShell version: 
- Spicetify installed: no

## 📝 Description of the problem

The Equaliser wont change anything at the Sound if i turn it on, i tried to edit it manually or with the profiles but both didn't work.

**Comment by amd64fox** [comment]
Clean reinstall, if it does not help, then you need to wait for the next version of Spotify, maybe it will be fixed in it by spotify developers.
