### ISSUE TITLE
"Sort By" setting not staying saved on any playlist.

### ISSUE THREAD

**Issue by f-faa** [SpotX-Official/SpotX#91]
## ℹ Computer information

- Spotify version: 1.1.90.859.gf1bb1e36 
- Plan Spotify: Free
- Windows version: 10
- PowerShell version: 5.1
- Spicetify installed: No

## 📝 Description of the problem

Everytime I set a playlist sorting to something other than custom order and then restart Spotify client, the setting does not stay saved.

1. Go to a playlist and set "**Sort by**" from **Custom Order** to any other order. Example: **Date added**
2. Close Spotify and turn it on again.
3. Playlist sorting goes back to **Custom Order**.

Note: Sorting playlist stays saved and doesn't change on normal Spotify client.

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/76886727/180875281-968fc96c-73e0-404b-9aa2-b549fc90e456.png)

**Comment by amd64fox** [comment]
Hi
- which SpotX installer did you use?
- were there any errors during the installation?

This bug could not be reproduced, try the clean uninstall/install described in the first paragraph of [possible problems](https://github.com/amd64fox/SpotX#possible-problems)

**Comment by f-faa** [comment]
Yeah nvm a clean install fixed the issue
