### ISSUE TITLE
Upgrade Button is back

### ISSUE THREAD

**Issue by Max0Black** [SpotX-Official/SpotX#92]
## ℹ Computer information

- Spotify version: 1.1.90.859.gf1bb1e36
- Plan Spotify: premium
- Windows version: 22H2 (OB Build 22000.795)
- PowerShell version: 5.1.22000.653
- Spicetify installed: no

## 📝 Description of the problem

1. I installed Spotify and SpotX via the Usual installation and also on another try via Automatic full installation. In both ways the upgrade Button was back in Spotify.

## 📷 Screenshots

<details>
<summary><small>Screenshot</small></summary><p>

![Screenshot_1](https://user-images.githubusercontent.com/52931019/181234041-21336ada-614d-4035-81da-37fac17bab8a.png)

</small></summary><p>

</details>

**Comment by amd64fox** [comment]
You have a premium account, you need to run a special installation with premium support
https://raw.githack.com/amd64fox/SpotX/main/scripts/Install_Prem.bat
