### ISSUE TITLE
Remove the inscription "Free" on the button in the taskbar

### ISSUE THREAD

**Issue by eshaane** [SpotX-Official/SpotX#95]
### Description of the new feature / enhancement

I know this is a very small thing but I was wondering if it was possible to Rename what the window shows up as, currently it shows up as "Spotify Free" but when I was on a premium plan it showed "Spotify Premium", I would like to know if renaming this window is possible. Attached screenshots for reference. 

### 📸 Screenshots

![Screenshot_180](https://user-images.githubusercontent.com/84348006/182009485-c2c8a717-a6ab-4587-a7a6-9f47b5499369.png)

**Comment by amd64fox** [comment]
Previously I tried to remove this "Free" label, but it's probably somewhere in the compiled code, hard to find, I'll try again later...

**Comment by eshaane** [comment]
Alright thank you :)

**Comment by eshaane** [comment]
Any updates on this or same status?

**Comment by amd64fox** [comment]
Didn't find a solution to the problem as long as it stays as it is

**Comment by Nuzair46** [comment]
@amd64fox , as we found out in BlockTheSpot, there is no safer way to remove this without getting DMCA'd by Spotify because we will need to directly change the binaries.

**Comment by eshaane** [comment]
@Nuzair46 in this case is there a way for the user themselves without spotx to be able to change the binaries' ?

**Comment by PigeonNotFound** [comment]
![image](https://user-images.githubusercontent.com/71892423/196287938-f4391f2e-7309-46f3-a88b-527b903c5754.png)
Doesn't seem like it's there for me anymore unless they changed something?

**Comment by amd64fox** [comment]
@DarkPower202 

you clicked on the icon with the right mouse button

you should have just hovered over the icon

**Comment by Othmane-ElAlami** [comment]
It's not a big deal really, the label changes when you're listening to something. 
![image](https://user-images.githubusercontent.com/111425505/201358074-24bdf31f-877b-4f8d-9fbc-5d39cf0a6367.png)

Pretty sure it's hardcoded somewhere inside the .exe anyway and if it's the case it needs some reverse engineering and even if someone do that and release a tool to patch this it's only gonna work for one version. So, too much pain for just one word you rarely see.

**Comment by amd64fox** [comment]
I don’t see it at all because I have square icons on the taskbar, to notice this I need to pause the song in Spotify and hover over the icon with the mouse

for now I will close it as an unfinished problem, if there is a simple solution to hide this inscription, then I will return to it

**Comment by amd64fox** [comment]
seems to have found a way to change the title of "Spotify Free" to the taskbar
![Снимок экрана 2023-04-23 145712](https://user-images.githubusercontent.com/62529699/233838481-89f887b9-989f-4e96-8e31-073165694c88.png)

**Comment by yodaluca23** [comment]
> seems to have found a way to change the title of "Spotify Free" to the taskbar
> 
> ![Снимок экрана 2023-04-23 145712](https://user-images.githubusercontent.com/62529699/233838481-89f887b9-989f-4e96-8e31-073165694c88.png)
> 
> 

Without messing with binaries? Or anything that could get y'all DMCAed?

**Comment by amd64fox** [comment]
> Without messing with binaries? Or anything that could get y'all DMCAed?

via js

**Comment by yodaluca23** [comment]
😃😃
![image](https://user-images.githubusercontent.com/67206487/236087506-0775079f-c1b9-41f3-9874-621fb50e0d6d.png)

**Comment by amd64fox** [comment]
although when loading the client for about a second, the inscription "Spotify Free" is still visible 😃

**Comment by yodaluca23** [comment]
> although when loading the client for about a second, the inscription "Spotify Free" is still visible 😃

I noticed that xD
