### ISSUE TITLE
Allow to choose "Very High" song quality (visual only)

### ISSUE THREAD

**Issue by NguyenASang** [SpotX-Official/SpotX#96]
### Description of the new feature / enhancement

Free users of Spotify is only allow to listen with High quality. Can you remove that limitation ?

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/87893636/182024426-3a4aeddd-c45b-475f-b5bb-208dd4bfdbde.png)

**Comment by amd64fox** [comment]
Unfortunately, this is a server feature and cannot be unlocked at the moment.

**Comment by NguyenASang** [comment]
@amd64fox How about just visual only ?:)

**Comment by NguyenASang** [comment]
@amd64fox That would be okay for me, I just want it to be perfect =)) And why do you [hide](https://github.com/amd64fox/SpotX/blob/main/patches/patches.json#L578-L580) it ?

Reopen this and see what everyone thinks about pls.

**Comment by amd64fox** [comment]
> And why do you [hide](https://github.com/amd64fox/SpotX/blob/main/patches/patches.json#L578-L580) it ?

very high quality is hidden for free users, this function does not work if you do not have a premium account.

SpotX hides all non-working interface elements that can only be activated if you have a premium account.



> How about just visual only ?:)

didn't get your logic

what will it give you if it is included visually?

in any case it does not activate very high sound quality

**Comment by NguyenASang** [comment]
@amd64fox
> in any case it does not activate very high sound quality

 Yes I know that in any case it doesn't activate
 
 > what will it give you if it is included visually?
 
Idk how to explain but I want it. Well, I can try working around it to see if it's possible.

**Comment by NguyenASang** [comment]
I found it, will open a pull request if you accept it.

https://user-images.githubusercontent.com/87893636/225829421-ec3691a2-8aea-4dfc-81af-ceeb56eb185d.mp4

**Comment by amd64fox** [comment]
besides the fact that you visually switch it, what does it give?

**Comment by NguyenASang** [comment]
Looks more perfect for me

**Comment by amd64fox** [comment]
> Looks more perfect for me

unfortunately, this is not an argument for most people, you can use your fork if it's so important.

**Comment by NguyenASang** [comment]
I think I'll give up on this idea, sorry to bother you.
