### ISSUE TITLE
SpotX + Spicetify installation (first FAQ approach) shows ads on Home

### ISSUE THREAD

**Issue by francescoaracu** [SpotX-Official/SpotX#98]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/blob/main/.github/Doc/FAQ.md#i-have-an-error--bug--strange-client-behavior-what-can-i-do-">described in the FAQ</a>

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.1.91.824.g07f1e963
- Windows: Windows 11 22H2 22621.317
- PowerShell: 7.2.5
```

### 📝 Description

1. Clean installed SpotX.
2. Installed Spicetify and tweaked to my own taste.
3. This is the situation on the first opening of Spotify.

Edit: just got an audio and banner ad. I'm assuming it could be related to the fact that Spicetify has 1.1.90 as last official supported Spotify version.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/48188510/182117701-d213bbeb-0536-4497-9997-90fcb87e3edd.png)

**Comment by francescoaracu** [comment]
Closing issue, I restarted Spotify and it's all gone! Good to know.

**Comment by amd64fox** [comment]
The audio ad and banner should be blocked by BTS, maybe it started to work badly.

Watch, if the problem repeats, open it again.
